import type { FeatureCopy, FeatureDetailLabels, FeatureUiCopy, FeaturesPageCopy } from "../types";
import { PAYLOAD_EXAMPLE } from "./samples";

/**
 * German (de) copy of the features area. Same shape as en.ts; see docs/14-localization.md.
 */

export const FEATURES_DE: FeatureCopy[] = [
  {
    slug: "ai-setup",
    title: "KI-geführte Einrichtung",
    short: "Site beschreiben, jeden Schritt bestätigen, signierte Konfiguration veröffentlichen.",
    benefit: "Deine erste Destination geht in einer geführten Sitzung live — ohne einen Tag zu schreiben und ohne die Kontrolle darüber abzugeben, was veröffentlicht wird.",
    intro: "Der Assistent macht aus einer Domain ein funktionierendes Messsetup: Er erkennt Plattform und Consent-Tool, schlägt einen Eventplan für deinen Geschäftstyp vor, sammelt öffentliche IDs im Chat und Geheimnisse in einer Tresor-Karte, sendet einen echten Testevent und bereitet ein Publish-Diff vor, das du freigibst.",
    flow: {
      title: "Jede Aktion ist ein typisierter Tool-Aufruf, den du siehst",
      text: "Der Assistent führt nie freien Code aus. Er ruft serverseitig validierte Tools auf: Plattform erkennen, Eventplan entwerfen, Pixel-ID prüfen, Testevent senden, Diff vorbereiten. Alles Unumkehrbare — Veröffentlichen, Rollback, Credential-Rotation — stoppt an einer Freigabe-Karte, die an genau die Änderung gebunden ist, die du gerade siehst.",
      caption: "Assistent → typisierte Tools → Freigabe-Karte → signierte Konfiguration. Geheimnisse gehen direkt in den Tresor und laufen nie durch den Chat.",
    },
    viewCaption: "Beispielsitzung: Plattform erkannt, Eventplan vorgeschlagen, Token im Tresor abgelegt, echter Testevent akzeptiert, Veröffentlichung wartet auf deine Freigabe.",
    sections: [
      { title: "Typisierte Tools statt freier Aktionen", text: "Jede Aktion des Assistenten ist ein serverseitig validierter Tool-Aufruf mit Rollenprüfung, Audit-Eintrag und — bei allem Unumkehrbaren — einem Freigabe-Token, das an das exakte Diff gebunden ist." },
      { title: "Geheimnisse erreichen das Modell nie", text: "Access-Tokens gehen über eine eigene Karte oder OAuth direkt in den verschlüsselten Tresor. Transkript, Modell und Browser sehen sie nie; eine DLP-Schicht schwärzt eingefügte Secrets und PII." },
      { title: "Deterministische State Machine", text: "Die Einrichtung folgt einer expliziten State Machine mit Anforderungen und Evidenz je Zustand. Dieselben Zustände gibt es als regelbasierten Assistenten, wenn der KI-Anbieter nicht erreichbar ist — nichts hängt davon ab, dass ein Modell online ist." },
    ],
    bullets: ["Erkennung von Geschäftstyp und Plattform mit Konfidenzangabe", "Eventplan-Vorlagen für Shops, Leadgenerierung, SaaS und Publisher", "Öffentliche IDs gegen Anbieterformate validiert", "Veröffentlichung nur nach Diff, Empfängerliste und expliziter Bestätigung"],
    comparison: {
      title: "Einrichtung von Hand versus geführte Sitzung",
      text: "Was sich ändert, wenn der Assistent die Einrichtung übernimmt und du die Freigaben behältst.",
      beforeLabel: "Manuelle Container-Einrichtung",
      afterLabel: "Geführte Einrichtung mit Track",
      rows: [
        { aspect: "Eventplan", before: "Aus dem Gedächtnis geschrieben, ein Tag nach dem anderen", after: "Für deinen Geschäftstyp vorgeschlagen, im Chat bearbeitet, vor der Veröffentlichung validiert" },
        { aspect: "Zugangsdaten", before: "In Tag-Felder eingefügt und für alle mit Container-Zugriff sichtbar", after: "In einer Tresor-Karte oder per OAuth eingegeben; nie im Transkript sichtbar" },
        { aspect: "Verifikation", before: "Hoffen, dass beim Anbieter etwas ankam", after: "Ein echter Testevent durch die echte Pipeline mit dem Urteil des Anbieters" },
        { aspect: "Veröffentlichen", before: "Veröffentlichen und danach herausfinden, was sich geändert hat", after: "Erst Diff, Empfänger und Freigabe; danach ein signiertes, versioniertes Bundle" },
      ],
    },
    faq: [
      { q: "Kann der Assistent ohne mich veröffentlichen?", a: "Nein. Veröffentlichen, Rollbacks, Credential-Rotation und Aktivierung von Destinationen erfordern immer deinen Klick auf eine Freigabe-Karte, die an die exakte Änderung gebunden ist." },
      { q: "Welches Modell wird genutzt?", a: "OpenAI Responses API mit Structured Outputs und striktem Function Calling. Modellnamen werden serverseitig konfiguriert und beim Start geprüft; die Oberfläche kodiert sie nie fest." },
    ],
  },
  {
    slug: "server-side-tracking",
    title: "Serverseitiger Event-Router",
    short: "Ein Event, jede Plattform: Browser- und Server-Zustellung mit gemeinsamer Deduplizierung.",
    benefit: "Sende jede Conversion einmal und lass jede Plattform sie so empfangen, wie sie am besten zählt — Browser, Server oder beides — ohne Doppelzählung.",
    intro: "Track empfängt Events aus dem Browser-SDK, deinem Server, Shopsystemen und Affiliate-Netzwerken, normalisiert sie in ein Schema, wendet Consent an und leitet sie mit Retries, Circuit Breakern, Dead-Letter-Queue und Replay an 22 Destinationstypen weiter.",
    flow: {
      title: "Browser und Server teilen eine Event-ID",
      text: "Browser-SDK und dein Server (oder Shop-Webhook) senden denselben Kauf mit derselben Event-ID. Track normalisiert beide, prüft Consent pro Destination und leitet weiter; Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn und die anderen deduplizieren über diese ID, Google Ads über die Bestellnummer.",
      caption: "Website → Track → Consent/Policy → Destinationen. Beide Ursprünge enden bei denselben Destinationen und werden dort dedupliziert.",
    },
    viewCaption: "Beispiel für Destination Health: zwei gesunde Destinationen, ein Anbieterausfall, den der Circuit Breaker abfängt, eine per Kill-Switch pausierte Destination.",
    sections: [
      { title: "Hybrid als Standard", text: "Jede Destination kann per Browser-Tag, Server-API oder beidem laufen. Beide Wege teilen eine Event-ID, sodass Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn und die anderen zuverlässig deduplizieren." },
      { title: "Dauerhaft und beobachtbar", text: "Dauerhafte Queue mit idempotenten Nachrichten, Retries pro Destination mit Jitter-Backoff, Circuit Breaker bei ausfallenden Anbietern, Dead-Letter-Speicher und Replay. Jeder Versuch wird mit geschwärzter Payload-Vorschau protokolliert." },
      { title: "First-Party by Design", text: "Der Tracker kommt von deinem CDN-Host, Events gehen an deinen Ingest-Host, Konfigurationsbundles sind Ed25519-signiert und werden im Browser geprüft, bevor irgendetwas lädt." },
    ],
    bullets: ["Browser-SDK durch ein CI-Budget unter 30 KB gzip gehalten, mit consent-gesteuertem Speicher", "Server-API mit Source-Keys für CRM- und Offline-Conversions", "Kill-Switches pro Site und Organisation", "EU-Datenebene mit Row-Level-Mandantentrennung"],
    comparison: {
      title: "Reine Browser-Tags versus hybrider Router",
      text: "Warum ein Event über Track mehr wert ist als derselbe Pixel, der zweimal feuert.",
      beforeLabel: "Nur Browser-Tags",
      afterLabel: "Browser + Server mit Track",
      rows: [
        { aspect: "Verlorene Events", before: "Blockierte Skripte und geschlossene Tabs verwerfen die Conversion einfach", after: "Der Server-Weg liefert sie trotzdem; der Browser-Weg ergänzt Matching-Daten, wenn verfügbar" },
        { aspect: "Duplikate", before: "Pixel und Server-API zählen dieselbe Bestellung doppelt", after: "Gemeinsame Event-ID und Bestellnummer; die Anbieter deduplizieren" },
        { aspect: "Anbieterausfall", before: "Stiller Fehler, kein Retry", after: "Retries mit Backoff, Circuit Breaker, Dead-Letter-Queue und Replay" },
        { aspect: "Wohin Daten gehen", before: "Drittanbieter-Endpunkte werden aus der Seite aufgerufen", after: "First-Party-Ingest-Host; Anbieter erhalten nur gemappte Felder" },
      ],
    },
    faq: [
      { q: "Umgeht serverseitiges Tracking den Consent?", a: "Nein. Consent wird für jedes Event und jede Destination geprüft; ohne den erforderlichen Zweck wird nichts gespeichert, gesendet oder später nachgeliefert." },
      { q: "Was passiert, wenn ein Anbieter ausfällt?", a: "Zustellungen werden mit Backoff wiederholt, der Circuit Breaker pausiert die Destination, fehlgeschlagene Events landen in der Dead-Letter-Queue und können nach der Erholung erneut gesendet werden." },
    ],
  },
  {
    slug: "event-debugger",
    title: "Event-Debugger und Herkunft",
    short: "Jedes Event mit Consent-Snapshot, Routing-Entscheidung und Anbieterantwort.",
    benefit: "Wenn eine Zahl in einer Werbeplattform falsch aussieht, findest du an einer Stelle heraus, warum — statt zwischen Browser-Konsole, Anbieter-Oberfläche und dem Gedächtnis eines Kollegen zu raten.",
    intro: "Öffne ein Event und lies seine Geschichte: Quelle und SDK-Version, der zu diesem Zeitpunkt erteilte Consent, erfasste Click-IDs, die Konfigurationsversion, die es geroutet hat, und der Zustellversuch pro Destination inklusive geschwärzter Payload und Anbieterantwort.",
    flow: {
      title: "Ein Event, der ganze Weg",
      text: "Der Debugger folgt einem Event vom Ursprung über Normalisierung und Consent-Entscheidung bis zu jedem Zustellversuch. Verwerfungen sind nie still: Jede trägt einen Grund wie fehlender Consent, blockierte PII, ungültiger Name, Duplikat oder pausierte Destination.",
      caption: "Die Herkunft hält Ursprung, Consent-Snapshot, Routing-Entscheidung und die Antwort jedes Anbieters zusammen.",
    },
    viewCaption: "Beispiel-Eventstream: zugestellte Events, ein deduplizierter Kauf und ein Server-Kauf, der wegen fehlendem Marketing-Zweck blockiert wurde.",
    sections: [
      { title: "Geschwärzt, nicht versteckt", text: "Payload-Vorschauen zeigen Struktur und gehashte Kennungen, damit du Mappings prüfen kannst, ohne personenbezogene Daten oder Tokens offenzulegen." },
      { title: "Testevents durch die echte Pipeline", text: "Testevents sind markiert, laufen durch dieselbe Queue und denselben Worker und melden das Urteil des Anbieters — kein simulierter Erfolg." },
      { title: "Verwerfungen werden erklärt", text: "Jedes verworfene Event trägt einen Grund: fehlender Consent, PII blockiert, ungültiger Name, Duplikat, pausierte Destination oder Policy-Block." },
    ],
    bullets: ["Filter nach Eventname, Status und Quelle", "Versuchshistorie pro Destination mit HTTP-Status und Fehlerklasse", "Testmodus-Hinweise pro Plattform", "Direkte Links in den Destination-Assistenten"],
    comparison: {
      title: "Debugging per Konsole versus Debugging per Herkunft",
      text: "Dieselbe Frage — warum hat dieser Kauf Meta nicht erreicht? — zweimal beantwortet.",
      beforeLabel: "Browser-Konsole und Anbieter-Oberfläche",
      afterLabel: "Event-Herkunft in Track",
      rows: [
        { aspect: "Wo suchen", before: "Netzwerk-Tab, Tag-Vorschaumodus, der Event-Manager des Anbieters", after: "Ein Event-Datensatz mit jedem Versuch und jeder Antwort" },
        { aspect: "Consent zu diesem Zeitpunkt", before: "Unbekannt; aus den Banner-Einstellungen rekonstruiert", after: "Als Snapshot mit dem Event gespeichert" },
        { aspect: "Serverseitige Events", before: "Aus dem Browser unsichtbar", after: "Dieselbe Herkunft, mit ihrem Ursprung markiert" },
        { aspect: "Personenbezogene Daten", before: "Rohe Payloads in Logs und Screenshots", after: "Gehashte Kennungen, geschwärzte Vorschauen" },
      ],
    },
    faq: [{ q: "Wie lange werden Debugger-Daten aufbewahrt?", a: "Zustellversuche standardmäßig 90 Tage, Events 13 Monate; beides ist pro Organisation im Datenschutz-Center konfigurierbar." }],
  },
  {
    slug: "data-quality",
    title: "Datenqualität und Health-Score",
    short: "Ein Score mit erklärbaren Komponenten und Problemen, die auf ihre Lösung verlinken.",
    benefit: "Erfahre, wenn Tracking bricht, sieh, welcher Teil gebrochen ist, und spring direkt zur Lösung — bevor eine Kampagne auf schlechten Daten läuft.",
    intro: "Der Worker berechnet einen Tracking-Health-Score aus Consent-Abdeckung, Abdeckung kritischer Events, Schemaqualität, Duplikatrate, Zustellerfolg und Aktualität. Jedes erkannte Problem benennt das Assistenten-Tool, das es löst.",
    flow: {
      title: "Sechs Komponenten, ein erklärbarer Score",
      text: "Der Score wird aus den Events des letzten Zeitraums berechnet: wie viele ein explizites Consent-Signal tragen, welche geplanten kritischen Events gesehen wurden, wie viele Schema- und PII-Prüfungen bestehen, die Duplikatrate, den Zustellerfolg pro Destination und wann das letzte Browser-Event ankam. Die Gewichte stehen neben dem Score, sodass eine niedrigere Zahl immer auf ihre Ursache zeigt.",
      caption: "Events → Prüfungen → gewichtete Komponenten → Score mit den Problemen, die ihn gesenkt haben.",
    },
    viewCaption: "Beispiel-Score mit seinen sechs Komponenten und zwei offenen Problemen, die jeweils das Tool benennen, das sie löst.",
    sections: [
      { title: "Probleme mit Fingerprints", text: "Wiederkehrende Probleme werden gruppiert, gezählt und mit Zeitstempeln versehen, damit du Trends statt Rauschen siehst." },
      { title: "Schema-Leitplanken", text: "Standardevents haben Pflichtparameter; Custom-Events folgen Namensregeln; PII in Properties wird vor dem Speichern blockiert." },
      { title: "Benchmarks nur mit Opt-in", text: "Anonymisierte, aggregierte Benchmarks gibt es nur für Organisationen, die sich dafür entscheiden." },
    ],
    bullets: ["Score pro Site mit seinen Komponenten", "Probleme lösen oder ignorieren mit Audit-Trail", "Consent-Abdeckung und Duplikatrate als zentrale Kennzahlen"],
    comparison: {
      title: "Probleme bemerken versus gemeldet bekommen",
      text: "Wie ein kaputter Kauf-Event mit und ohne Health-Score sichtbar wird.",
      beforeLabel: "Ohne Monitoring",
      afterLabel: "Mit dem Health-Score",
      rows: [
        { aspect: "Erkennung", before: "Jemand bemerkt Tage später einen Einbruch im Ads-Dashboard", after: "Der Score sinkt und ein Problem wird geöffnet" },
        { aspect: "Diagnose", before: "Welcher Tag, welche Seite, welcher Browser?", after: "Die gesunkene Komponente und die Events dahinter" },
        { aspect: "Behebung", before: "Ticket, Tag-Änderung, erneut veröffentlichen, warten", after: "Das Problem benennt das Assistenten-Tool; du gibst die Änderung frei" },
        { aspect: "Trend", before: "Keine Historie", after: "Gruppierte, gezählte Probleme mit Zeitstempeln" },
      ],
    },
    faq: [{ q: "Ist der Score über Sites vergleichbar?", a: "Die Komponenten sind für jede Site identisch; die Gewichte stehen in der Score-Karte, damit Teams Unterschiede nachvollziehen können." }],
  },
  {
    slug: "consent",
    title: "Consent-konform von Grund auf",
    short: "Strikte Opt-in-Standards, Consent Mode v2, zweckgebundene Destinationen, kein Replay nach Consent.",
    benefit: "Jede Destination erhält genau das, dem der Besucher zugestimmt hat — geprüft für jedes Event, im Browser und noch einmal auf dem Server — statt einer Banner-Einstellung, von der du hoffst, dass sie stimmt.",
    intro: "Consent ist keine Banner-Integration, sondern eine Policy-Engine: Zwecke, Regionen, Destinationsanforderungen und Click-ID-Erfassung werden für jedes Event im Browser und erneut auf dem Server geprüft.",
    flow: {
      title: "Das Gate steht vor jeder Destination",
      text: "Jede Destination deklariert den Zweck, den sie braucht. Kommt ein Event an, vergleicht Track den Consent-Snapshot mit dieser Anforderung: Analyse-Destinationen erhalten Events mit Analyse-Consent, Werbe-Destinationen nur mit Marketing-Consent. Ein Widerruf stoppt Sendungen sofort, und nichts, was vor dem Consent gespeichert wurde, wird danach nachgeliefert.",
      caption: "Website → Track → Consent/Policy-Gate → nur die Destinationen, deren Zweck erteilt wurde.",
    },
    viewCaption: "Beispiel-Consent-Zustand: Analyse erteilt, Marketing verweigert — und die daraus abgeleiteten Consent-Mode-v2-Flags und Blockgründe.",
    sections: [
      { title: "CMP-Adapter und API", text: "TCF 2.2, GPP und Global Privacy Control, Adapter für Cookiebot, OneTrust und Usercentrics sowie eine Consent-API für eigene Banner." },
      { title: "Consent Mode v2, zweckbasiert", text: "Google-Consent-Signale werden aus Zwecken abgeleitet; der erweiterte Modus ist nur mit dokumentierter juristischer Prüfung verfügbar." },
      { title: "Nachweis", text: "Deduplizierte Consent-Snapshots werden mit jedem Event gespeichert, damit du belegen kannst, was wann erteilt wurde." },
    ],
    bullets: ["Abgeleiteter Consent wird nie an Werbeplattformen exportiert", "Ein Widerruf stoppt Sendungen sofort", "Server-Käufe bleiben operativ, aber ohne Consent nie Werbung"],
    comparison: {
      title: "Consent pro Tag versus Policy-Engine",
      text: "Wo die Entscheidung fällt — und ob du sie später belegen kannst.",
      beforeLabel: "Consent pro Tag gehandhabt",
      afterLabel: "Policy-Engine in Track",
      rows: [
        { aspect: "Entscheidungspunkt", before: "Der Trigger jedes Tags, von Hand konfiguriert", after: "Jedes Event, jede Destination, im Browser und auf dem Server" },
        { aspect: "Serverseitige Events", before: "Unabhängig vom Banner gesendet", after: "Dieselbe Zweckprüfung wie bei Browser-Events" },
        { aspect: "Widerruf", before: "Greift beim nächsten Seitenaufruf, wenn überhaupt", after: "Stoppt Sendungen sofort; kein Replay früherer Events" },
        { aspect: "Nachweis", before: "Keiner", after: "Consent-Snapshot mit jedem Event gespeichert" },
      ],
    },
    faq: [{ q: "Welche Regionen werden unterstützt?", a: "Striktes Opt-in für EU/EWR/UK/CH als Standard; regionale Policies sind konfigurierbar, aber nie schwächer als die rechtliche Basis ohne explizite Entscheidung." }],
  },
  {
    slug: "attribution",
    title: "Click-IDs und Attribution richtig gemacht",
    short: "Nur die IDs erfassen, die die Destination braucht, nur mit Consent, nur für das dokumentierte Zeitfenster.",
    benefit: "Deine Kampagnen bekommen die Click-IDs, die sie brauchen, um eine Conversion zuzuordnen — und keine Plattform erhält je eine ID, die zu einer anderen gehört.",
    intro: "Der Tracker erfasst gclid, fbclid, ttclid, msclkid, li_fat_id und die anderen Plattform-Click-IDs auf Landingpages nach Marketing-Consent, speichert sie First-Party für das Zeitfenster des Anbieters und leitet jede ID nur an die Plattform weiter, zu der sie gehört.",
    flow: {
      title: "Jede ID reist zu genau einer Plattform",
      text: "Eine Landingpage mit gclid und fbclid erzeugt nach Marketing-Consent zwei gespeicherte IDs. Kommt der Kauf an, hängt Track die gclid an die Google-Ads-Zustellung und die fbclid an die Meta-Zustellung — die Matrix wird maschinell geprüft, ein anbieterübergreifendes Leck ist also kein Konfigurationsfehler, den du machen kannst.",
      caption: "Landingpage → First-Party-Click-ID-Speicher → Kauf → Weitergabe pro Destination.",
    },
    viewCaption: "Beispielmatrix: welche Click-ID erfasst wird, wohin sie weitergegeben wird und wie lange sie aufbewahrt wird.",
    sections: [
      { title: "Weitergabe pro Destination", text: "Meta sieht nie deine gclid und Google nie deine fbclid. Die Policy-Matrix wird maschinell geprüft." },
      { title: "Deduplizierung auf Bestellebene", text: "Käufe tragen die Bestellnummer zu jedem Anbieter, der sie unterstützt, damit Browser- und Server-Conversions korrekt zusammenlaufen." },
      { title: "Offline und CRM", text: "Server-Events mit Offline-Flag erreichen Google Ads, CM360, Microsoft, Meta, TikTok, Pinterest, Snapchat, Amazon, Yahoo und LinkedIn als Offline-Conversions." },
    ],
    bullets: ["Dokumentierte Aufbewahrung pro Click-ID (standardmäßig 90 Tage)", "Enhanced Conversions mit normalisiertem Hashing", "Affiliate-Netzwerke mit Click-IDs pro Netzwerk"],
    comparison: {
      title: "URL-Parameter im dataLayer versus zweckgebundener Click-ID-Speicher",
      text: "Der Unterschied zwischen alles sammeln und weitergeben, was wohin gehört.",
      beforeLabel: "Click-IDs im dataLayer",
      afterLabel: "Click-ID-Speicher in Track",
      rows: [
        { aspect: "Erfassung", before: "Jeder Parameter, auf jeder Seite, unabhängig vom Consent", after: "Nur bekannte IDs, auf Landingpages, nach Marketing-Consent" },
        { aspect: "Weitergabe", before: "Was eine Tag-Vorlage eben ausliest", after: "Pro Destination aus einer maschinell geprüften Matrix" },
        { aspect: "Aufbewahrung", before: "Cookie-Laufzeit von jedem Tag selbst gesetzt", after: "Dokumentiertes Zeitfenster pro ID, standardmäßig 90 Tage" },
        { aspect: "Offline-Conversions", before: "Manuelle Uploads", after: "Server-Events mit Offline-Flag" },
      ],
    },
    faq: [{ q: "Baut ihr seitenübergreifende Profile?", a: "Nein. Es gibt kein Fingerprinting und keine seitenübergreifende Identität; Kennungen bleiben innerhalb der Site und der eingewilligten Zwecke." }],
  },
];

export const FEATURES_PAGE_COPY_DE: FeaturesPageCopy = {
  eyebrow: "Funktionen",
  title: "Jede Conversion einmal zugestellt, mit Consent, an die Plattform, zu der sie gehört",
  text: "Track ersetzt den Tag-Container durch eine geführte Einrichtung, einen consent-konformen serverseitigen Router und einen Debugger, der jedes Event erklärt. Diese Seite zeigt das Produkt, wie es arbeitet — die Zustände unten sind Beispieldaten, kein Live-Traffic.",
  cta: "Mit deiner Domain starten",
  ctaSecondary: "So funktioniert es",
  stage: {
    title: "Datenfluss von der Website über Track zu den Destinationen",
    description: "Eine Website sendet Events aus dem Browser-SDK und vom Server an Track. Track prüft Consent an einem Policy-Gate und leitet jedes Event nur an Destinationen weiter, deren Zweck erteilt wurde: Meta, Google Ads, Google Analytics 4 und TikTok.",
    caption: "Website → Track → Consent/Policy → Destinationen. Browser und Server teilen eine Event-ID; das Gate entscheidet pro Destination.",
  },
  scenarios: {
    title: "Was mit einem Kauf passiert",
    text: "Wechsle das Szenario, um zu sehen, wie dasselbe Event geroutet wird, wenn Consent erteilt oder widerrufen wurde oder ein Anbieter ausfällt. Entscheidung und Grund sind das, was du später im Debugger liest.",
    tabsLabel: "Routing-Szenarien",
    items: [
      {
        id: "granted",
        label: "Consent erteilt",
        title: "Analyse und Marketing erteilt",
        text: "Der Kauf kommt aus dem Browser und vom Server mit derselben Event-ID. Das Gate findet die nötigen Zwecke und leitet ihn an alle vier Destinationen weiter; Meta und TikTok deduplizieren über die Event-ID, Google Ads über die Bestellnummer.",
        points: ["Entscheidung: zugestellt an Meta, Google Ads, GA4, TikTok", "Deduplizierung: Event-ID (Meta, TikTok), Bestellnummer (Google Ads)", "Click-IDs pro Destination angehängt: gclid → Google, fbclid → Meta"],
      },
      {
        id: "withdrawn",
        label: "Marketing widerrufen",
        title: "Analyse erteilt, Marketing verweigert",
        text: "Der Besucher hat den Marketing-Consent vor dem Kauf widerrufen. Das Gate lässt das Event zu Google Analytics 4 durch und blockiert die Werbe-Destinationen mit dem Grund purpose_not_granted. Nichts wird für später gespeichert; wird Consent wieder erteilt, werden frühere Events nicht nachgeliefert.",
        points: ["Entscheidung: zugestellt an GA4; blockiert für Meta, Google Ads, TikTok", "Grund im Debugger: purpose_not_granted (marketing)", "Consent Mode v2: analytics_storage granted, ad_storage denied"],
      },
      {
        id: "outage",
        label: "Anbieter ausgefallen",
        title: "Consent erteilt, ein Anbieter nicht erreichbar",
        text: "TikTok antwortet mit einem Serverfehler. Track wiederholt mit Jitter-Backoff, öffnet nach wiederholten Fehlern den Circuit Breaker und parkt das Event in der Dead-Letter-Queue. Die anderen drei Destinationen sind nicht betroffen. Sobald TikTok wieder erreichbar ist, wird die Dead-Letter-Queue erneut gesendet.",
        points: ["Entscheidung: zugestellt an Meta, Google Ads, GA4; TikTok wird wiederholt", "Circuit Breaker für TikTok offen; Events in der Dead-Letter-Queue", "Replay nach der Erholung behält die ursprüngliche Event-ID, nichts zählt doppelt"],
      },
    ],
  },
  index: {
    title: "Sechs Fähigkeiten, eine Event-Ebene",
    text: "Jede Fähigkeit baut auf derselben signierten Konfiguration und demselben Eventschema auf. Öffne eine Fähigkeit für Produktansicht, Datenfluss und einen Vorher/Nachher-Vergleich.",
    more: "Mehr lesen",
  },
  comparison: {
    title: "Tag-Container versus Event-Ebene",
    text: "Wo ein klassischer Container die Arbeit dir überlässt und wo Track sie von Grund auf erledigt.",
    beforeLabel: "Klassischer Tag-Container",
    afterLabel: "Track",
    rows: [
      { aspect: "Was auf deiner Site läuft", before: "Custom-HTML- und JavaScript-Tags von allen mit Container-Zugriff", after: "Ein Snippet und eine signierte, versionierte Konfiguration — keine Ausführung von Custom-Code" },
      { aspect: "Consent", before: "Trigger-Bedingungen pro Tag, von Hand gepflegt", after: "Policy-Engine, die jedes Event für jede Destination prüft, im Browser und auf dem Server" },
      { aspect: "Serverseitige Zustellung", before: "Ein zweiter Container, ein zweiter Satz Tags, manuelle Deduplizierung", after: "Eingebaut: gemeinsame Event-ID, Retries, Circuit Breaker, Replay" },
      { aspect: "Fehler finden", before: "Vorschaumodus und Anbieter-Oberflächen", after: "Event-Herkunft mit Consent-Snapshot, Routing-Entscheidung und Anbieterantwort" },
      { aspect: "Änderungen", before: "Veröffentlichen und hoffen", after: "Diff, Freigabe, signierte Version, Rollback per Klick" },
    ],
  },
  trust: {
    title: "Fakten, die du prüfen kannst",
    items: [
      { title: "EU-Datenregion", text: "Events werden in der EU verarbeitet; Anbieter-APIs erhalten nur die Felder, die du gemappt hast, auf der pro Destination dokumentierten Übermittlungsgrundlage." },
      { title: "Signierte Konfigurationen", text: "Jedes veröffentlichte Bundle ist unveränderlich, versioniert und Ed25519-signiert; das SDK prüft die Signatur, bevor es sie anwendet." },
      { title: "Kein Custom-Code", text: "Es gibt keinen Custom-HTML- oder JavaScript-Tagtyp. Transformationen sind deklarativ und werden auf dem Server validiert." },
      { title: "Striktes Opt-in als Standard", text: "EU/EWR/UK/CH starten mit striktem Opt-in; abgeleiteter Consent wird nie an Werbeplattformen exportiert." },
    ],
  },
  closing: { title: "Sieh diese Ansichten mit deinen eigenen Events", text: "Site anlegen, Snippet einfügen und den Assistenten die erste Destination einrichten lassen — Debugger und Health-Score füllen sich ab dem ersten Event.", cta: "Mit deiner Domain starten", secondary: "Preise ansehen" },
};

export const FEATURE_DETAIL_COPY_DE: FeatureDetailLabels = {
  features: "Funktionen",
  breadcrumb: "Navigationspfad",
  howBuilt: "So ist es gebaut",
  howBuiltText: "Die technischen Entscheidungen hinter der Fähigkeit — der Beleg nach dem Nutzen.",
  proof: "Was du prüfen kannst",
  proofText: "Produktfakten, die du im Dashboard, in der Dokumentation und im Audit-Log findest.",
  faq: "Fragen",
  more: "Weitere Fähigkeiten",
  moreText: "Gebaut auf derselben signierten Konfiguration und demselben Eventschema.",
  cta: "Auf deiner Domain ausprobieren",
  ctaText: "Site anlegen, ein Snippet installieren und den Assistenten in Minuten die erste Destination einrichten lassen.",
  start: "Kostenlos starten",
  pricing: "Preise ansehen",
};

export const FEATURE_UI_COPY_DE: FeatureUiCopy = {
  example: "Beispieldaten",
  exampleHint: "Statischer Beispielzustand — kein Live-Traffic, keine echten Kundendaten.",
  diagram: {
    website: "Website",
    browser: "Browser-SDK",
    server: "Server-API",
    track: "Track",
    gate: "Consent / Policy",
    gateGranted: "Consent erteilt",
    gateDenied: "Marketing verweigert",
    gatePending: "Consent ausstehend",
    dedup: "eine Event-ID",
    notUsed: "nicht genutzt",
    delivered: "zugestellt",
    blocked: "blockiert",
    retrying: "wird wiederholt",
    paused: "pausiert",
    destinations: { meta: "Meta", googleAds: "Google Ads", ga4: "GA4", tiktok: "TikTok", linkedin: "LinkedIn" },
    describe: (paths, gate) => {
      const origin = paths === "browser" ? "nur aus dem Browser-SDK" : paths === "server" ? "nur aus der Server-API" : "aus Browser-SDK und Server-API mit einer gemeinsamen Event-ID";
      const decision = gate === "granted" ? "das Consent-Gate ist offen und die Events erreichen die Destinationen" : gate === "denied" ? "das Consent-Gate blockiert Werbe-Destinationen und nur die Analyse erhält das Event" : "das Consent-Gate wartet auf ein Signal und nichts wird weitergeleitet";
      return `Die Website sendet Events ${origin} an Track; ${decision}.`;
    },
    chains: {
      setup: { ai: "Track AI", aiSub: "schlägt vor", tools: "Typisierte Tools", toolsSub: "serverseitig validiert", approval: "Deine Freigabe", approvalSub: "an das Diff gebunden", config: "Signierte Config", configSub: "Version 13", website: "Website", websiteSub: "prüft Signatur", describe: "Track AI schlägt Änderungen über typisierte, serverseitig validierte Tools vor; deine an das Diff gebundene Freigabe veröffentlicht eine signierte Konfiguration, die die Website vor dem Laden prüft." },
      health: { events: "Events", eventsSub: "letzter Zeitraum", checks: "Prüfungen", checksSub: "Consent · Schema · Zustellung", score: "Score 86", scoreSub: "6 gewichtete Komponenten", issues: "2 Probleme", issuesSub: "jedes benennt seine Lösung", describe: "Die Events des letzten Zeitraums laufen durch die Prüfungen; sechs gewichtete Komponenten bilden den Score, und jedes offene Problem benennt das Tool, das es löst." },
      attribution: { landing: "Landingpage", landingSub: "gclid · fbclid", consent: "Marketing-Consent", consentSub: "erteilt", store: "Click-ID-Speicher", storeSub: "First-Party · 90 Tage", purchase: "Kauf", purchaseSub: "3 Tage später", google: "Google Ads", googleSub: "nur gclid", meta: "Meta", metaSub: "nur fbclid", describe: "Eine Landingpage mit gclid und fbclid speichert beide IDs nach Marketing-Consent First-Party; der Kauf drei Tage später erreicht Google Ads nur mit der gclid und Meta nur mit der fbclid." },
    },
  },
  stream: {
    title: "Live-Events",
    caption: "Jede Zeile ist ein Event mit Ursprung, dem Consent zu diesem Zeitpunkt, der Routing-Entscheidung und den Destinationen.",
    columns: { event: "Event", origin: "Ursprung", consent: "Consent", decision: "Entscheidung", destination: "Destinationen" },
    rows: [
      { event: "page_view", origin: "Browser", consent: "Analyse", consentTone: "ok", decision: "zugestellt", decisionTone: "ok", destination: "GA4" },
      { event: "add_to_cart", origin: "Browser", consent: "Marketing", consentTone: "ok", decision: "zugestellt", decisionTone: "ok", destination: "Meta, TikTok" },
      { event: "purchase", origin: "Browser + Server", consent: "Marketing", consentTone: "ok", decision: "zugestellt, dedupliziert (Bestellnummer)", decisionTone: "ok", destination: "Meta CAPI, Google Ads" },
      { event: "purchase", origin: "Server", consent: "Marketing fehlt", consentTone: "bad", decision: "blockiert: consent_missing", decisionTone: "bad", destination: "Meta CAPI" },
      { event: "generate_lead", origin: "Browser", consent: "Marketing", consentTone: "ok", decision: "zugestellt", decisionTone: "ok", destination: "LinkedIn" },
    ],
  },
  lineage: {
    title: "Event-Herkunft",
    caption: "Ein Kauf, gelesen vom Ursprung bis zur Anbieterantwort.",
    facts: [
      { label: "Event", value: "purchase · evt_…7f2a" },
      { label: "Ursprung", value: "Browser-SDK + Server (Shop-Webhook)" },
      { label: "Konfiguration", value: "Version 12, Signatur geprüft" },
      { label: "Consent-Snapshot", value: "Analyse, Marketing · Quelle: CMP" },
      { label: "Click-IDs", value: "gclid (vor 3 Tagen erfasst)" },
    ],
    attempts: {
      title: "Zustellversuche",
      columns: { destination: "Destination", status: "Status", result: "Ergebnis" },
      rows: [
        { destination: "Meta Conversions API", status: "200", tone: "ok", result: "akzeptiert, dedupliziert über Event-ID" },
        { destination: "Google Ads", status: "200", tone: "ok", result: "akzeptiert, dedupliziert über Bestellnummer" },
        { destination: "TikTok Events API", status: "503", tone: "warn", result: "Versuch 2 mit Backoff geplant" },
      ],
    },
    payload: { title: "Geschwärzte Payload", copy: "Payload kopieren", copied: "Kopiert", code: PAYLOAD_EXAMPLE },
  },
  health: {
    title: "Tracking-Zustand",
    caption: "Gewichtete Komponenten; ein niedrigerer Score zeigt immer auf seine Ursache.",
    scoreLabel: "Score",
    score: 86,
    componentsLabel: "Komponenten",
    weight: (percent) => `${percent} % Gewicht`,
    components: [
      { key: "consent", label: "Consent-Abdeckung", score: 91, weight: 20, detail: "91 % der Events tragen ein explizites Consent-Signal" },
      { key: "coverage", label: "Kritische Events", score: 78, weight: 25, detail: "7 von 9 geplanten kritischen Events gesehen" },
      { key: "schema", label: "Schemaqualität", score: 74, weight: 15, detail: "74 % der Events bestehen Schema- und PII-Prüfungen" },
      { key: "dedup", label: "Duplikate", score: 96, weight: 10, detail: "1,0 % Duplikate" },
      { key: "delivery", label: "Zustellung", score: 88, weight: 20, detail: "94 % zugestellt, 1 Integration mit Credential-Problemen" },
      { key: "liveness", label: "Aktualität", score: 100, weight: 10, detail: "Letztes Browser-Event vor 4 Minuten" },
    ],
    issuesLabel: "Offene Probleme",
    issues: [
      { title: "purchase ohne currency", detail: "12 Events in den letzten 24 h fehlt der Pflichtparameter", fix: "Lösung: Event-Mapping aktualisieren", tone: "warn" },
      { title: "Consent-Signal fehlt", detail: "9 % der Events kamen ohne expliziten Consent-Zustand an", fix: "Lösung: CMP-Adapter verbinden", tone: "warn" },
    ],
  },
  consent: {
    title: "Consent-Zustand und abgeleitete Signale",
    caption: "Zwecke kommen aus deinem CMP; alles andere wird abgeleitet, nie geraten.",
    purposesLabel: "Zwecke",
    purposes: [
      { label: "Technisch erforderlich", granted: true },
      { label: "Analyse", granted: true },
      { label: "Marketing", granted: false },
      { label: "Personalisierung", granted: false },
    ],
    granted: "erteilt",
    denied: "verweigert",
    flagsLabel: "Consent Mode v2",
    flags: [
      { key: "analytics_storage", value: "granted" },
      { key: "ad_storage", value: "denied" },
      { key: "ad_user_data", value: "denied" },
      { key: "ad_personalization", value: "denied" },
    ],
    reasonsLabel: "Blockgründe, die die Policy-Engine meldet",
    reasons: [
      { code: "consent_missing", text: "noch kein Consent-Signal für das Event" },
      { code: "consent_denied", text: "der Besucher hat abgelehnt" },
      { code: "purpose_not_granted", text: "die Destination braucht einen nicht erteilten Zweck" },
      { code: "gpc_opt_out", text: "Global Privacy Control gesetzt" },
      { code: "destination_paused", text: "Kill-Switch oder Circuit Breaker" },
      { code: "inferred_data_not_exportable", text: "abgeleiteter Consent erreicht nie Werbeplattformen" },
    ],
  },
  attribution: {
    title: "Click-ID-Matrix",
    caption: "Nach Marketing-Consent erfasst, First-Party gespeichert, nur an die zugehörige Plattform weitergegeben.",
    columns: { id: "Click-ID", captured: "Erfasst", forwarded: "Weitergabe nur an", retention: "Aufbewahrt" },
    rows: [
      { id: "gclid", captured: "Landingpage, nach Marketing-Consent", forwarded: "Google Ads, GA4, Google Marketing Platform", retention: "90 Tage" },
      { id: "fbclid", captured: "Landingpage, nach Marketing-Consent", forwarded: "Meta", retention: "90 Tage" },
      { id: "ttclid", captured: "Landingpage, nach Marketing-Consent", forwarded: "TikTok", retention: "90 Tage" },
      { id: "msclkid", captured: "Landingpage, nach Marketing-Consent", forwarded: "Microsoft Advertising", retention: "90 Tage" },
      { id: "li_fat_id", captured: "Landingpage, nach Marketing-Consent", forwarded: "LinkedIn", retention: "90 Tage" },
    ],
    note: "Die Aufbewahrung ist pro ID dokumentiert und konfigurierbar; 90 Tage sind der Standard.",
  },
  setup: {
    title: "Geführte Einrichtung",
    caption: "Der Assistent schlägt vor, Tools validieren, du gibst frei.",
    assistant: "Track AI",
    you: "Du",
    messages: [
      { from: "assistant", text: "example-shop.test läuft auf Shopify mit Cookiebot als Consent-Tool (hohe Konfidenz). Für einen Shop schlage ich view_item, add_to_cart, begin_checkout und purchase vor. Soll ich den Plan für Meta und Google Ads entwerfen?" },
      { from: "you", text: "Ja, Meta zuerst." },
      { from: "assistant", text: "Pixel-ID geprüft. Die Conversions API braucht einen Access-Token — bitte in der Tresor-Karte unten eingeben; er erscheint nie in diesem Chat." },
    ],
    vault: { title: "Tresor-Karte · Meta-Access-Token", text: "Verschlüsselt gespeichert; für niemanden sichtbar, auch nicht für das Modell.", state: "gespeichert" },
    test: { title: "Testevent · purchase", text: "Durch die echte Pipeline gesendet, mit dem Test-Event-Code des Anbieters.", state: "von Meta akzeptiert" },
    approval: {
      title: "Version 13 veröffentlichen",
      text: "Gebunden an genau dieses Diff und an dich als freigebende Person.",
      diff: ["+ destination meta: browser + server", "+ mapping purchase → Purchase (event id, order id)", "~ consent: marketing required for meta"],
      state: "wartet auf deine Freigabe",
      action: "Freigeben und veröffentlichen",
    },
  },
  destinations: {
    title: "Destination Health",
    caption: "Zustand, Modus und Queue pro Destination; Fehler werden behandelt, nicht versteckt.",
    columns: { destination: "Destination", mode: "Modus", health: "Zustand", last: "Letzte Zustellung", queue: "Queue" },
    rows: [
      { destination: "Meta", mode: "Browser + Server", health: "gesund", tone: "ok", last: "vor 12 s", queue: "0 Retries" },
      { destination: "Google Ads", mode: "Server", health: "gesund", tone: "ok", last: "vor 40 s", queue: "0 Retries" },
      { destination: "TikTok", mode: "Browser + Server", health: "beeinträchtigt, Circuit Breaker offen", tone: "warn", last: "vor 6 min", queue: "3 in der Dead-Letter-Queue" },
      { destination: "LinkedIn", mode: "Server", health: "per Kill-Switch pausiert", tone: "neutral", last: "vor 2 h", queue: "zurückgehalten" },
    ],
  },
};
