import type { FeatureCopy, FeatureDetailLabels, FeatureUiCopy, FeaturesPageCopy } from "../types";
import { PAYLOAD_EXAMPLE } from "./samples";

/**
 * Spanish (es, European Spanish, tuteo) copy of the features area. Same shape as en.ts; see docs/14-localization.md.
 */

export const FEATURES_ES: FeatureCopy[] = [
  {
    slug: "ai-setup",
    title: "Configuración guiada por IA",
    short: "Describe tu sitio, confirma cada paso, publica una configuración firmada.",
    benefit: "Tu primer destino entra en producción en una sola sesión guiada, sin escribir una etiqueta y sin renunciar al control sobre lo que se publica.",
    intro: "El asistente convierte un dominio en una configuración de medición operativa: detecta la plataforma y la herramienta de consentimiento, propone un plan de eventos para tu tipo de negocio, recoge los identificadores públicos en el chat y los secretos en una tarjeta segura de credenciales, envía un evento de prueba real y prepara un diff de publicación que tú apruebas.",
    flow: {
      title: "Cada acción es una llamada a una herramienta tipada que puedes ver",
      text: "El asistente nunca ejecuta código libre. Llama a herramientas validadas en el servidor: detectar la plataforma, redactar el plan de eventos, validar un ID de píxel, enviar un evento de prueba, preparar un diff. Todo lo irreversible (publicar, rollback, rotación de credenciales) se detiene en una tarjeta de aprobación vinculada exactamente al cambio que estás viendo.",
      caption: "Asistente → herramientas tipadas → tarjeta de aprobación → configuración firmada. Los secretos van directamente al almacén cifrado y nunca pasan por el chat.",
    },
    viewCaption: "Sesión de ejemplo: plataforma detectada, plan de eventos propuesto, token guardado en el almacén cifrado, evento de prueba real aceptado, publicación a la espera de tu aprobación.",
    sections: [
      { title: "Herramientas tipadas en lugar de acciones libres", text: "Cada acción del asistente es una llamada a una herramienta validada en el servidor, con comprobación de roles, entrada de auditoría y, para todo lo irreversible, un token de aprobación vinculado al diff exacto que viste." },
      { title: "Los secretos nunca llegan al modelo", text: "Los tokens de acceso van directamente al almacén cifrado a través de una tarjeta dedicada u OAuth. La transcripción, el modelo y el navegador nunca los ven; una capa DLP censura los secretos y la PII que se peguen." },
      { title: "Máquina de estados determinista", text: "La configuración sigue una máquina de estados explícita con requisitos y evidencias para cada estado. Los mismos estados están disponibles como asistente basado en reglas cuando el proveedor de IA no está disponible: nada depende de que un modelo esté en línea." },
    ],
    bullets: ["Detección del tipo de negocio y la plataforma con un nivel de confianza", "Plantillas de plan de eventos para tiendas, generación de leads, SaaS y publishers", "IDs públicos validados contra los formatos de los proveedores", "Publicación solo tras el diff, la lista de destinatarios y una confirmación explícita"],
    comparison: {
      title: "Configuración manual frente a sesión guiada",
      text: "Lo que cambia cuando el asistente dirige la configuración y tú conservas las aprobaciones.",
      beforeLabel: "Configuración manual del contenedor",
      afterLabel: "Configuración guiada con Track",
      rows: [
        { aspect: "Plan de eventos", before: "Escrito de memoria, una etiqueta cada vez", after: "Propuesto para tu tipo de negocio, editado en el chat, validado antes de publicar" },
        { aspect: "Credenciales", before: "Pegadas en campos de etiquetas y visibles para cualquiera con acceso al contenedor", after: "Introducidas en una tarjeta segura de credenciales o mediante OAuth; nunca se muestran en la transcripción" },
        { aspect: "Verificación", before: "Esperar que el proveedor haya recibido algo", after: "Un evento de prueba real a través del pipeline real, con el veredicto del proveedor" },
        { aspect: "Publicación", before: "Publicar y después descubrir qué ha cambiado", after: "Primero diff, destinatarios y aprobación; después un bundle firmado y versionado" },
      ],
    },
    faq: [
      { q: "¿Puede el asistente publicar sin mí?", a: "No. Publicar, hacer rollback, rotar credenciales y activar destinos requieren siempre tu clic en una tarjeta de aprobación vinculada al cambio exacto." },
      { q: "¿Qué modelo se utiliza?", a: "OpenAI Responses API con structured outputs y function calling estricto. Los nombres de los modelos se configuran en el servidor y se verifican al arrancar; la interfaz nunca los incluye de forma fija." },
    ],
  },
  {
    slug: "server-side-tracking",
    title: "Router de eventos server-side",
    short: "Un evento, todas las plataformas: entrega desde el navegador y el servidor con deduplicación compartida.",
    benefit: "Envía cada conversión una sola vez y deja que cada plataforma la reciba de la forma en que mejor la contabiliza (navegador, servidor o ambos) sin contarla dos veces.",
    intro: "Track recibe eventos del SDK del navegador, de tu servidor, de plataformas de e-commerce y de redes de afiliación, los normaliza en un único esquema, aplica el consentimiento y los enruta a 22 tipos de destino con reintentos, circuit breakers, una cola de mensajes fallidos y reenvío.",
    flow: {
      title: "El navegador y el servidor comparten un ID de evento",
      text: "El SDK del navegador y tu servidor (o el webhook de tu tienda) envían la misma compra con el mismo ID de evento. Track normaliza ambos, evalúa el consentimiento por destino y los transmite; Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn y los demás deduplican por ese ID, Google Ads por el ID de pedido.",
      caption: "Sitio web → Track → Consentimiento/política → Destinos. Ambos orígenes terminan en los mismos destinos y allí se deduplican.",
    },
    viewCaption: "Ejemplo de Destination Health: dos destinos correctos, una caída de proveedor gestionada por el circuit breaker y un destino pausado por un kill switch.",
    sections: [
      { title: "Híbrido por defecto", text: "Cada destino puede funcionar con etiqueta en el navegador, API de servidor o ambas. Los dos caminos comparten un ID de evento, de modo que Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn y los demás deduplican de forma fiable." },
      { title: "Duradero y observable", text: "Una cola duradera con mensajes idempotentes, reintentos por destino con backoff con jitter, circuit breakers ante proveedores que fallan, almacenamiento de mensajes fallidos y reenvío. Cada intento se registra con una vista previa censurada del payload." },
      { title: "First-party por diseño", text: "El tracker se sirve desde tu host CDN, los eventos van a tu host de ingesta y los bundles de configuración están firmados con Ed25519 y se verifican en el navegador antes de cargar nada." },
    ],
    bullets: ["SDK del navegador por debajo de 30 KB gzip gracias a un presupuesto en CI, con almacenamiento condicionado al consentimiento", "API de servidor con claves de origen para CRM y conversiones offline", "Kill switches por sitio y por organización", "Plano de datos en la UE con aislamiento por tenant a nivel de fila"],
    comparison: {
      title: "Etiquetas solo en el navegador frente al router híbrido",
      text: "Por qué un evento a través de Track vale más que el mismo píxel disparado dos veces.",
      beforeLabel: "Etiquetas solo en el navegador",
      afterLabel: "Navegador + servidor con Track",
      rows: [
        { aspect: "Eventos perdidos", before: "Los scripts bloqueados y las pestañas cerradas simplemente pierden la conversión", after: "El camino del servidor la entrega igualmente; el del navegador añade datos de coincidencia cuando están disponibles" },
        { aspect: "Duplicados", before: "El píxel y la API de servidor cuentan el mismo pedido dos veces", after: "ID de evento e ID de pedido compartidos; los proveedores deduplican" },
        { aspect: "Caída del proveedor", before: "Fallo silencioso, sin reintento", after: "Reintentos con backoff, circuit breaker, cola de mensajes fallidos y reenvío" },
        { aspect: "Adónde van los datos", before: "Endpoints de terceros llamados desde la página", after: "Host de ingesta first-party; los proveedores solo reciben los campos mapeados" },
      ],
    },
    faq: [
      { q: "¿El tracking server-side elude el consentimiento?", a: "No. El consentimiento se evalúa para cada evento y cada destino; sin la finalidad requerida no se almacena, envía ni reenvía nada más tarde." },
      { q: "¿Qué ocurre cuando un proveedor está caído?", a: "Las entregas se reintentan con backoff, el circuit breaker pausa el destino, los eventos fallidos van a la cola de mensajes fallidos y pueden reenviarse cuando el proveedor se recupera." },
    ],
  },
  {
    slug: "event-debugger",
    title: "Depurador de eventos y trazabilidad",
    short: "Ve cada evento con su instantánea de consentimiento, su decisión de enrutamiento y la respuesta del proveedor.",
    benefit: "Cuando una cifra en una plataforma publicitaria parece incorrecta, descubres por qué en un solo lugar, sin adivinar entre la consola del navegador, la interfaz del proveedor y la memoria de un compañero.",
    intro: "Abre cualquier evento y lee su historia: origen y versión del SDK, el consentimiento concedido en ese momento, los IDs de clic capturados, la versión de la configuración que lo enrutó y el intento de entrega por destino, incluidos el payload censurado y la respuesta del proveedor.",
    flow: {
      title: "Un evento, todo el recorrido",
      text: "El depurador sigue un evento desde el origen, pasando por la normalización, la decisión de consentimiento y cada intento de entrega. Los descartes nunca son silenciosos: cada uno lleva un motivo, como consentimiento ausente, PII bloqueada, nombre no válido, duplicado o destino pausado.",
      caption: "La trazabilidad mantiene juntos el origen, la instantánea de consentimiento, la decisión de enrutamiento y la respuesta de cada proveedor.",
    },
    viewCaption: "Flujo de eventos de ejemplo: eventos entregados, una compra deduplicada y una compra de servidor bloqueada por falta de la finalidad de marketing.",
    sections: [
      { title: "Censurado, no oculto", text: "Las vistas previas del payload muestran la estructura y los identificadores con hash para que puedas verificar los mapeos sin exponer datos personales ni tokens." },
      { title: "Eventos de prueba a través del pipeline real", text: "Los eventos de prueba se marcan, pasan por la misma cola y el mismo worker e informan del veredicto del proveedor: ningún éxito simulado." },
      { title: "Los descartes se explican", text: "Cada evento descartado lleva un motivo: consentimiento ausente, PII bloqueada, nombre no válido, duplicado, destino pausado o bloqueo por política." },
    ],
    bullets: ["Filtra por nombre de evento, estado y origen", "Historial de intentos por destino con estado HTTP y clase de error", "Indicaciones del modo de prueba de cada proveedor por plataforma", "Enlaces directos al asistente de destinos"],
    comparison: {
      title: "Depurar con la consola frente a depurar con la trazabilidad",
      text: "La misma pregunta (¿por qué esta compra no llegó a Meta?) respondida de dos maneras.",
      beforeLabel: "Consola del navegador e interfaz del proveedor",
      afterLabel: "Trazabilidad de eventos en Track",
      rows: [
        { aspect: "Dónde mirar", before: "Pestaña de red, modo de vista previa de etiquetas, el gestor de eventos del proveedor", after: "Un único registro de evento con cada intento y cada respuesta" },
        { aspect: "Consentimiento en ese momento", before: "Desconocido; reconstruido a partir de la configuración del banner", after: "Guardado como instantánea junto con el evento" },
        { aspect: "Eventos server-side", before: "Invisibles desde el navegador", after: "La misma trazabilidad, marcados con su origen" },
        { aspect: "Datos personales", before: "Payloads en bruto en logs y capturas de pantalla", after: "Identificadores con hash, vistas previas censuradas" },
      ],
    },
    faq: [{ q: "¿Cuánto tiempo se conservan los registros del depurador?", a: "Los intentos de entrega, 90 días por defecto; los eventos, 13 meses. Ambos plazos se pueden configurar por organización en el centro de privacidad." }],
  },
  {
    slug: "data-quality",
    title: "Calidad de datos y Health Score",
    short: "Una única puntuación con componentes explicables e incidencias que enlazan con su solución.",
    benefit: "Entérate cuando el tracking se rompe, ve qué parte ha fallado y salta directamente a la solución, antes de que una campaña se ejecute con datos erróneos.",
    intro: "El worker calcula un Tracking Health Score a partir de la cobertura de consentimiento, la cobertura de eventos críticos, la calidad del esquema, la tasa de duplicados, el éxito de entrega y la actualidad. Cada incidencia detectada indica la herramienta del asistente que la resuelve.",
    flow: {
      title: "Seis componentes, una puntuación explicable",
      text: "La puntuación se calcula a partir de los eventos del último periodo: cuántos llevan una señal explícita de consentimiento, qué eventos críticos planificados se han visto, cuántos superan las comprobaciones de esquema y PII, la tasa de duplicados, el éxito de entrega por destino y cuándo llegó el último evento del navegador. Los pesos se muestran junto a la puntuación, de modo que una cifra más baja siempre señala su causa.",
      caption: "Eventos → comprobaciones → componentes ponderados → puntuación con las incidencias que la han reducido.",
    },
    viewCaption: "Puntuación de ejemplo con sus seis componentes y dos incidencias abiertas, cada una con la herramienta que la corrige.",
    sections: [
      { title: "Incidencias con huella", text: "Los problemas recurrentes se agrupan, se cuentan y se fechan para que veas tendencias en lugar de ruido." },
      { title: "Barreras de esquema", text: "Los eventos estándar tienen parámetros obligatorios; los eventos personalizados siguen reglas de nomenclatura; la PII en las propiedades se bloquea antes de almacenarse." },
      { title: "Benchmarks solo con opt-in", text: "Los benchmarks anonimizados y agregados solo están disponibles para las organizaciones que optan por participar." },
    ],
    bullets: ["Puntuación por sitio con sus componentes", "Resuelve o ignora incidencias con traza de auditoría", "Cobertura de consentimiento y tasa de duplicados como métricas de primer nivel"],
    comparison: {
      title: "Darse cuenta de los problemas frente a que te avisen",
      text: "Cómo aflora un evento de compra roto con y sin el Health Score.",
      beforeLabel: "Sin monitorización",
      afterLabel: "Con el Health Score",
      rows: [
        { aspect: "Detección", before: "Alguien nota una caída en el panel de anuncios días después", after: "La puntuación baja y se abre una incidencia" },
        { aspect: "Diagnóstico", before: "¿Qué etiqueta, qué página, qué navegador?", after: "El componente que ha bajado y los eventos que hay detrás" },
        { aspect: "Solución", before: "Ticket, cambio de etiqueta, volver a publicar, esperar", after: "La incidencia indica la herramienta del asistente; tú apruebas el cambio" },
        { aspect: "Tendencia", before: "Sin historial", after: "Incidencias agrupadas, contadas y fechadas" },
      ],
    },
    faq: [{ q: "¿La puntuación es comparable entre sitios?", a: "Los componentes son idénticos para todos los sitios; los pesos están documentados en la tarjeta de puntuación para que los equipos puedan razonar sobre las diferencias." }],
  },
  {
    slug: "consent",
    title: "Consentimiento por diseño",
    short: "Opt-in estricto por defecto, Consent Mode v2, destinos basados en finalidades, sin reenvío tras el consentimiento.",
    benefit: "Cada destino recibe exactamente lo que el visitante ha aceptado, evaluado para cada evento, en el navegador y de nuevo en el servidor, de modo que el cumplimiento no es un ajuste del banner que esperas que sea correcto.",
    intro: "El consentimiento no es una integración con el banner, sino un motor de políticas: finalidades, regiones, requisitos de los destinos y captura de IDs de clic se evalúan para cada evento en el navegador y de nuevo en el servidor.",
    flow: {
      title: "El filtro está delante de cada destino",
      text: "Cada destino declara la finalidad que necesita. Cuando llega un evento, Track compara la instantánea de consentimiento con ese requisito: los destinos de analítica reciben eventos con consentimiento de analítica, los destinos publicitarios solo con consentimiento de marketing. Una retirada detiene los envíos de inmediato, y nada de lo almacenado antes del consentimiento se reenvía después.",
      caption: "Sitio web → Track → filtro de consentimiento/política → solo los destinos cuya finalidad se ha concedido.",
    },
    viewCaption: "Estado de consentimiento de ejemplo: analítica concedida, marketing denegado, y los indicadores de Consent Mode v2 y los motivos de bloqueo derivados de él.",
    sections: [
      { title: "Adaptadores de CMP y API", text: "TCF 2.2, GPP y Global Privacy Control, adaptadores para Cookiebot, OneTrust y Usercentrics, además de una API de consentimiento para banners personalizados." },
      { title: "Consent Mode v2, basado en finalidades", text: "Las señales de consentimiento de Google se derivan de las finalidades; el modo avanzado solo está disponible con una nota documentada de revisión jurídica." },
      { title: "Evidencia", text: "Las instantáneas de consentimiento deduplicadas se guardan con cada evento para que puedas demostrar qué se concedió y cuándo." },
    ],
    bullets: ["El consentimiento inferido nunca se exporta a las plataformas publicitarias", "La retirada detiene los envíos de inmediato", "Las compras de servidor siguen siendo operativas, pero nunca publicitarias sin consentimiento"],
    comparison: {
      title: "Consentimiento por etiqueta frente a un motor de políticas",
      text: "Dónde se toma la decisión y si podrás demostrarla más tarde.",
      beforeLabel: "Consentimiento gestionado por etiqueta",
      afterLabel: "Motor de políticas en Track",
      rows: [
        { aspect: "Punto de decisión", before: "El activador de cada etiqueta, configurado a mano", after: "Cada evento, cada destino, en el navegador y en el servidor" },
        { aspect: "Eventos server-side", before: "Enviados independientemente del banner", after: "La misma comprobación de finalidad que los eventos del navegador" },
        { aspect: "Retirada", before: "Surte efecto en la siguiente carga de página, si es que lo hace", after: "Detiene los envíos de inmediato; sin reenvío de eventos anteriores" },
        { aspect: "Evidencia", before: "Ninguna", after: "Instantánea de consentimiento guardada con cada evento" },
      ],
    },
    faq: [{ q: "¿Qué regiones se admiten?", a: "Opt-in estricto para UE/EEE/Reino Unido/Suiza por defecto; se pueden configurar políticas por región, pero nunca más laxas que la base legal sin una decisión explícita." }],
  },
  {
    slug: "attribution",
    title: "IDs de clic y atribución bien hechos",
    short: "Captura solo los IDs que el destino necesita, solo con consentimiento y solo durante la ventana documentada.",
    benefit: "Tus campañas reciben los IDs de clic que necesitan para atribuir una conversión, y ninguna plataforma recibe nunca un ID que pertenece a otra.",
    intro: "El tracker captura gclid, fbclid, ttclid, msclkid, li_fat_id y los demás IDs de clic de las plataformas en las landing pages tras el consentimiento de marketing, los almacena en modo first-party durante la ventana del proveedor y transmite cada ID solo a la plataforma a la que pertenece.",
    flow: {
      title: "Cada ID viaja exactamente a una plataforma",
      text: "Una landing page con un gclid y un fbclid genera dos IDs almacenados tras el consentimiento de marketing. Cuando llega la compra, Track adjunta el gclid a la entrega a Google Ads y el fbclid a la entrega a Meta; la matriz se comprueba automáticamente, así que una fuga entre proveedores no es un error de configuración que puedas cometer.",
      caption: "Landing page → almacén first-party de IDs de clic → compra → transmisión limitada por destino.",
    },
    viewCaption: "Matriz de ejemplo: qué ID de clic se captura, adónde se transmite y cuánto tiempo se conserva.",
    sections: [
      { title: "Transmisión limitada por destino", text: "Meta nunca ve tu gclid y Google nunca ve tu fbclid. La matriz de políticas se comprueba automáticamente." },
      { title: "Deduplicación a nivel de pedido", text: "Las compras llevan el ID de pedido a cada proveedor que lo admite, de modo que las conversiones del navegador y del servidor se fusionan correctamente." },
      { title: "Offline y CRM", text: "Los eventos de servidor con indicador offline llegan a Google Ads, CM360, Microsoft, Meta, TikTok, Pinterest, Snapchat, Amazon, Yahoo y LinkedIn como conversiones offline." },
    ],
    bullets: ["Retención documentada por ID de clic (90 días por defecto)", "Enhanced Conversions con hashing normalizado", "Redes de afiliación con IDs de clic por red"],
    comparison: {
      title: "Parámetros de URL en el dataLayer frente a un almacén de IDs de clic limitado por destino",
      text: "La diferencia entre recogerlo todo y transmitir cada cosa solo adonde pertenece.",
      beforeLabel: "IDs de clic en el dataLayer",
      afterLabel: "Almacén de IDs de clic en Track",
      rows: [
        { aspect: "Captura", before: "Todos los parámetros, en todas las páginas, con independencia del consentimiento", after: "Solo IDs conocidos, en landing pages, tras el consentimiento de marketing" },
        { aspect: "Transmisión", before: "Lo que lea una plantilla de etiqueta", after: "Por destino, a partir de una matriz comprobada automáticamente" },
        { aspect: "Retención", before: "Duración de cookie fijada por cada etiqueta", after: "Ventana documentada por ID, 90 días por defecto" },
        { aspect: "Conversiones offline", before: "Subidas manuales", after: "Eventos de servidor con indicador offline" },
      ],
    },
    faq: [{ q: "¿Creáis perfiles entre sitios?", a: "No. No hay fingerprinting ni identidad entre sitios; los identificadores permanecen dentro del sitio y de las finalidades consentidas." }],
  },
];

export const FEATURES_PAGE_COPY_ES: FeaturesPageCopy = {
  eyebrow: "Funcionalidades",
  title: "Cada conversión entregada una sola vez, con consentimiento, a la plataforma a la que pertenece",
  text: "Track sustituye el contenedor de etiquetas por una configuración guiada, un router server-side que respeta el consentimiento y un depurador que explica cada evento. Esta página muestra el producto tal como funciona: los estados de abajo son datos de ejemplo, no tráfico real.",
  cta: "Empieza con tu dominio",
  ctaSecondary: "Ver cómo funciona",
  stage: {
    title: "Flujo de datos desde el sitio web, a través de Track, hasta los destinos",
    description: "Un sitio web envía eventos desde el SDK del navegador y desde el servidor a Track. Track evalúa el consentimiento en un filtro de políticas y transmite cada evento solo a los destinos cuya finalidad se ha concedido: Meta, Google Ads, Google Analytics 4 y TikTok.",
    caption: "Sitio web → Track → Consentimiento/política → Destinos. El navegador y el servidor comparten un ID de evento; el filtro decide por destino.",
  },
  scenarios: {
    title: "Qué le pasa a una compra",
    text: "Cambia de escenario para ver cómo se enruta el mismo evento cuando el consentimiento se concede, se retira o un proveedor está caído. La decisión y su motivo son lo que después lees en el depurador.",
    tabsLabel: "Escenarios de enrutamiento",
    items: [
      {
        id: "granted",
        label: "Consentimiento concedido",
        title: "Analítica y marketing concedidos",
        text: "La compra llega desde el navegador y desde el servidor con el mismo ID de evento. El filtro encuentra las finalidades requeridas y la transmite a los cuatro destinos; Meta y TikTok deduplican por ID de evento, Google Ads por ID de pedido.",
        points: ["Decisión: entregado a Meta, Google Ads, GA4, TikTok", "Deduplicación: ID de evento (Meta, TikTok), ID de pedido (Google Ads)", "IDs de clic adjuntados por destino: gclid → Google, fbclid → Meta"],
      },
      {
        id: "withdrawn",
        label: "Marketing retirado",
        title: "Analítica concedida, marketing denegado",
        text: "El visitante retiró el consentimiento de marketing antes de la compra. El filtro deja pasar el evento a Google Analytics 4 y bloquea los destinos publicitarios con el motivo purpose_not_granted. No se guarda nada para más tarde; cuando el consentimiento se vuelve a conceder, los eventos anteriores no se reenvían.",
        points: ["Decisión: entregado a GA4; bloqueado para Meta, Google Ads, TikTok", "Motivo mostrado en el depurador: purpose_not_granted (marketing)", "Consent Mode v2: analytics_storage granted, ad_storage denied"],
      },
      {
        id: "outage",
        label: "Proveedor caído",
        title: "Consentimiento concedido, un proveedor no disponible",
        text: "TikTok responde con un error de servidor. Track reintenta con backoff con jitter, abre el circuit breaker tras fallos repetidos y aparca el evento en la cola de mensajes fallidos. Los otros tres destinos no se ven afectados. Cuando TikTok se recupera, la cola de mensajes fallidos se reenvía.",
        points: ["Decisión: entregado a Meta, Google Ads, GA4; TikTok en reintento", "Circuit breaker abierto para TikTok; eventos en la cola de mensajes fallidos", "El reenvío tras la recuperación conserva el ID de evento original, así que nada se cuenta dos veces"],
      },
    ],
  },
  index: {
    title: "Seis capacidades, una capa de eventos",
    text: "Cada capacidad se construye sobre la misma configuración firmada y el mismo esquema de eventos. Abre una capacidad para ver su vista del producto, su flujo de datos y una comparación antes/después.",
    more: "Leer más",
  },
  comparison: {
    title: "Contenedor de etiquetas frente a capa de eventos",
    text: "Dónde un contenedor clásico te deja el trabajo a ti y dónde Track lo hace por diseño.",
    beforeLabel: "Contenedor de etiquetas clásico",
    afterLabel: "Track",
    rows: [
      { aspect: "Lo que se ejecuta en tu sitio", before: "Etiquetas de HTML y JavaScript personalizados de cualquiera con acceso al contenedor", after: "Un snippet y una configuración firmada y versionada, sin ejecución de código personalizado" },
      { aspect: "Consentimiento", before: "Condiciones de activación por etiqueta, mantenidas a mano", after: "Motor de políticas que evalúa cada evento para cada destino, en el navegador y en el servidor" },
      { aspect: "Entrega server-side", before: "Un segundo contenedor, un segundo conjunto de etiquetas, deduplicación manual", after: "Integrada: ID de evento compartido, reintentos, circuit breakers, reenvío" },
      { aspect: "Encontrar errores", before: "Modo de vista previa e interfaces de los proveedores", after: "Trazabilidad del evento con instantánea de consentimiento, decisión de enrutamiento y respuesta del proveedor" },
      { aspect: "Cambios", before: "Publicar y esperar que salga bien", after: "Diff, aprobación, versión firmada, rollback con un clic" },
    ],
  },
  trust: {
    title: "Hechos que puedes verificar",
    items: [
      { title: "Región de datos de la UE", text: "Los eventos se tratan en la UE; las API de los proveedores solo reciben los campos que has mapeado, bajo la base de transferencia documentada por destino." },
      { title: "Configuraciones firmadas", text: "Cada bundle publicado es inmutable, versionado y firmado con Ed25519; el SDK verifica la firma antes de aplicarlo." },
      { title: "Sin código personalizado", text: "No existe ningún tipo de etiqueta de HTML o JavaScript personalizado. Las transformaciones son declarativas y se validan en el servidor." },
      { title: "Opt-in estricto por defecto", text: "UE/EEE/Reino Unido/Suiza empiezan con opt-in estricto; el consentimiento inferido nunca se exporta a las plataformas publicitarias." },
    ],
  },
  closing: { title: "Ve estas vistas con tus propios eventos", text: "Crea tu sitio, pega el snippet y deja que el asistente configure el primer destino: el depurador y el Health Score se llenan desde el primer evento.", cta: "Empieza con tu dominio", secondary: "Ver precios" },
};

export const FEATURE_DETAIL_COPY_ES: FeatureDetailLabels = {
  features: "Funcionalidades",
  breadcrumb: "Ruta de navegación",
  howBuilt: "Cómo está construido",
  howBuiltText: "Las decisiones técnicas detrás de la capacidad: la prueba después del beneficio.",
  proof: "Lo que puedes verificar",
  proofText: "Hechos del producto que encontrarás en el panel, en la documentación y en el registro de auditoría.",
  faq: "Preguntas",
  more: "Más capacidades",
  moreText: "Construidas sobre la misma configuración firmada y el mismo esquema de eventos.",
  cta: "Pruébalo con tu dominio",
  ctaText: "Crea un sitio, instala un snippet y deja que el asistente configure el primer destino en minutos.",
  start: "Empieza gratis",
  pricing: "Ver precios",
};

export const FEATURE_UI_COPY_ES: FeatureUiCopy = {
  example: "Datos de ejemplo",
  exampleHint: "Estado de ejemplo estático: no es tráfico real ni datos reales de clientes.",
  diagram: {
    website: "Sitio web",
    browser: "SDK del navegador",
    server: "API de servidor",
    track: "Track",
    gate: "Consentimiento / política",
    gateGranted: "consentimiento concedido",
    gateDenied: "marketing denegado",
    gatePending: "consentimiento pendiente",
    dedup: "un ID de evento",
    notUsed: "no se usa",
    delivered: "entregado",
    blocked: "bloqueado",
    retrying: "reintentando",
    paused: "pausado",
    destinations: { meta: "Meta", googleAds: "Google Ads", ga4: "GA4", tiktok: "TikTok", linkedin: "LinkedIn" },
    describe: (paths, gate) => {
      const origin = paths === "browser" ? "solo desde el SDK del navegador" : paths === "server" ? "solo desde la API de servidor" : "desde el SDK del navegador y la API de servidor con un ID de evento compartido";
      const decision = gate === "granted" ? "el filtro de consentimiento está abierto y los eventos llegan a los destinos" : gate === "denied" ? "el filtro de consentimiento bloquea los destinos publicitarios y solo la analítica recibe el evento" : "el filtro de consentimiento espera una señal y no se transmite nada";
      return `El sitio web envía eventos ${origin} a Track; ${decision}.`;
    },
    chains: {
      setup: { ai: "Track AI", aiSub: "propone", tools: "Herramientas tipadas", toolsSub: "validadas en el servidor", approval: "Tu aprobación", approvalSub: "vinculada al diff", config: "Config firmada", configSub: "versión 13", website: "Sitio web", websiteSub: "verifica la firma", describe: "Track AI propone cambios a través de herramientas tipadas y validadas en el servidor; tu aprobación, vinculada al diff, publica una configuración firmada que el sitio web verifica antes de cargarla." },
      health: { events: "Eventos", eventsSub: "último periodo", checks: "Comprobaciones", checksSub: "consentimiento · esquema · entrega", score: "Puntuación 86", scoreSub: "6 componentes ponderados", issues: "2 incidencias", issuesSub: "cada una indica su solución", describe: "Los eventos del último periodo pasan por las comprobaciones; seis componentes ponderados forman la puntuación, y cada incidencia abierta indica la herramienta que la resuelve." },
      attribution: { landing: "Landing page", landingSub: "gclid · fbclid", consent: "Consentimiento de marketing", consentSub: "concedido", store: "Almacén de IDs de clic", storeSub: "first-party · 90 días", purchase: "Compra", purchaseSub: "3 días después", google: "Google Ads", googleSub: "solo gclid", meta: "Meta", metaSub: "solo fbclid", describe: "Una landing page con gclid y fbclid almacena ambos IDs en modo first-party tras el consentimiento de marketing; la compra, tres días después, llega a Google Ads solo con el gclid y a Meta solo con el fbclid." },
    },
  },
  stream: {
    title: "Eventos en directo",
    caption: "Cada fila es un evento con su origen, el consentimiento en ese momento, la decisión de enrutamiento y los destinos.",
    columns: { event: "Evento", origin: "Origen", consent: "Consentimiento", decision: "Decisión", destination: "Destinos" },
    rows: [
      { event: "page_view", origin: "navegador", consent: "analítica", consentTone: "ok", decision: "entregado", decisionTone: "ok", destination: "GA4" },
      { event: "add_to_cart", origin: "navegador", consent: "marketing", consentTone: "ok", decision: "entregado", decisionTone: "ok", destination: "Meta, TikTok" },
      { event: "purchase", origin: "navegador + servidor", consent: "marketing", consentTone: "ok", decision: "entregado, deduplicado (ID de pedido)", decisionTone: "ok", destination: "Meta CAPI, Google Ads" },
      { event: "purchase", origin: "servidor", consent: "falta marketing", consentTone: "bad", decision: "bloqueado: consent_missing", decisionTone: "bad", destination: "Meta CAPI" },
      { event: "generate_lead", origin: "navegador", consent: "marketing", consentTone: "ok", decision: "entregado", decisionTone: "ok", destination: "LinkedIn" },
    ],
  },
  lineage: {
    title: "Trazabilidad del evento",
    caption: "Una compra, leída desde el origen hasta la respuesta del proveedor.",
    facts: [
      { label: "Evento", value: "purchase · evt_…7f2a" },
      { label: "Origen", value: "SDK del navegador + servidor (webhook de la tienda)" },
      { label: "Configuración", value: "versión 12, firma verificada" },
      { label: "Instantánea de consentimiento", value: "analítica, marketing · origen: CMP" },
      { label: "IDs de clic", value: "gclid (capturado hace 3 días)" },
    ],
    attempts: {
      title: "Intentos de entrega",
      columns: { destination: "Destino", status: "Estado", result: "Resultado" },
      rows: [
        { destination: "Meta Conversions API", status: "200", tone: "ok", result: "aceptado, deduplicado por ID de evento" },
        { destination: "Google Ads", status: "200", tone: "ok", result: "aceptado, deduplicado por ID de pedido" },
        { destination: "TikTok Events API", status: "503", tone: "warn", result: "reintento 2 programado con backoff" },
      ],
    },
    payload: { title: "Payload censurado", copy: "Copiar payload", copied: "Copiado", code: PAYLOAD_EXAMPLE },
  },
  health: {
    title: "Tracking Health Score",
    caption: "Componentes ponderados; una puntuación más baja siempre señala su causa.",
    scoreLabel: "Puntuación",
    score: 86,
    componentsLabel: "Componentes",
    weight: (percent) => `${percent}% de peso`,
    components: [
      { key: "consent", label: "Cobertura de consentimiento", score: 91, weight: 20, detail: "El 91% de los eventos llevan una señal explícita de consentimiento" },
      { key: "coverage", label: "Eventos críticos", score: 78, weight: 25, detail: "7 de 9 eventos críticos planificados observados" },
      { key: "schema", label: "Calidad del esquema", score: 74, weight: 15, detail: "El 74% de los eventos superan las comprobaciones de esquema y PII" },
      { key: "dedup", label: "Duplicados", score: 96, weight: 10, detail: "1,0% de duplicados" },
      { key: "delivery", label: "Entrega", score: 88, weight: 20, detail: "94% entregados, 1 integración con problemas de credenciales" },
      { key: "liveness", label: "Actualidad", score: 100, weight: 10, detail: "Último evento del navegador hace 4 min" },
    ],
    issuesLabel: "Incidencias abiertas",
    issues: [
      { title: "purchase sin currency", detail: "A 12 eventos de las últimas 24 h les falta el parámetro obligatorio", fix: "Solución: actualizar el mapeo de eventos", tone: "warn" },
      { title: "Falta la señal de consentimiento", detail: "El 9% de los eventos llegaron sin un estado de consentimiento explícito", fix: "Solución: conectar el adaptador de CMP", tone: "warn" },
    ],
  },
  consent: {
    title: "Estado del consentimiento y señales derivadas",
    caption: "Las finalidades vienen de tu CMP; todo lo demás se deriva, nunca se adivina.",
    purposesLabel: "Finalidades",
    purposes: [
      { label: "Estrictamente necesarias", granted: true },
      { label: "Analítica", granted: true },
      { label: "Marketing", granted: false },
      { label: "Personalización", granted: false },
    ],
    granted: "concedido",
    denied: "denegado",
    flagsLabel: "Consent Mode v2",
    flags: [
      { key: "analytics_storage", value: "granted" },
      { key: "ad_storage", value: "denied" },
      { key: "ad_user_data", value: "denied" },
      { key: "ad_personalization", value: "denied" },
    ],
    reasonsLabel: "Motivos de bloqueo que informa el motor de políticas",
    reasons: [
      { code: "consent_missing", text: "todavía no hay señal de consentimiento para el evento" },
      { code: "consent_denied", text: "el visitante lo rechazó" },
      { code: "purpose_not_granted", text: "el destino necesita una finalidad que no se ha concedido" },
      { code: "gpc_opt_out", text: "Global Privacy Control activado" },
      { code: "destination_paused", text: "kill switch o circuit breaker" },
      { code: "inferred_data_not_exportable", text: "el consentimiento inferido nunca llega a las plataformas publicitarias" },
    ],
  },
  attribution: {
    title: "Matriz de IDs de clic",
    caption: "Capturados tras el consentimiento de marketing, almacenados en modo first-party y transmitidos solo a la plataforma propietaria.",
    columns: { id: "ID de clic", captured: "Capturado", forwarded: "Transmitido solo a", retention: "Conservado" },
    rows: [
      { id: "gclid", captured: "landing page, tras el consentimiento de marketing", forwarded: "Google Ads, GA4, Google Marketing Platform", retention: "90 días" },
      { id: "fbclid", captured: "landing page, tras el consentimiento de marketing", forwarded: "Meta", retention: "90 días" },
      { id: "ttclid", captured: "landing page, tras el consentimiento de marketing", forwarded: "TikTok", retention: "90 días" },
      { id: "msclkid", captured: "landing page, tras el consentimiento de marketing", forwarded: "Microsoft Advertising", retention: "90 días" },
      { id: "li_fat_id", captured: "landing page, tras el consentimiento de marketing", forwarded: "LinkedIn", retention: "90 días" },
    ],
    note: "La retención está documentada por ID y es configurable; 90 días es el valor por defecto.",
  },
  setup: {
    title: "Configuración guiada",
    caption: "El asistente propone, las herramientas validan, tú apruebas.",
    assistant: "Track AI",
    you: "Tú",
    messages: [
      { from: "assistant", text: "example-shop.test funciona con Shopify y usa Cookiebot como herramienta de consentimiento (confianza alta). Para una tienda propongo view_item, add_to_cart, begin_checkout y purchase. ¿Preparo el borrador del plan para Meta y Google Ads?" },
      { from: "you", text: "Sí, Meta primero." },
      { from: "assistant", text: "ID de píxel validado. La Conversions API necesita un token de acceso: introdúcelo en la tarjeta segura de credenciales de abajo; nunca aparecerá en este chat." },
    ],
    vault: { title: "Tarjeta de credenciales · token de acceso de Meta", text: "Guardado cifrado; nadie puede verlo, ni siquiera el modelo.", state: "guardado" },
    test: { title: "Evento de prueba · purchase", text: "Enviado a través del pipeline real con el código de evento de prueba del proveedor.", state: "aceptado por Meta" },
    approval: {
      title: "Publicar la versión 13",
      text: "Vinculada exactamente a este diff y a ti como aprobador.",
      diff: ["+ destination meta: browser + server", "+ mapping purchase → Purchase (event id, order id)", "~ consent: marketing required for meta"],
      state: "a la espera de tu aprobación",
      action: "Aprobar y publicar",
    },
  },
  destinations: {
    title: "Destination Health",
    caption: "Salud, modo y cola por destino; los fallos se gestionan, no se ocultan.",
    columns: { destination: "Destino", mode: "Modo", health: "Salud", last: "Última entrega", queue: "Cola" },
    rows: [
      { destination: "Meta", mode: "navegador + servidor", health: "correcto", tone: "ok", last: "hace 12 s", queue: "0 reintentos" },
      { destination: "Google Ads", mode: "servidor", health: "correcto", tone: "ok", last: "hace 40 s", queue: "0 reintentos" },
      { destination: "TikTok", mode: "navegador + servidor", health: "degradado, circuit breaker abierto", tone: "warn", last: "hace 6 min", queue: "3 en la cola de mensajes fallidos" },
      { destination: "LinkedIn", mode: "servidor", health: "pausado por kill switch", tone: "neutral", last: "hace 2 h", queue: "retenido" },
    ],
  },
};
