import type { FeatureCopy, FeatureDetailLabels, FeatureUiCopy, FeaturesPageCopy } from "../types";
import { PAYLOAD_EXAMPLE } from "./samples";

/**
 * French (fr) copy of the features area. Same shape as en.ts; see docs/14-localization.md.
 */

export const FEATURES_FR: FeatureCopy[] = [
  {
    slug: "ai-setup",
    title: "Configuration guidée par l’IA",
    short: "Décrivez votre site, confirmez chaque étape, publiez une configuration signée.",
    benefit: "Votre première destination est en ligne en une seule session guidée — sans écrire un tag, et sans renoncer au contrôle de ce qui est publié.",
    intro: "L’assistant transforme un domaine en dispositif de mesure opérationnel : il détecte la plateforme et l’outil de consentement, propose un plan d’événements adapté à votre type d’activité, collecte les identifiants publics dans le chat et les secrets dans une carte coffre-fort, envoie un véritable événement de test et prépare un diff de publication que vous approuvez.",
    flow: {
      title: "Chaque action est un appel d’outil typé que vous pouvez voir",
      text: "L’assistant n’exécute jamais de code libre. Il appelle des outils validés côté serveur : détecter la plateforme, rédiger le plan d’événements, valider un ID de pixel, envoyer un événement de test, préparer un diff. Tout ce qui est irréversible — publication, rollback, rotation des identifiants d’accès — s’arrête à une carte d’approbation liée à la modification exacte que vous avez sous les yeux.",
      caption: "Assistant → outils typés → carte d’approbation → configuration signée. Les secrets vont directement dans le coffre-fort et ne transitent jamais par le chat.",
    },
    viewCaption: "Exemple de session : plateforme détectée, plan d’événements proposé, jeton stocké dans le coffre-fort, un véritable événement de test accepté, publication en attente de votre approbation.",
    sections: [
      { title: "Des outils typés plutôt que des actions libres", text: "Chaque action de l’assistant est un appel d’outil validé côté serveur, avec contrôle des rôles, entrée d’audit et, pour tout ce qui est irréversible, un jeton d’approbation lié au diff exact que vous avez vu." },
      { title: "Les secrets n’atteignent jamais le modèle", text: "Les jetons d’accès vont directement dans le coffre-fort chiffré via une carte dédiée ou OAuth. La transcription, le modèle et le navigateur ne les voient jamais ; une couche DLP masque les secrets et les données personnelles collés dans le chat." },
      { title: "Machine à états déterministe", text: "La configuration suit une machine à états explicite, avec des prérequis et des preuves pour chaque état. Les mêmes états existent sous forme d’assistant à base de règles lorsque le fournisseur d’IA est indisponible — rien ne dépend de la disponibilité d’un modèle." },
    ],
    bullets: ["Détection du type d’activité et de la plateforme avec un niveau de confiance", "Modèles de plan d’événements pour les boutiques, la génération de leads, le SaaS et les éditeurs", "ID publics validés selon les formats des fournisseurs", "Publication uniquement après un diff, une liste de destinataires et une confirmation explicite"],
    comparison: {
      title: "Configuration manuelle contre session guidée",
      text: "Ce qui change quand l’assistant pilote la configuration et que vous gardez la main sur les approbations.",
      beforeLabel: "Configuration manuelle du conteneur",
      afterLabel: "Configuration guidée avec Track",
      rows: [
        { aspect: "Plan d’événements", before: "Écrit de mémoire, un tag à la fois", after: "Proposé pour votre type d’activité, modifié dans le chat, validé avant publication" },
        { aspect: "Identifiants d’accès", before: "Collés dans les champs des tags et visibles par quiconque a accès au conteneur", after: "Saisis dans une carte coffre-fort ou via OAuth ; jamais affichés dans la transcription" },
        { aspect: "Vérification", before: "Espérer que le fournisseur a reçu quelque chose", after: "Un véritable événement de test dans le vrai pipeline, avec le verdict du fournisseur" },
        { aspect: "Publication", before: "Publier, puis découvrir ce qui a changé", after: "D’abord le diff, les destinataires et l’approbation ; ensuite un bundle signé et versionné" },
      ],
    },
    faq: [
      { q: "L’assistant peut-il publier sans moi ?", a: "Non. La publication, les rollbacks, la rotation des identifiants d’accès et l’activation des destinations exigent toujours votre clic sur une carte d’approbation liée à la modification exacte." },
      { q: "Quel modèle est utilisé ?", a: "OpenAI Responses API avec Structured Outputs et Function Calling strict. Les noms de modèles sont configurés côté serveur et vérifiés au démarrage ; l’interface ne les code jamais en dur." },
    ],
  },
  {
    slug: "server-side-tracking",
    title: "Routeur d’événements côté serveur",
    short: "Un événement, toutes les plateformes : transmission navigateur et serveur avec déduplication partagée.",
    benefit: "Envoyez chaque conversion une seule fois et laissez chaque plateforme la recevoir de la façon qui compte le mieux pour elle — navigateur, serveur ou les deux — sans double comptage.",
    intro: "Track reçoit les événements du SDK navigateur, de votre serveur, des plateformes e-commerce et des réseaux d’affiliation, les normalise dans un schéma unique, applique le consentement et les route vers 22 types de destinations avec nouvelles tentatives, circuit breakers, dead-letter queue et rejeu.",
    flow: {
      title: "Navigateur et serveur partagent un seul ID d’événement",
      text: "Le SDK navigateur et votre serveur (ou le webhook de votre boutique) envoient le même achat avec le même ID d’événement. Track normalise les deux, évalue le consentement par destination et les transmet ; Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn et les autres dédupliquent sur cet ID, Google Ads sur l’ID de commande.",
      caption: "Site web → Track → Consentement/règles → Destinations. Les deux origines aboutissent aux mêmes destinations et y sont dédupliquées.",
    },
    viewCaption: "Exemple de santé des destinations : deux destinations opérationnelles, une panne de fournisseur gérée par le circuit breaker, une destination mise en pause par un kill switch.",
    sections: [
      { title: "Hybride par défaut", text: "Chaque destination peut fonctionner via tag navigateur, API serveur ou les deux. Les deux chemins partagent un seul ID d’événement, si bien que Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn et les autres dédupliquent de façon fiable." },
      { title: "Durable et observable", text: "Une file d’attente durable avec des messages idempotents, des nouvelles tentatives par destination avec backoff et jitter, des circuit breakers sur les fournisseurs défaillants, un stockage dead-letter et le rejeu. Chaque tentative est enregistrée avec un aperçu masqué de la charge utile." },
      { title: "First-party dès la conception", text: "Le tracker est servi depuis votre hôte CDN, les événements vont vers votre hôte d’ingestion, les bundles de configuration sont signés en Ed25519 et vérifiés dans le navigateur avant tout chargement." },
    ],
    bullets: ["SDK navigateur maintenu sous 30 Ko gzip par un budget CI, avec stockage conditionné au consentement", "API serveur avec clés de source pour le CRM et les conversions hors ligne", "Kill switches par site et par organisation", "Data plane UE avec isolation des tenants au niveau des lignes"],
    comparison: {
      title: "Tags navigateur seuls contre routeur hybride",
      text: "Pourquoi un événement passé par Track vaut plus que le même pixel déclenché deux fois.",
      beforeLabel: "Tags navigateur seuls",
      afterLabel: "Navigateur + serveur avec Track",
      rows: [
        { aspect: "Événements perdus", before: "Scripts bloqués et onglets fermés font simplement disparaître la conversion", after: "Le chemin serveur la transmet quand même ; le chemin navigateur ajoute les données de correspondance quand elles sont disponibles" },
        { aspect: "Doublons", before: "Le pixel et l’API serveur comptent la même commande deux fois", after: "ID d’événement et ID de commande communs ; les fournisseurs dédupliquent" },
        { aspect: "Panne du fournisseur", before: "Échec silencieux, aucune nouvelle tentative", after: "Nouvelles tentatives avec backoff, circuit breaker, dead-letter queue et rejeu" },
        { aspect: "Où vont les données", before: "Des points de terminaison tiers appelés depuis la page", after: "Hôte d’ingestion first-party ; les fournisseurs ne reçoivent que les champs mappés" },
      ],
    },
    faq: [
      { q: "Le tracking côté serveur contourne-t-il le consentement ?", a: "Non. Le consentement est évalué pour chaque événement et chaque destination ; sans la finalité requise, rien n’est stocké, envoyé ni rejoué plus tard." },
      { q: "Que se passe-t-il quand un fournisseur est en panne ?", a: "Les transmissions sont retentées avec backoff, le circuit breaker met la destination en pause, les événements en échec atterrissent dans la dead-letter queue et peuvent être rejoués une fois le fournisseur rétabli." },
    ],
  },
  {
    slug: "event-debugger",
    title: "Event Debugger et traçabilité",
    short: "Voyez chaque événement avec son instantané de consentement, sa décision de routage et la réponse du fournisseur.",
    benefit: "Quand un chiffre semble faux dans une plateforme publicitaire, vous découvrez pourquoi à un seul endroit — sans jongler entre la console du navigateur, l’interface du fournisseur et la mémoire d’un collègue.",
    intro: "Ouvrez n’importe quel événement et lisez son histoire : la source et la version du SDK, le consentement accordé à cet instant, les ID de clic capturés, la version de configuration qui l’a routé, et la tentative de transmission par destination, y compris la charge utile masquée et la réponse du fournisseur.",
    flow: {
      title: "Un événement, tout le parcours",
      text: "Le débogueur suit un événement depuis son origine, à travers la normalisation, la décision de consentement et chaque tentative de transmission. Les rejets ne sont jamais silencieux : chacun porte une raison, comme un consentement manquant, des données personnelles bloquées, un nom invalide, un doublon ou une destination en pause.",
      caption: "La traçabilité conserve ensemble l’origine, l’instantané de consentement, la décision de routage et la réponse de chaque fournisseur.",
    },
    viewCaption: "Exemple de flux d’événements : événements transmis, un achat dédupliqué et un achat serveur bloqué pour finalité marketing manquante.",
    sections: [
      { title: "Masqué, pas caché", text: "Les aperçus de charge utile montrent la structure et des identifiants hachés, pour que vous puissiez vérifier les mappings sans exposer de données personnelles ni de jetons." },
      { title: "Des événements de test dans le vrai pipeline", text: "Les événements de test sont marqués, passent par la même file d’attente et le même worker, et rapportent le verdict du fournisseur — aucun succès simulé." },
      { title: "Les rejets sont expliqués", text: "Chaque événement rejeté porte une raison : consentement manquant, données personnelles bloquées, nom invalide, doublon, destination en pause ou blocage par les règles." },
    ],
    bullets: ["Filtrez par nom d’événement, état et source", "Historique des tentatives par destination avec statut HTTP et classe d’erreur", "Indications du mode test du fournisseur par plateforme", "Liens directs vers l’assistant de configuration des destinations"],
    comparison: {
      title: "Déboguer par la console contre déboguer par la traçabilité",
      text: "La même question — pourquoi cet achat n’a-t-il pas atteint Meta ? — avec deux réponses.",
      beforeLabel: "Console du navigateur et interface du fournisseur",
      afterLabel: "Traçabilité des événements dans Track",
      rows: [
        { aspect: "Où chercher", before: "Onglet réseau, mode aperçu des tags, le gestionnaire d’événements du fournisseur", after: "Une fiche d’événement avec chaque tentative et chaque réponse" },
        { aspect: "Consentement à cet instant", before: "Inconnu ; reconstitué à partir des réglages du bandeau", after: "Stocké sous forme d’instantané avec l’événement" },
        { aspect: "Événements côté serveur", before: "Invisibles depuis le navigateur", after: "Même traçabilité, marqués avec leur origine" },
        { aspect: "Données personnelles", before: "Charges utiles brutes dans les journaux et les captures d’écran", after: "Identifiants hachés, aperçus masqués" },
      ],
    },
    faq: [{ q: "Combien de temps les données du débogueur sont-elles conservées ?", a: "Les tentatives de transmission sont conservées 90 jours par défaut et les événements 13 mois ; les deux durées sont configurables par organisation dans le centre de confidentialité." }],
  },
  {
    slug: "data-quality",
    title: "Qualité des données et score de santé",
    short: "Un score unique aux composantes explicables, et des problèmes qui renvoient vers leur solution.",
    benefit: "Sachez quand le tracking se casse, voyez quelle partie a cassé et allez droit à la correction — avant qu’une campagne ne tourne sur de mauvaises données.",
    intro: "Le worker calcule un score de santé du tracking à partir de la couverture du consentement, de la couverture des événements critiques, de la qualité du schéma, du taux de doublons, du succès de transmission et de la fraîcheur. Chaque problème détecté nomme l’outil de l’assistant qui le résout.",
    flow: {
      title: "Six composantes, un score explicable",
      text: "Le score est calculé à partir des événements de la dernière période : combien portent un signal de consentement explicite, quels événements critiques planifiés ont été observés, combien passent les contrôles de schéma et de données personnelles, le taux de doublons, le succès de transmission par destination et l’heure d’arrivée du dernier événement navigateur. Les pondérations sont affichées à côté du score, si bien qu’un chiffre plus bas pointe toujours vers sa cause.",
      caption: "Événements → contrôles → composantes pondérées → score avec les problèmes qui l’ont fait baisser.",
    },
    viewCaption: "Exemple de score avec ses six composantes et deux problèmes ouverts, chacun nommant l’outil qui le corrige.",
    sections: [
      { title: "Des problèmes avec empreintes", text: "Les problèmes récurrents sont regroupés, comptés et horodatés, pour que vous voyiez des tendances plutôt que du bruit." },
      { title: "Garde-fous de schéma", text: "Les événements standard ont des paramètres obligatoires ; les événements personnalisés suivent des règles de nommage ; les données personnelles dans les propriétés sont bloquées avant le stockage." },
      { title: "Des benchmarks uniquement avec opt-in", text: "Des benchmarks anonymisés et agrégés ne sont disponibles que pour les organisations qui y adhèrent." },
    ],
    bullets: ["Score par site avec ses composantes", "Résolvez ou ignorez les problèmes avec une piste d’audit", "Couverture du consentement et taux de doublons comme indicateurs de premier plan"],
    comparison: {
      title: "Remarquer les problèmes contre en être informé",
      text: "Comment un événement d’achat cassé apparaît avec et sans le score de santé.",
      beforeLabel: "Sans surveillance",
      afterLabel: "Avec le score de santé",
      rows: [
        { aspect: "Détection", before: "Quelqu’un remarque une baisse dans le tableau de bord publicitaire des jours plus tard", after: "Le score baisse et un problème est ouvert" },
        { aspect: "Diagnostic", before: "Quel tag, quelle page, quel navigateur ?", after: "La composante qui a baissé et les événements derrière elle" },
        { aspect: "Correction", before: "Ticket, modification du tag, republication, attente", after: "Le problème nomme l’outil de l’assistant ; vous approuvez la modification" },
        { aspect: "Tendance", before: "Aucun historique", after: "Problèmes regroupés, comptés et horodatés" },
      ],
    },
    faq: [{ q: "Le score est-il comparable d’un site à l’autre ?", a: "Les composantes sont identiques pour chaque site ; les pondérations sont documentées dans la carte du score, pour que les équipes puissent raisonner sur les écarts." }],
  },
  {
    slug: "consent",
    title: "Respectueux du consentement par construction",
    short: "Opt-in strict par défaut, Consent Mode v2, destinations par finalité, aucun rejeu après consentement.",
    benefit: "Chaque destination reçoit exactement ce que le visiteur a accepté — évalué pour chaque événement, dans le navigateur puis à nouveau sur le serveur — pour que la conformité ne soit pas un réglage de bandeau dont vous espérez qu’il est correct.",
    intro: "Le consentement n’est pas une intégration de bandeau mais un moteur de règles : finalités, régions, exigences des destinations et capture des ID de clic sont évaluées pour chaque événement dans le navigateur, puis à nouveau sur le serveur.",
    flow: {
      title: "La barrière se trouve devant chaque destination",
      text: "Chaque destination déclare la finalité dont elle a besoin. Quand un événement arrive, Track compare l’instantané de consentement à cette exigence : les destinations d’analyse reçoivent les événements avec le consentement analyse, les destinations publicitaires uniquement avec le consentement marketing. Un retrait arrête immédiatement les envois, et rien de ce qui a été stocké avant le consentement n’est rejoué ensuite.",
      caption: "Site web → Track → barrière consentement/règles → uniquement les destinations dont la finalité a été accordée.",
    },
    viewCaption: "Exemple d’état du consentement : analyse accordée, marketing refusé — et les indicateurs Consent Mode v2 et raisons de blocage qui en découlent.",
    sections: [
      { title: "Adaptateurs CMP et API", text: "TCF 2.2, GPP et Global Privacy Control, adaptateurs Cookiebot, OneTrust et Usercentrics, plus une API de consentement pour les bandeaux personnalisés." },
      { title: "Consent Mode v2, fondé sur les finalités", text: "Les signaux de consentement Google sont dérivés des finalités ; le mode avancé n’est disponible qu’avec une note de revue juridique documentée." },
      { title: "Preuve", text: "Des instantanés de consentement dédupliqués sont stockés avec chaque événement, pour que vous puissiez prouver ce qui a été accordé et quand." },
    ],
    bullets: ["Le consentement déduit n’est jamais exporté vers les plateformes publicitaires", "Un retrait arrête immédiatement les envois", "Les achats serveur restent opérationnels, jamais publicitaires sans consentement"],
    comparison: {
      title: "Consentement par tag contre moteur de règles",
      text: "Où la décision est prise — et si vous pouvez la prouver plus tard.",
      beforeLabel: "Consentement géré par tag",
      afterLabel: "Moteur de règles dans Track",
      rows: [
        { aspect: "Point de décision", before: "Le déclencheur de chaque tag, configuré à la main", after: "Chaque événement, chaque destination, dans le navigateur et sur le serveur" },
        { aspect: "Événements côté serveur", before: "Envoyés quel que soit le bandeau", after: "Même contrôle de finalité que pour les événements navigateur" },
        { aspect: "Retrait", before: "Prend effet au chargement de page suivant, au mieux", after: "Arrête immédiatement les envois ; aucun rejeu des événements antérieurs" },
        { aspect: "Preuve", before: "Aucune", after: "Instantané de consentement stocké avec chaque événement" },
      ],
    },
    faq: [{ q: "Quelles régions sont prises en charge ?", a: "Opt-in strict pour l’UE/EEE/Royaume-Uni/Suisse par défaut ; des règles par région peuvent être configurées, mais jamais plus faibles que le socle légal sans décision explicite." }],
  },
  {
    slug: "attribution",
    title: "ID de clic et attribution bien faits",
    short: "Capturez uniquement les ID dont la destination a besoin, uniquement avec consentement, uniquement pour la fenêtre documentée.",
    benefit: "Vos campagnes obtiennent les ID de clic dont elles ont besoin pour attribuer une conversion — et aucune plateforme ne reçoit jamais un ID qui appartient à une autre.",
    intro: "Le tracker capture gclid, fbclid, ttclid, msclkid, li_fat_id et les autres ID de clic des plateformes sur les pages d’atterrissage après consentement marketing, les stocke en first-party pour la fenêtre du fournisseur et ne transmet chaque ID qu’à la plateforme à laquelle il appartient.",
    flow: {
      title: "Chaque ID voyage vers exactement une plateforme",
      text: "Une page d’atterrissage avec un gclid et un fbclid produit deux ID stockés après consentement marketing. Quand l’achat arrive, Track attache le gclid à la transmission Google Ads et le fbclid à la transmission Meta — la matrice est vérifiée automatiquement, si bien qu’une fuite entre fournisseurs n’est pas une erreur de configuration que vous pouvez commettre.",
      caption: "Page d’atterrissage → stockage first-party des ID de clic → achat → transmission limitée à chaque destination.",
    },
    viewCaption: "Exemple de matrice : quel ID de clic est capturé, où il est transmis et combien de temps il est conservé.",
    sections: [
      { title: "Transmission limitée à chaque destination", text: "Meta ne voit jamais votre gclid et Google ne voit jamais votre fbclid. La matrice de règles est vérifiée automatiquement." },
      { title: "Déduplication au niveau de la commande", text: "Les achats portent l’ID de commande vers chaque fournisseur qui le prend en charge, pour que les conversions navigateur et serveur fusionnent correctement." },
      { title: "Hors ligne et CRM", text: "Les événements serveur avec un indicateur hors ligne atteignent Google Ads, CM360, Microsoft, Meta, TikTok, Pinterest, Snapchat, Amazon, Yahoo et LinkedIn sous forme de conversions hors ligne." },
    ],
    bullets: ["Conservation documentée par ID de clic (90 jours par défaut)", "Enhanced Conversions avec hachage normalisé", "Réseaux d’affiliation avec ID de clic par réseau"],
    comparison: {
      title: "Paramètres d’URL dans le dataLayer contre stockage cloisonné des ID de clic",
      text: "La différence entre tout collecter et transmettre ce qui appartient à qui.",
      beforeLabel: "ID de clic dans le dataLayer",
      afterLabel: "Stockage des ID de clic dans Track",
      rows: [
        { aspect: "Capture", before: "Chaque paramètre, sur chaque page, quel que soit le consentement", after: "Uniquement les ID connus, sur les pages d’atterrissage, après consentement marketing" },
        { aspect: "Transmission", before: "Ce qu’un modèle de tag lit", after: "Par destination, à partir d’une matrice vérifiée automatiquement" },
        { aspect: "Conservation", before: "Durée de vie du cookie définie par chaque tag", after: "Fenêtre documentée par ID, 90 jours par défaut" },
        { aspect: "Conversions hors ligne", before: "Imports manuels", after: "Événements serveur avec un indicateur hors ligne" },
      ],
    },
    faq: [{ q: "Construisez-vous des profils inter-sites ?", a: "Non. Il n’y a ni fingerprinting ni identité inter-sites ; les identifiants restent dans le périmètre du site et des finalités consenties." }],
  },
];

export const FEATURES_PAGE_COPY_FR: FeaturesPageCopy = {
  eyebrow: "Fonctionnalités",
  title: "Chaque conversion transmise une seule fois, avec consentement, à la plateforme à laquelle elle appartient",
  text: "Track remplace le conteneur de tags par une configuration guidée, un routeur côté serveur respectueux du consentement et un débogueur qui explique chaque événement. Cette page montre le produit tel qu’il fonctionne — les états ci-dessous sont des données d’exemple, pas du trafic réel.",
  cta: "Commencer avec votre domaine",
  ctaSecondary: "Voir comment ça fonctionne",
  stage: {
    title: "Flux de données du site web vers les destinations, en passant par Track",
    description: "Un site web envoie des événements depuis le SDK navigateur et depuis le serveur vers Track. Track évalue le consentement à une barrière de règles et ne transmet chaque événement qu’aux destinations dont la finalité a été accordée : Meta, Google Ads, Google Analytics 4 et TikTok.",
    caption: "Site web → Track → Consentement/règles → Destinations. Navigateur et serveur partagent un ID d’événement ; la barrière décide par destination.",
  },
  scenarios: {
    title: "Ce qui arrive à un achat",
    text: "Changez de scénario pour voir comment le même événement est routé lorsque le consentement est accordé, retiré, ou qu’un fournisseur est en panne. La décision et sa raison sont ce que vous lirez plus tard dans le débogueur.",
    tabsLabel: "Scénarios de routage",
    items: [
      {
        id: "granted",
        label: "Consentement accordé",
        title: "Analyse et marketing accordés",
        text: "L’achat arrive du navigateur et du serveur avec le même ID d’événement. La barrière trouve les finalités requises et le transmet aux quatre destinations ; Meta et TikTok dédupliquent sur l’ID d’événement, Google Ads sur l’ID de commande.",
        points: ["Décision : transmis à Meta, Google Ads, GA4, TikTok", "Déduplication : ID d’événement (Meta, TikTok), ID de commande (Google Ads)", "ID de clic attachés par destination : gclid → Google, fbclid → Meta"],
      },
      {
        id: "withdrawn",
        label: "Marketing retiré",
        title: "Analyse accordée, marketing refusé",
        text: "Le visiteur a retiré son consentement marketing avant l’achat. La barrière laisse passer l’événement vers Google Analytics 4 et bloque les destinations publicitaires avec la raison purpose_not_granted. Rien n’est stocké pour plus tard ; lorsque le consentement est à nouveau accordé, les événements antérieurs ne sont pas rejoués.",
        points: ["Décision : transmis à GA4 ; bloqué pour Meta, Google Ads, TikTok", "Raison affichée dans le débogueur : purpose_not_granted (marketing)", "Consent Mode v2 : analytics_storage granted, ad_storage denied"],
      },
      {
        id: "outage",
        label: "Fournisseur en panne",
        title: "Consentement accordé, un fournisseur indisponible",
        text: "TikTok répond par une erreur serveur. Track réessaie avec backoff et jitter, ouvre le circuit breaker après des échecs répétés et place l’événement dans la dead-letter queue. Les trois autres destinations ne sont pas affectées. Une fois TikTok rétabli, la dead-letter queue est rejouée.",
        points: ["Décision : transmis à Meta, Google Ads, GA4 ; TikTok en nouvelle tentative", "Circuit breaker ouvert pour TikTok ; événements dans la dead-letter queue", "Le rejeu après rétablissement conserve l’ID d’événement d’origine, donc rien n’est compté deux fois"],
      },
    ],
  },
  index: {
    title: "Six fonctionnalités, une seule couche d’événements",
    text: "Chaque fonctionnalité repose sur la même configuration signée et le même schéma d’événements. Ouvrez une fonctionnalité pour voir sa vue produit, son flux de données et une comparaison avant/après.",
    more: "En savoir plus",
  },
  comparison: {
    title: "Conteneur de tags contre couche d’événements",
    text: "Là où un conteneur classique vous laisse le travail, et là où Track le fait par construction.",
    beforeLabel: "Conteneur de tags classique",
    afterLabel: "Track",
    rows: [
      { aspect: "Ce qui s’exécute sur votre site", before: "Des tags HTML et JavaScript personnalisés de quiconque a accès au conteneur", after: "Un snippet et une configuration signée et versionnée — aucune exécution de code personnalisé" },
      { aspect: "Consentement", before: "Conditions de déclenchement par tag, maintenues à la main", after: "Moteur de règles qui évalue chaque événement pour chaque destination, navigateur et serveur" },
      { aspect: "Transmission côté serveur", before: "Un second conteneur, un second jeu de tags, déduplication manuelle", after: "Intégré : ID d’événement commun, nouvelles tentatives, circuit breakers, rejeu" },
      { aspect: "Trouver les erreurs", before: "Mode aperçu et interfaces des fournisseurs", after: "Traçabilité des événements avec instantané de consentement, décision de routage et réponse du fournisseur" },
      { aspect: "Modifications", before: "Publier et espérer", after: "Diff, approbation, version signée, rollback en un clic" },
    ],
  },
  trust: {
    title: "Des faits que vous pouvez vérifier",
    items: [
      { title: "Région de données UE", text: "Les événements sont traités dans l’UE ; les API des fournisseurs ne reçoivent que les champs que vous avez mappés, sur la base de transfert documentée pour chaque destination." },
      { title: "Configurations signées", text: "Chaque bundle publié est immuable, versionné et signé en Ed25519 ; le SDK vérifie la signature avant de l’appliquer." },
      { title: "Pas de code personnalisé", text: "Il n’existe aucun type de tag HTML ou JavaScript personnalisé. Les transformations sont déclaratives et validées sur le serveur." },
      { title: "Opt-in strict par défaut", text: "L’UE/EEE/Royaume-Uni/Suisse démarrent en opt-in strict ; le consentement déduit n’est jamais exporté vers les plateformes publicitaires." },
    ],
  },
  closing: { title: "Voyez ces vues avec vos propres événements", text: "Créez votre site, collez le snippet et laissez l’assistant configurer la première destination — le débogueur et le score de santé se remplissent dès le premier événement.", cta: "Commencer avec votre domaine", secondary: "Voir les tarifs" },
};

export const FEATURE_DETAIL_COPY_FR: FeatureDetailLabels = {
  features: "Fonctionnalités",
  breadcrumb: "Fil d’Ariane",
  howBuilt: "Comment c’est construit",
  howBuiltText: "Les décisions techniques derrière la fonctionnalité — la preuve après le bénéfice.",
  proof: "Ce que vous pouvez vérifier",
  proofText: "Des faits produit que vous retrouverez dans le tableau de bord, la documentation et le journal d’audit.",
  faq: "Questions",
  more: "Autres fonctionnalités",
  moreText: "Construites sur la même configuration signée et le même schéma d’événements.",
  cta: "Essayez-le sur votre domaine",
  ctaText: "Créez un site, installez un snippet et laissez l’assistant configurer la première destination en quelques minutes.",
  start: "Commencer gratuitement",
  pricing: "Voir les tarifs",
};

export const FEATURE_UI_COPY_FR: FeatureUiCopy = {
  example: "Données d’exemple",
  exampleHint: "État d’exemple statique — pas de trafic réel, aucune donnée client réelle.",
  diagram: {
    website: "Site web",
    browser: "SDK navigateur",
    server: "API serveur",
    track: "Track",
    gate: "Consentement / règles",
    gateGranted: "consentement accordé",
    gateDenied: "marketing refusé",
    gatePending: "consentement en attente",
    dedup: "un seul ID d’événement",
    notUsed: "non utilisé",
    delivered: "transmis",
    blocked: "bloqué",
    retrying: "nouvelle tentative",
    paused: "en pause",
    destinations: { meta: "Meta", googleAds: "Google Ads", ga4: "GA4", tiktok: "TikTok", linkedin: "LinkedIn" },
    describe: (paths, gate) => {
      const origin = paths === "browser" ? "uniquement depuis le SDK navigateur" : paths === "server" ? "uniquement depuis l’API serveur" : "depuis le SDK navigateur et l’API serveur avec un seul ID d’événement commun";
      const decision = gate === "granted" ? "la barrière de consentement est ouverte et les événements atteignent les destinations" : gate === "denied" ? "la barrière de consentement bloque les destinations publicitaires et seule l’analyse reçoit l’événement" : "la barrière de consentement attend un signal et rien n’est transmis";
      return `Le site web envoie des événements ${origin} vers Track\u202f; ${decision}.`;
    },
    chains: {
      setup: { ai: "Track AI", aiSub: "propose", tools: "Outils typés", toolsSub: "validés côté serveur", approval: "Votre approbation", approvalSub: "liée au diff", config: "Config signée", configSub: "version 13", website: "Site web", websiteSub: "vérifie la signature", describe: "Track AI propose des modifications via des outils typés validés côté serveur ; votre approbation, liée au diff, publie une configuration signée que le site web vérifie avant de la charger." },
      health: { events: "Événements", eventsSub: "dernière période", checks: "Contrôles", checksSub: "consentement · schéma · transmission", score: "Score 86", scoreSub: "6 composantes pondérées", issues: "2 problèmes", issuesSub: "chacun nomme sa solution", describe: "Les événements de la dernière période passent par les contrôles ; six composantes pondérées forment le score, et chaque problème ouvert nomme l’outil qui le corrige." },
      attribution: { landing: "Page d’atterrissage", landingSub: "gclid · fbclid", consent: "Consentement marketing", consentSub: "accordé", store: "Stockage des ID de clic", storeSub: "first-party · 90 jours", purchase: "Achat", purchaseSub: "3 jours plus tard", google: "Google Ads", googleSub: "gclid uniquement", meta: "Meta", metaSub: "fbclid uniquement", describe: "Une page d’atterrissage avec gclid et fbclid stocke les deux ID en first-party après consentement marketing ; l’achat trois jours plus tard atteint Google Ads avec le gclid uniquement et Meta avec le fbclid uniquement." },
    },
  },
  stream: {
    title: "Événements en direct",
    caption: "Chaque ligne est un événement avec son origine, le consentement à cet instant, la décision de routage et les destinations.",
    columns: { event: "Événement", origin: "Origine", consent: "Consentement", decision: "Décision", destination: "Destinations" },
    rows: [
      { event: "page_view", origin: "navigateur", consent: "analyse", consentTone: "ok", decision: "transmis", decisionTone: "ok", destination: "GA4" },
      { event: "add_to_cart", origin: "navigateur", consent: "marketing", consentTone: "ok", decision: "transmis", decisionTone: "ok", destination: "Meta, TikTok" },
      { event: "purchase", origin: "navigateur + serveur", consent: "marketing", consentTone: "ok", decision: "transmis, dédupliqué (ID de commande)", decisionTone: "ok", destination: "Meta CAPI, Google Ads" },
      { event: "purchase", origin: "serveur", consent: "marketing manquant", consentTone: "bad", decision: "bloqué : consent_missing", decisionTone: "bad", destination: "Meta CAPI" },
      { event: "generate_lead", origin: "navigateur", consent: "marketing", consentTone: "ok", decision: "transmis", decisionTone: "ok", destination: "LinkedIn" },
    ],
  },
  lineage: {
    title: "Traçabilité de l’événement",
    caption: "Un achat, lu de l’origine à la réponse du fournisseur.",
    facts: [
      { label: "Événement", value: "purchase · evt_…7f2a" },
      { label: "Origine", value: "SDK navigateur + serveur (webhook de la boutique)" },
      { label: "Configuration", value: "version 12, signature vérifiée" },
      { label: "Instantané de consentement", value: "analyse, marketing · source : CMP" },
      { label: "ID de clic", value: "gclid (capturé il y a 3 jours)" },
    ],
    attempts: {
      title: "Tentatives de transmission",
      columns: { destination: "Destination", status: "Statut", result: "Résultat" },
      rows: [
        { destination: "Meta Conversions API", status: "200", tone: "ok", result: "accepté, dédupliqué par ID d’événement" },
        { destination: "Google Ads", status: "200", tone: "ok", result: "accepté, dédupliqué par ID de commande" },
        { destination: "TikTok Events API", status: "503", tone: "warn", result: "tentative 2 planifiée avec backoff" },
      ],
    },
    payload: { title: "Charge utile masquée", copy: "Copier la charge utile", copied: "Copié", code: PAYLOAD_EXAMPLE },
  },
  health: {
    title: "Santé du tracking",
    caption: "Composantes pondérées ; un score plus bas pointe toujours vers sa cause.",
    scoreLabel: "Score",
    score: 86,
    componentsLabel: "Composantes",
    weight: (percent) => `${percent}\u202f% de pondération`,
    components: [
      { key: "consent", label: "Couverture du consentement", score: 91, weight: 20, detail: "91 % des événements portent un signal de consentement explicite" },
      { key: "coverage", label: "Événements critiques", score: 78, weight: 25, detail: "7 des 9 événements critiques planifiés observés" },
      { key: "schema", label: "Qualité du schéma", score: 74, weight: 15, detail: "74 % des événements passent les contrôles de schéma et de données personnelles" },
      { key: "dedup", label: "Doublons", score: 96, weight: 10, detail: "1,0 % de doublons" },
      { key: "delivery", label: "Transmission", score: 88, weight: 20, detail: "94 % transmis, 1 intégration avec des problèmes d’identifiants d’accès" },
      { key: "liveness", label: "Fraîcheur", score: 100, weight: 10, detail: "Dernier événement navigateur il y a 4 min" },
    ],
    issuesLabel: "Problèmes ouverts",
    issues: [
      { title: "purchase sans currency", detail: "12 événements au cours des dernières 24 h n’ont pas le paramètre obligatoire", fix: "Solution : mettre à jour le mapping de l’événement", tone: "warn" },
      { title: "Signal de consentement manquant", detail: "9 % des événements sont arrivés sans état de consentement explicite", fix: "Solution : connecter l’adaptateur CMP", tone: "warn" },
    ],
  },
  consent: {
    title: "État du consentement et signaux dérivés",
    caption: "Les finalités viennent de votre CMP ; tout le reste est dérivé, jamais deviné.",
    purposesLabel: "Finalités",
    purposes: [
      { label: "Strictement nécessaires", granted: true },
      { label: "Analyse", granted: true },
      { label: "Marketing", granted: false },
      { label: "Personnalisation", granted: false },
    ],
    granted: "accordé",
    denied: "refusé",
    flagsLabel: "Consent Mode v2",
    flags: [
      { key: "analytics_storage", value: "granted" },
      { key: "ad_storage", value: "denied" },
      { key: "ad_user_data", value: "denied" },
      { key: "ad_personalization", value: "denied" },
    ],
    reasonsLabel: "Raisons de blocage rapportées par le moteur de règles",
    reasons: [
      { code: "consent_missing", text: "pas encore de signal de consentement pour l’événement" },
      { code: "consent_denied", text: "le visiteur a refusé" },
      { code: "purpose_not_granted", text: "la destination requiert une finalité qui n’a pas été accordée" },
      { code: "gpc_opt_out", text: "Global Privacy Control activé" },
      { code: "destination_paused", text: "kill switch ou circuit breaker" },
      { code: "inferred_data_not_exportable", text: "le consentement déduit n’atteint jamais les plateformes publicitaires" },
    ],
  },
  attribution: {
    title: "Matrice des ID de clic",
    caption: "Capturés après consentement marketing, stockés en first-party, transmis uniquement à la plateforme propriétaire.",
    columns: { id: "ID de clic", captured: "Capturé", forwarded: "Transmis uniquement à", retention: "Conservé" },
    rows: [
      { id: "gclid", captured: "page d’atterrissage, après consentement marketing", forwarded: "Google Ads, GA4, Google Marketing Platform", retention: "90 jours" },
      { id: "fbclid", captured: "page d’atterrissage, après consentement marketing", forwarded: "Meta", retention: "90 jours" },
      { id: "ttclid", captured: "page d’atterrissage, après consentement marketing", forwarded: "TikTok", retention: "90 jours" },
      { id: "msclkid", captured: "page d’atterrissage, après consentement marketing", forwarded: "Microsoft Advertising", retention: "90 jours" },
      { id: "li_fat_id", captured: "page d’atterrissage, après consentement marketing", forwarded: "LinkedIn", retention: "90 jours" },
    ],
    note: "La conservation est documentée par ID et configurable ; 90 jours est la valeur par défaut.",
  },
  setup: {
    title: "Configuration guidée",
    caption: "L’assistant propose, les outils valident, vous approuvez.",
    assistant: "Track AI",
    you: "Vous",
    messages: [
      { from: "assistant", text: "example-shop.test fonctionne sur Shopify avec Cookiebot comme outil de consentement (confiance élevée). Pour une boutique, je suggère view_item, add_to_cart, begin_checkout et purchase. Dois-je rédiger le plan pour Meta et Google Ads ?" },
      { from: "you", text: "Oui, Meta d’abord." },
      { from: "assistant", text: "ID de pixel validé. La Conversions API a besoin d’un jeton d’accès — veuillez le saisir dans la carte coffre-fort ci-dessous ; il n’apparaît jamais dans ce chat." },
    ],
    vault: { title: "Carte coffre-fort · jeton d’accès Meta", text: "Stocké chiffré ; visible par personne, pas même par le modèle.", state: "stocké" },
    test: { title: "Événement de test · purchase", text: "Envoyé dans le vrai pipeline avec le code d’événement de test du fournisseur.", state: "accepté par Meta" },
    approval: {
      title: "Publier la version 13",
      text: "Liée exactement à ce diff et à vous en tant qu’approbateur.",
      diff: ["+ destination meta: browser + server", "+ mapping purchase → Purchase (event id, order id)", "~ consent: marketing required for meta"],
      state: "en attente de votre approbation",
      action: "Approuver et publier",
    },
  },
  destinations: {
    title: "Santé des destinations",
    caption: "Santé, mode et file d’attente par destination ; les échecs sont gérés, pas cachés.",
    columns: { destination: "Destination", mode: "Mode", health: "Santé", last: "Dernière transmission", queue: "File d’attente" },
    rows: [
      { destination: "Meta", mode: "navigateur + serveur", health: "opérationnelle", tone: "ok", last: "il y a 12 s", queue: "0 nouvelle tentative" },
      { destination: "Google Ads", mode: "serveur", health: "opérationnelle", tone: "ok", last: "il y a 40 s", queue: "0 nouvelle tentative" },
      { destination: "TikTok", mode: "navigateur + serveur", health: "dégradée, circuit breaker ouvert", tone: "warn", last: "il y a 6 min", queue: "3 dans la dead-letter queue" },
      { destination: "LinkedIn", mode: "serveur", health: "en pause par kill switch", tone: "neutral", last: "il y a 2 h", queue: "retenue" },
    ],
  },
};
