import type { FeatureCopy, FeatureDetailLabels, FeatureUiCopy, FeaturesPageCopy } from "../types";
import { PAYLOAD_EXAMPLE } from "./samples";

/**
 * Italian (it, "tu" register) copy of the features area. Same shape as en.ts; see docs/14-localization.md.
 */

export const FEATURES_IT: FeatureCopy[] = [
  {
    slug: "ai-setup",
    title: "Configurazione guidata dall'AI",
    short: "Descrivi il tuo sito, conferma ogni passaggio, pubblica una configurazione firmata.",
    benefit: "La tua prima destinazione va live in una sola sessione guidata — senza scrivere un tag e senza rinunciare al controllo su ciò che viene pubblicato.",
    intro: "L'assistente trasforma un dominio in una configurazione di misurazione funzionante: rileva piattaforma e strumento di consenso, propone un piano eventi per il tuo tipo di attività, raccoglie gli identificatori pubblici in chat e i segreti in una scheda vault, invia un evento di test reale e prepara un diff di pubblicazione che approvi tu.",
    flow: {
      title: "Ogni azione è una chiamata a un tool tipizzato che puoi vedere",
      text: "L'assistente non esegue mai codice libero. Chiama tool validati sul server: rilevare la piattaforma, abbozzare il piano eventi, validare un ID pixel, inviare un evento di test, preparare un diff. Tutto ciò che è irreversibile — pubblicazione, rollback, rotazione delle credenziali — si ferma a una scheda di approvazione vincolata esattamente alla modifica che stai guardando.",
      caption: "Assistente → tool tipizzati → scheda di approvazione → configurazione firmata. I segreti vanno direttamente nel vault e non passano mai dalla chat.",
    },
    viewCaption: "Sessione di esempio: piattaforma rilevata, piano eventi proposto, token salvato nel vault, evento di test reale accettato, pubblicazione in attesa della tua approvazione.",
    sections: [
      { title: "Tool tipizzati invece di azioni libere", text: "Ogni azione dell'assistente è una chiamata a un tool validata sul server, con controllo dei ruoli, una voce di audit e, per tutto ciò che è irreversibile, un token di approvazione vincolato esattamente al diff che hai visto." },
      { title: "I segreti non raggiungono mai il modello", text: "I token di accesso vanno direttamente nel vault cifrato tramite una scheda dedicata o OAuth. Trascrizione, modello e browser non li vedono mai; un livello DLP oscura i segreti e le PII incollati nella chat." },
      { title: "Macchina a stati deterministica", text: "La configurazione segue una macchina a stati esplicita, con requisiti ed evidenze per ogni stato. Gli stessi stati sono disponibili come procedura guidata basata su regole quando il provider AI non è disponibile — nulla dipende dal fatto che un modello sia online." },
    ],
    bullets: ["Rilevamento del tipo di attività e della piattaforma con un livello di confidenza", "Modelli di piano eventi per shop, lead generation, SaaS e publisher", "ID pubblici validati rispetto ai formati delle piattaforme", "Pubblicazione solo dopo diff, elenco dei destinatari e conferma esplicita"],
    comparison: {
      title: "Configurazione manuale contro sessione guidata",
      text: "Cosa cambia quando è l'assistente a guidare la configurazione e tu mantieni le approvazioni.",
      beforeLabel: "Configurazione manuale del container",
      afterLabel: "Configurazione guidata con Track",
      rows: [
        { aspect: "Piano eventi", before: "Scritto a memoria, un tag alla volta", after: "Proposto per il tuo tipo di attività, modificato in chat, validato prima della pubblicazione" },
        { aspect: "Credenziali", before: "Incollate nei campi dei tag e visibili a chiunque abbia accesso al container", after: "Inserite in una scheda vault o via OAuth; mai mostrate nella trascrizione" },
        { aspect: "Verifica", before: "Sperare che la piattaforma abbia ricevuto qualcosa", after: "Un evento di test reale attraverso la pipeline reale, con il verdetto della piattaforma" },
        { aspect: "Pubblicazione", before: "Pubblicare, poi scoprire cosa è cambiato", after: "Prima diff, destinatari e approvazione; poi un bundle firmato e versionato" },
      ],
    },
    faq: [
      { q: "L'assistente può pubblicare senza di me?", a: "No. Pubblicazione, rollback, rotazione delle credenziali e attivazione delle destinazioni richiedono sempre il tuo clic su una scheda di approvazione vincolata alla modifica esatta." },
      { q: "Quale modello viene usato?", a: "OpenAI Responses API con structured outputs e function calling in modalità strict. I nomi dei modelli sono configurati sul server e verificati all'avvio; l'interfaccia non li codifica mai in modo fisso." },
    ],
  },
  {
    slug: "server-side-tracking",
    title: "Router di eventi server-side",
    short: "Un evento, ogni piattaforma: consegna da browser e server con deduplicazione condivisa.",
    benefit: "Invia ogni conversione una sola volta e lascia che ogni piattaforma la riceva nel modo in cui la conta meglio — browser, server o entrambi — senza doppi conteggi.",
    intro: "Track riceve eventi dall'SDK browser, dal tuo server, dai sistemi e-commerce e dai network di affiliazione, li normalizza in un unico schema, applica il consenso e li instrada verso 22 tipi di destinazione con retry, circuit breaker, dead-letter queue e replay.",
    flow: {
      title: "Browser e server condividono un unico ID evento",
      text: "L'SDK browser e il tuo server (o il webhook dello shop) inviano lo stesso acquisto con lo stesso ID evento. Track normalizza entrambi, valuta il consenso per ogni destinazione e li inoltra; Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn e le altre deduplicano su quell'ID, Google Ads sull'ID ordine.",
      caption: "Sito web → Track → consenso/policy → destinazioni. Entrambe le origini finiscono nelle stesse destinazioni e lì vengono deduplicate.",
    },
    viewCaption: "Esempio di stato delle destinazioni: due destinazioni in salute, un'interruzione di una piattaforma gestita dal circuit breaker, una destinazione messa in pausa da un kill switch.",
    sections: [
      { title: "Ibrido di default", text: "Ogni destinazione può funzionare con tag browser, API server o entrambi. I due percorsi condividono un unico ID evento, così Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn e le altre deduplicano in modo affidabile." },
      { title: "Durevole e osservabile", text: "Una coda durevole con messaggi idempotenti, retry per destinazione con backoff e jitter, circuit breaker sulle piattaforme in errore, archiviazione dead-letter e replay. Ogni tentativo viene registrato con un'anteprima oscurata del payload." },
      { title: "First-party by design", text: "Il tracker viene servito dal tuo host CDN, gli eventi vanno al tuo host di ingest, i bundle di configurazione sono firmati con Ed25519 e verificati nel browser prima che qualsiasi cosa venga caricata." },
    ],
    bullets: ["SDK browser mantenuto sotto i 30 KB gzip da un budget in CI, con storage condizionato al consenso", "API server con source key per CRM e conversioni offline", "Kill switch per sito e per organizzazione", "Data plane nell'UE con isolamento dei tenant a livello di riga"],
    comparison: {
      title: "Tag solo browser contro router ibrido",
      text: "Perché un evento attraverso Track vale più dello stesso pixel attivato due volte.",
      beforeLabel: "Tag solo browser",
      afterLabel: "Browser + server con Track",
      rows: [
        { aspect: "Eventi persi", before: "Script bloccati e schede chiuse fanno semplicemente sparire la conversione", after: "Il percorso server la consegna comunque; il percorso browser aggiunge dati di matching quando disponibili" },
        { aspect: "Duplicati", before: "Pixel e API server contano lo stesso ordine due volte", after: "ID evento e ID ordine condivisi; le piattaforme deduplicano" },
        { aspect: "Interruzione della piattaforma", before: "Errore silenzioso, nessun nuovo tentativo", after: "Retry con backoff, circuit breaker, dead-letter queue e replay" },
        { aspect: "Dove vanno i dati", before: "Endpoint di terze parti chiamati dalla pagina", after: "Host di ingest first-party; le piattaforme ricevono solo i campi mappati" },
      ],
    },
    faq: [
      { q: "Il tracking server-side aggira il consenso?", a: "No. Il consenso viene valutato per ogni evento e destinazione; senza la finalità richiesta nulla viene memorizzato, inviato o riprodotto in seguito." },
      { q: "Cosa succede quando una piattaforma è giù?", a: "Le consegne vengono ritentate con backoff, il circuit breaker mette in pausa la destinazione, gli eventi falliti finiscono nella dead-letter queue e possono essere riprodotti quando la piattaforma torna disponibile." },
    ],
  },
  {
    slug: "event-debugger",
    title: "Debugger degli eventi e lineage",
    short: "Vedi ogni evento con il suo snapshot del consenso, la decisione di routing e la risposta della piattaforma.",
    benefit: "Quando un numero in una piattaforma pubblicitaria sembra sbagliato, scopri il perché in un unico posto — senza tirare a indovinare tra console del browser, interfaccia della piattaforma e memoria di un collega.",
    intro: "Apri un evento qualsiasi e leggi la sua storia: origine e versione dell'SDK, il consenso concesso in quel momento, i click ID catturati, la versione di configurazione che lo ha instradato e il tentativo di consegna per ogni destinazione, incluso il payload oscurato e la risposta della piattaforma.",
    flow: {
      title: "Un evento, l'intero percorso",
      text: "Il debugger segue un evento dall'origine attraverso la normalizzazione, la decisione sul consenso e ogni tentativo di consegna. Gli scarti non sono mai silenziosi: ognuno riporta una motivazione come consenso mancante, PII bloccate, nome non valido, duplicato o destinazione in pausa.",
      caption: "Il lineage tiene insieme origine, snapshot del consenso, decisione di routing e risposta di ogni piattaforma.",
    },
    viewCaption: "Stream di eventi di esempio: eventi consegnati, un acquisto deduplicato e un acquisto server bloccato per mancanza della finalità marketing.",
    sections: [
      { title: "Oscurato, non nascosto", text: "Le anteprime del payload mostrano struttura e identificatori con hash, così puoi verificare le mappature senza esporre dati personali o token." },
      { title: "Eventi di test attraverso la pipeline reale", text: "Gli eventi di test sono contrassegnati, passano per la stessa coda e lo stesso worker e riportano il verdetto della piattaforma — nessun successo simulato." },
      { title: "Gli scarti sono spiegati", text: "Ogni evento scartato riporta una motivazione: consenso mancante, PII bloccate, nome non valido, duplicato, destinazione in pausa o blocco di policy." },
    ],
    bullets: ["Filtra per nome evento, stato e origine", "Cronologia dei tentativi per destinazione con stato HTTP e classe di errore", "Suggerimenti sulla modalità test di ogni piattaforma", "Link diretti alla procedura guidata della destinazione"],
    comparison: {
      title: "Debug dalla console contro debug dal lineage",
      text: "La stessa domanda — perché questo acquisto non è arrivato a Meta? — con due risposte diverse.",
      beforeLabel: "Console del browser e interfaccia della piattaforma",
      afterLabel: "Lineage degli eventi in Track",
      rows: [
        { aspect: "Dove guardare", before: "Scheda Network, modalità anteprima dei tag, l'event manager della piattaforma", after: "Un unico record dell'evento con ogni tentativo e risposta" },
        { aspect: "Consenso in quel momento", before: "Sconosciuto; ricostruito dalle impostazioni del banner", after: "Salvato come snapshot insieme all'evento" },
        { aspect: "Eventi server-side", before: "Invisibili dal browser", after: "Stesso lineage, contrassegnati con la loro origine" },
        { aspect: "Dati personali", before: "Payload in chiaro in log e screenshot", after: "Identificatori con hash, anteprime oscurate" },
      ],
    },
    faq: [{ q: "Per quanto tempo vengono conservati i record del debugger?", a: "I tentativi di consegna per 90 giorni di default e gli eventi per 13 mesi; entrambi configurabili per organizzazione nel centro privacy." }],
  },
  {
    slug: "data-quality",
    title: "Qualità dei dati e health score",
    short: "Un unico score con componenti spiegabili e problemi che rimandano alla loro soluzione.",
    benefit: "Scopri quando il tracking si rompe, vedi quale parte si è rotta e vai dritto alla correzione — prima che una campagna giri su dati sbagliati.",
    intro: "Il worker calcola un health score del tracking a partire da copertura del consenso, copertura degli eventi critici, qualità dello schema, tasso di duplicati, successo delle consegne e freschezza. Ogni problema rilevato indica il tool dell'assistente che lo risolve.",
    flow: {
      title: "Sei componenti, uno score spiegabile",
      text: "Lo score viene calcolato dagli eventi dell'ultimo periodo: quanti portano un segnale di consenso esplicito, quali eventi critici pianificati sono stati visti, quanti superano le verifiche di schema e PII, il tasso di duplicati, il successo delle consegne per destinazione e quando è arrivato l'ultimo evento browser. I pesi sono mostrati accanto allo score, così un numero più basso indica sempre la sua causa.",
      caption: "Eventi → verifiche → componenti pesate → score con i problemi che lo hanno abbassato.",
    },
    viewCaption: "Score di esempio con le sue sei componenti e due problemi aperti, ognuno con il tool che lo risolve.",
    sections: [
      { title: "Problemi con fingerprint", text: "I problemi ricorrenti vengono raggruppati, contati e datati, così vedi tendenze invece di rumore." },
      { title: "Guardrail sullo schema", text: "Gli eventi standard hanno parametri obbligatori; gli eventi personalizzati seguono regole di denominazione; le PII nelle proprietà vengono bloccate prima della memorizzazione." },
      { title: "Benchmark solo con opt-in", text: "Benchmark anonimizzati e aggregati sono disponibili solo per le organizzazioni che aderiscono esplicitamente." },
    ],
    bullets: ["Score per sito con le sue componenti", "Risolvi o ignora i problemi con una traccia di audit", "Copertura del consenso e tasso di duplicati come metriche di prima classe"],
    comparison: {
      title: "Accorgersi dei problemi contro esserne avvisati",
      text: "Come emerge un evento Purchase rotto con e senza l'health score.",
      beforeLabel: "Senza monitoraggio",
      afterLabel: "Con l'health score",
      rows: [
        { aspect: "Rilevamento", before: "Qualcuno nota un calo nella dashboard delle campagne giorni dopo", after: "Lo score scende e viene aperto un problema" },
        { aspect: "Diagnosi", before: "Quale tag, quale pagina, quale browser?", after: "La componente che è scesa e gli eventi dietro di essa" },
        { aspect: "Correzione", before: "Ticket, modifica del tag, nuova pubblicazione, attesa", after: "Il problema indica il tool dell'assistente; tu approvi la modifica" },
        { aspect: "Tendenza", before: "Nessuno storico", after: "Problemi raggruppati, contati e datati" },
      ],
    },
    faq: [{ q: "Lo score è confrontabile tra siti diversi?", a: "Le componenti sono identiche per ogni sito; i pesi sono documentati nella scheda dello score, così i team possono ragionare sulle differenze." }],
  },
  {
    slug: "consent",
    title: "Progettato attorno al consenso",
    short: "Opt-in rigoroso di default, Consent Mode v2, destinazioni basate sulle finalità, nessun replay dopo il consenso.",
    benefit: "Ogni destinazione riceve esattamente ciò che il visitatore ha accettato — valutato per ogni evento, nel browser e di nuovo sul server — così la conformità non è un'impostazione del banner che speri sia giusta.",
    intro: "Il consenso non è un'integrazione del banner ma un motore di policy: finalità, regioni, requisiti delle destinazioni e cattura dei click ID vengono valutati per ogni evento nel browser e di nuovo sul server.",
    flow: {
      title: "Il gate sta davanti a ogni destinazione",
      text: "Ogni destinazione dichiara la finalità di cui ha bisogno. Quando arriva un evento, Track confronta lo snapshot del consenso con quel requisito: le destinazioni di analisi ricevono gli eventi con il consenso per l'analisi, quelle pubblicitarie solo con il consenso marketing. Una revoca ferma subito gli invii e nulla di ciò che è stato memorizzato prima del consenso viene riprodotto dopo.",
      caption: "Sito web → Track → gate consenso/policy → solo le destinazioni la cui finalità è stata concessa.",
    },
    viewCaption: "Stato del consenso di esempio: analisi concessa, marketing negato — e i flag Consent Mode v2 e i motivi di blocco che ne derivano.",
    sections: [
      { title: "Adattatori CMP e API", text: "Adattatori per TCF 2.2, GPP e Global Privacy Control, Cookiebot, OneTrust e Usercentrics, più un'API di consenso per i banner personalizzati." },
      { title: "Consent Mode v2, basato sulle finalità", text: "I segnali di consenso di Google derivano dalle finalità; la modalità avanzata è disponibile solo con una nota documentata di revisione legale." },
      { title: "Evidenze", text: "Gli snapshot del consenso, deduplicati, vengono memorizzati con ogni evento, così puoi dimostrare cosa è stato concesso e quando." },
    ],
    bullets: ["Il consenso dedotto non viene mai esportato alle piattaforme pubblicitarie", "La revoca ferma subito gli invii", "Gli acquisti server restano operativi; mai verso la pubblicità senza consenso"],
    comparison: {
      title: "Consenso per singolo tag contro motore di policy",
      text: "Dove viene presa la decisione — e se potrai dimostrarla in seguito.",
      beforeLabel: "Consenso gestito per tag",
      afterLabel: "Motore di policy in Track",
      rows: [
        { aspect: "Punto di decisione", before: "Il trigger di ogni tag, configurato a mano", after: "Ogni evento, ogni destinazione, nel browser e sul server" },
        { aspect: "Eventi server-side", before: "Inviati a prescindere dal banner", after: "Stessa verifica delle finalità degli eventi browser" },
        { aspect: "Revoca", before: "Ha effetto solo al caricamento della pagina successiva, ammesso che lo abbia", after: "Ferma subito gli invii; nessun replay degli eventi precedenti" },
        { aspect: "Evidenze", before: "Nessuna", after: "Snapshot del consenso memorizzato con ogni evento" },
      ],
    },
    faq: [{ q: "Quali regioni sono supportate?", a: "Opt-in rigoroso per UE/SEE/Regno Unito/Svizzera di default; è possibile configurare policy per regione, ma mai più deboli della base legale senza una decisione esplicita." }],
  },
  {
    slug: "attribution",
    title: "Click ID e attribuzione fatti bene",
    short: "Cattura solo gli ID di cui la destinazione ha bisogno, solo con il consenso, solo per la finestra documentata.",
    benefit: "Le tue campagne ricevono i click ID che servono per attribuire una conversione — e nessuna piattaforma riceve mai un ID che appartiene a un'altra.",
    intro: "Il tracker cattura gclid, fbclid, ttclid, msclkid, li_fat_id e gli altri click ID delle piattaforme sulle landing page dopo il consenso marketing, li memorizza in modalità first-party per la finestra prevista dalla piattaforma e inoltra ogni ID solo alla piattaforma a cui appartiene.",
    flow: {
      title: "Ogni ID viaggia verso esattamente una piattaforma",
      text: "Una landing page con un gclid e un fbclid produce due ID memorizzati dopo il consenso marketing. Quando arriva l'acquisto, Track allega il gclid alla consegna verso Google Ads e il fbclid a quella verso Meta — la matrice è verificata automaticamente, quindi una fuga di dati tra piattaforme non è un errore di configurazione che puoi commettere.",
      caption: "Landing page → archivio first-party dei click ID → acquisto → inoltro limitato alla destinazione.",
    },
    viewCaption: "Matrice di esempio: quale click ID viene catturato, dove viene inoltrato e per quanto tempo viene conservato.",
    sections: [
      { title: "Inoltro limitato alla destinazione", text: "Meta non vede mai il tuo gclid e Google non vede mai il tuo fbclid. La matrice di policy è verificata automaticamente." },
      { title: "Deduplicazione a livello di ordine", text: "Gli acquisti portano l'ID ordine a ogni piattaforma che lo supporta, così le conversioni browser e server si uniscono correttamente." },
      { title: "Offline e CRM", text: "Gli eventi server con flag offline raggiungono Google Ads, CM360, Microsoft, Meta, TikTok, Pinterest, Snapchat, Amazon, Yahoo e LinkedIn come conversioni offline." },
    ],
    bullets: ["Conservazione documentata per ogni click ID (90 giorni di default)", "Enhanced Conversions con hashing normalizzato", "Network di affiliazione con click ID per network"],
    comparison: {
      title: "Parametri URL nel dataLayer contro un archivio dedicato dei click ID",
      text: "La differenza tra raccogliere tutto e inoltrare ogni cosa solo a chi appartiene.",
      beforeLabel: "Click ID nel dataLayer",
      afterLabel: "Archivio dei click ID in Track",
      rows: [
        { aspect: "Cattura", before: "Ogni parametro, su ogni pagina, a prescindere dal consenso", after: "Solo ID noti, sulle landing page, dopo il consenso marketing" },
        { aspect: "Inoltro", before: "Qualsiasi cosa legga un template di tag", after: "Per destinazione, da una matrice verificata automaticamente" },
        { aspect: "Conservazione", before: "Durata del cookie impostata da ogni tag", after: "Finestra documentata per ogni ID, 90 giorni di default" },
        { aspect: "Conversioni offline", before: "Caricamenti manuali", after: "Eventi server con flag offline" },
      ],
    },
    faq: [{ q: "Costruite profili cross-site?", a: "No. Non c'è fingerprinting né identità cross-site; gli identificatori restano all'interno del sito e delle finalità per cui è stato prestato il consenso." }],
  },
];

export const FEATURES_PAGE_COPY_IT: FeaturesPageCopy = {
  eyebrow: "Funzionalità",
  title: "Ogni conversione consegnata una sola volta, con il consenso, alla piattaforma a cui appartiene",
  text: "Track sostituisce il container di tag con una configurazione guidata, un router server-side basato sul consenso e un debugger che spiega ogni evento. Questa pagina mostra il prodotto così come funziona — gli stati qui sotto sono dati di esempio, non traffico reale.",
  cta: "Inizia con il tuo dominio",
  ctaSecondary: "Scopri come funziona",
  stage: {
    title: "Flusso dei dati dal sito web alle destinazioni, passando per Track",
    description: "Un sito web invia eventi dall'SDK browser e dal server a Track. Track valuta il consenso a un gate di policy e inoltra ogni evento solo alle destinazioni la cui finalità è stata concessa: Meta, Google Ads, Google Analytics 4 e TikTok.",
    caption: "Sito web → Track → consenso/policy → destinazioni. Browser e server condividono un unico ID evento; il gate decide per ogni destinazione.",
  },
  scenarios: {
    title: "Cosa succede a un acquisto",
    text: "Cambia scenario per vedere come lo stesso evento viene instradato quando il consenso è concesso, revocato o una piattaforma è giù. La decisione e la sua motivazione sono ciò che poi leggi nel debugger.",
    tabsLabel: "Scenari di routing",
    items: [
      {
        id: "granted",
        label: "Consenso concesso",
        title: "Analisi e marketing concessi",
        text: "L'acquisto arriva dal browser e dal server con lo stesso ID evento. Il gate trova le finalità richieste e lo inoltra a tutte e quattro le destinazioni; Meta e TikTok deduplicano sull'ID evento, Google Ads sull'ID ordine.",
        points: ["Decisione: consegnato a Meta, Google Ads, GA4, TikTok", "Deduplicazione: ID evento (Meta, TikTok), ID ordine (Google Ads)", "Click ID allegati per destinazione: gclid → Google, fbclid → Meta"],
      },
      {
        id: "withdrawn",
        label: "Marketing revocato",
        title: "Analisi concessa, marketing negato",
        text: "Il visitatore ha revocato il consenso marketing prima dell'acquisto. Il gate lascia passare l'evento verso Google Analytics 4 e blocca le destinazioni pubblicitarie con la motivazione purpose_not_granted. Nulla viene memorizzato per dopo; quando il consenso viene concesso di nuovo, gli eventi precedenti non vengono riprodotti.",
        points: ["Decisione: consegnato a GA4; bloccato per Meta, Google Ads, TikTok", "Motivazione mostrata nel debugger: purpose_not_granted (marketing)", "Consent Mode v2: analytics_storage granted, ad_storage denied"],
      },
      {
        id: "outage",
        label: "Piattaforma giù",
        title: "Consenso concesso, una piattaforma non disponibile",
        text: "TikTok risponde con un errore del server. Track ritenta con backoff e jitter, apre il circuit breaker dopo errori ripetuti e parcheggia l'evento nella dead-letter queue. Le altre tre destinazioni non ne risentono. Quando TikTok torna disponibile, la dead-letter queue viene riprodotta.",
        points: ["Decisione: consegnato a Meta, Google Ads, GA4; TikTok in retry", "Circuit breaker aperto per TikTok; eventi nella dead-letter queue", "Il replay dopo il ripristino mantiene l'ID evento originale, quindi nulla viene contato due volte"],
      },
    ],
  },
  index: {
    title: "Sei funzionalità, un unico layer di eventi",
    text: "Ogni funzionalità è costruita sulla stessa configurazione firmata e sullo stesso schema di eventi. Apri una funzionalità per vedere la sua vista prodotto, il flusso dei dati e un confronto prima/dopo.",
    more: "Scopri di più",
  },
  comparison: {
    title: "Container di tag contro layer di eventi",
    text: "Dove un container classico lascia il lavoro a te e dove Track lo fa per costruzione.",
    beforeLabel: "Container di tag classico",
    afterLabel: "Track",
    rows: [
      { aspect: "Cosa gira sul tuo sito", before: "Tag HTML e JavaScript personalizzati di chiunque abbia accesso al container", after: "Uno snippet e una configurazione firmata e versionata — nessuna esecuzione di codice personalizzato" },
      { aspect: "Consenso", before: "Condizioni di trigger per ogni tag, mantenute a mano", after: "Motore di policy che valuta ogni evento per ogni destinazione, browser e server" },
      { aspect: "Consegna server-side", before: "Un secondo container, un secondo set di tag, deduplicazione manuale", after: "Integrata: ID evento condiviso, retry, circuit breaker, replay" },
      { aspect: "Trovare gli errori", before: "Modalità anteprima e interfacce delle piattaforme", after: "Lineage degli eventi con snapshot del consenso, decisione di routing e risposta della piattaforma" },
      { aspect: "Modifiche", before: "Pubblicare e sperare", after: "Diff, approvazione, versione firmata, rollback con un clic" },
    ],
  },
  trust: {
    title: "Fatti che puoi verificare",
    items: [
      { title: "Regione dati UE", text: "Gli eventi vengono trattati nell'UE; le API delle piattaforme ricevono solo i campi che hai mappato, sulla base di trasferimento documentata per ogni destinazione." },
      { title: "Configurazioni firmate", text: "Ogni bundle pubblicato è immutabile, versionato e firmato con Ed25519; l'SDK verifica la firma prima di applicarlo." },
      { title: "Nessun codice personalizzato", text: "Non esiste un tipo di tag HTML o JavaScript personalizzato. Le trasformazioni sono dichiarative e validate sul server." },
      { title: "Opt-in rigoroso di default", text: "UE/SEE/Regno Unito/Svizzera partono con opt-in rigoroso; il consenso dedotto non viene mai esportato alle piattaforme pubblicitarie." },
    ],
  },
  closing: { title: "Guarda queste viste con i tuoi eventi", text: "Crea il tuo sito, incolla lo snippet e lascia che l'assistente configuri la prima destinazione — il debugger e l'health score si riempiono dal primo evento.", cta: "Inizia con il tuo dominio", secondary: "Vedi i prezzi" },
};

export const FEATURE_DETAIL_COPY_IT: FeatureDetailLabels = {
  features: "Funzionalità",
  breadcrumb: "Percorso di navigazione",
  howBuilt: "Come è costruita",
  howBuiltText: "Le decisioni tecniche dietro la funzionalità — la prova dopo il beneficio.",
  proof: "Cosa puoi verificare",
  proofText: "Fatti di prodotto che trovi nella dashboard, nella documentazione e nell'audit log.",
  faq: "Domande",
  more: "Altre funzionalità",
  moreText: "Costruite sulla stessa configurazione firmata e sullo stesso schema di eventi.",
  cta: "Provala sul tuo dominio",
  ctaText: "Crea un sito, installa uno snippet e lascia che l'assistente configuri la prima destinazione in pochi minuti.",
  start: "Inizia gratis",
  pricing: "Vedi i prezzi",
};

export const FEATURE_UI_COPY_IT: FeatureUiCopy = {
  example: "Dati di esempio",
  exampleHint: "Stato di esempio statico — nessun traffico reale, nessun dato reale di clienti.",
  diagram: {
    website: "Sito web",
    browser: "SDK browser",
    server: "API server",
    track: "Track",
    gate: "Consenso / policy",
    gateGranted: "consenso concesso",
    gateDenied: "marketing negato",
    gatePending: "consenso in sospeso",
    dedup: "un unico ID evento",
    notUsed: "non usato",
    delivered: "consegnato",
    blocked: "bloccato",
    retrying: "in retry",
    paused: "in pausa",
    destinations: { meta: "Meta", googleAds: "Google Ads", ga4: "GA4", tiktok: "TikTok", linkedin: "LinkedIn" },
    describe: (paths, gate) => {
      const origin = paths === "browser" ? "solo dall'SDK browser" : paths === "server" ? "solo dall'API server" : "dall'SDK browser e dall'API server con un unico ID evento condiviso";
      const decision = gate === "granted" ? "il gate del consenso è aperto e gli eventi raggiungono le destinazioni" : gate === "denied" ? "il gate del consenso blocca le destinazioni pubblicitarie e solo l'analisi riceve l'evento" : "il gate del consenso attende un segnale e nulla viene inoltrato";
      return `Il sito web invia eventi ${origin} a Track; ${decision}.`;
    },
    chains: {
      setup: { ai: "Track AI", aiSub: "propone", tools: "Tool tipizzati", toolsSub: "validati sul server", approval: "La tua approvazione", approvalSub: "vincolata al diff", config: "Config firmata", configSub: "versione 13", website: "Sito web", websiteSub: "verifica la firma", describe: "Track AI propone modifiche tramite tool tipizzati e validati sul server; la tua approvazione, vincolata al diff, pubblica una configurazione firmata che il sito web verifica prima di caricarla." },
      health: { events: "Eventi", eventsSub: "ultimo periodo", checks: "Verifiche", checksSub: "consenso · schema · consegna", score: "Score 86", scoreSub: "6 componenti pesate", issues: "2 problemi", issuesSub: "ognuno indica la sua soluzione", describe: "Gli eventi dell'ultimo periodo passano attraverso le verifiche; sei componenti pesate formano lo score e ogni problema aperto indica il tool che lo risolve." },
      attribution: { landing: "Landing page", landingSub: "gclid · fbclid", consent: "Consenso marketing", consentSub: "concesso", store: "Archivio dei click ID", storeSub: "first-party · 90 giorni", purchase: "Acquisto", purchaseSub: "3 giorni dopo", google: "Google Ads", googleSub: "solo gclid", meta: "Meta", metaSub: "solo fbclid", describe: "Una landing page con gclid e fbclid memorizza entrambi gli ID in modalità first-party dopo il consenso marketing; l'acquisto tre giorni dopo raggiunge Google Ads solo con il gclid e Meta solo con il fbclid." },
    },
  },
  stream: {
    title: "Eventi live",
    caption: "Ogni riga è un evento con la sua origine, il consenso in quel momento, la decisione di routing e le destinazioni.",
    columns: { event: "Evento", origin: "Origine", consent: "Consenso", decision: "Decisione", destination: "Destinazioni" },
    rows: [
      { event: "page_view", origin: "browser", consent: "analisi", consentTone: "ok", decision: "consegnato", decisionTone: "ok", destination: "GA4" },
      { event: "add_to_cart", origin: "browser", consent: "marketing", consentTone: "ok", decision: "consegnato", decisionTone: "ok", destination: "Meta, TikTok" },
      { event: "purchase", origin: "browser + server", consent: "marketing", consentTone: "ok", decision: "consegnato, deduplicato (ID ordine)", decisionTone: "ok", destination: "Meta CAPI, Google Ads" },
      { event: "purchase", origin: "server", consent: "marketing mancante", consentTone: "bad", decision: "bloccato: consent_missing", decisionTone: "bad", destination: "Meta CAPI" },
      { event: "generate_lead", origin: "browser", consent: "marketing", consentTone: "ok", decision: "consegnato", decisionTone: "ok", destination: "LinkedIn" },
    ],
  },
  lineage: {
    title: "Lineage dell'evento",
    caption: "Un acquisto, letto dall'origine alla risposta della piattaforma.",
    facts: [
      { label: "Evento", value: "purchase · evt_…7f2a" },
      { label: "Origine", value: "SDK browser + server (webhook dello shop)" },
      { label: "Configurazione", value: "versione 12, firma verificata" },
      { label: "Snapshot del consenso", value: "analisi, marketing · fonte: CMP" },
      { label: "Click ID", value: "gclid (catturato 3 giorni fa)" },
    ],
    attempts: {
      title: "Tentativi di consegna",
      columns: { destination: "Destinazione", status: "Stato", result: "Risultato" },
      rows: [
        { destination: "Meta Conversions API", status: "200", tone: "ok", result: "accettato, deduplicato per ID evento" },
        { destination: "Google Ads", status: "200", tone: "ok", result: "accettato, deduplicato per ID ordine" },
        { destination: "TikTok Events API", status: "503", tone: "warn", result: "retry 2 pianificato con backoff" },
      ],
    },
    payload: { title: "Payload oscurato", copy: "Copia il payload", copied: "Copiato", code: PAYLOAD_EXAMPLE },
  },
  health: {
    title: "Salute del tracking",
    caption: "Componenti pesate; uno score più basso indica sempre la sua causa.",
    scoreLabel: "Score",
    score: 86,
    componentsLabel: "Componenti",
    weight: (percent) => `${percent}% di peso`,
    components: [
      { key: "consent", label: "Copertura del consenso", score: 91, weight: 20, detail: "Il 91% degli eventi porta un segnale di consenso esplicito" },
      { key: "coverage", label: "Eventi critici", score: 78, weight: 25, detail: "7 dei 9 eventi critici pianificati osservati" },
      { key: "schema", label: "Qualità dello schema", score: 74, weight: 15, detail: "Il 74% degli eventi supera le verifiche di schema e PII" },
      { key: "dedup", label: "Duplicati", score: 96, weight: 10, detail: "1,0% di duplicati" },
      { key: "delivery", label: "Consegna", score: 88, weight: 20, detail: "94% consegnato, 1 integrazione con problemi di credenziali" },
      { key: "liveness", label: "Freschezza", score: 100, weight: 10, detail: "Ultimo evento browser 4 min fa" },
    ],
    issuesLabel: "Problemi aperti",
    issues: [
      { title: "purchase senza currency", detail: "A 12 eventi nelle ultime 24 h manca il parametro obbligatorio", fix: "Soluzione: aggiorna la mappatura dell'evento", tone: "warn" },
      { title: "Segnale di consenso mancante", detail: "Il 9% degli eventi è arrivato senza uno stato del consenso esplicito", fix: "Soluzione: collega l'adattatore CMP", tone: "warn" },
    ],
  },
  consent: {
    title: "Stato del consenso e segnali derivati",
    caption: "Le finalità arrivano dal tuo CMP; tutto il resto è derivato, mai indovinato.",
    purposesLabel: "Finalità",
    purposes: [
      { label: "Strettamente necessari", granted: true },
      { label: "Analisi", granted: true },
      { label: "Marketing", granted: false },
      { label: "Personalizzazione", granted: false },
    ],
    granted: "concesso",
    denied: "negato",
    flagsLabel: "Consent Mode v2",
    flags: [
      { key: "analytics_storage", value: "granted" },
      { key: "ad_storage", value: "denied" },
      { key: "ad_user_data", value: "denied" },
      { key: "ad_personalization", value: "denied" },
    ],
    reasonsLabel: "Motivi di blocco riportati dal motore di policy",
    reasons: [
      { code: "consent_missing", text: "ancora nessun segnale di consenso per l'evento" },
      { code: "consent_denied", text: "il visitatore ha rifiutato" },
      { code: "purpose_not_granted", text: "la destinazione richiede una finalità non concessa" },
      { code: "gpc_opt_out", text: "Global Privacy Control attivo" },
      { code: "destination_paused", text: "kill switch o circuit breaker" },
      { code: "inferred_data_not_exportable", text: "il consenso dedotto non raggiunge mai le piattaforme pubblicitarie" },
    ],
  },
  attribution: {
    title: "Matrice dei click ID",
    caption: "Catturati dopo il consenso marketing, memorizzati in modalità first-party, inoltrati solo alla piattaforma a cui appartengono.",
    columns: { id: "Click ID", captured: "Catturato", forwarded: "Inoltrato solo a", retention: "Conservato" },
    rows: [
      { id: "gclid", captured: "landing page, dopo il consenso marketing", forwarded: "Google Ads, GA4, Google Marketing Platform", retention: "90 giorni" },
      { id: "fbclid", captured: "landing page, dopo il consenso marketing", forwarded: "Meta", retention: "90 giorni" },
      { id: "ttclid", captured: "landing page, dopo il consenso marketing", forwarded: "TikTok", retention: "90 giorni" },
      { id: "msclkid", captured: "landing page, dopo il consenso marketing", forwarded: "Microsoft Advertising", retention: "90 giorni" },
      { id: "li_fat_id", captured: "landing page, dopo il consenso marketing", forwarded: "LinkedIn", retention: "90 giorni" },
    ],
    note: "La conservazione è documentata per ogni ID ed è configurabile; 90 giorni è il valore di default.",
  },
  setup: {
    title: "Configurazione guidata",
    caption: "L'assistente propone, i tool validano, tu approvi.",
    assistant: "Track AI",
    you: "Tu",
    messages: [
      { from: "assistant", text: "example-shop.test gira su Shopify con Cookiebot come strumento di consenso (confidenza alta). Per uno shop suggerisco view_item, add_to_cart, begin_checkout e purchase. Preparo la bozza del piano per Meta e Google Ads?" },
      { from: "you", text: "Sì, prima Meta." },
      { from: "assistant", text: "ID pixel validato. La Conversions API ha bisogno di un token di accesso — inseriscilo nella scheda vault qui sotto; non comparirà mai in questa chat." },
    ],
    vault: { title: "Scheda vault · token di accesso Meta", text: "Salvato cifrato; non visibile a nessuno, modello incluso.", state: "salvato" },
    test: { title: "Evento di test · purchase", text: "Inviato attraverso la pipeline reale con il codice evento di test della piattaforma.", state: "accettato da Meta" },
    approval: {
      title: "Pubblica la versione 13",
      text: "Vincolata esattamente a questo diff e a te come approvatore.",
      diff: ["+ destination meta: browser + server", "+ mapping purchase → Purchase (event id, order id)", "~ consent: marketing required for meta"],
      state: "in attesa della tua approvazione",
      action: "Approva e pubblica",
    },
  },
  destinations: {
    title: "Stato delle destinazioni",
    caption: "Salute, modalità e coda per ogni destinazione; gli errori vengono gestiti, non nascosti.",
    columns: { destination: "Destinazione", mode: "Modalità", health: "Salute", last: "Ultima consegna", queue: "Coda" },
    rows: [
      { destination: "Meta", mode: "browser + server", health: "in salute", tone: "ok", last: "12 s fa", queue: "0 retry" },
      { destination: "Google Ads", mode: "server", health: "in salute", tone: "ok", last: "40 s fa", queue: "0 retry" },
      { destination: "TikTok", mode: "browser + server", health: "degradata, circuit breaker aperto", tone: "warn", last: "6 min fa", queue: "3 nella dead-letter queue" },
      { destination: "LinkedIn", mode: "server", health: "in pausa per kill switch", tone: "neutral", last: "2 h fa", queue: "trattenuti" },
    ],
  },
};
