import type { FeatureCopy, FeatureDetailLabels, FeatureUiCopy, FeaturesPageCopy } from "../types";
import { PAYLOAD_EXAMPLE } from "./samples";

/**
 * Dutch (nl, "je" register) copy of the features area. Same shape as en.ts; see docs/14-localization.md.
 */

export const FEATURES_NL: FeatureCopy[] = [
  {
    slug: "ai-setup",
    title: "AI-begeleide setup",
    short: "Beschrijf je site, bevestig elke stap, publiceer een ondertekende configuratie.",
    benefit: "Je eerste destination gaat live in één begeleide sessie – zonder een tag te schrijven en zonder de controle op te geven over wat er wordt gepubliceerd.",
    intro: "De assistent maakt van een domein een werkende meetsetup: hij detecteert platform en toestemmingstool, stelt een eventplan voor jouw type bedrijf voor, verzamelt openbare ID's in de chat en secrets in een kluiskaart, verstuurt een echt testevent en bereidt een publicatiediff voor die jij goedkeurt.",
    flow: {
      title: "Elke actie is een getypeerde tool-aanroep die je kunt zien",
      text: "De assistent voert nooit vrije code uit. Hij roept server-gevalideerde tools aan: platform detecteren, eventplan opstellen, pixel-ID valideren, testevent versturen, diff voorbereiden. Alles wat onomkeerbaar is – publiceren, rollback, rotatie van credentials – stopt bij een goedkeuringskaart die is gekoppeld aan precies de wijziging die je voor je hebt.",
      caption: "Assistent → getypeerde tools → goedkeuringskaart → ondertekende configuratie. Secrets gaan rechtstreeks de kluis in en passeren nooit de chat.",
    },
    viewCaption: "Voorbeeldsessie: platform gedetecteerd, eventplan voorgesteld, token in de kluis opgeslagen, een echt testevent geaccepteerd, publicatie wacht op je goedkeuring.",
    sections: [
      { title: "Getypeerde tools in plaats van vrije acties", text: "Elke actie van de assistent is een server-gevalideerde tool-aanroep met rolcontrole, een auditvermelding en – voor alles wat onomkeerbaar is – een goedkeuringstoken dat is gekoppeld aan precies de diff die je zag." },
      { title: "Secrets bereiken het model nooit", text: "Access tokens gaan via een aparte kaart of OAuth rechtstreeks de versleutelde kluis in. Het transcript, het model en de browser zien ze nooit; een DLP-laag maskeert geplakte secrets en PII." },
      { title: "Deterministische state machine", text: "De setup volgt een expliciete state machine met vereisten en bewijs per status. Dezelfde statussen zijn beschikbaar als regelgebaseerde wizard wanneer de AI-provider niet beschikbaar is – niets hangt af van een model dat online is." },
    ],
    bullets: ["Detectie van type bedrijf en platform met een betrouwbaarheidsniveau", "Eventplansjablonen voor webshops, leadgeneratie, SaaS en publishers", "Openbare ID's gevalideerd tegen platformformaten", "Publiceren alleen na diff, ontvangerslijst en expliciete bevestiging"],
    comparison: {
      title: "Handmatige setup versus de begeleide sessie",
      text: "Wat er verandert als de assistent de setup aanstuurt en jij de goedkeuringen houdt.",
      beforeLabel: "Handmatige containersetup",
      afterLabel: "Begeleide setup met Track",
      rows: [
        { aspect: "Eventplan", before: "Uit het hoofd geschreven, één tag tegelijk", after: "Voorgesteld voor jouw type bedrijf, bewerkt in de chat, gevalideerd vóór publicatie" },
        { aspect: "Credentials", before: "In tagvelden geplakt en zichtbaar voor iedereen met containertoegang", after: "Ingevoerd in een kluiskaart of via OAuth; nooit zichtbaar in het transcript" },
        { aspect: "Verificatie", before: "Hopen dat het platform iets heeft ontvangen", after: "Een echt testevent door de echte pipeline met het oordeel van het platform" },
        { aspect: "Publiceren", before: "Publiceren en daarna ontdekken wat er is veranderd", after: "Eerst diff, ontvangers en goedkeuring; daarna een ondertekende, geversioneerde bundle" },
      ],
    },
    faq: [
      { q: "Kan de assistent publiceren zonder mij?", a: "Nee. Publiceren, rollbacks, rotatie van credentials en het activeren van destinations vereisen altijd jouw klik op een goedkeuringskaart die aan de exacte wijziging is gekoppeld." },
      { q: "Welk model wordt gebruikt?", a: "OpenAI Responses API met structured outputs en strikte function calling. Modelnamen worden server-side geconfigureerd en bij de start geverifieerd; de UI codeert ze nooit hard." },
    ],
  },
  {
    slug: "server-side-tracking",
    title: "Server-side event router",
    short: "Eén event, elk platform: aflevering via browser en server met gedeelde deduplicatie.",
    benefit: "Verstuur elke conversie één keer en laat elk platform die ontvangen op de manier die voor dat platform het beste telt – browser, server of beide – zonder dubbeltelling.",
    intro: "Track ontvangt events van de browser-SDK, je server, shopplatformen en affiliatenetwerken, normaliseert ze naar één schema, past toestemming toe en routeert ze naar 22 destinationtypes met retries, circuit breakers, een dead-letter queue en replay.",
    flow: {
      title: "Browser en server delen één event-ID",
      text: "De browser-SDK en je server (of shopwebhook) versturen dezelfde aankoop met dezelfde event-ID. Track normaliseert beide, beoordeelt de toestemming per destination en stuurt ze door; Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn en de andere dedupliceren op die ID, Google Ads op de order-ID.",
      caption: "Website → Track → Toestemming/policy → Destinations. Beide herkomsten eindigen bij dezelfde destinations en worden daar gededupliceerd.",
    },
    viewCaption: "Voorbeeld van destination health: twee gezonde destinations, één platformstoring die door de circuit breaker wordt opgevangen, één destination gepauzeerd door een kill switch.",
    sections: [
      { title: "Hybride als standaard", text: "Elke destination kan draaien via browsertag, server-API of beide. Beide routes delen één event-ID, zodat Meta, TikTok, Pinterest, Snapchat, Microsoft, LinkedIn en de andere betrouwbaar dedupliceren." },
      { title: "Duurzaam en observeerbaar", text: "Een duurzame queue met idempotente berichten, retries per destination met jittered backoff, circuit breakers bij falende platformen, dead-letter-opslag en replay. Elke poging wordt vastgelegd met een gemaskeerde payloadpreview." },
      { title: "First-party by design", text: "De tracker wordt geleverd vanaf je CDN-host, events gaan naar je ingest-host, configuratiebundles zijn Ed25519-ondertekend en worden in de browser geverifieerd voordat er iets laadt." },
    ],
    bullets: ["Browser-SDK door een CI-budget onder 30 KB gzip gehouden, met toestemmingsgebonden opslag", "Server-API met source keys voor CRM- en offline conversies", "Kill switches per site en organisatie", "EU data plane met row-level tenantisolatie"],
    comparison: {
      title: "Alleen browsertags versus de hybride router",
      text: "Waarom één event via Track meer waard is dan dezelfde pixel die twee keer afgaat.",
      beforeLabel: "Alleen browsertags",
      afterLabel: "Browser + server met Track",
      rows: [
        { aspect: "Verloren events", before: "Geblokkeerde scripts en gesloten tabbladen laten de conversie gewoon vallen", after: "De serverroute levert de conversie alsnog af; de browserroute voegt matchdata toe als die beschikbaar is" },
        { aspect: "Duplicaten", before: "Pixel en server-API tellen dezelfde bestelling twee keer", after: "Gedeelde event-ID en order-ID; de platformen dedupliceren" },
        { aspect: "Platformstoring", before: "Stille fout, geen retry", after: "Retries met backoff, circuit breaker, dead-letter queue en replay" },
        { aspect: "Waar data naartoe gaat", before: "Third-party endpoints aangeroepen vanaf de pagina", after: "First-party ingest-host; platformen ontvangen alleen gemapte velden" },
      ],
    },
    faq: [
      { q: "Omzeilt server-side tracking de toestemming?", a: "Nee. Toestemming wordt beoordeeld voor elk event en elke destination; zonder het vereiste doel wordt niets opgeslagen, verstuurd of later opnieuw afgespeeld." },
      { q: "Wat gebeurt er als een platform down is?", a: "Afleveringen worden opnieuw geprobeerd met backoff, de circuit breaker pauzeert de destination, mislukte events komen in de dead-letter queue en kunnen opnieuw worden afgespeeld zodra het platform hersteld is." },
    ],
  },
  {
    slug: "event-debugger",
    title: "Event Debugger en lineage",
    short: "Bekijk elk event met zijn toestemmingssnapshot, routingbeslissing en platformantwoord.",
    benefit: "Als een cijfer in een advertentieplatform er verkeerd uitziet, ontdek je op één plek waarom – niet door te gokken tussen browserconsole, platform-UI en het geheugen van een collega.",
    intro: "Open een willekeurig event en lees zijn verhaal: bron en SDK-versie, de toestemming die op dat moment was gegeven, vastgelegde click-ID's, de configuratieversie die het heeft gerouteerd en de afleverpoging per destination, inclusief de gemaskeerde payload en het antwoord van het platform.",
    flow: {
      title: "Eén event, de hele route",
      text: "De debugger volgt een event vanaf de herkomst door de normalisatie, de toestemmingsbeslissing en elke afleverpoging. Drops zijn nooit stil: elke drop draagt een reden, zoals ontbrekende toestemming, geblokkeerde PII, een ongeldige naam, een duplicaat of een gepauzeerde destination.",
      caption: "De lineage houdt de herkomst, het toestemmingssnapshot, de routingbeslissing en het antwoord van elk platform bij elkaar.",
    },
    viewCaption: "Voorbeeld-eventstream: afgeleverde events, één gededupliceerde aankoop en één serveraankoop geblokkeerd wegens een ontbrekend marketingdoel.",
    sections: [
      { title: "Gemaskeerd, niet verborgen", text: "Payloadpreviews tonen structuur en gehashte identifiers, zodat je mappings kunt controleren zonder persoonsgegevens of tokens bloot te leggen." },
      { title: "Testevents door de echte pipeline", text: "Testevents worden gemarkeerd, doorlopen dezelfde queue en worker en rapporteren het oordeel van het platform – geen gesimuleerd succes." },
      { title: "Drops worden verklaard", text: "Elk gedropt event draagt een reden: ontbrekende toestemming, PII geblokkeerd, ongeldige naam, duplicaat, gepauzeerde destination of policy-blokkering." },
    ],
    bullets: ["Filteren op eventnaam, status en bron", "Pogingsgeschiedenis per destination met HTTP-status en foutklasse", "Testmodus-hints per platform", "Directe links naar de destination-wizard"],
    comparison: {
      title: "Debuggen via de console versus debuggen via lineage",
      text: "Dezelfde vraag – waarom heeft deze aankoop Meta niet bereikt? – op twee manieren beantwoord.",
      beforeLabel: "Browserconsole en platform-UI",
      afterLabel: "Event-lineage in Track",
      rows: [
        { aspect: "Waar je moet kijken", before: "Netwerktabblad, tag-previewmodus, de eventmanager van het platform", after: "Eén eventrecord met elke poging en elk antwoord" },
        { aspect: "Toestemming op dat moment", before: "Onbekend; gereconstrueerd uit de bannerinstellingen", after: "Opgeslagen als snapshot bij het event" },
        { aspect: "Server-side events", before: "Onzichtbaar vanuit de browser", after: "Dezelfde lineage, gemarkeerd met hun herkomst" },
        { aspect: "Persoonsgegevens", before: "Ruwe payloads in logs en screenshots", after: "Gehashte identifiers, gemaskeerde previews" },
      ],
    },
    faq: [{ q: "Hoe lang worden debuggerrecords bewaard?", a: "Afleverpogingen standaard 90 dagen en events 13 maanden; beide zijn per organisatie instelbaar in het privacycenter." }],
  },
  {
    slug: "data-quality",
    title: "Datakwaliteit en healthscore",
    short: "Eén score met verklaarbare onderdelen en problemen die naar hun oplossing linken.",
    benefit: "Weet wanneer tracking breekt, zie welk onderdeel is gebroken en spring direct naar de oplossing – voordat een campagne op slechte data draait.",
    intro: "De worker berekent een tracking-healthscore uit toestemmingsdekking, dekking van kritieke events, schemakwaliteit, duplicaatpercentage, afleversucces en actualiteit. Elk gedetecteerd probleem noemt de assistent-tool die het oplost.",
    flow: {
      title: "Zes onderdelen, één verklaarbare score",
      text: "De score wordt berekend uit de events van de laatste periode: hoeveel een expliciet toestemmingssignaal dragen, welke geplande kritieke events zijn gezien, hoeveel de schema- en PII-controles doorstaan, het duplicaatpercentage, het afleversucces per destination en wanneer het laatste browserevent binnenkwam. De wegingen staan naast de score, zodat een lager getal altijd naar zijn oorzaak wijst.",
      caption: "Events → controles → gewogen onderdelen → score met de problemen die hem hebben verlaagd.",
    },
    viewCaption: "Voorbeeldscore met zijn zes onderdelen en twee open problemen, elk met de tool die het oplost.",
    sections: [
      { title: "Problemen met fingerprints", text: "Terugkerende problemen worden gegroepeerd, geteld en van een tijdstempel voorzien, zodat je trends ziet in plaats van ruis." },
      { title: "Schema-vangrails", text: "Standaardevents hebben verplichte parameters; custom events volgen naamregels; PII in properties wordt geblokkeerd vóór opslag." },
      { title: "Benchmarks alleen met opt-in", text: "Geanonimiseerde, geaggregeerde benchmarks zijn alleen beschikbaar voor organisaties die zich daarvoor aanmelden." },
    ],
    bullets: ["Score per site met zijn onderdelen", "Problemen oplossen of negeren met een audittrail", "Toestemmingsdekking en duplicaatpercentage als volwaardige metrics"],
    comparison: {
      title: "Problemen opmerken versus gemeld krijgen",
      text: "Hoe een kapot purchase-event zichtbaar wordt met en zonder de healthscore.",
      beforeLabel: "Zonder monitoring",
      afterLabel: "Met de healthscore",
      rows: [
        { aspect: "Detectie", before: "Iemand merkt dagen later een dip op in het advertentiedashboard", after: "De score daalt en er wordt een probleem geopend" },
        { aspect: "Diagnose", before: "Welke tag, welke pagina, welke browser?", after: "Het onderdeel dat is gedaald en de events erachter" },
        { aspect: "Oplossing", before: "Ticket, tagwijziging, opnieuw publiceren, wachten", after: "Het probleem noemt de assistent-tool; jij keurt de wijziging goed" },
        { aspect: "Trend", before: "Geen geschiedenis", after: "Gegroepeerde, getelde problemen met tijdstempel" },
      ],
    },
    faq: [{ q: "Is de score vergelijkbaar tussen sites?", a: "De onderdelen zijn voor elke site identiek; de wegingen staan gedocumenteerd op de scorekaart, zodat teams verschillen kunnen duiden." }],
  },
  {
    slug: "consent",
    title: "Toestemmingsbewust vanaf de basis",
    short: "Strikte opt-in als standaard, Consent Mode v2, doelgebonden destinations, geen replay na toestemming.",
    benefit: "Elke destination ontvangt precies waar de bezoeker mee heeft ingestemd – beoordeeld per event, in de browser en nogmaals op de server – zodat compliance geen bannerinstelling is waarvan je hoopt dat die klopt.",
    intro: "Toestemming is geen bannerintegratie maar een policy-engine: doeleinden, regio's, destinationvereisten en het vastleggen van click-ID's worden voor elk event beoordeeld in de browser en nogmaals op de server.",
    flow: {
      title: "De check staat vóór elke destination",
      text: "Elke destination declareert het doel dat ervoor vereist is. Als een event binnenkomt, vergelijkt Track het toestemmingssnapshot met die vereiste: analytics-destinations ontvangen events met analytics-toestemming, advertentiedestinations alleen met marketingtoestemming. Een intrekking stopt het versturen onmiddellijk, en niets wat vóór de toestemming is opgeslagen wordt daarna opnieuw afgespeeld.",
      caption: "Website → Track → Toestemmings-/policycheck → alleen de destinations waarvan het doel is toegestaan.",
    },
    viewCaption: "Voorbeeld van een toestemmingsstatus: analytics gegeven, marketing geweigerd – en de Consent Mode v2-vlaggen en blokkeerredenen die daaruit zijn afgeleid.",
    sections: [
      { title: "CMP-adapters en API", text: "TCF 2.2, GPP en Global Privacy Control, adapters voor Cookiebot, OneTrust en Usercentrics, plus een toestemmings-API voor eigen banners." },
      { title: "Consent Mode v2, doelgebaseerd", text: "Google-toestemmingssignalen worden afgeleid uit doeleinden; de geavanceerde modus is alleen beschikbaar met een gedocumenteerde juridische beoordeling." },
      { title: "Bewijs", text: "Gededupliceerde toestemmingssnapshots worden bij elk event opgeslagen, zodat je kunt aantonen wat wanneer is toegestaan." },
    ],
    bullets: ["Afgeleide toestemming wordt nooit geëxporteerd naar advertentieplatformen", "Intrekking stopt het versturen onmiddellijk", "Serveraankopen blijven operationeel verwerkt, maar gaan zonder toestemming nooit naar advertising"],
    comparison: {
      title: "Toestemming per tag versus een policy-engine",
      text: "Waar de beslissing valt – en of je die later kunt aantonen.",
      beforeLabel: "Toestemming per tag afgehandeld",
      afterLabel: "Policy-engine in Track",
      rows: [
        { aspect: "Beslispunt", before: "De trigger van elke tag, handmatig geconfigureerd", after: "Elk event, elke destination, in de browser en op de server" },
        { aspect: "Server-side events", before: "Verstuurd ongeacht de banner", after: "Dezelfde doelcheck als browserevents" },
        { aspect: "Intrekking", before: "Gaat in bij de volgende paginalading, als het al gebeurt", after: "Stopt het versturen onmiddellijk; geen replay van eerdere events" },
        { aspect: "Bewijs", before: "Geen", after: "Toestemmingssnapshot opgeslagen bij elk event" },
      ],
    },
    faq: [{ q: "Welke regio's worden ondersteund?", a: "Strikte opt-in voor de EU/EER/VK/CH als standaard; policies per regio zijn instelbaar, maar nooit zwakker dan de wettelijke basis zonder een expliciete beslissing." }],
  },
  {
    slug: "attribution",
    title: "Click-ID's en attributie zoals het hoort",
    short: "Leg alleen de ID's vast die de destination nodig heeft, alleen met toestemming, alleen voor het gedocumenteerde venster.",
    benefit: "Je campagnes krijgen de click-ID's die ze nodig hebben om een conversie toe te schrijven – en geen enkel platform ontvangt ooit een ID die bij een ander platform hoort.",
    intro: "De tracker legt gclid, fbclid, ttclid, msclkid, li_fat_id en de andere platform-click-ID's vast op landingspagina's na marketingtoestemming, slaat ze first-party op voor het venster van het platform en stuurt elke ID alleen door naar het platform waar die bij hoort.",
    flow: {
      title: "Elke ID reist naar precies één platform",
      text: "Een landingspagina met een gclid en een fbclid levert na marketingtoestemming twee opgeslagen ID's op. Als de aankoop binnenkomt, koppelt Track de gclid aan de Google Ads-aflevering en de fbclid aan de Meta-aflevering – de matrix wordt machinaal gecontroleerd, dus een lek tussen platformen is geen configuratiefout die je kunt maken.",
      caption: "Landingspagina → first-party click-ID-opslag → aankoop → doorsturen per destination.",
    },
    viewCaption: "Voorbeeldmatrix: welke click-ID wordt vastgelegd, waarheen die wordt doorgestuurd en hoe lang die wordt bewaard.",
    sections: [
      { title: "Doorsturen per destination", text: "Meta ziet nooit je gclid en Google nooit je fbclid. De policymatrix wordt machinaal gecontroleerd." },
      { title: "Deduplicatie op bestelniveau", text: "Aankopen dragen de order-ID naar elk platform dat die ondersteunt, zodat browser- en serverconversies correct samenkomen." },
      { title: "Offline en CRM", text: "Server-events met een offline-vlag bereiken Google Ads, CM360, Microsoft, Meta, TikTok, Pinterest, Snapchat, Amazon, Yahoo en LinkedIn als offline conversies." },
    ],
    bullets: ["Gedocumenteerde bewaartermijn per click-ID (standaard 90 dagen)", "Enhanced Conversions met genormaliseerde hashing", "Affiliatenetwerken met click-ID's per netwerk"],
    comparison: {
      title: "URL-parameters in de dataLayer versus een afgebakende click-ID-opslag",
      text: "Het verschil tussen alles verzamelen en doorsturen wat waar hoort.",
      beforeLabel: "Click-ID's in de dataLayer",
      afterLabel: "Click-ID-opslag in Track",
      rows: [
        { aspect: "Vastleggen", before: "Elke parameter, op elke pagina, ongeacht toestemming", after: "Alleen bekende ID's, op landingspagina's, na marketingtoestemming" },
        { aspect: "Doorsturen", before: "Wat een tagsjabloon toevallig uitleest", after: "Per destination vanuit een machinaal gecontroleerde matrix" },
        { aspect: "Bewaartermijn", before: "Cookielevensduur ingesteld door elke tag afzonderlijk", after: "Gedocumenteerd venster per ID, standaard 90 dagen" },
        { aspect: "Offline conversies", before: "Handmatige uploads", after: "Server-events met een offline-vlag" },
      ],
    },
    faq: [{ q: "Bouwen jullie cross-site profielen?", a: "Nee. Er is geen fingerprinting en geen cross-site identiteit; identifiers blijven binnen de site en de doeleinden waarvoor toestemming is gegeven." }],
  },
];

export const FEATURES_PAGE_COPY_NL: FeaturesPageCopy = {
  eyebrow: "Functies",
  title: "Elke conversie één keer afgeleverd, met toestemming, bij het platform waar ze bij hoort",
  text: "Track vervangt de tagcontainer door een begeleide setup, een toestemmingsbewuste server-side router en een debugger die elk event verklaart. Deze pagina toont het product zoals het werkt – de statussen hieronder zijn voorbeelddata, geen live verkeer.",
  cta: "Start met je domein",
  ctaSecondary: "Bekijk hoe het werkt",
  stage: {
    title: "Datastroom van de website via Track naar de destinations",
    description: "Een website verstuurt events vanuit de browser-SDK en vanaf de server naar Track. Track beoordeelt de toestemming bij een policycheck en stuurt elk event alleen door naar destinations waarvan het doel is toegestaan: Meta, Google Ads, Google Analytics 4 en TikTok.",
    caption: "Website → Track → Toestemming/policy → Destinations. Browser en server delen één event-ID; de check beslist per destination.",
  },
  scenarios: {
    title: "Wat er met één aankoop gebeurt",
    text: "Wissel van scenario om te zien hoe hetzelfde event wordt gerouteerd als toestemming is gegeven of ingetrokken, of als een platform down is. De beslissing en de reden zijn wat je later in de debugger leest.",
    tabsLabel: "Routingscenario's",
    items: [
      {
        id: "granted",
        label: "Toestemming gegeven",
        title: "Analytics en marketing toegestaan",
        text: "De aankoop komt binnen vanuit de browser en vanaf de server met dezelfde event-ID. De check vindt de vereiste doeleinden en stuurt hem door naar alle vier de destinations; Meta en TikTok dedupliceren op de event-ID, Google Ads op de order-ID.",
        points: ["Beslissing: afgeleverd bij Meta, Google Ads, GA4, TikTok", "Deduplicatie: event-ID (Meta, TikTok), order-ID (Google Ads)", "Click-ID's per destination meegestuurd: gclid → Google, fbclid → Meta"],
      },
      {
        id: "withdrawn",
        label: "Marketing ingetrokken",
        title: "Analytics toegestaan, marketing geweigerd",
        text: "De bezoeker heeft de marketingtoestemming vóór de aankoop ingetrokken. De check laat het event door naar Google Analytics 4 en blokkeert de advertentiedestinations met de reden purpose_not_granted. Er wordt niets bewaard voor later; als de toestemming opnieuw wordt gegeven, worden eerdere events niet opnieuw afgespeeld.",
        points: ["Beslissing: afgeleverd bij GA4; geblokkeerd voor Meta, Google Ads, TikTok", "Reden in de debugger: purpose_not_granted (marketing)", "Consent Mode v2: analytics_storage granted, ad_storage denied"],
      },
      {
        id: "outage",
        label: "Platform down",
        title: "Toestemming gegeven, één platform niet beschikbaar",
        text: "TikTok antwoordt met een serverfout. Track probeert het opnieuw met jittered backoff, opent na herhaalde fouten de circuit breaker en parkeert het event in de dead-letter queue. De andere drie destinations blijven onaangetast. Zodra TikTok hersteld is, wordt de dead-letter queue opnieuw afgespeeld.",
        points: ["Beslissing: afgeleverd bij Meta, Google Ads, GA4; TikTok wordt opnieuw geprobeerd", "Circuit breaker open voor TikTok; events in de dead-letter queue", "Replay na herstel behoudt de oorspronkelijke event-ID, dus niets telt dubbel"],
      },
    ],
  },
  index: {
    title: "Zes mogelijkheden, één eventlaag",
    text: "Elke mogelijkheid is gebouwd op dezelfde ondertekende configuratie en hetzelfde eventschema. Open een mogelijkheid voor de productweergave, de datastroom en een voor/na-vergelijking.",
    more: "Lees meer",
  },
  comparison: {
    title: "Tagcontainer versus eventlaag",
    text: "Waar een klassieke container het werk aan jou overlaat en waar Track het vanaf de basis doet.",
    beforeLabel: "Klassieke tagcontainer",
    afterLabel: "Track",
    rows: [
      { aspect: "Wat er op je site draait", before: "Custom HTML- en JavaScript-tags van iedereen met containertoegang", after: "Eén snippet en een ondertekende, geversioneerde configuratie – geen uitvoering van custom code" },
      { aspect: "Toestemming", before: "Triggervoorwaarden per tag, handmatig onderhouden", after: "Policy-engine die elk event voor elke destination beoordeelt, browser en server" },
      { aspect: "Server-side aflevering", before: "Een tweede container, een tweede set tags, handmatige deduplicatie", after: "Ingebouwd: gedeelde event-ID, retries, circuit breakers, replay" },
      { aspect: "Fouten vinden", before: "Previewmodus en platform-UI's", after: "Event-lineage met toestemmingssnapshot, routingbeslissing en platformantwoord" },
      { aspect: "Wijzigingen", before: "Publiceren en hopen", after: "Diff, goedkeuring, ondertekende versie, rollback met één klik" },
    ],
  },
  trust: {
    title: "Feiten die je kunt nagaan",
    items: [
      { title: "EU-dataregio", text: "Events worden in de EU verwerkt; platform-API's ontvangen alleen de velden die je hebt gemapt, op basis van de per destination gedocumenteerde doorgiftegrondslag." },
      { title: "Ondertekende configuraties", text: "Elke gepubliceerde bundle is onveranderlijk, geversioneerd en Ed25519-ondertekend; de SDK verifieert de handtekening voordat hij die toepast." },
      { title: "Geen custom code", text: "Er is geen custom HTML- of JavaScript-tagtype. Transformaties zijn declaratief en worden op de server gevalideerd." },
      { title: "Strikte opt-in als standaard", text: "EU/EER/VK/CH starten met strikte opt-in; afgeleide toestemming wordt nooit geëxporteerd naar advertentieplatformen." },
    ],
  },
  closing: { title: "Bekijk deze weergaven met je eigen events", text: "Maak je site aan, plak de snippet en laat de assistent de eerste destination configureren – de debugger en de healthscore vullen zich vanaf het eerste event.", cta: "Start met je domein", secondary: "Bekijk de prijzen" },
};

export const FEATURE_DETAIL_COPY_NL: FeatureDetailLabels = {
  features: "Functies",
  breadcrumb: "Kruimelpad",
  howBuilt: "Zo is het gebouwd",
  howBuiltText: "De technische beslissingen achter de mogelijkheid – het bewijs na het voordeel.",
  proof: "Wat je kunt nagaan",
  proofText: "Productfeiten die je terugvindt in het dashboard, de docs en het auditlog.",
  faq: "Vragen",
  more: "Meer mogelijkheden",
  moreText: "Gebouwd op dezelfde ondertekende configuratie en hetzelfde eventschema.",
  cta: "Probeer het op je domein",
  ctaText: "Maak een site aan, installeer één snippet en laat de assistent binnen enkele minuten de eerste destination configureren.",
  start: "Gratis starten",
  pricing: "Bekijk de prijzen",
};

export const FEATURE_UI_COPY_NL: FeatureUiCopy = {
  example: "Voorbeelddata",
  exampleHint: "Statische voorbeeldstatus – geen live verkeer, geen echte klantdata.",
  diagram: {
    website: "Website",
    browser: "Browser-SDK",
    server: "Server-API",
    track: "Track",
    gate: "Toestemming / policy",
    gateGranted: "toestemming gegeven",
    gateDenied: "marketing geweigerd",
    gatePending: "toestemming in afwachting",
    dedup: "één event-ID",
    notUsed: "niet gebruikt",
    delivered: "afgeleverd",
    blocked: "geblokkeerd",
    retrying: "opnieuw proberen",
    paused: "gepauzeerd",
    destinations: { meta: "Meta", googleAds: "Google Ads", ga4: "GA4", tiktok: "TikTok", linkedin: "LinkedIn" },
    describe: (paths, gate) => {
      const origin = paths === "browser" ? "alleen vanuit de browser-SDK" : paths === "server" ? "alleen vanuit de server-API" : "vanuit de browser-SDK en de server-API met één gedeelde event-ID";
      const decision = gate === "granted" ? "de toestemmingscheck staat open en events bereiken de destinations" : gate === "denied" ? "de toestemmingscheck blokkeert advertentiedestinations en alleen analytics ontvangt het event" : "de toestemmingscheck wacht op een signaal en er wordt niets doorgestuurd";
      return `De website verstuurt events ${origin} naar Track; ${decision}.`;
    },
    chains: {
      setup: { ai: "Track AI", aiSub: "stelt voor", tools: "Getypeerde tools", toolsSub: "server-gevalideerd", approval: "Jouw goedkeuring", approvalSub: "gekoppeld aan de diff", config: "Ondertekende config", configSub: "versie 13", website: "Website", websiteSub: "verifieert handtekening", describe: "Track AI stelt wijzigingen voor via getypeerde, server-gevalideerde tools; jouw goedkeuring, gekoppeld aan de diff, publiceert een ondertekende configuratie die de website verifieert voordat die wordt geladen." },
      health: { events: "Events", eventsSub: "laatste periode", checks: "Controles", checksSub: "toestemming · schema · aflevering", score: "Score 86", scoreSub: "6 gewogen onderdelen", issues: "2 problemen", issuesSub: "elk noemt zijn oplossing", describe: "Events van de laatste periode doorlopen de controles; zes gewogen onderdelen vormen de score, en elk open probleem noemt de tool die het oplost." },
      attribution: { landing: "Landingspagina", landingSub: "gclid · fbclid", consent: "Marketingtoestemming", consentSub: "gegeven", store: "Click-ID-opslag", storeSub: "first-party · 90 dagen", purchase: "Aankoop", purchaseSub: "3 dagen later", google: "Google Ads", googleSub: "alleen gclid", meta: "Meta", metaSub: "alleen fbclid", describe: "Een landingspagina met gclid en fbclid slaat beide ID's na marketingtoestemming first-party op; de aankoop drie dagen later bereikt Google Ads alleen met de gclid en Meta alleen met de fbclid." },
    },
  },
  stream: {
    title: "Live events",
    caption: "Elke rij is één event met zijn herkomst, de toestemming op dat moment, de routingbeslissing en de destinations.",
    columns: { event: "Event", origin: "Herkomst", consent: "Toestemming", decision: "Beslissing", destination: "Destinations" },
    rows: [
      { event: "page_view", origin: "browser", consent: "analytics", consentTone: "ok", decision: "afgeleverd", decisionTone: "ok", destination: "GA4" },
      { event: "add_to_cart", origin: "browser", consent: "marketing", consentTone: "ok", decision: "afgeleverd", decisionTone: "ok", destination: "Meta, TikTok" },
      { event: "purchase", origin: "browser + server", consent: "marketing", consentTone: "ok", decision: "afgeleverd, gededupliceerd (order-ID)", decisionTone: "ok", destination: "Meta CAPI, Google Ads" },
      { event: "purchase", origin: "server", consent: "marketing ontbreekt", consentTone: "bad", decision: "geblokkeerd: consent_missing", decisionTone: "bad", destination: "Meta CAPI" },
      { event: "generate_lead", origin: "browser", consent: "marketing", consentTone: "ok", decision: "afgeleverd", decisionTone: "ok", destination: "LinkedIn" },
    ],
  },
  lineage: {
    title: "Event-lineage",
    caption: "Eén aankoop, gelezen van herkomst tot platformantwoord.",
    facts: [
      { label: "Event", value: "purchase · evt_…7f2a" },
      { label: "Herkomst", value: "browser-SDK + server (shopwebhook)" },
      { label: "Configuratie", value: "versie 12, handtekening geverifieerd" },
      { label: "Toestemmingssnapshot", value: "analytics, marketing · bron: CMP" },
      { label: "Click-ID's", value: "gclid (3 dagen geleden vastgelegd)" },
    ],
    attempts: {
      title: "Afleverpogingen",
      columns: { destination: "Destination", status: "Status", result: "Resultaat" },
      rows: [
        { destination: "Meta Conversions API", status: "200", tone: "ok", result: "geaccepteerd, gededupliceerd op event-ID" },
        { destination: "Google Ads", status: "200", tone: "ok", result: "geaccepteerd, gededupliceerd op order-ID" },
        { destination: "TikTok Events API", status: "503", tone: "warn", result: "poging 2 ingepland met backoff" },
      ],
    },
    payload: { title: "Gemaskeerde payload", copy: "Payload kopiëren", copied: "Gekopieerd", code: PAYLOAD_EXAMPLE },
  },
  health: {
    title: "Tracking health",
    caption: "Gewogen onderdelen; een lagere score wijst altijd naar zijn oorzaak.",
    scoreLabel: "Score",
    score: 86,
    componentsLabel: "Onderdelen",
    weight: (percent) => `${percent}% weging`,
    components: [
      { key: "consent", label: "Toestemmingsdekking", score: 91, weight: 20, detail: "91% van de events draagt een expliciet toestemmingssignaal" },
      { key: "coverage", label: "Kritieke events", score: 78, weight: 25, detail: "7 van de 9 geplande kritieke events waargenomen" },
      { key: "schema", label: "Schemakwaliteit", score: 74, weight: 15, detail: "74% van de events doorstaat de schema- en PII-controles" },
      { key: "dedup", label: "Duplicaten", score: 96, weight: 10, detail: "1,0% duplicaten" },
      { key: "delivery", label: "Aflevering", score: 88, weight: 20, detail: "94% afgeleverd, 1 integratie met problemen met credentials" },
      { key: "liveness", label: "Actualiteit", score: 100, weight: 10, detail: "Laatste browserevent 4 min geleden" },
    ],
    issuesLabel: "Open problemen",
    issues: [
      { title: "purchase zonder currency", detail: "12 events in de afgelopen 24 uur missen de verplichte parameter", fix: "Oplossing: werk de eventmapping bij", tone: "warn" },
      { title: "Toestemmingssignaal ontbreekt", detail: "9% van de events kwam binnen zonder expliciete toestemmingsstatus", fix: "Oplossing: koppel de CMP-adapter", tone: "warn" },
    ],
  },
  consent: {
    title: "Toestemmingsstatus en afgeleide signalen",
    caption: "Doeleinden komen uit je CMP; al het andere wordt afgeleid, nooit gegokt.",
    purposesLabel: "Doeleinden",
    purposes: [
      { label: "Strikt noodzakelijk", granted: true },
      { label: "Analytics", granted: true },
      { label: "Marketing", granted: false },
      { label: "Personalisatie", granted: false },
    ],
    granted: "gegeven",
    denied: "geweigerd",
    flagsLabel: "Consent Mode v2",
    flags: [
      { key: "analytics_storage", value: "granted" },
      { key: "ad_storage", value: "denied" },
      { key: "ad_user_data", value: "denied" },
      { key: "ad_personalization", value: "denied" },
    ],
    reasonsLabel: "Blokkeerredenen die de policy-engine rapporteert",
    reasons: [
      { code: "consent_missing", text: "nog geen toestemmingssignaal voor het event" },
      { code: "consent_denied", text: "de bezoeker heeft geweigerd" },
      { code: "purpose_not_granted", text: "de destination vereist een doel dat niet is toegestaan" },
      { code: "gpc_opt_out", text: "Global Privacy Control ingeschakeld" },
      { code: "destination_paused", text: "kill switch of circuit breaker" },
      { code: "inferred_data_not_exportable", text: "afgeleide toestemming bereikt nooit advertentieplatformen" },
    ],
  },
  attribution: {
    title: "Click-ID-matrix",
    caption: "Vastgelegd na marketingtoestemming, first-party opgeslagen, alleen doorgestuurd naar het eigen platform.",
    columns: { id: "Click-ID", captured: "Vastgelegd", forwarded: "Alleen doorgestuurd naar", retention: "Bewaard" },
    rows: [
      { id: "gclid", captured: "landingspagina, na marketingtoestemming", forwarded: "Google Ads, GA4, Google Marketing Platform", retention: "90 dagen" },
      { id: "fbclid", captured: "landingspagina, na marketingtoestemming", forwarded: "Meta", retention: "90 dagen" },
      { id: "ttclid", captured: "landingspagina, na marketingtoestemming", forwarded: "TikTok", retention: "90 dagen" },
      { id: "msclkid", captured: "landingspagina, na marketingtoestemming", forwarded: "Microsoft Advertising", retention: "90 dagen" },
      { id: "li_fat_id", captured: "landingspagina, na marketingtoestemming", forwarded: "LinkedIn", retention: "90 dagen" },
    ],
    note: "De bewaartermijn is per ID gedocumenteerd en instelbaar; 90 dagen is de standaard.",
  },
  setup: {
    title: "Begeleide setup",
    caption: "De assistent stelt voor, tools valideren, jij keurt goed.",
    assistant: "Track AI",
    you: "Jij",
    messages: [
      { from: "assistant", text: "example-shop.test draait op Shopify met Cookiebot als toestemmingstool (hoge betrouwbaarheid). Voor een webshop stel ik view_item, add_to_cart, begin_checkout en purchase voor. Zal ik het plan voor Meta en Google Ads opstellen?" },
      { from: "you", text: "Ja, Meta eerst." },
      { from: "assistant", text: "Pixel-ID gevalideerd. De Conversions API heeft een access token nodig – voer die hieronder in de kluiskaart in; hij verschijnt nooit in deze chat." },
    ],
    vault: { title: "Kluiskaart · Meta access token", text: "Versleuteld opgeslagen; voor niemand zichtbaar, ook niet voor het model.", state: "opgeslagen" },
    test: { title: "Testevent · purchase", text: "Verstuurd via de echte pipeline met de test-eventcode van het platform.", state: "geaccepteerd door Meta" },
    approval: {
      title: "Versie 13 publiceren",
      text: "Gekoppeld aan precies deze diff en aan jou als goedkeurder.",
      diff: ["+ destination meta: browser + server", "+ mapping purchase → Purchase (event id, order id)", "~ consent: marketing required for meta"],
      state: "wacht op je goedkeuring",
      action: "Goedkeuren en publiceren",
    },
  },
  destinations: {
    title: "Destination health",
    caption: "Gezondheid, modus en queue per destination; fouten worden afgehandeld, niet verborgen.",
    columns: { destination: "Destination", mode: "Modus", health: "Gezondheid", last: "Laatste aflevering", queue: "Queue" },
    rows: [
      { destination: "Meta", mode: "browser + server", health: "gezond", tone: "ok", last: "12 s geleden", queue: "0 retries" },
      { destination: "Google Ads", mode: "server", health: "gezond", tone: "ok", last: "40 s geleden", queue: "0 retries" },
      { destination: "TikTok", mode: "browser + server", health: "verminderd, circuit breaker open", tone: "warn", last: "6 min geleden", queue: "3 in dead-letter queue" },
      { destination: "LinkedIn", mode: "server", health: "gepauzeerd door kill switch", tone: "neutral", last: "2 u geleden", queue: "vastgehouden" },
    ],
  },
};
