packages:
  - "apps/*"
  - "packages/*"
  - "integrations/*"
verifyDepsBeforeRun: false
allowBuilds:
  esbuild: true
  sharp: true
  "@tailwindcss/oxide": true
  unrs-resolver: true
  "@swc/core": true
  "@parcel/watcher": true
  '@embedded-postgres/windows-x64': set this to true or false
minimumReleaseAgeExclude:
  - "@aws-sdk/client-kms"
  - "@aws-sdk/client-sqs"
  - framer-motion
  - motion-dom
  - motion
  - openai
