import type { DemoCopy, HomeCopy } from "../types";

/**
 * German (de) copy of the home area. Same shape as en.ts; see docs/14-localization.md.
 */

const DEMO_DE: DemoCopy = {
  label: "Interaktive Demo",
  sample: "Beispieldaten – es wird nichts an eine Plattform gesendet",
  sampleShort: "Beispieldaten",
  region: "Track-Produktdemo",
  configLive: "Config v{version} live",
  controls: {
    reset: "Demo zurücksetzen",
    pause: "Stream pausieren",
    play: "Stream abspielen",
    next: "Nächstes Event",
    paused: "Stream pausiert",
    reducedMotion: "Reduzierte Bewegung ist aktiv: Der Stream läuft nur weiter, wenn du „Nächstes Event“ drückst.",
    offscreen: "Stream pausiert, solange die Demo nicht sichtbar ist",
    complete: "Der Stream wiederholt dasselbe Beispielskript.",
  },
  viewsLabel: "Demo-Ansichten",
  views: { overview: "Overview", events: "Live Events", destinations: "Destinations", ai: "AI Setup", attribution: "Attribution" },
  metrics: { accepted: "Angenommen", delivered: "Zugestellt", duplicates: "Duplikate entfernt", blocked: "Durch Consent blockiert", held: "Zurückgehalten" },
  health: {
    title: "Tracking Health Score",
    outOf: "von 100",
    explain: "So entsteht der Score",
    parts: {
      consent: { label: "Consent-Entscheidungen", detail: "{decided} von {accepted} angenommenen Events haben eine Consent-Entscheidung; {pending} offen" },
      dedup: { label: "Browser/Server-Paarung", detail: "{paired} von {conversions} Conversions kamen aus Browser und Server" },
      params: { label: "Purchase-Parameter", detail: "{complete} von {purchases} Purchase-Events enthalten Wert und Währung" },
      delivery: { label: "Zustellung", detail: "{delivered} von {routable} zustellbaren Events zugestellt; {held} zurückgehalten" },
    },
  },
  events: {
    title: "Live-Eventstream",
    latest: "Letzte Events",
    origin: { browser: "Browser", server: "Server" },
    dedup: { unique: "Eine Quelle", paired: "Mit der anderen Quelle gepaart", duplicate: "Duplikat verworfen" },
    consent: { granted: "Consent erteilt", denied: "Consent abgelehnt", pending: "Consent offen" },
    outcome: { delivered: "Zugestellt", blocked: "Blockiert", held: "Zurückgehalten", duplicate: "Duplikat" },
    reasons: {
      delivered: "An alle gerouteten Ziele zugestellt.",
      consent_denied: "Marketing-Consent wurde abgelehnt – nichts geht an Werbeplattformen.",
      consent_pending: "Noch keine Consent-Entscheidung – das Event wartet und wird nicht gesendet.",
      missing_currency: "Der Purchase hat einen Wert, aber keine Währung – zurückgehalten, bis eine Währung gesetzt ist.",
      duplicate: "Dieselbe Event-ID wurde bereits aus der anderen Quelle angenommen – verworfen und nicht gezählt.",
      released: "Nach der Währungskorrektur freigegeben und zugestellt.",
    },
    routedTo: { one: "{n} Ziel", other: "{n} Ziele" },
    none: "Kein Ziel",
    columns: { event: "Event", origin: "Herkunft", consent: "Consent", outcome: "Ergebnis", time: "Zeit" },
    detail: { eventId: "Event-ID", value: "Wert", currency: "Währung", missing: "fehlt", order: "Bestellung", destinations: "Zugestellt an", route: "Route", expand: "Details anzeigen", collapse: "Details ausblenden", consentLabel: "Consent", dedupLabel: "Deduplizierung" },
  },
  flow: { website: "Website", track: "Track", consent: "Consent / Policy", destinations: "Ziele", caption: "Weg des letzten Events: Website → Track → Consent-Prüfung → Ziele." },
  destinations: {
    title: "Destination Health",
    pick: "Plattform wählen",
    health: { ok: "Gesund", warn: "Braucht Aufmerksamkeit", bad: "Fehlerhaft" },
    lastDelivery: "Letzte erfolgreiche Zustellung",
    none: "In diesem Durchlauf noch keine Zustellung",
    modes: "Modi",
    browserServer: "Browser-Tag + Server-API",
    dedupKey: "Dedup-Schlüssel",
    clickParam: "Click-ID",
    counts: { delivered: "Zugestellt", held: "Zurückgehalten", blocked: "Durch Consent blockiert" },
    heldHint: { one: "{n} Purchase wird zurückgehalten, bis eine Währung gesetzt ist.", other: "{n} Purchases werden zurückgehalten, bis eine Währung gesetzt ist." },
    openAi: "Im AI Setup beheben",
  },
  ai: {
    title: "AI Setup",
    from: "Track AI",
    found: {
      one: "{n} Purchase-Event kam mit Wert, aber ohne Währung an. Die Ziele können den Umsatz so nicht korrekt ausweisen.",
      other: "{n} Purchase-Events kamen mit Wert, aber ohne Währung an. Die Ziele können den Umsatz so nicht korrekt ausweisen.",
    },
    foundNone: "Keine offene Empfehlung. Purchase-Events enthalten jetzt Wert und Währung.",
    evidence: "Beleg im Beispielstream",
    evidenceRow: "{name} · {origin} · Wert {value}, Währung fehlt · {time}",
    question: "Welche Währung soll Track verwenden, wenn der Shop keine sendet?",
    options: { EUR: "Euro (EUR)", USD: "US-Dollar (USD)", GBP: "Pfund Sterling (GBP)" },
    confirm: "Bestätigen und Entwurf veröffentlichen",
    result: {
      one: "Config v{version} für die Demo veröffentlicht. {n} zurückgehaltener Purchase wurde zugestellt.",
      other: "Config v{version} für die Demo veröffentlicht. {n} zurückgehaltene Purchases wurden zugestellt.",
      zero: "Config v{version} für die Demo veröffentlicht.",
    },
    note: "Das ändert nur die Beispieldaten. In deinem Workspace bereitet Track AI dieselbe Änderung als Entwurf vor und wartet auf deine Freigabe.",
    overviewHint: { one: "Empfehlung: {n} Purchase wird ohne Währung zurückgehalten", other: "Empfehlung: {n} Purchases werden ohne Währung zurückgehalten" },
    overviewDone: "Empfehlung erledigt: Währung gesetzt, zurückgehaltene Purchases zugestellt",
    open: "AI Setup öffnen",
    stepLabel: "Standardwährung",
  },
  attribution: {
    title: "Attribution & Click-IDs",
    intro: "Welche Click-IDs die Beispielsitzungen trugen, ob Consent die Weitergabe erlaubte und was unbekannt bleibt.",
    columns: { platform: "Plattform", clickId: "Click-ID", captured: "Beobachtet", consent: "Consent", forwarded: "Serverseitig weitergegeben" },
    captured: { yes: "Ja", no: "Nicht in diesem Durchlauf" },
    forwarded: { yes: "Ja", no: "Zurückgehalten", na: "—" },
    consentNa: "—",
    note: "Nur beobachtete Fakten: Click-IDs auf Landing-URLs der Beispielsitzungen. Geräteübergreifende Journeys sind unbekannt und bleiben es – nichts wird modelliert.",
  },
  announce: { event: "Neues Event: {name} aus {origin}, {outcome}.", setupDone: "Setup-Schritt bestätigt. Zurückgehaltene Purchases zugestellt.", reset: "Demo auf den Ausgangszustand zurückgesetzt." },
  mobileHint: "Kompakte Demo: dieselben Beispieldaten mit weniger Zeilen.",
};

export const HOME_COPY_DE: HomeCopy = {
  eyebrow: "AI-first Tag Manager",
  title: "Ein Snippet. Jede Plattform. Jede Conversion genau einmal gezählt.",
  subtitle: "Track erfasst deine Website-Events first-party, prüft Consent, bevor etwas deine Seite verlässt, und liefert sie serverseitig an Meta, Google, TikTok, LinkedIn und mehr – dedupliziert, erklärt und gemeinsam mit Track AI eingerichtet.",
  cta: "Mit deiner Domain starten",
  ctaSecondary: "So funktioniert es",
  domainPlaceholder: "deinshop.de",
  domainLabel: "Deine Website",
  domainHelp: "Hier prüfen wir nur das Format. Danach legen wir deine Site mit einer sechsstelligen Tracking-ID an und führen dich im Chat durch die Einrichtung.",
  domainInvalid: "Gib eine Domain wie deinshop.de ein – ohne https:// und ohne Pfad.",
  trust: {
    eu: "EU-Datenregion",
    consent: "Consent wird vor der Zustellung geprüft",
    signed: "Signierte, versionierte Konfigurationen",
    noCode: "Kein Custom HTML oder JavaScript",
  },
  demoHeading: "Interaktive Produktdemo",
  platforms: {
    title: "Funktioniert mit den Plattformen und Shopsystemen, die du schon nutzt",
    text: "Browser-Tag plus serverseitige API für jedes Ziel, das eine anbietet – mit einer gemeinsamen Event-ID, damit nichts doppelt zählt. Shopify, WooCommerce und Shopware senden verifizierte Bestellungen direkt.",
    all: "Alle Integrationen",
    groups: { ads: "Werbeplattformen", analytics: "Analytics", commerce: "Shopsysteme" },
    modes: { browser: "Browser", server: "Server", offline: "Offline" },
  },
  outcomes: {
    eyebrow: "Was du bekommst",
    title: "Drei Dinge, die dein Tracking können sollte – und meist nicht kann",
    text: "Pixel allein verlieren Events, serverseitige Setups brauchen Entwickler, und Consent ist oft ein Banner statt einer Regel. Track macht aus allen dreien eine geführte Einrichtung.",
    items: [
      { title: "Jede Conversion genau einmal gezählt", text: "Browser und Server senden dieselbe Event-ID; Track führt das Paar zusammen und leitet eine Conversion pro Bestellung weiter. Wiederholungen erzeugen nie eine zweite.", proof: "In der Demo: die Dedup-Markierung im Live-Eventstream" },
      { title: "Nur, was Consent erlaubt, verlässt deine Seite", text: "Jedes Event durchläuft vor der Zustellung eine Policy-Prüfung. Ein abgelehnter Consent blockiert das Ziel, eine fehlende Entscheidung wird nie zum Ja, und jede Entscheidung wird mit Grund festgehalten.", proof: "In der Demo: der Blockgrund an jedem zurückgehaltenen Event" },
      { title: "Du weißt immer, was als Nächstes zu tun ist", text: "Ein Tracking Health Score mit erklärbaren Teilwerten und Track-AI-Empfehlungen, die auf das genaue Event und den Parameter zeigen – mit einem Entwurf, den du freigibst.", proof: "In der Demo: der Purchase, der ohne Währung ankommt" },
    ],
  },
  flow: {
    eyebrow: "So funktioniert es",
    title: "Snippet → Track → Plattformen",
    text: "Ein asynchrones Script auf deinen Seiten, ein Router in der EU, der Consent prüft und Duplikate zusammenführt, und jedes Ziel serverseitig aus demselben verifizierten Event versorgt.",
    steps: [
      { title: "Ein Snippet einbauen", text: "Den asynchronen Tracker mit deiner sechsstelligen Site-ID einfügen. Er lädt eine signierte Konfiguration, blockiert nie das Rendering und ist fail-safe, falls etwas nicht stimmt." },
      { title: "Track prüft und routet", text: "Events werden validiert, ihrer Consent-Entscheidung zugeordnet, über Event-ID und Bestellnummer dedupliziert und dann je Ziel getrennt in die Warteschlange gestellt." },
      { title: "Plattformen erhalten verifizierte Events", text: "Meta, Google, TikTok, LinkedIn, Reddit und mehr bekommen Browser- und Server-Events mit gemeinsamen IDs; du siehst Zustellstatus und letzte Antwort je Ziel." },
    ],
    snippetTitle: "Das Snippet",
    copy: "Snippet kopieren",
    copied: "Kopiert",
    caption: "Website → Track → Consent / Policy → Ziele: der Weg, den jedes Event nimmt.",
    nodes: { website: "Deine Website", track: "Track", consent: "Consent / Policy", destination: "Ziele" },
    more: "Den ganzen Ablauf lesen",
  },
  aiSetup: {
    eyebrow: "Geführte Einrichtung",
    title: "Mit Track AI einrichten. Veröffentlicht wird nur, was du freigibst.",
    text: "Track AI erkennt deine Plattform, schlägt einen Messplan vor und verbindet Ziele mit validierten Eingaben. Jede Änderung wird zum Entwurf mit lesbarem Diff – nichts geht live, bevor du bestätigst.",
    bullets: ["Erkennt dein CMS oder Shopsystem und die Events, die dafür zählen", "Stellt eine Frage nach der anderen; Zugangsdaten landen in sicheren Karten, nie im Chat", "Jede Änderung ist ein Entwurf mit Diff, Freigabe-Button und Rollback per Klick"],
    transcriptLabel: "Beispielunterhaltung (statisch)",
    transcript: [
      { role: "assistant", text: "Ich habe demo-shop.example geprüft und Shopware 6 erkannt. Purchase-Events kommen mit Wert, aber ohne Währung an, deshalb können Meta und TikTok keinen Umsatz zählen." },
      { role: "you", text: "Nimm EUR als Standard." },
      { role: "assistant", text: "Die Änderung ist bereit für deine Prüfung. Nichts ändert sich, bevor du bestätigst." },
    ],
    approval: { title: "Entwurf v15 – vor der Veröffentlichung prüfen", diff: ["+ purchase.currency: Standard EUR, wenn der Shop keine sendet", "+ destinations.meta.value_currency: EUR", "= 1 zurückgehaltenes Purchase-Event würde zugestellt"], confirm: "v15 veröffentlichen", cancel: "Verwerfen" },
    note: "Statisches Beispiel mit Beispieldaten. In deinem Workspace läuft derselbe Ablauf gegen deine echte Konfiguration und fragt vor der Veröffentlichung nach deiner Bestätigung.",
    more: "So arbeitet Track AI",
  },
  useCases: {
    eyebrow: "Anwendungsfälle",
    title: "Gebaut für Shops, Lead-Generierung und Agenturen",
    text: "Derselbe Router mit einem Messplan, der zu deinem Geschäft passt.",
    items: [
      { title: "E-Commerce", text: "Verifizierte Bestellungen statt Browser-Schätzungen.", points: ["Purchase-, Refund- und Subscription-Events aus Shopify-, WooCommerce- oder Shopware-Webhooks", "Bestellnummer als Source of Truth für die Deduplizierung", "Wert und Währung vor der Zustellung validiert"] },
      { title: "Lead-Generierung", text: "Jeder qualifizierte Lead zugeordnet, keiner doppelt gezählt.", points: ["Lead-Events aus Formular und Server mit gemeinsamer Event-ID", "Click-IDs wie gclid und li_fat_id nur mit Consent weitergegeben", "Offline-Conversions hochgeladen, wenn der Abschluss steht"] },
      { title: "Agenturen", text: "Viele Sites, ein Arbeitsablauf.", points: ["Mehrere Sites und Marken pro Workspace", "Entwürfe, Freigaben und ein Audit-Log für jede Änderung", "Tracking Health je Kunde, ohne fünf Dashboards zu öffnen"] },
    ],
  },
  trustSection: {
    eyebrow: "Consent, Sicherheit, EU-Daten",
    title: "Datenschutz wird im Code erzwungen, nicht im Banner versprochen",
    text: "Track ist als Daten-, Consent- und Routing-Layer gebaut. Das sind Produktfakten, die du in der Dokumentation und im Auftragsverarbeitungsvertrag nachprüfen kannst.",
    groups: [
      { title: "Consent", items: ["Strikte Opt-in-Defaults; eine fehlende Entscheidung wird nie zum Ja", "Consent Mode v2, TCF 2.2, GPP- und GPC-Signale sowie die gängigen CMPs", "Serverseitige Zustellung umgeht nie einen abgelehnten Consent"] },
      { title: "Sicherheit", items: ["Signierte, versionierte Konfigurationen, im Browser verifiziert", "Zugangsdaten envelope-verschlüsselt; Secrets gelangen nie in Chat, Logs oder das Modell", "Row-Level Security isoliert jeden Workspace in der Datenbank"] },
      { title: "EU-Daten", items: ["Verarbeitung standardmäßig in der EU-Datenregion", "Auftragsverarbeiter nach Art. 28 DSGVO mit Auftragsverarbeitungsvertrag", "Kein Fingerprinting, keine Consent-Umgehung, keine synthetischen Conversions"] },
    ],
    links: { security: "Sicherheit", privacy: "Datenschutz", dpa: "Auftragsverarbeitung (AVV)", subprocessors: "Subunternehmer" },
  },
  knowledge: {
    eyebrow: "Tracking Knowledge",
    title: "Verstehen, wie Tracking wirklich funktioniert",
    text: "Leitfäden zu Server-Side Tracking, Deduplizierung und Consent – geschrieben vom Team, das Track baut.",
    all: "Alle Artikel",
    minutes: "{n} Min. Lesezeit",
  },
  pricing: {
    eyebrow: "Preise",
    title: "Tarife, die mit deinem Eventvolumen wachsen",
    text: "Jeder Tarif enthält Browser- und Server-Side-Tracking, alle Standard-Destinations, Track AI und die Consent Engine. Monatliche Abrechnung ist voreingestellt; ein Jahr kostet zehn Monatsraten.",
    perMonth: "pro Monat",
    events: "{n} akzeptierte Events pro Monat",
    sites: { one: "{n} produktive Website", other: "{n} produktive Websites" },
    custom: "Custom",
    customText: "Individuelles Volumen, Vertrag und SLA.",
    trial: "{days} Tage {plan} testen, keine Kreditkarte, keine automatische Umwandlung in einen bezahlten Tarif.",
    all: "Alle Tarife vergleichen",
    taxNote: "Listenpreise netto in EUR; zzgl. USt., sofern anwendbar.",
    recommended: "Empfohlen",
    enterprise: "Enterprise",
    enterpriseText: "Individuelle Volumina, Infrastruktur, Governance und SLA.",
    contact: "Mit dem Vertrieb sprechen",
  },
  finalCta: {
    title: "Bereit für verifizierte Events?",
    text: "Site anlegen, Snippet einfügen und Track AI durch den Rest führen lassen. Zum Start ist keine Kreditkarte nötig.",
    cta: "Site anlegen",
    secondary: "Demo buchen",
  },
  demo: DEMO_DE,
};
