import type { DemoCopy, HomeCopy } from "../types";

/**
 * English (source language) copy of the home area. Same shape as every other locale file; see docs/14-localization.md.
 */

/**
 * Home page copy (supplement §4): benefit first, technical proof later; no invented customers,
 * numbers or results — every statement is a verifiable product fact or clearly labelled sample data.
 * The demo labels are function-free (placeholders in braces) because they are passed to a client
 * component; see `components/marketing/demo/text.ts`.
 */

const DEMO_EN: DemoCopy = {
  label: "Interactive demo",
  sample: "Sample data — nothing is sent to any platform",
  sampleShort: "Sample data",
  region: "Track product demo",
  configLive: "Config v{version} live",
  controls: {
    reset: "Reset demo",
    pause: "Pause stream",
    play: "Play stream",
    next: "Next event",
    paused: "Stream paused",
    reducedMotion: "Reduced motion is on: the stream only advances when you press “Next event”.",
    offscreen: "Stream paused while the demo is out of view",
    complete: "The stream loops through the same sample script.",
  },
  viewsLabel: "Demo views",
  views: { overview: "Overview", events: "Live Events", destinations: "Destinations", ai: "AI Setup", attribution: "Attribution" },
  metrics: { accepted: "Accepted", delivered: "Delivered", duplicates: "Duplicates removed", blocked: "Blocked by consent", held: "Held" },
  health: {
    title: "Tracking Health Score",
    outOf: "of 100",
    explain: "How the score is calculated",
    parts: {
      consent: { label: "Consent decisions", detail: "{decided} of {accepted} accepted events have a consent decision; {pending} pending" },
      dedup: { label: "Browser/server pairing", detail: "{paired} of {conversions} conversions arrived from both browser and server" },
      params: { label: "Purchase parameters", detail: "{complete} of {purchases} Purchase events carry value and currency" },
      delivery: { label: "Delivery", detail: "{delivered} of {routable} routable events delivered; {held} held" },
    },
  },
  events: {
    title: "Live event stream",
    latest: "Latest events",
    origin: { browser: "Browser", server: "Server" },
    dedup: { unique: "Single source", paired: "Paired with the other source", duplicate: "Duplicate dropped" },
    consent: { granted: "Consent granted", denied: "Consent denied", pending: "Consent pending" },
    outcome: { delivered: "Delivered", blocked: "Blocked", held: "Held", duplicate: "Duplicate" },
    reasons: {
      delivered: "Delivered to every routed destination.",
      consent_denied: "Marketing consent was denied — nothing is sent to ad platforms.",
      consent_pending: "No consent decision yet — the event waits and is not sent.",
      missing_currency: "The Purchase has a value but no currency — held until a currency is set.",
      duplicate: "The same event ID was already accepted from the other source — dropped and not counted.",
      released: "Released after the currency fix and delivered.",
    },
    routedTo: { one: "{n} destination", other: "{n} destinations" },
    none: "No destination",
    columns: { event: "Event", origin: "Origin", consent: "Consent", outcome: "Outcome", time: "Time" },
    detail: { eventId: "Event ID", value: "Value", currency: "Currency", missing: "missing", order: "Order", destinations: "Delivered to", route: "Route", expand: "Show details", collapse: "Hide details", consentLabel: "Consent", dedupLabel: "Deduplication" },
  },
  flow: { website: "Website", track: "Track", consent: "Consent / policy", destinations: "Destinations", caption: "Path of the latest event: website → Track → consent check → destinations." },
  destinations: {
    title: "Destination health",
    pick: "Choose a platform",
    health: { ok: "Healthy", warn: "Needs attention", bad: "Failing" },
    lastDelivery: "Last successful delivery",
    none: "No delivery yet in this run",
    modes: "Modes",
    browserServer: "Browser tag + server API",
    dedupKey: "Dedup key",
    clickParam: "Click ID",
    counts: { delivered: "Delivered", held: "Held", blocked: "Blocked by consent" },
    heldHint: { one: "{n} Purchase is held until a currency is set.", other: "{n} Purchases are held until a currency is set." },
    openAi: "Fix it in AI Setup",
  },
  ai: {
    title: "AI Setup",
    from: "Track AI",
    found: {
      one: "{n} Purchase event arrived with a value but without a currency. Destinations cannot report the revenue correctly without it.",
      other: "{n} Purchase events arrived with a value but without a currency. Destinations cannot report the revenue correctly without it.",
    },
    foundNone: "No open recommendation. Purchase events now carry value and currency.",
    evidence: "Evidence in the sample stream",
    evidenceRow: "{name} · {origin} · value {value}, currency missing · {time}",
    question: "Which currency should Track apply when the shop sends none?",
    options: { EUR: "Euro (EUR)", USD: "US dollar (USD)", GBP: "Pound sterling (GBP)" },
    confirm: "Confirm and publish draft",
    result: {
      one: "Config v{version} published for the demo. {n} held Purchase was delivered.",
      other: "Config v{version} published for the demo. {n} held Purchases were delivered.",
      zero: "Config v{version} published for the demo.",
    },
    note: "This changes only the sample data. In your workspace Track AI prepares the same change as a draft and waits for your approval.",
    overviewHint: { one: "Recommendation: {n} Purchase is held without a currency", other: "Recommendation: {n} Purchases are held without a currency" },
    overviewDone: "Recommendation resolved: currency set, held Purchases delivered",
    open: "Open AI Setup",
    stepLabel: "Default currency",
  },
  attribution: {
    title: "Attribution & click IDs",
    intro: "Which click IDs the sample sessions carried, whether consent allowed forwarding them, and what stays unknown.",
    columns: { platform: "Platform", clickId: "Click ID", captured: "Observed", consent: "Consent", forwarded: "Forwarded server-side" },
    captured: { yes: "Yes", no: "Not in this run" },
    forwarded: { yes: "Yes", no: "Withheld", na: "—" },
    consentNa: "—",
    note: "Observed facts only: click IDs seen on landing URLs of the sample sessions. Cross-device journeys are unknown and stay unknown — nothing is modelled.",
  },
  announce: { event: "New event: {name} from {origin}, {outcome}.", setupDone: "Setup step confirmed. Held Purchases delivered.", reset: "Demo reset to its starting state." },
  mobileHint: "Compact demo: the same sample data with fewer rows.",
};

export const HOME_COPY_EN: HomeCopy = {
  eyebrow: "AI-first tag manager",
  title: "One snippet. Every platform. Every conversion counted once.",
  subtitle: "Track collects your website events first-party, checks consent before anything leaves your site and delivers them server-side to Meta, Google, TikTok, LinkedIn and more — deduplicated, explained, and set up together with Track AI.",
  cta: "Start with your domain",
  ctaSecondary: "See how it works",
  domainPlaceholder: "yourshop.com",
  domainLabel: "Your website",
  domainHelp: "We only check the format here. Next, we create your site with a six-character tracking ID and guide you through the setup in chat.",
  domainInvalid: "Enter a domain such as yourshop.com — without https:// or a path.",
  trust: {
    eu: "EU data region",
    consent: "Consent checked before delivery",
    signed: "Signed, versioned configs",
    noCode: "No custom HTML or JavaScript",
  },
  demoHeading: "Interactive product demo",
  platforms: {
    title: "Works with the platforms and shop systems you already use",
    text: "Browser tag plus server-side API for every destination that offers one, sharing one event ID so nothing is counted twice. Shopify, WooCommerce and Shopware send verified orders directly.",
    all: "All integrations",
    groups: { ads: "Ad platforms", analytics: "Analytics", commerce: "Shop systems" },
    modes: { browser: "Browser", server: "Server", offline: "Offline" },
  },
  outcomes: {
    eyebrow: "What you get",
    title: "Three things your tracking should do — and usually doesn't",
    text: "Pixels alone lose events, server-side setups need engineers, and consent is often a banner instead of a rule. Track turns all three into one guided setup.",
    items: [
      { title: "Every conversion counted once", text: "Browser and server send the same event ID; Track merges the pair and forwards one conversion per order. Replays never create a second one.", proof: "In the demo: the dedup marker in the live event stream" },
      { title: "Only what consent allows leaves your site", text: "Each event passes a policy check before delivery. A denied consent blocks the destination, a missing decision never becomes a yes, and every decision is recorded with its reason.", proof: "In the demo: the block reason on every held event" },
      { title: "You always know what to fix next", text: "A tracking health score with explainable parts and Track AI recommendations that point to the exact event and parameter — with a draft you approve.", proof: "In the demo: the Purchase that arrives without a currency" },
    ],
  },
  flow: {
    eyebrow: "How it works",
    title: "Snippet → Track → Platforms",
    text: "One asynchronous script on your pages, one router in the EU that checks consent and merges duplicates, and every destination fed server-side from the same verified event.",
    steps: [
      { title: "Install one snippet", text: "Add the asynchronous tracker with your six-character site ID. It loads a signed configuration, never blocks rendering and fails safe if anything is wrong." },
      { title: "Track checks and routes", text: "Events are validated, matched to their consent decision, deduplicated by event ID and order ID, then queued for each destination separately." },
      { title: "Platforms receive verified events", text: "Meta, Google, TikTok, LinkedIn, Reddit and more get browser and server events with shared IDs; you see the delivery status and the last response per destination." },
    ],
    snippetTitle: "The snippet",
    copy: "Copy snippet",
    copied: "Copied",
    caption: "Website → Track → Consent / policy → Destinations: the path every event takes.",
    nodes: { website: "Your website", track: "Track", consent: "Consent / policy", destination: "Destinations" },
    more: "Read the full walkthrough",
  },
  aiSetup: {
    eyebrow: "Guided setup",
    title: "Set up with Track AI. Publish only what you approve.",
    text: "Track AI detects your platform, proposes a measurement plan and connects destinations with validated inputs. Every change becomes a draft with a readable diff — nothing goes live until you confirm.",
    bullets: ["Detects your CMS or shop system and the events that matter for it", "Asks one question at a time; credentials go into secure cards, never into the chat", "Every change is a draft with a diff, an approval button and one-click rollback"],
    transcriptLabel: "Example conversation (static)",
    transcript: [
      { role: "assistant", text: "I checked demo-shop.example and detected Shopware 6. Purchase events arrive with a value but without a currency, so Meta and TikTok cannot count revenue." },
      { role: "you", text: "Use EUR as the default." },
      { role: "assistant", text: "The change is ready for your review. Nothing changes until you confirm." },
    ],
    approval: { title: "Draft v15 — review before publishing", diff: ["+ purchase.currency: default EUR when the shop sends none", "+ destinations.meta.value_currency: EUR", "= 1 held Purchase event would be delivered"], confirm: "Publish v15", cancel: "Discard" },
    note: "Static example with sample data. In your workspace the same flow runs against your real configuration and asks for your confirmation before publishing.",
    more: "How Track AI works",
  },
  useCases: {
    eyebrow: "Use cases",
    title: "Built for shops, lead generation and agencies",
    text: "The same router with a measurement plan that fits your business.",
    items: [
      { title: "E-commerce", text: "Verified orders instead of browser guesses.", points: ["Purchase, refund and subscription events from Shopify, WooCommerce or Shopware webhooks", "Order ID as the source of truth for deduplication", "Value and currency validated before delivery"] },
      { title: "Lead generation", text: "Every qualified lead attributed, none counted twice.", points: ["Lead events from forms and server with a shared event ID", "Click IDs such as gclid and li_fat_id forwarded only with consent", "Offline conversions uploaded when the deal is won"] },
      { title: "Agencies", text: "Many sites, one workflow.", points: ["Several sites and brands per workspace", "Drafts, approvals and an audit log for every change", "Tracking health per client without opening five dashboards"] },
    ],
  },
  trustSection: {
    eyebrow: "Consent, security, EU data",
    title: "Privacy is enforced in code, not promised in a banner",
    text: "Track is built as a data, consent and routing layer. These are product facts you can verify in the documentation and the data processing agreement.",
    groups: [
      { title: "Consent", items: ["Strict opt-in defaults; a missing decision never becomes a yes", "Consent Mode v2, TCF 2.2, GPP and GPC signals plus the common CMPs", "Server-side delivery never bypasses a denied consent"] },
      { title: "Security", items: ["Signed, versioned configurations verified in the browser", "Credentials envelope-encrypted; secrets never reach chat, logs or the model", "Row-level security isolates every workspace in the database"] },
      { title: "EU data", items: ["Processing in the EU data region by default", "Processor under Art. 28 GDPR with a data processing agreement", "No fingerprinting, no consent bypass, no synthetic conversions"] },
    ],
    links: { security: "Security", privacy: "Privacy", dpa: "Data processing (DPA)", subprocessors: "Subprocessors" },
  },
  knowledge: {
    eyebrow: "Tracking Knowledge",
    title: "Learn how tracking really works",
    text: "Guides on server-side tracking, deduplication and consent — written by the team building Track.",
    all: "All articles",
    minutes: "{n} min read",
  },
  pricing: {
    eyebrow: "Pricing",
    title: "Plans that grow with your event volume",
    text: "Every plan includes browser and server-side tracking, all standard destinations, Track AI and the consent engine. Monthly billing is the default; a year costs ten monthly instalments.",
    perMonth: "per month",
    events: "{n} accepted events per month",
    sites: { one: "{n} production website", other: "{n} production websites" },
    custom: "Custom",
    customText: "Custom volume, contract and SLA.",
    trial: "{days}-day {plan} trial, no credit card, no automatic conversion into a paid plan.",
    all: "Compare all plans",
    taxNote: "Net list prices in EUR; VAT is added where applicable.",
    recommended: "Recommended",
    enterprise: "Enterprise",
    enterpriseText: "Custom volumes, infrastructure, governance and SLA.",
    contact: "Talk to sales",
  },
  finalCta: {
    title: "Ready for verified events?",
    text: "Create your site, paste the snippet and let Track AI guide the rest. No credit card needed to start.",
    cta: "Create your site",
    secondary: "Book a demo",
  },
  demo: DEMO_EN,
};
