import type { DemoCopy, HomeCopy } from "../types";

/**
 * Spanish (es, European Spanish, tuteo) copy of the home area. Same shape as en.ts; see docs/14-localization.md.
 */

const DEMO_ES: DemoCopy = {
  label: "Demo interactiva",
  sample: "Datos de ejemplo: no se envía nada a ninguna plataforma",
  sampleShort: "Datos de ejemplo",
  region: "Demo del producto Track",
  configLive: "Config v{version} activa",
  controls: {
    reset: "Reiniciar la demo",
    pause: "Pausar el flujo",
    play: "Reproducir el flujo",
    next: "Siguiente evento",
    paused: "Flujo en pausa",
    reducedMotion: "El movimiento reducido está activado: el flujo solo avanza cuando pulsas «Siguiente evento».",
    offscreen: "Flujo en pausa mientras la demo no está a la vista",
    complete: "El flujo repite en bucle el mismo guion de ejemplo.",
  },
  viewsLabel: "Vistas de la demo",
  views: { overview: "Overview", events: "Live Events", destinations: "Destinations", ai: "AI Setup", attribution: "Attribution" },
  metrics: { accepted: "Aceptados", delivered: "Entregados", duplicates: "Duplicados eliminados", blocked: "Bloqueados por consentimiento", held: "Retenidos" },
  health: {
    title: "Tracking Health Score",
    outOf: "de 100",
    explain: "Cómo se calcula la puntuación",
    parts: {
      consent: { label: "Decisiones de consentimiento", detail: "{decided} de {accepted} eventos aceptados tienen una decisión de consentimiento; {pending} pendientes" },
      dedup: { label: "Emparejamiento navegador/servidor", detail: "{paired} de {conversions} conversiones llegaron tanto del navegador como del servidor" },
      params: { label: "Parámetros de Purchase", detail: "{complete} de {purchases} eventos Purchase incluyen valor y moneda" },
      delivery: { label: "Entrega", detail: "{delivered} de {routable} eventos enrutables entregados; {held} retenidos" },
    },
  },
  events: {
    title: "Flujo de eventos en directo",
    latest: "Últimos eventos",
    origin: { browser: "Navegador", server: "Servidor" },
    dedup: { unique: "Una sola fuente", paired: "Emparejado con la otra fuente", duplicate: "Duplicado descartado" },
    consent: { granted: "Consentimiento concedido", denied: "Consentimiento denegado", pending: "Consentimiento pendiente" },
    outcome: { delivered: "Entregado", blocked: "Bloqueado", held: "Retenido", duplicate: "Duplicado" },
    reasons: {
      delivered: "Entregado a todos los destinos enrutados.",
      consent_denied: "Se denegó el consentimiento de marketing: no se envía nada a las plataformas publicitarias.",
      consent_pending: "Todavía no hay decisión de consentimiento: el evento espera y no se envía.",
      missing_currency: "El Purchase tiene valor pero no moneda: se retiene hasta que se defina una moneda.",
      duplicate: "El mismo ID de evento ya se aceptó desde la otra fuente: descartado y no contado.",
      released: "Liberado tras corregir la moneda y entregado.",
    },
    routedTo: { one: "{n} destino", other: "{n} destinos" },
    none: "Sin destino",
    columns: { event: "Evento", origin: "Origen", consent: "Consentimiento", outcome: "Resultado", time: "Hora" },
    detail: { eventId: "ID de evento", value: "Valor", currency: "Moneda", missing: "falta", order: "Pedido", destinations: "Entregado a", route: "Ruta", expand: "Mostrar detalles", collapse: "Ocultar detalles", consentLabel: "Consentimiento", dedupLabel: "Deduplicación" },
  },
  flow: { website: "Sitio web", track: "Track", consent: "Consentimiento / política", destinations: "Destinos", caption: "Recorrido del último evento: sitio web → Track → comprobación del consentimiento → destinos." },
  destinations: {
    title: "Destination Health",
    pick: "Elige una plataforma",
    health: { ok: "Correcto", warn: "Requiere atención", bad: "Con errores" },
    lastDelivery: "Última entrega correcta",
    none: "Todavía no hay entregas en esta ejecución",
    modes: "Modos",
    browserServer: "Etiqueta en el navegador + API de servidor",
    dedupKey: "Clave de deduplicación",
    clickParam: "ID de clic",
    counts: { delivered: "Entregados", held: "Retenidos", blocked: "Bloqueados por consentimiento" },
    heldHint: { one: "{n} Purchase se retiene hasta que se defina una moneda.", other: "{n} Purchases se retienen hasta que se defina una moneda." },
    openAi: "Corregirlo en AI Setup",
  },
  ai: {
    title: "AI Setup",
    from: "Track AI",
    found: {
      one: "{n} evento Purchase ha llegado con valor pero sin moneda. Sin ella, los destinos no pueden registrar los ingresos correctamente.",
      other: "{n} eventos Purchase han llegado con valor pero sin moneda. Sin ella, los destinos no pueden registrar los ingresos correctamente.",
    },
    foundNone: "No hay recomendaciones pendientes. Los eventos Purchase ya incluyen valor y moneda.",
    evidence: "Evidencia en el flujo de ejemplo",
    evidenceRow: "{name} · {origin} · valor {value}, falta la moneda · {time}",
    question: "¿Qué moneda debe aplicar Track cuando la tienda no envía ninguna?",
    options: { EUR: "Euro (EUR)", USD: "Dólar estadounidense (USD)", GBP: "Libra esterlina (GBP)" },
    confirm: "Confirmar y publicar el borrador",
    result: {
      one: "Config v{version} publicada para la demo. Se ha entregado {n} Purchase retenido.",
      other: "Config v{version} publicada para la demo. Se han entregado {n} Purchases retenidos.",
      zero: "Config v{version} publicada para la demo.",
    },
    note: "Esto solo cambia los datos de ejemplo. En tu espacio de trabajo, Track AI prepara el mismo cambio como borrador y espera tu aprobación.",
    overviewHint: { one: "Recomendación: {n} Purchase está retenido sin moneda", other: "Recomendación: {n} Purchases están retenidos sin moneda" },
    overviewDone: "Recomendación resuelta: moneda definida, Purchases retenidos entregados",
    open: "Abrir AI Setup",
    stepLabel: "Moneda por defecto",
  },
  attribution: {
    title: "Atribución e IDs de clic",
    intro: "Qué IDs de clic llevaban las sesiones de ejemplo, si el consentimiento permitió transmitirlos y qué sigue siendo desconocido.",
    columns: { platform: "Plataforma", clickId: "ID de clic", captured: "Observado", consent: "Consentimiento", forwarded: "Transmitido desde el servidor" },
    captured: { yes: "Sí", no: "No en esta ejecución" },
    forwarded: { yes: "Sí", no: "Retenido", na: "—" },
    consentNa: "—",
    note: "Solo hechos observados: IDs de clic vistos en las URL de entrada de las sesiones de ejemplo. Los recorridos entre dispositivos son desconocidos y siguen siéndolo: no se modela nada.",
  },
  announce: { event: "Nuevo evento: {name} desde {origin}, {outcome}.", setupDone: "Paso de configuración confirmado. Purchases retenidos entregados.", reset: "Demo restablecida a su estado inicial." },
  mobileHint: "Demo compacta: los mismos datos de ejemplo con menos filas.",
};

export const HOME_COPY_ES: HomeCopy = {
  eyebrow: "Tag manager AI-first",
  title: "Un snippet. Todas las plataformas. Cada conversión contada una sola vez.",
  subtitle: "Track recoge los eventos de tu sitio web en modo first-party, comprueba el consentimiento antes de que nada salga de tu sitio y los entrega desde el servidor a Meta, Google, TikTok, LinkedIn y más: deduplicados, explicados y configurados junto con Track AI.",
  cta: "Empieza con tu dominio",
  ctaSecondary: "Ver cómo funciona",
  domainPlaceholder: "tutienda.es",
  domainLabel: "Tu sitio web",
  domainHelp: "Aquí solo comprobamos el formato. A continuación creamos tu sitio con un ID de tracking de seis caracteres y te guiamos por la configuración en el chat.",
  domainInvalid: "Introduce un dominio como tutienda.es, sin https:// ni ruta.",
  trust: {
    eu: "Región de datos de la UE",
    consent: "Consentimiento comprobado antes de la entrega",
    signed: "Configuraciones firmadas y versionadas",
    noCode: "Sin HTML ni JavaScript personalizados",
  },
  demoHeading: "Demo interactiva del producto",
  platforms: {
    title: "Funciona con las plataformas y los sistemas de e-commerce que ya utilizas",
    text: "Etiqueta en el navegador más API server-side para cada destino que la ofrezca, con un ID de evento compartido para que nada se cuente dos veces. Shopify, WooCommerce y Shopware envían pedidos verificados directamente.",
    all: "Todas las integraciones",
    groups: { ads: "Plataformas publicitarias", analytics: "Analítica", commerce: "Plataformas de e-commerce" },
    modes: { browser: "Navegador", server: "Servidor", offline: "Offline" },
  },
  outcomes: {
    eyebrow: "Lo que obtienes",
    title: "Tres cosas que tu tracking debería hacer, y que normalmente no hace",
    text: "Los píxeles por sí solos pierden eventos, las configuraciones server-side necesitan ingenieros y el consentimiento suele ser un banner en lugar de una regla. Track convierte las tres en una única configuración guiada.",
    items: [
      { title: "Cada conversión contada una sola vez", text: "El navegador y el servidor envían el mismo ID de evento; Track fusiona el par y transmite una conversión por pedido. Los reenvíos nunca crean una segunda.", proof: "En la demo: el marcador de deduplicación en el flujo de eventos en directo" },
      { title: "De tu sitio solo sale lo que el consentimiento permite", text: "Cada evento pasa una comprobación de política antes de la entrega. Un consentimiento denegado bloquea el destino, una decisión ausente nunca se convierte en un sí, y cada decisión queda registrada con su motivo.", proof: "En la demo: el motivo de bloqueo en cada evento retenido" },
      { title: "Siempre sabes qué corregir a continuación", text: "Un Tracking Health Score con componentes explicables y recomendaciones de Track AI que señalan el evento y el parámetro exactos, con un borrador que tú apruebas.", proof: "En la demo: el Purchase que llega sin moneda" },
    ],
  },
  flow: {
    eyebrow: "Cómo funciona",
    title: "Snippet → Track → Plataformas",
    text: "Un script asíncrono en tus páginas, un router en la UE que comprueba el consentimiento y fusiona los duplicados, y cada destino alimentado desde el servidor con el mismo evento verificado.",
    steps: [
      { title: "Instala un snippet", text: "Añade el tracker asíncrono con el ID de seis caracteres de tu sitio. Carga una configuración firmada, nunca bloquea el renderizado y falla de forma segura si algo no está bien." },
      { title: "Track comprueba y enruta", text: "Los eventos se validan, se asocian a su decisión de consentimiento, se deduplican por ID de evento e ID de pedido y después se ponen en cola por separado para cada destino." },
      { title: "Las plataformas reciben eventos verificados", text: "Meta, Google, TikTok, LinkedIn, Reddit y más reciben eventos del navegador y del servidor con IDs compartidos; tú ves el estado de entrega y la última respuesta por destino." },
    ],
    snippetTitle: "El snippet",
    copy: "Copiar snippet",
    copied: "Copiado",
    caption: "Sitio web → Track → Consentimiento / política → Destinos: el recorrido que sigue cada evento.",
    nodes: { website: "Tu sitio web", track: "Track", consent: "Consentimiento / política", destination: "Destinos" },
    more: "Leer el recorrido completo",
  },
  aiSetup: {
    eyebrow: "Configuración guiada",
    title: "Configura con Track AI. Publica solo lo que apruebes.",
    text: "Track AI detecta tu plataforma, propone un plan de medición y conecta destinos con datos validados. Cada cambio se convierte en un borrador con un diff legible: nada entra en producción hasta que lo confirmes.",
    bullets: ["Detecta tu CMS o plataforma de e-commerce y los eventos que importan para ella", "Hace una pregunta cada vez; las credenciales van a tarjetas seguras, nunca al chat", "Cada cambio es un borrador con diff, botón de aprobación y rollback con un clic"],
    transcriptLabel: "Conversación de ejemplo (estática)",
    transcript: [
      { role: "assistant", text: "He comprobado demo-shop.example y he detectado Shopware 6. Los eventos Purchase llegan con valor pero sin moneda, así que Meta y TikTok no pueden contabilizar los ingresos." },
      { role: "you", text: "Usa EUR por defecto." },
      { role: "assistant", text: "El cambio está listo para tu revisión. Nada cambia hasta que lo confirmes." },
    ],
    approval: { title: "Borrador v15: revisar antes de publicar", diff: ["+ purchase.currency: EUR por defecto cuando la tienda no envía ninguna", "+ destinations.meta.value_currency: EUR", "= se entregaría 1 evento Purchase retenido"], confirm: "Publicar v15", cancel: "Descartar" },
    note: "Ejemplo estático con datos de ejemplo. En tu espacio de trabajo, el mismo flujo se ejecuta contra tu configuración real y pide tu confirmación antes de publicar.",
    more: "Cómo trabaja Track AI",
  },
  useCases: {
    eyebrow: "Casos de uso",
    title: "Pensado para tiendas, generación de leads y agencias",
    text: "El mismo router con un plan de medición que encaja con tu negocio.",
    items: [
      { title: "E-commerce", text: "Pedidos verificados en lugar de estimaciones del navegador.", points: ["Eventos Purchase, Refund y Subscription desde los webhooks de Shopify, WooCommerce o Shopware", "El ID de pedido como fuente de verdad para la deduplicación", "Valor y moneda validados antes de la entrega"] },
      { title: "Generación de leads", text: "Cada lead cualificado atribuido, ninguno contado dos veces.", points: ["Eventos Lead desde formularios y servidor con un ID de evento compartido", "IDs de clic como gclid y li_fat_id transmitidos solo con consentimiento", "Conversiones offline subidas cuando se cierra la venta"] },
      { title: "Agencias", text: "Muchos sitios, un solo flujo de trabajo.", points: ["Varios sitios y marcas por espacio de trabajo", "Borradores, aprobaciones y un registro de auditoría para cada cambio", "Salud del tracking por cliente sin abrir cinco paneles"] },
    ],
  },
  trustSection: {
    eyebrow: "Consentimiento, seguridad, datos en la UE",
    title: "La privacidad se aplica en el código, no se promete en un banner",
    text: "Track está construido como capa de datos, consentimiento y enrutamiento. Estos son hechos del producto que puedes verificar en la documentación y en el contrato de encargo de tratamiento.",
    groups: [
      { title: "Consentimiento", items: ["Opt-in estricto por defecto; una decisión ausente nunca se convierte en un sí", "Consent Mode v2, TCF 2.2, señales GPP y GPC, además de los CMP más habituales", "La entrega server-side nunca elude un consentimiento denegado"] },
      { title: "Seguridad", items: ["Configuraciones firmadas y versionadas, verificadas en el navegador", "Credenciales con cifrado de sobre; los secretos nunca llegan al chat, a los logs ni al modelo", "La seguridad a nivel de fila aísla cada espacio de trabajo en la base de datos"] },
      { title: "Datos en la UE", items: ["Tratamiento en la región de datos de la UE por defecto", "Encargado del tratamiento según el art. 28 del RGPD con contrato de encargo de tratamiento", "Sin fingerprinting, sin elusión del consentimiento, sin conversiones sintéticas"] },
    ],
    links: { security: "Seguridad", privacy: "Privacidad", dpa: "Encargo de tratamiento (DPA)", subprocessors: "Subencargados" },
  },
  knowledge: {
    eyebrow: "Tracking Knowledge",
    title: "Aprende cómo funciona el tracking de verdad",
    text: "Guías sobre tracking server-side, deduplicación y consentimiento, escritas por el equipo que construye Track.",
    all: "Todos los artículos",
    minutes: "{n} min de lectura",
  },
  pricing: {
    eyebrow: "Precios",
    title: "Planes que crecen con tu volumen de eventos",
    text: "Todos los planes incluyen tracking en el navegador y server-side, todos los destinos estándar, Track AI y el Consent Engine. La facturación mensual es la opción por defecto; un año cuesta diez cuotas mensuales.",
    perMonth: "al mes",
    events: "{n} eventos aceptados al mes",
    sites: { one: "{n} sitio web en producción", other: "{n} sitios web en producción" },
    custom: "A medida",
    customText: "Volumen, contrato y SLA a medida.",
    trial: "Prueba de {plan} durante {days} días, sin tarjeta de crédito y sin conversión automática a un plan de pago.",
    all: "Comparar todos los planes",
    taxNote: "Precios de lista netos en EUR; se añade el IVA cuando corresponda.",
    recommended: "Recomendado",
    enterprise: "Enterprise",
    enterpriseText: "Volúmenes, infraestructura, gobernanza y SLA a medida.",
    contact: "Hablar con ventas",
  },
  finalCta: {
    title: "¿Listo para eventos verificados?",
    text: "Crea tu sitio, pega el snippet y deja que Track AI te guíe en el resto. No necesitas tarjeta de crédito para empezar.",
    cta: "Crea tu sitio",
    secondary: "Reservar una demo",
  },
  demo: DEMO_ES,
};
