import type { DemoCopy, HomeCopy } from "../types";

/**
 * French (fr) copy of the home area. Same shape as en.ts; see docs/14-localization.md.
 */

const DEMO_FR: DemoCopy = {
  label: "Démo interactive",
  sample: "Données d’exemple — rien n’est envoyé à aucune plateforme",
  sampleShort: "Données d’exemple",
  region: "Démo du produit Track",
  configLive: "Config v{version} en ligne",
  controls: {
    reset: "Réinitialiser la démo",
    pause: "Mettre le flux en pause",
    play: "Lancer le flux",
    next: "Événement suivant",
    paused: "Flux en pause",
    reducedMotion: "La réduction des animations est activée : le flux n’avance que lorsque vous appuyez sur « Événement suivant ».",
    offscreen: "Flux en pause tant que la démo n’est pas visible",
    complete: "Le flux rejoue le même scénario d’exemple en boucle.",
  },
  viewsLabel: "Vues de la démo",
  views: { overview: "Overview", events: "Live Events", destinations: "Destinations", ai: "AI Setup", attribution: "Attribution" },
  metrics: { accepted: "Acceptés", delivered: "Transmis", duplicates: "Doublons supprimés", blocked: "Bloqués par le consentement", held: "Retenus" },
  health: {
    title: "Tracking Health Score",
    outOf: "sur 100",
    explain: "Comment le score est calculé",
    parts: {
      consent: { label: "Décisions de consentement", detail: "{decided} des {accepted} événements acceptés ont une décision de consentement ; {pending} en attente" },
      dedup: { label: "Appariement navigateur/serveur", detail: "{paired} des {conversions} conversions sont arrivées à la fois du navigateur et du serveur" },
      params: { label: "Paramètres Purchase", detail: "{complete} des {purchases} événements Purchase contiennent une valeur et une devise" },
      delivery: { label: "Transmission", detail: "{delivered} des {routable} événements routables transmis ; {held} retenus" },
    },
  },
  events: {
    title: "Flux d’événements en direct",
    latest: "Derniers événements",
    origin: { browser: "Navigateur", server: "Serveur" },
    dedup: { unique: "Source unique", paired: "Apparié avec l’autre source", duplicate: "Doublon écarté" },
    consent: { granted: "Consentement accordé", denied: "Consentement refusé", pending: "Consentement en attente" },
    outcome: { delivered: "Transmis", blocked: "Bloqué", held: "Retenu", duplicate: "Doublon" },
    reasons: {
      delivered: "Transmis à toutes les destinations routées.",
      consent_denied: "Le consentement marketing a été refusé — rien n’est envoyé aux plateformes publicitaires.",
      consent_pending: "Pas encore de décision de consentement — l’événement attend et n’est pas envoyé.",
      missing_currency: "Le Purchase a une valeur mais pas de devise — retenu jusqu’à ce qu’une devise soit définie.",
      duplicate: "Le même ID d’événement a déjà été accepté depuis l’autre source — écarté et non comptabilisé.",
      released: "Libéré après la correction de la devise et transmis.",
    },
    routedTo: { one: "{n} destination", other: "{n} destinations" },
    none: "Aucune destination",
    columns: { event: "Événement", origin: "Origine", consent: "Consentement", outcome: "Résultat", time: "Heure" },
    detail: { eventId: "ID d’événement", value: "Valeur", currency: "Devise", missing: "manquante", order: "Commande", destinations: "Transmis à", route: "Route", expand: "Afficher les détails", collapse: "Masquer les détails", consentLabel: "Consentement", dedupLabel: "Déduplication" },
  },
  flow: { website: "Site web", track: "Track", consent: "Consentement / règles", destinations: "Destinations", caption: "Parcours du dernier événement : site web → Track → contrôle du consentement → destinations." },
  destinations: {
    title: "Santé des destinations",
    pick: "Choisir une plateforme",
    health: { ok: "Opérationnelle", warn: "À surveiller", bad: "En échec" },
    lastDelivery: "Dernière transmission réussie",
    none: "Aucune transmission pour l’instant dans cette exécution",
    modes: "Modes",
    browserServer: "Tag navigateur + API serveur",
    dedupKey: "Clé de déduplication",
    clickParam: "ID de clic",
    counts: { delivered: "Transmis", held: "Retenus", blocked: "Bloqués par le consentement" },
    heldHint: { one: "{n} Purchase est retenu jusqu’à ce qu’une devise soit définie.", other: "{n} Purchases sont retenus jusqu’à ce qu’une devise soit définie." },
    openAi: "Corriger dans AI Setup",
  },
  ai: {
    title: "AI Setup",
    from: "Track AI",
    found: {
      one: "{n} événement Purchase est arrivé avec une valeur mais sans devise. Sans elle, les destinations ne peuvent pas comptabiliser correctement le chiffre d’affaires.",
      other: "{n} événements Purchase sont arrivés avec une valeur mais sans devise. Sans elle, les destinations ne peuvent pas comptabiliser correctement le chiffre d’affaires.",
    },
    foundNone: "Aucune recommandation ouverte. Les événements Purchase contiennent désormais une valeur et une devise.",
    evidence: "Preuves dans le flux d’exemple",
    evidenceRow: "{name} · {origin} · valeur {value}, devise manquante · {time}",
    question: "Quelle devise Track doit-il appliquer lorsque la boutique n’en envoie aucune ?",
    options: { EUR: "Euro (EUR)", USD: "Dollar américain (USD)", GBP: "Livre sterling (GBP)" },
    confirm: "Confirmer et publier le brouillon",
    result: {
      one: "Config v{version} publiée pour la démo. {n} Purchase retenu a été transmis.",
      other: "Config v{version} publiée pour la démo. {n} Purchases retenus ont été transmis.",
      zero: "Config v{version} publiée pour la démo.",
    },
    note: "Cela ne modifie que les données d’exemple. Dans votre espace de travail, Track AI prépare la même modification sous forme de brouillon et attend votre approbation.",
    overviewHint: { one: "Recommandation : {n} Purchase est retenu sans devise", other: "Recommandation : {n} Purchases sont retenus sans devise" },
    overviewDone: "Recommandation résolue : devise définie, Purchases retenus transmis",
    open: "Ouvrir AI Setup",
    stepLabel: "Devise par défaut",
  },
  attribution: {
    title: "Attribution & ID de clic",
    intro: "Quels ID de clic les sessions d’exemple portaient, si le consentement autorisait leur transmission, et ce qui reste inconnu.",
    columns: { platform: "Plateforme", clickId: "ID de clic", captured: "Observé", consent: "Consentement", forwarded: "Transmis côté serveur" },
    captured: { yes: "Oui", no: "Pas dans cette exécution" },
    forwarded: { yes: "Oui", no: "Non transmis", na: "—" },
    consentNa: "—",
    note: "Uniquement des faits observés : les ID de clic vus sur les URL d’atterrissage des sessions d’exemple. Les parcours multi-appareils sont inconnus et le restent — rien n’est modélisé.",
  },
  announce: { event: "Nouvel événement : {name} depuis {origin}, {outcome}.", setupDone: "Étape de configuration confirmée. Purchases retenus transmis.", reset: "Démo réinitialisée à son état initial." },
  mobileHint: "Démo compacte : les mêmes données d’exemple avec moins de lignes.",
};

export const HOME_COPY_FR: HomeCopy = {
  eyebrow: "Tag manager AI-first",
  title: "Un snippet. Toutes les plateformes. Chaque conversion comptée une seule fois.",
  subtitle: "Track collecte les événements de votre site web en first-party, vérifie le consentement avant que quoi que ce soit ne quitte votre site et les transmet côté serveur à Meta, Google, TikTok, LinkedIn et bien d’autres — dédupliqués, expliqués et configurés avec Track AI.",
  cta: "Commencer avec votre domaine",
  ctaSecondary: "Voir comment ça fonctionne",
  domainPlaceholder: "votreboutique.fr",
  domainLabel: "Votre site web",
  domainHelp: "Nous vérifions ici uniquement le format. Ensuite, nous créons votre site avec un ID de tracking à six caractères et vous guidons dans la configuration par chat.",
  domainInvalid: "Saisissez un domaine comme votreboutique.fr — sans https:// ni chemin.",
  trust: {
    eu: "Région de données UE",
    consent: "Consentement vérifié avant la transmission",
    signed: "Configurations signées et versionnées",
    noCode: "Pas de HTML ni de JavaScript personnalisé",
  },
  demoHeading: "Démo interactive du produit",
  platforms: {
    title: "Compatible avec les plateformes et solutions e-commerce que vous utilisez déjà",
    text: "Tag navigateur plus API côté serveur pour chaque destination qui en propose une, avec un ID d’événement commun pour que rien ne soit compté deux fois. Shopify, WooCommerce et Shopware envoient directement les commandes vérifiées.",
    all: "Toutes les intégrations",
    groups: { ads: "Plateformes publicitaires", analytics: "Analytics", commerce: "Plateformes e-commerce" },
    modes: { browser: "Navigateur", server: "Serveur", offline: "Hors ligne" },
  },
  outcomes: {
    eyebrow: "Ce que vous obtenez",
    title: "Trois choses que votre tracking devrait faire — et qu’il ne fait généralement pas",
    text: "Les pixels seuls perdent des événements, les configurations côté serveur exigent des développeurs, et le consentement est souvent un bandeau plutôt qu’une règle. Track réunit les trois dans une seule configuration guidée.",
    items: [
      { title: "Chaque conversion comptée une seule fois", text: "Le navigateur et le serveur envoient le même ID d’événement ; Track fusionne la paire et transmet une conversion par commande. Les rejeux ne créent jamais de seconde conversion.", proof: "Dans la démo : le marqueur de déduplication dans le flux d’événements en direct" },
      { title: "Seul ce que le consentement autorise quitte votre site", text: "Chaque événement passe un contrôle des règles avant la transmission. Un consentement refusé bloque la destination, une décision manquante ne devient jamais un oui, et chaque décision est consignée avec sa raison.", proof: "Dans la démo : la raison du blocage sur chaque événement retenu" },
      { title: "Vous savez toujours quoi corriger ensuite", text: "Un score de santé du tracking aux composantes explicables et des recommandations de Track AI qui pointent vers l’événement et le paramètre exacts — avec un brouillon que vous approuvez.", proof: "Dans la démo : le Purchase qui arrive sans devise" },
    ],
  },
  flow: {
    eyebrow: "Comment ça fonctionne",
    title: "Snippet → Track → Plateformes",
    text: "Un script asynchrone sur vos pages, un routeur dans l’UE qui vérifie le consentement et fusionne les doublons, et chaque destination alimentée côté serveur à partir du même événement vérifié.",
    steps: [
      { title: "Installez un snippet", text: "Ajoutez le tracker asynchrone avec votre ID de site à six caractères. Il charge une configuration signée, ne bloque jamais le rendu et se met en sécurité si quelque chose ne va pas." },
      { title: "Track vérifie et route", text: "Les événements sont validés, associés à leur décision de consentement, dédupliqués par ID d’événement et ID de commande, puis mis en file d’attente séparément pour chaque destination." },
      { title: "Les plateformes reçoivent des événements vérifiés", text: "Meta, Google, TikTok, LinkedIn, Reddit et d’autres reçoivent des événements navigateur et serveur avec des ID communs ; vous voyez l’état de transmission et la dernière réponse par destination." },
    ],
    snippetTitle: "Le snippet",
    copy: "Copier le snippet",
    copied: "Copié",
    caption: "Site web → Track → Consentement / règles → Destinations : le parcours de chaque événement.",
    nodes: { website: "Votre site web", track: "Track", consent: "Consentement / règles", destination: "Destinations" },
    more: "Lire le parcours complet",
  },
  aiSetup: {
    eyebrow: "Configuration guidée",
    title: "Configurez avec Track AI. Ne publiez que ce que vous approuvez.",
    text: "Track AI détecte votre plateforme, propose un plan de mesure et connecte les destinations avec des entrées validées. Chaque modification devient un brouillon avec un diff lisible — rien n’est mis en ligne tant que vous n’avez pas confirmé.",
    bullets: ["Détecte votre CMS ou votre solution e-commerce et les événements qui comptent pour elle", "Pose une question à la fois ; les identifiants d’accès vont dans des cartes sécurisées, jamais dans le chat", "Chaque modification est un brouillon avec un diff, un bouton d’approbation et un rollback en un clic"],
    transcriptLabel: "Exemple de conversation (statique)",
    transcript: [
      { role: "assistant", text: "J’ai analysé demo-shop.example et détecté Shopware 6. Les événements Purchase arrivent avec une valeur mais sans devise, donc Meta et TikTok ne peuvent pas comptabiliser le chiffre d’affaires." },
      { role: "you", text: "Utilisez EUR par défaut." },
      { role: "assistant", text: "La modification est prête pour votre relecture. Rien ne change tant que vous n’avez pas confirmé." },
    ],
    approval: { title: "Brouillon v15 — à relire avant publication", diff: ["+ purchase.currency: EUR par défaut lorsque la boutique n’en envoie aucune", "+ destinations.meta.value_currency: EUR", "= 1 événement Purchase retenu serait transmis"], confirm: "Publier v15", cancel: "Abandonner" },
    note: "Exemple statique avec des données d’exemple. Dans votre espace de travail, le même flux s’exécute sur votre configuration réelle et demande votre confirmation avant la publication.",
    more: "Comment Track AI fonctionne",
  },
  useCases: {
    eyebrow: "Cas d’usage",
    title: "Conçu pour les boutiques en ligne, la génération de leads et les agences",
    text: "Le même routeur, avec un plan de mesure adapté à votre activité.",
    items: [
      { title: "E-commerce", text: "Des commandes vérifiées plutôt que des estimations navigateur.", points: ["Événements d’achat, de remboursement et d’abonnement issus des webhooks Shopify, WooCommerce ou Shopware", "L’ID de commande comme source de vérité pour la déduplication", "Valeur et devise validées avant la transmission"] },
      { title: "Génération de leads", text: "Chaque lead qualifié attribué, aucun compté deux fois.", points: ["Événements Lead depuis les formulaires et le serveur avec un ID d’événement commun", "ID de clic tels que gclid et li_fat_id transmis uniquement avec consentement", "Conversions hors ligne importées lorsque l’affaire est gagnée"] },
      { title: "Agences", text: "Plusieurs sites, un seul flux de travail.", points: ["Plusieurs sites et marques par espace de travail", "Brouillons, approbations et journal d’audit pour chaque modification", "Santé du tracking par client sans ouvrir cinq tableaux de bord"] },
    ],
  },
  trustSection: {
    eyebrow: "Consentement, sécurité, données UE",
    title: "La protection des données est imposée dans le code, pas promise dans un bandeau",
    text: "Track est conçu comme une couche de données, de consentement et de routage. Ce sont des faits produit que vous pouvez vérifier dans la documentation et dans l’accord de traitement des données.",
    groups: [
      { title: "Consentement", items: ["Opt-in strict par défaut ; une décision manquante ne devient jamais un oui", "Consent Mode v2, TCF 2.2, signaux GPP et GPC, plus les CMP courantes", "La transmission côté serveur ne contourne jamais un consentement refusé"] },
      { title: "Sécurité", items: ["Configurations signées et versionnées, vérifiées dans le navigateur", "Identifiants d’accès chiffrés par enveloppe ; les secrets n’atteignent jamais le chat, les journaux ni le modèle", "La sécurité au niveau des lignes isole chaque espace de travail dans la base de données"] },
      { title: "Données UE", items: ["Traitement dans la région de données UE par défaut", "Sous-traitant au sens de l’art. 28 du RGPD avec un accord de traitement des données", "Pas de fingerprinting, pas de contournement du consentement, pas de conversions synthétiques"] },
    ],
    links: { security: "Sécurité", privacy: "Confidentialité", dpa: "Traitement des données (DPA)", subprocessors: "Sous-traitants ultérieurs" },
  },
  knowledge: {
    eyebrow: "Tracking Knowledge",
    title: "Comprendre comment le tracking fonctionne vraiment",
    text: "Des guides sur le tracking côté serveur, la déduplication et le consentement — rédigés par l’équipe qui construit Track.",
    all: "Tous les articles",
    minutes: "{n} min de lecture",
  },
  pricing: {
    eyebrow: "Tarifs",
    title: "Des formules qui évoluent avec votre volume d’événements",
    text: "Chaque formule inclut le tracking navigateur et côté serveur, toutes les destinations standard, Track AI et le Consent Engine. La facturation mensuelle est le réglage par défaut ; une année coûte dix mensualités.",
    perMonth: "par mois",
    events: "{n} événements acceptés par mois",
    sites: { one: "{n} site web de production", other: "{n} sites web de production" },
    custom: "Sur mesure",
    customText: "Volume, contrat et SLA sur mesure.",
    trial: "Essai {plan} de {days} jours, sans carte bancaire, sans conversion automatique en formule payante.",
    all: "Comparer toutes les formules",
    taxNote: "Prix catalogue hors taxes en EUR ; TVA en sus le cas échéant.",
    recommended: "Recommandée",
    enterprise: "Enterprise",
    enterpriseText: "Volumes, infrastructure, gouvernance et SLA sur mesure.",
    contact: "Parler à l’équipe commerciale",
  },
  finalCta: {
    title: "Prêt pour des événements vérifiés ?",
    text: "Créez votre site, collez le snippet et laissez Track AI vous guider pour la suite. Aucune carte bancaire n’est nécessaire pour commencer.",
    cta: "Créer votre site",
    secondary: "Réserver une démo",
  },
  demo: DEMO_FR,
};
