import type { DemoCopy, HomeCopy } from "../types";

/**
 * Italian (it, "tu" register) copy of the home area. Same shape as en.ts; see docs/14-localization.md.
 */

const DEMO_IT: DemoCopy = {
  label: "Demo interattiva",
  sample: "Dati di esempio — nulla viene inviato a nessuna piattaforma",
  sampleShort: "Dati di esempio",
  region: "Demo del prodotto Track",
  configLive: "Config v{version} live",
  controls: {
    reset: "Reimposta la demo",
    pause: "Metti in pausa lo stream",
    play: "Riproduci lo stream",
    next: "Evento successivo",
    paused: "Stream in pausa",
    reducedMotion: "Il movimento ridotto è attivo: lo stream avanza solo quando premi “Evento successivo”.",
    offscreen: "Stream in pausa finché la demo non è visibile",
    complete: "Lo stream ripete in loop lo stesso script di esempio.",
  },
  viewsLabel: "Viste della demo",
  views: { overview: "Overview", events: "Live Events", destinations: "Destinations", ai: "AI Setup", attribution: "Attribution" },
  metrics: { accepted: "Accettati", delivered: "Consegnati", duplicates: "Duplicati rimossi", blocked: "Bloccati dal consenso", held: "Trattenuti" },
  health: {
    title: "Tracking Health Score",
    outOf: "su 100",
    explain: "Come viene calcolato lo score",
    parts: {
      consent: { label: "Decisioni sul consenso", detail: "{decided} di {accepted} eventi accettati hanno una decisione sul consenso; {pending} in sospeso" },
      dedup: { label: "Abbinamento browser/server", detail: "{paired} di {conversions} conversioni sono arrivate sia dal browser sia dal server" },
      params: { label: "Parametri Purchase", detail: "{complete} di {purchases} eventi Purchase contengono valore e valuta" },
      delivery: { label: "Consegna", detail: "{delivered} di {routable} eventi instradabili consegnati; {held} trattenuti" },
    },
  },
  events: {
    title: "Stream di eventi live",
    latest: "Ultimi eventi",
    origin: { browser: "Browser", server: "Server" },
    dedup: { unique: "Fonte singola", paired: "Abbinato all'altra fonte", duplicate: "Duplicato scartato" },
    consent: { granted: "Consenso concesso", denied: "Consenso negato", pending: "Consenso in sospeso" },
    outcome: { delivered: "Consegnato", blocked: "Bloccato", held: "Trattenuto", duplicate: "Duplicato" },
    reasons: {
      delivered: "Consegnato a tutte le destinazioni instradate.",
      consent_denied: "Il consenso marketing è stato negato — nulla viene inviato alle piattaforme pubblicitarie.",
      consent_pending: "Ancora nessuna decisione sul consenso — l'evento attende e non viene inviato.",
      missing_currency: "Il Purchase ha un valore ma nessuna valuta — trattenuto finché non viene impostata una valuta.",
      duplicate: "Lo stesso ID evento era già stato accettato dall'altra fonte — scartato e non conteggiato.",
      released: "Rilasciato dopo la correzione della valuta e consegnato.",
    },
    routedTo: { one: "{n} destinazione", other: "{n} destinazioni" },
    none: "Nessuna destinazione",
    columns: { event: "Evento", origin: "Origine", consent: "Consenso", outcome: "Esito", time: "Ora" },
    detail: { eventId: "ID evento", value: "Valore", currency: "Valuta", missing: "mancante", order: "Ordine", destinations: "Consegnato a", route: "Percorso", expand: "Mostra dettagli", collapse: "Nascondi dettagli", consentLabel: "Consenso", dedupLabel: "Deduplicazione" },
  },
  flow: { website: "Sito web", track: "Track", consent: "Consenso / policy", destinations: "Destinazioni", caption: "Percorso dell'ultimo evento: sito web → Track → verifica del consenso → destinazioni." },
  destinations: {
    title: "Stato delle destinazioni",
    pick: "Scegli una piattaforma",
    health: { ok: "In salute", warn: "Richiede attenzione", bad: "In errore" },
    lastDelivery: "Ultima consegna riuscita",
    none: "Nessuna consegna ancora in questa esecuzione",
    modes: "Modalità",
    browserServer: "Tag browser + API server",
    dedupKey: "Chiave di deduplicazione",
    clickParam: "Click ID",
    counts: { delivered: "Consegnati", held: "Trattenuti", blocked: "Bloccati dal consenso" },
    heldHint: { one: "{n} Purchase è trattenuto finché non viene impostata una valuta.", other: "{n} Purchase sono trattenuti finché non viene impostata una valuta." },
    openAi: "Correggi in AI Setup",
  },
  ai: {
    title: "AI Setup",
    from: "Track AI",
    found: {
      one: "{n} evento Purchase è arrivato con un valore ma senza valuta. Senza di essa le destinazioni non possono riportare correttamente i ricavi.",
      other: "{n} eventi Purchase sono arrivati con un valore ma senza valuta. Senza di essa le destinazioni non possono riportare correttamente i ricavi.",
    },
    foundNone: "Nessuna raccomandazione aperta. Gli eventi Purchase ora contengono valore e valuta.",
    evidence: "Evidenze nello stream di esempio",
    evidenceRow: "{name} · {origin} · valore {value}, valuta mancante · {time}",
    question: "Quale valuta deve applicare Track quando lo shop non ne invia nessuna?",
    options: { EUR: "Euro (EUR)", USD: "Dollaro USA (USD)", GBP: "Sterlina britannica (GBP)" },
    confirm: "Conferma e pubblica la bozza",
    result: {
      one: "Config v{version} pubblicata per la demo. {n} Purchase trattenuto è stato consegnato.",
      other: "Config v{version} pubblicata per la demo. {n} Purchase trattenuti sono stati consegnati.",
      zero: "Config v{version} pubblicata per la demo.",
    },
    note: "Questo modifica solo i dati di esempio. Nel tuo workspace Track AI prepara la stessa modifica come bozza e attende la tua approvazione.",
    overviewHint: { one: "Raccomandazione: {n} Purchase è trattenuto senza valuta", other: "Raccomandazione: {n} Purchase sono trattenuti senza valuta" },
    overviewDone: "Raccomandazione risolta: valuta impostata, Purchase trattenuti consegnati",
    open: "Apri AI Setup",
    stepLabel: "Valuta predefinita",
  },
  attribution: {
    title: "Attribuzione e click ID",
    intro: "Quali click ID portavano le sessioni di esempio, se il consenso ne ha permesso l'inoltro e cosa resta sconosciuto.",
    columns: { platform: "Piattaforma", clickId: "Click ID", captured: "Osservato", consent: "Consenso", forwarded: "Inoltrato server-side" },
    captured: { yes: "Sì", no: "Non in questa esecuzione" },
    forwarded: { yes: "Sì", no: "Trattenuto", na: "—" },
    consentNa: "—",
    note: "Solo fatti osservati: click ID visti sugli URL delle landing page delle sessioni di esempio. I percorsi cross-device sono sconosciuti e restano tali — nulla viene modellato.",
  },
  announce: { event: "Nuovo evento: {name} da {origin}, {outcome}.", setupDone: "Passaggio di configurazione confermato. Purchase trattenuti consegnati.", reset: "Demo riportata allo stato iniziale." },
  mobileHint: "Demo compatta: gli stessi dati di esempio con meno righe.",
};

export const HOME_COPY_IT: HomeCopy = {
  eyebrow: "Tag manager AI-first",
  title: "Uno snippet. Ogni piattaforma. Ogni conversione contata una sola volta.",
  subtitle: "Track raccoglie gli eventi del tuo sito web in modalità first-party, verifica il consenso prima che qualsiasi dato lasci il tuo sito e li consegna server-side a Meta, Google, TikTok, LinkedIn e altre piattaforme — deduplicati, spiegati e configurati insieme a Track AI.",
  cta: "Inizia con il tuo dominio",
  ctaSecondary: "Scopri come funziona",
  domainPlaceholder: "tuoshop.it",
  domainLabel: "Il tuo sito web",
  domainHelp: "Qui controlliamo solo il formato. Subito dopo creiamo il tuo sito con un ID di tracking di sei caratteri e ti guidiamo nella configurazione in chat.",
  domainInvalid: "Inserisci un dominio come tuoshop.it — senza https:// e senza percorso.",
  trust: {
    eu: "Regione dati UE",
    consent: "Consenso verificato prima della consegna",
    signed: "Configurazioni firmate e versionate",
    noCode: "Nessun HTML o JavaScript personalizzato",
  },
  demoHeading: "Demo interattiva del prodotto",
  platforms: {
    title: "Funziona con le piattaforme e i sistemi e-commerce che già usi",
    text: "Tag browser più API server-side per ogni destinazione che ne offre una, con un unico ID evento condiviso perché nulla venga contato due volte. Shopify, WooCommerce e Shopware inviano direttamente ordini verificati.",
    all: "Tutte le integrazioni",
    groups: { ads: "Piattaforme pubblicitarie", analytics: "Analytics", commerce: "Sistemi e-commerce" },
    modes: { browser: "Browser", server: "Server", offline: "Offline" },
  },
  outcomes: {
    eyebrow: "Cosa ottieni",
    title: "Tre cose che il tuo tracking dovrebbe fare — e di solito non fa",
    text: "I pixel da soli perdono eventi, le configurazioni server-side richiedono sviluppatori e il consenso è spesso un banner invece di una regola. Track trasforma tutte e tre in un'unica configurazione guidata.",
    items: [
      { title: "Ogni conversione contata una sola volta", text: "Browser e server inviano lo stesso ID evento; Track unisce la coppia e inoltra una conversione per ordine. I replay non ne creano mai una seconda.", proof: "Nella demo: l'indicatore di deduplicazione nello stream di eventi live" },
      { title: "Dal tuo sito esce solo ciò che il consenso permette", text: "Ogni evento passa una verifica di policy prima della consegna. Un consenso negato blocca la destinazione, una decisione mancante non diventa mai un sì e ogni decisione viene registrata con la sua motivazione.", proof: "Nella demo: il motivo del blocco su ogni evento trattenuto" },
      { title: "Sai sempre cosa correggere per primo", text: "Un health score del tracking con componenti spiegabili e raccomandazioni di Track AI che indicano esattamente l'evento e il parametro — con una bozza che approvi tu.", proof: "Nella demo: il Purchase che arriva senza valuta" },
    ],
  },
  flow: {
    eyebrow: "Come funziona",
    title: "Snippet → Track → piattaforme",
    text: "Uno script asincrono sulle tue pagine, un router nell'UE che verifica il consenso e unisce i duplicati, e ogni destinazione alimentata server-side dallo stesso evento verificato.",
    steps: [
      { title: "Installa uno snippet", text: "Aggiungi il tracker asincrono con l'ID di sei caratteri del tuo sito. Carica una configurazione firmata, non blocca mai il rendering ed è fail-safe se qualcosa non va." },
      { title: "Track verifica e instrada", text: "Gli eventi vengono validati, abbinati alla loro decisione sul consenso, deduplicati per ID evento e ID ordine e poi messi in coda separatamente per ogni destinazione." },
      { title: "Le piattaforme ricevono eventi verificati", text: "Meta, Google, TikTok, LinkedIn, Reddit e altre ricevono eventi browser e server con ID condivisi; vedi lo stato di consegna e l'ultima risposta per ogni destinazione." },
    ],
    snippetTitle: "Lo snippet",
    copy: "Copia lo snippet",
    copied: "Copiato",
    caption: "Sito web → Track → consenso / policy → destinazioni: il percorso che fa ogni evento.",
    nodes: { website: "Il tuo sito web", track: "Track", consent: "Consenso / policy", destination: "Destinazioni" },
    more: "Leggi la guida completa",
  },
  aiSetup: {
    eyebrow: "Configurazione guidata",
    title: "Configura con Track AI. Pubblica solo ciò che approvi.",
    text: "Track AI rileva la tua piattaforma, propone un piano di misurazione e collega le destinazioni con input validati. Ogni modifica diventa una bozza con un diff leggibile — nulla va live finché non confermi.",
    bullets: ["Rileva il tuo CMS o sistema e-commerce e gli eventi che contano per la tua attività", "Fa una domanda alla volta; le credenziali vanno in schede sicure, mai nella chat", "Ogni modifica è una bozza con diff, pulsante di approvazione e rollback con un clic"],
    transcriptLabel: "Conversazione di esempio (statica)",
    transcript: [
      { role: "assistant", text: "Ho controllato demo-shop.example e ho rilevato Shopware 6. Gli eventi Purchase arrivano con un valore ma senza valuta, quindi Meta e TikTok non possono conteggiare i ricavi." },
      { role: "you", text: "Usa EUR come valuta predefinita." },
      { role: "assistant", text: "La modifica è pronta per la tua revisione. Nulla cambia finché non confermi." },
    ],
    approval: { title: "Bozza v15 — rivedi prima di pubblicare", diff: ["+ purchase.currency: EUR di default quando lo shop non ne invia nessuna", "+ destinations.meta.value_currency: EUR", "= 1 evento Purchase trattenuto verrebbe consegnato"], confirm: "Pubblica v15", cancel: "Scarta" },
    note: "Esempio statico con dati di esempio. Nel tuo workspace lo stesso flusso gira sulla tua configurazione reale e chiede la tua conferma prima di pubblicare.",
    more: "Come lavora Track AI",
  },
  useCases: {
    eyebrow: "Casi d'uso",
    title: "Pensato per shop, lead generation e agenzie",
    text: "Lo stesso router con un piano di misurazione adatto alla tua attività.",
    items: [
      { title: "E-commerce", text: "Ordini verificati invece di stime dal browser.", points: ["Eventi di acquisto (Purchase), rimborso e abbonamento dai webhook di Shopify, WooCommerce o Shopware", "ID ordine come fonte di verità per la deduplicazione", "Valore e valuta validati prima della consegna"] },
      { title: "Lead generation", text: "Ogni lead qualificato attribuito, nessuno contato due volte.", points: ["Eventi Lead da moduli e server con un ID evento condiviso", "Click ID come gclid e li_fat_id inoltrati solo con il consenso", "Conversioni offline caricate quando la trattativa si chiude"] },
      { title: "Agenzie", text: "Molti siti, un solo flusso di lavoro.", points: ["Più siti e brand per workspace", "Bozze, approvazioni e un audit log per ogni modifica", "Salute del tracking per ogni cliente senza aprire cinque dashboard"] },
    ],
  },
  trustSection: {
    eyebrow: "Consenso, sicurezza, dati nell'UE",
    title: "La privacy è garantita dal codice, non promessa da un banner",
    text: "Track è costruito come layer di dati, consenso e routing. Questi sono fatti di prodotto che puoi verificare nella documentazione e nell'accordo sul trattamento dei dati.",
    groups: [
      { title: "Consenso", items: ["Opt-in rigoroso di default; una decisione mancante non diventa mai un sì", "Consent Mode v2, TCF 2.2, segnali GPP e GPC più i CMP più diffusi", "La consegna server-side non aggira mai un consenso negato"] },
      { title: "Sicurezza", items: ["Configurazioni firmate e versionate, verificate nel browser", "Credenziali cifrate con envelope encryption; i segreti non raggiungono mai chat, log o modello", "La row-level security isola ogni workspace nel database"] },
      { title: "Dati nell'UE", items: ["Trattamento nella regione dati UE di default", "Responsabile del trattamento ai sensi dell'art. 28 GDPR con accordo sul trattamento dei dati", "Nessun fingerprinting, nessuna elusione del consenso, nessuna conversione sintetica"] },
    ],
    links: { security: "Sicurezza", privacy: "Privacy", dpa: "Trattamento dei dati (DPA)", subprocessors: "Sub-responsabili" },
  },
  knowledge: {
    eyebrow: "Tracking Knowledge",
    title: "Scopri come funziona davvero il tracking",
    text: "Guide su tracking server-side, deduplicazione e consenso — scritte dal team che costruisce Track.",
    all: "Tutti gli articoli",
    minutes: "{n} min di lettura",
  },
  pricing: {
    eyebrow: "Prezzi",
    title: "Piani che crescono con il tuo volume di eventi",
    text: "Ogni piano include tracking browser e server-side, tutte le destinazioni standard, Track AI e il Consent Engine. La fatturazione mensile è quella di default; un anno costa dieci rate mensili.",
    perMonth: "al mese",
    events: "{n} eventi accettati al mese",
    sites: { one: "{n} sito web di produzione", other: "{n} siti web di produzione" },
    custom: "Su misura",
    customText: "Volume, contratto e SLA su misura.",
    trial: "{days} giorni di prova di {plan}, senza carta di credito e senza conversione automatica in un piano a pagamento.",
    all: "Confronta tutti i piani",
    taxNote: "Prezzi di listino netti in EUR; IVA aggiunta dove applicabile.",
    recommended: "Consigliato",
    enterprise: "Enterprise",
    enterpriseText: "Volumi, infrastruttura, governance e SLA su misura.",
    contact: "Parla con il team commerciale",
  },
  finalCta: {
    title: "Pronto per eventi verificati?",
    text: "Crea il tuo sito, incolla lo snippet e lascia che Track AI ti guidi nel resto. Per iniziare non serve una carta di credito.",
    cta: "Crea il tuo sito",
    secondary: "Prenota una demo",
  },
  demo: DEMO_IT,
};
