import type { DemoCopy, HomeCopy } from "../types";

/**
 * Dutch (nl, "je" register) copy of the home area. Same shape as en.ts; see docs/14-localization.md.
 */

const DEMO_NL: DemoCopy = {
  label: "Interactieve demo",
  sample: "Voorbeelddata – er wordt niets naar een platform verstuurd",
  sampleShort: "Voorbeelddata",
  region: "Track-productdemo",
  configLive: "Config v{version} live",
  controls: {
    reset: "Demo resetten",
    pause: "Stream pauzeren",
    play: "Stream afspelen",
    next: "Volgend event",
    paused: "Stream gepauzeerd",
    reducedMotion: "Verminderde beweging staat aan: de stream gaat alleen verder als je op ‘Volgend event’ drukt.",
    offscreen: "Stream gepauzeerd zolang de demo niet in beeld is",
    complete: "De stream herhaalt hetzelfde voorbeeldscript.",
  },
  viewsLabel: "Demoweergaven",
  views: { overview: "Overview", events: "Live Events", destinations: "Destinations", ai: "AI Setup", attribution: "Attribution" },
  metrics: { accepted: "Geaccepteerd", delivered: "Afgeleverd", duplicates: "Duplicaten verwijderd", blocked: "Geblokkeerd door toestemming", held: "Vastgehouden" },
  health: {
    title: "Tracking Health Score",
    outOf: "van 100",
    explain: "Zo wordt de score berekend",
    parts: {
      consent: { label: "Toestemmingsbeslissingen", detail: "{decided} van {accepted} geaccepteerde events hebben een toestemmingsbeslissing; {pending} in afwachting" },
      dedup: { label: "Browser/server-koppeling", detail: "{paired} van {conversions} conversies kwamen binnen via zowel browser als server" },
      params: { label: "Purchase-parameters", detail: "{complete} van {purchases} Purchase-events bevatten waarde en valuta" },
      delivery: { label: "Aflevering", detail: "{delivered} van {routable} routeerbare events afgeleverd; {held} vastgehouden" },
    },
  },
  events: {
    title: "Live eventstream",
    latest: "Laatste events",
    origin: { browser: "Browser", server: "Server" },
    dedup: { unique: "Eén bron", paired: "Gekoppeld aan de andere bron", duplicate: "Duplicaat verwijderd" },
    consent: { granted: "Toestemming gegeven", denied: "Toestemming geweigerd", pending: "Toestemming in afwachting" },
    outcome: { delivered: "Afgeleverd", blocked: "Geblokkeerd", held: "Vastgehouden", duplicate: "Duplicaat" },
    reasons: {
      delivered: "Afgeleverd bij elke gerouteerde destination.",
      consent_denied: "Marketingtoestemming is geweigerd – er wordt niets naar advertentieplatformen verstuurd.",
      consent_pending: "Nog geen toestemmingsbeslissing – het event wacht en wordt niet verstuurd.",
      missing_currency: "De Purchase heeft een waarde maar geen valuta – vastgehouden totdat een valuta is ingesteld.",
      duplicate: "Dezelfde event-ID was al geaccepteerd vanuit de andere bron – verwijderd en niet meegeteld.",
      released: "Vrijgegeven na de valutacorrectie en afgeleverd.",
    },
    routedTo: { one: "{n} destination", other: "{n} destinations" },
    none: "Geen destination",
    columns: { event: "Event", origin: "Herkomst", consent: "Toestemming", outcome: "Resultaat", time: "Tijd" },
    detail: { eventId: "Event-ID", value: "Waarde", currency: "Valuta", missing: "ontbreekt", order: "Bestelling", destinations: "Afgeleverd bij", route: "Route", expand: "Details tonen", collapse: "Details verbergen", consentLabel: "Toestemming", dedupLabel: "Deduplicatie" },
  },
  flow: { website: "Website", track: "Track", consent: "Toestemming / policy", destinations: "Destinations", caption: "Route van het laatste event: website → Track → toestemmingscheck → destinations." },
  destinations: {
    title: "Destination health",
    pick: "Kies een platform",
    health: { ok: "Gezond", warn: "Aandacht nodig", bad: "Faalt" },
    lastDelivery: "Laatste geslaagde aflevering",
    none: "Nog geen aflevering in deze run",
    modes: "Modi",
    browserServer: "Browsertag + server-API",
    dedupKey: "Dedup-sleutel",
    clickParam: "Click-ID",
    counts: { delivered: "Afgeleverd", held: "Vastgehouden", blocked: "Geblokkeerd door toestemming" },
    heldHint: { one: "{n} Purchase wordt vastgehouden totdat een valuta is ingesteld.", other: "{n} Purchases worden vastgehouden totdat een valuta is ingesteld." },
    openAi: "Oplossen in AI Setup",
  },
  ai: {
    title: "AI Setup",
    from: "Track AI",
    found: {
      one: "{n} Purchase-event kwam binnen met een waarde maar zonder valuta. Zonder valuta kunnen destinations de omzet niet correct rapporteren.",
      other: "{n} Purchase-events kwamen binnen met een waarde maar zonder valuta. Zonder valuta kunnen destinations de omzet niet correct rapporteren.",
    },
    foundNone: "Geen open aanbeveling. Purchase-events bevatten nu waarde en valuta.",
    evidence: "Bewijs in de voorbeeldstream",
    evidenceRow: "{name} · {origin} · waarde {value}, valuta ontbreekt · {time}",
    question: "Welke valuta moet Track gebruiken als de shop er geen meestuurt?",
    options: { EUR: "Euro (EUR)", USD: "Amerikaanse dollar (USD)", GBP: "Britse pond (GBP)" },
    confirm: "Bevestigen en concept publiceren",
    result: {
      one: "Config v{version} gepubliceerd voor de demo. {n} vastgehouden Purchase is afgeleverd.",
      other: "Config v{version} gepubliceerd voor de demo. {n} vastgehouden Purchases zijn afgeleverd.",
      zero: "Config v{version} gepubliceerd voor de demo.",
    },
    note: "Dit verandert alleen de voorbeelddata. In je workspace bereidt Track AI dezelfde wijziging voor als concept en wacht op je goedkeuring.",
    overviewHint: { one: "Aanbeveling: {n} Purchase wordt vastgehouden zonder valuta", other: "Aanbeveling: {n} Purchases worden vastgehouden zonder valuta" },
    overviewDone: "Aanbeveling opgelost: valuta ingesteld, vastgehouden Purchases afgeleverd",
    open: "AI Setup openen",
    stepLabel: "Standaardvaluta",
  },
  attribution: {
    title: "Attributie & click-ID's",
    intro: "Welke click-ID's de voorbeeldsessies bevatten, of toestemming het doorsturen toeliet en wat onbekend blijft.",
    columns: { platform: "Platform", clickId: "Click-ID", captured: "Waargenomen", consent: "Toestemming", forwarded: "Server-side doorgestuurd" },
    captured: { yes: "Ja", no: "Niet in deze run" },
    forwarded: { yes: "Ja", no: "Achtergehouden", na: "—" },
    consentNa: "—",
    note: "Alleen waargenomen feiten: click-ID's die op landings-URL's van de voorbeeldsessies zijn gezien. Cross-device journeys zijn onbekend en blijven onbekend – er wordt niets gemodelleerd.",
  },
  announce: { event: "Nieuw event: {name} vanuit {origin}, {outcome}.", setupDone: "Setupstap bevestigd. Vastgehouden Purchases afgeleverd.", reset: "Demo teruggezet naar de beginstand." },
  mobileHint: "Compacte demo: dezelfde voorbeelddata met minder rijen.",
};

export const HOME_COPY_NL: HomeCopy = {
  eyebrow: "AI-first tagmanager",
  title: "Eén snippet. Elk platform. Elke conversie één keer geteld.",
  subtitle: "Track verzamelt je website-events first-party, controleert de toestemming voordat er iets je site verlaat en levert ze server-side af bij Meta, Google, TikTok, LinkedIn en meer – gededupliceerd, verklaard en samen met Track AI ingericht.",
  cta: "Start met je domein",
  ctaSecondary: "Bekijk hoe het werkt",
  domainPlaceholder: "jouwshop.nl",
  domainLabel: "Je website",
  domainHelp: "We controleren hier alleen het formaat. Daarna maken we je site aan met een tracking-ID van zes tekens en begeleiden we je in de chat door de setup.",
  domainInvalid: "Voer een domein in zoals jouwshop.nl – zonder https:// of pad.",
  trust: {
    eu: "EU-dataregio",
    consent: "Toestemming gecontroleerd vóór aflevering",
    signed: "Ondertekende, geversioneerde configs",
    noCode: "Geen custom HTML of JavaScript",
  },
  demoHeading: "Interactieve productdemo",
  platforms: {
    title: "Werkt met de platformen en shopsystemen die je al gebruikt",
    text: "Browsertag plus server-side API voor elke destination die er een aanbiedt, met één gedeelde event-ID zodat niets dubbel telt. Shopify, WooCommerce en Shopware sturen geverifieerde bestellingen rechtstreeks door.",
    all: "Alle integraties",
    groups: { ads: "Advertentieplatformen", analytics: "Analytics", commerce: "Shopsystemen" },
    modes: { browser: "Browser", server: "Server", offline: "Offline" },
  },
  outcomes: {
    eyebrow: "Wat je krijgt",
    title: "Drie dingen die je tracking zou moeten doen – en meestal niet doet",
    text: "Pixels alleen verliezen events, server-side setups vragen om developers en toestemming is vaak een banner in plaats van een regel. Track maakt van alle drie één begeleide setup.",
    items: [
      { title: "Elke conversie één keer geteld", text: "Browser en server versturen dezelfde event-ID; Track voegt het paar samen en stuurt één conversie per bestelling door. Replays maken nooit een tweede.", proof: "In de demo: de dedup-markering in de live eventstream" },
      { title: "Alleen wat toestemming toelaat verlaat je site", text: "Elk event doorloopt een policycheck vóór de aflevering. Een geweigerde toestemming blokkeert de destination, een ontbrekende beslissing wordt nooit een ja, en elke beslissing wordt met reden vastgelegd.", proof: "In de demo: de blokkeerreden bij elk vastgehouden event" },
      { title: "Je weet altijd wat je hierna moet oplossen", text: "Een tracking-healthscore met verklaarbare onderdelen en Track AI-aanbevelingen die precies het event en de parameter aanwijzen – met een concept dat jij goedkeurt.", proof: "In de demo: de Purchase die zonder valuta binnenkomt" },
    ],
  },
  flow: {
    eyebrow: "Zo werkt het",
    title: "Snippet → Track → Platformen",
    text: "Eén asynchroon script op je pagina's, één router in de EU die toestemming controleert en duplicaten samenvoegt, en elke destination server-side gevoed vanuit hetzelfde geverifieerde event.",
    steps: [
      { title: "Plaats één snippet", text: "Voeg de asynchrone tracker toe met je site-ID van zes tekens. Hij laadt een ondertekende configuratie, blokkeert nooit het renderen en faalt veilig als er iets mis is." },
      { title: "Track controleert en routeert", text: "Events worden gevalideerd, gekoppeld aan hun toestemmingsbeslissing, gededupliceerd op event-ID en order-ID en daarna per destination apart in de wachtrij gezet." },
      { title: "Platformen ontvangen geverifieerde events", text: "Meta, Google, TikTok, LinkedIn, Reddit en meer krijgen browser- en server-events met gedeelde ID's; je ziet de afleverstatus en het laatste antwoord per destination." },
    ],
    snippetTitle: "De snippet",
    copy: "Snippet kopiëren",
    copied: "Gekopieerd",
    caption: "Website → Track → Toestemming / policy → Destinations: de route die elk event aflegt.",
    nodes: { website: "Je website", track: "Track", consent: "Toestemming / policy", destination: "Destinations" },
    more: "Lees de volledige uitleg",
  },
  aiSetup: {
    eyebrow: "Begeleide setup",
    title: "Inrichten met Track AI. Publiceer alleen wat je goedkeurt.",
    text: "Track AI herkent je platform, stelt een meetplan voor en koppelt destinations met gevalideerde invoer. Elke wijziging wordt een concept met een leesbare diff – niets gaat live voordat jij bevestigt.",
    bullets: ["Herkent je CMS of shopsysteem en de events die daarvoor tellen", "Stelt één vraag tegelijk; credentials gaan in beveiligde kaarten, nooit in de chat", "Elke wijziging is een concept met diff, goedkeuringsknop en rollback met één klik"],
    transcriptLabel: "Voorbeeldgesprek (statisch)",
    transcript: [
      { role: "assistant", text: "Ik heb demo-shop.example gecontroleerd en Shopware 6 herkend. Purchase-events komen binnen met een waarde maar zonder valuta, waardoor Meta en TikTok geen omzet kunnen tellen." },
      { role: "you", text: "Gebruik EUR als standaard." },
      { role: "assistant", text: "De wijziging staat klaar voor je review. Er verandert niets voordat je bevestigt." },
    ],
    approval: { title: "Concept v15 – controleer vóór publicatie", diff: ["+ purchase.currency: standaard EUR als de shop er geen meestuurt", "+ destinations.meta.value_currency: EUR", "= 1 vastgehouden Purchase-event zou worden afgeleverd"], confirm: "v15 publiceren", cancel: "Verwerpen" },
    note: "Statisch voorbeeld met voorbeelddata. In je workspace draait dezelfde flow tegen je echte configuratie en vraagt om je bevestiging vóór publicatie.",
    more: "Zo werkt Track AI",
  },
  useCases: {
    eyebrow: "Toepassingen",
    title: "Gebouwd voor webshops, leadgeneratie en bureaus",
    text: "Dezelfde router met een meetplan dat past bij je bedrijf.",
    items: [
      { title: "E-commerce", text: "Geverifieerde bestellingen in plaats van browserschattingen.", points: ["Purchase-, refund- en subscription-events uit Shopify-, WooCommerce- of Shopware-webhooks", "Order-ID als bron van waarheid voor deduplicatie", "Waarde en valuta gevalideerd vóór aflevering"] },
      { title: "Leadgeneratie", text: "Elke gekwalificeerde lead toegeschreven, geen enkele dubbel geteld.", points: ["Lead-events uit formulieren en server met een gedeelde event-ID", "Click-ID's zoals gclid en li_fat_id alleen met toestemming doorgestuurd", "Offline conversies geüpload zodra de deal is gesloten"] },
      { title: "Bureaus", text: "Veel sites, één workflow.", points: ["Meerdere sites en merken per workspace", "Concepten, goedkeuringen en een auditlog voor elke wijziging", "Tracking health per klant zonder vijf dashboards te openen"] },
    ],
  },
  trustSection: {
    eyebrow: "Toestemming, beveiliging, EU-data",
    title: "Privacy wordt afgedwongen in code, niet beloofd in een banner",
    text: "Track is gebouwd als data-, toestemmings- en routinglaag. Dit zijn productfeiten die je kunt nagaan in de documentatie en de verwerkersovereenkomst.",
    groups: [
      { title: "Toestemming", items: ["Strikte opt-in als standaard; een ontbrekende beslissing wordt nooit een ja", "Consent Mode v2, TCF 2.2, GPP- en GPC-signalen plus de gangbare CMP's", "Server-side aflevering omzeilt nooit een geweigerde toestemming"] },
      { title: "Beveiliging", items: ["Ondertekende, geversioneerde configuraties, geverifieerd in de browser", "Credentials envelope-versleuteld; secrets bereiken nooit chat, logs of het model", "Row-level security isoleert elke workspace in de database"] },
      { title: "EU-data", items: ["Verwerking standaard in de EU-dataregio", "Verwerker volgens art. 28 AVG met een verwerkersovereenkomst", "Geen fingerprinting, geen omzeiling van toestemming, geen synthetische conversies"] },
    ],
    links: { security: "Beveiliging", privacy: "Privacy", dpa: "Verwerkersovereenkomst", subprocessors: "Subverwerkers" },
  },
  knowledge: {
    eyebrow: "Tracking Knowledge",
    title: "Leer hoe tracking echt werkt",
    text: "Gidsen over server-side tracking, deduplicatie en toestemming – geschreven door het team dat Track bouwt.",
    all: "Alle artikelen",
    minutes: "{n} min leestijd",
  },
  pricing: {
    eyebrow: "Prijzen",
    title: "Abonnementen die meegroeien met je eventvolume",
    text: "Elk abonnement bevat browser- en server-side tracking, alle standaard-destinations, Track AI en de Consent Engine. Maandelijkse facturering is de standaard; een jaar kost tien maandtermijnen.",
    perMonth: "per maand",
    events: "{n} geaccepteerde events per maand",
    sites: { one: "{n} productiewebsite", other: "{n} productiewebsites" },
    custom: "Op maat",
    customText: "Volume, contract en SLA op maat.",
    trial: "{days} dagen {plan} proberen, geen creditcard, geen automatische omzetting naar een betaald abonnement.",
    all: "Alle abonnementen vergelijken",
    taxNote: "Nettoprijzen in EUR; btw wordt toegevoegd waar van toepassing.",
    recommended: "Aanbevolen",
    enterprise: "Enterprise",
    enterpriseText: "Volumes, infrastructuur, governance en SLA op maat.",
    contact: "Praat met sales",
  },
  finalCta: {
    title: "Klaar voor geverifieerde events?",
    text: "Maak je site aan, plak de snippet en laat Track AI de rest begeleiden. Je hebt geen creditcard nodig om te starten.",
    cta: "Maak je site aan",
    secondary: "Plan een demo",
  },
  demo: DEMO_NL,
};
