export { LivingAICore } from "./living-ai-core";
export { AssistantAmbient } from "./assistant-ambient";
export { AiMotionControl } from "./motion-control";
export { createCoreStateMachine, resolveCoreState, CORE_STATE_PRIORITY, STATE_PARAMS } from "./state-machine";
export type { CoreParams, CoreSample, CoreSignals, CoreStateMachine } from "./state-machine";
export { selectTier, effectiveMotion, createFrameBudget, isConstrainedDevice, webglPermitted } from "./tier";
export type { DeviceHints } from "./tier";
export { scheduleWebglUpgrade, UPGRADE_MIN_ELAPSED_MS, UPGRADE_IDLE_TIMEOUT_MS } from "./upgrade-gate";
export { useAiMotionPreference, useReducedMotionPreference, readDeviceHints } from "./preference";
export { CORE_STATES, CORE_MOTIONS, isCoreState, isCoreMotion } from "./types";
export type { CoreMode, CoreMotion, CoreState, CoreTier, LivingAICoreProps } from "./types";
