import type { IntegrationsCopy } from "../types";

/**
 * German (de) copy of the integrations area. Same shape as en.ts; see docs/14-localization.md.
 */

export const INTEGRATIONS_COPY_DE: IntegrationsCopy = {
  eyebrow: "Integrationen",
  title: "Jede Plattform mit Browser-Tag, Server-API und gemeinsamer Deduplizierung",
  text: "Werbeplattformen, Analytics, Affiliate-Netzwerke, eigene Systeme und drei Shopsysteme — jeweils umgesetzt, dokumentiert und gegen den Anbieter-Vertrag getestet. Kein „Coming soon“.",
  cta: "Erste Plattform verbinden",
  ctaText: "Der Assistent führt durch Kennungen, Zugangsdaten, Mapping und einen verifizierten Testevent.",
  start: "Kostenlos starten",
  how: "So funktioniert es",
  breadcrumbs: { home: "Track", label: "Integrationen", nav: "Navigationspfad" },
  stats: {
    destinations: (n) => `${n} Destinationstypen`,
    presets: (n) => `${n} Affiliate-Postback-Presets`,
    shops: (n) => `${n} Shopsysteme`,
  },
  diagram: {
    title: "So erreichen Events eine Destination",
    description: "Browser-Events von der Website sowie Server- oder Offline-Events aus deinen Systemen kommen bei Track an, passieren das Consent- und Policy-Gate und werden an Werbeplattformen, Analytics und eigene Systeme zugestellt.",
    caption: "Ein Event, eine Consent-Entscheidung, eine Zustellung pro Destination. Browser- und Serverpfad teilen dieselbe Event-ID, damit Plattformen jede Conversion nur einmal zählen.",
    nodes: { website: "Website", websiteSub: "Browser-Tag", server: "Server · CRM", serverSub: "Server · Offline", track: "Track", trackSub: "Policy · Dedup", consent: "Consent", ads: "Werbeplattformen", analytics: "Analytics", own: "Eigene Systeme" },
  },
  explorer: {
    heading: "Plattform finden",
    searchLabel: "Integrationen durchsuchen",
    searchPlaceholder: "Nach Plattform, Produkt oder Click-ID suchen (z. B. Meta, GA4, gclid)",
    clear: "Suche löschen",
    resultsAll: "{total} Integrationen",
    resultsSome: "{shown} von {total} Integrationen",
    categoryFilter: "Nach Kategorie filtern",
    modeFilter: "Nach Zustellmodus filtern",
    allCategories: "Alle Kategorien",
    allModes: "Alle Modi",
    reset: "Filter zurücksetzen",
    emptyTitle: "Keine passende Integration",
    emptyText: "Versuche einen kürzeren Suchbegriff oder entferne einen Filter. Jede hier gelistete Plattform ist heute umgesetzt — eine Warteliste gibt es nicht.",
    resultsHeading: "Ergebnisse",
    details: "Details",
    presets: "{n} Netzwerk-Presets",
  },
  categories: { ads: "Ads", analytics: "Analytics", commerce: "Commerce", affiliate: "Affiliate", custom: "Eigene Systeme" },
  categoryText: {
    ads: "Pixel oder Tag im Browser plus Conversions-API des Anbieters auf dem Server, dedupliziert über eine gemeinsame Event-ID.",
    analytics: "Browser-Messung plus serverseitige Erfassung mit Validierung, bevor etwas gesendet wird.",
    commerce: "Shopsysteme liefern verifizierte Bestellungen und Erstattungen an Track; der Browser ergänzt Consent und Click-IDs.",
    affiliate: "Server-to-Server-Postbacks an Affiliate- und Performance-Netzwerke, attribuiert über die erfasste Click-ID.",
    custom: "Signierte JSON-Events an deine eigenen Endpunkte — CRM, Data Warehouse, interne Tools.",
  },
  kinds: { destination: "Destination", source: "Shop-Integration" },
  modes: { browser: "Browser", server: "Server", offline: "Offline" },
  modeText: {
    browser: "Das Track-Snippet lädt das Anbieter-Tag erst nach Consent für seinen Zweck. Im Template liegt kein Anbieter-Code.",
    server: "Der Worker stellt dasselbe Event über die API des Anbieters zu — mit Retries, Health-Checks und geschwärzter Payload-Vorschau pro Versuch.",
    offline: "Als offline markierte Server-Events (CRM-Abschlüsse, Ladenkäufe) erreichen Plattformen, deren API Non-Web-Action-Sources akzeptiert.",
  },
  modesSection: {
    title: "Drei Zustellmodi, ein Event",
    text: "Welche Modi eine Plattform unterstützt, entscheidet ihre API, nicht ein Tarif. Der Katalog zeigt genau, was jeder Connector umsetzt.",
    hybridTitle: "Hybrid als Standard",
    hybridText: "Unterstützt eine Plattform beide Wege, tragen Browser-Tag und Server-Request dieselbe Event-ID, Käufe zusätzlich die Bestellnummer. Der Anbieter dedupliziert, und Tracks eigener Schutz verwirft wiederholte Quell-Events vor der Zustellung.",
  },
  verification: {
    vendor_docs: "Umgesetzt · gegen die Anbieter-Dokumentation verifiziert",
    secondary_sources: "Umgesetzt · gegen Sekundärquellen verifiziert (Anbieter-Doku nur nach Login)",
    recorded_payloads: "Umgesetzt · mit signierten, aufgezeichneten Webhook-Payloads getestet",
  },
  verificationShort: { vendor_docs: "Umgesetzt", secondary_sources: "Umgesetzt (Sekundärquellen)", recorded_payloads: "Umgesetzt (aufgezeichnete Payloads)" },
  verifiedOn: (date) => `verifiziert am ${date}`,
  access: {
    open: "Keine Freigabe durch den Anbieter nötig",
    vendor_setup: "Einrichtung im Anbieter-Konto erforderlich",
    vendor_approval: "Freigabe durch den Anbieter erforderlich",
    vendor_beta: "Anbieter-API in Beta",
  },
  purposes: { necessary: "Notwendig", analytics: "Analytics", marketing: "Marketing" },
  credentialKinds: {
    access_token: "API-Zugangstoken",
    api_secret: "API-Secret",
    oauth_refresh_token: "OAuth-Verbindung",
    oauth_access_token: "OAuth-Verbindung",
    oauth_token_secret: "OAuth-Token-Secret",
    client_id: "API-Client-ID",
    client_secret: "API-Client-Secret",
    webhook_secret: "Webhook-Secret",
    signing_secret: "Signatur-Secret (von Track erzeugt)",
  },
  oauthProviders: { google: "Google", linkedin: "LinkedIn", amazon: "Amazon", x: "X" },
  optional: "optional",
  detail: {
    eyebrow: { destination: "Integration · Destination", source: "Integration · Shopsystem" },
    flow: {
      title: (name) => `So erreichen Events ${name}`,
      text: {
        destination: "Jeder Pfad endet an derselben Stelle: Die Policy-Engine prüft den Consent-Zweck, den diese Destination benötigt, entfernt, was nicht hinaus darf, und der Worker stellt mit der gemeinsamen Event-ID zu.",
        source: "Die Webhooks des Shops sind die verbindliche Quelle für Käufe und Erstattungen. Track prüft die Signatur, paart die Bestellung über die Bestellnummer mit dem Browser-Kauf und leitet erst dann weiter — Consent wird geerbt, nie angenommen.",
      },
      diagramTitle: (name) => `Datenfluss von Website und Systemen über Track zu ${name}`,
      caption: {
        destination: "Nur unterstützte Pfade. Nicht unterstützte Modi werden nicht gezeichnet — und nicht behauptet.",
        source: "Browser-Kauf und verifizierter Shop-Webhook werden über die Bestellnummer gepaart; der Shop-Datensatz erbt Consent und Click-IDs des Besuchers.",
      },
      nodes: {
        website: "Website",
        websiteSub: "Browser-Tag",
        server: "Dein Server",
        serverSub: "Server-API",
        offline: "CRM · Offline",
        offlineSub: "Offline-Conversions",
        shop: "Shop-Webhooks",
        shopSub: "Orders · Refunds",
        track: "Track",
        trackSub: "Policy · Dedup",
        trackPairing: "Pairing über Bestellnummer",
        consent: "Consent",
        destinations: "Destinationen",
      },
      edges: { browser: "Browser", server: "Server", offline: "Offline", shop: "signierter Webhook" },
    },
    modeDetail: {
      browser: "Browser-Tag — vom Track-Snippet nach Consent geladen; das Anbieter-Skript liegt nie im Template und wird ohne den nötigen Zweck nie geladen.",
      server: "Server-API — vom Worker zugestellt, mit Retries, Health-Checks, Fehlerklassifikation und geschwärzter Payload-Vorschau für jeden Versuch.",
      offline: "Offline-Conversions — als offline markierte Server-Events (CRM-Abschlüsse, Telefonbestellungen, Ladenkäufe) erreichen diese Plattform mit der Offline-Action-Source des Anbieters.",
    },
    sourceModes: {
      browser: "Browser — das Storefront-Script sendet Standard-Events mit Consent-Zustand und Click-IDs des Besuchers; der Kauf trägt die Bestellnummer für das Pairing.",
      server: "Server — die signierten Webhooks des Shops liefern bezahlte Bestellungen und Erstattungen mit Summen und Positionen; Track prüft jede Signatur, bevor ein Datensatz angenommen wird.",
    },
    hybrid: (field) => `Hybrid — Browser-Tag und Server-Request teilen eine Event-ID; die Plattform dedupliziert über ${field}.`,
    hybridNoField: "Hybrid — Browser-Tag und Server-Request teilen eine Event-ID; Conversions werden über die Bestellnummer zusammengeführt.",
    sends: {
      title: "Was gesendet wird",
      intro: "Nur, was du im Event-Mapping konfigurierst — und erst, nachdem die Policy-Engine das Event für diese Destination freigegeben hat.",
      event: "Eventname und Zeitstempel, von Tracks Standard-Events auf die Eventnamen der Plattform abgebildet.",
      eventId: (field) => `Die gemeinsame Event-ID im Feld ${field} der Plattform, damit Browser- und Serverzustellung nur einmal zählen.`,
      eventIdNoField: "Die gemeinsame Event-ID, damit Browser- und Serverzustellung zusammengeführt werden können.",
      clickIds: (ids) => `Click-IDs, die diese Plattform erhalten darf: ${ids}. Click-IDs anderer Anbieter werden nie weitergegeben.`,
      noClickIds: "Keine Anbieter-Click-IDs — diese Destination ist dein eigenes System, die Attribution bleibt bei dir.",
      order: "Bestellnummer, Wert, Währung und Positionen bei Kauf-Events.",
      hashed: "SHA-256-gehashte Kennungen (E-Mail, Telefon, externe ID) für das Matching — nur mit dem nötigen Consent und nur, wenn erfasst.",
      noHashed: "Keine gehashten Kennungen — diese Plattform attribuiert allein über ihre Click-ID.",
      consent: "Der Consent-Zustand, unter dem das Event erfasst wurde, sofern die Plattform Consent-Signale annimmt.",
      neverTitle: "Nie gesendet",
      never: ["E-Mail-Adressen, Telefonnummern oder Namen im Klartext — Kennungen werden beim Ingest gehasht.", "Abgeleitete Werte: Unbekannt bleibt unbekannt, nichts wird geraten.", "Events, die ohne den von dieser Destination benötigten Zweck erfasst wurden.", "Geheimnisse: Tokens liegen im verschlüsselten Tresor und erreichen nie Browser, Assistent oder Log."],
    },
    receives: {
      title: "Was Track empfängt",
      intro: "Zwei sich ergänzende Pfade, im Ingest über die Bestellnummer gepaart.",
      items: ["Bezahlte Bestellungen und Erstattungen aus den signierten Webhooks des Shops: Bestellnummer, Summen, Währung, Positionen und die Matching-Daten des Kunden — beim Ingest gehasht.", "Standard-Browser-Events aus dem Storefront (Ansicht, In den Warenkorb, Checkout, Kauf) mit Consent-Datensatz und erfassten Click-IDs des Besuchers.", "Die Bestellnummer auf beiden Pfaden, damit der verifizierte Shop-Datensatz den Browser-Kauf ohne Doppelzählung ersetzt."],
      neverTitle: "Nie angenommen",
      never: ["Marketing-Consent: Ein Shop-Webhook trägt keinen eigenen Consent. Ohne gepaarten Browser-Kauf bleibt der Datensatz operativ und erreicht nur Destinationen, die keinen Consent benötigen.", "Kundendaten im Klartext in Werbeplattformen — Matching-Daten werden vor dem Speichern gehasht.", "Unsignierte oder nicht prüfbare Webhooks — eine fehlgeschlagene Signaturprüfung wird protokolliert und verworfen."],
    },
    facts: {
      title: "Technische Fakten",
      dedup: "Deduplizierungsfeld",
      pairing: "Pairing-Schlüssel",
      clickIds: "Click-IDs",
      purpose: "Consent-Zweck",
      apiVersion: "Gepinnte API-Version",
      verified: "Verifizierung",
      status: "Umsetzungsstatus",
      docs: "Anbieter-Dokumentation",
      docsLink: (name) => `API-Dokumentation von ${name}`,
      ownDocs: "Track-Dokumentation",
      none: "keine",
      presets: "Netzwerk-Presets",
    },
    ids: {
      title: "Was du brauchst",
      intro: "Öffentliche Kennungen kannst du im Chat oder Assistenten eingeben; Geheimnisse gehen über die sichere Zugangsdaten-Karte oder OAuth und werden verschlüsselt gespeichert.",
      publicIds: "Öffentliche Kennungen",
      credentials: "Zugangsdaten",
      vault: "im verschlüsselten Tresor gespeichert",
      noCredentials: "Keine Zugangsdaten — diese Plattform nimmt Server-Events allein mit den öffentlichen Kennungen an.",
      key: "Schlüssel",
      label: "Beschreibung",
    },
    prerequisites: "Voraussetzung beim Anbieter",
    consent: {
      title: "Consent",
      text: {
        marketing: "Benötigt den Zweck Marketing. Ohne ihn wird im Browser nichts geladen und vom Server nichts gesendet. Abgeleiteter Consent wird nie exportiert, und Global-Privacy-Control-Opt-outs blockieren die Zustellung.",
        analytics: "Benötigt den Zweck Analytics. Ohne ihn wird im Browser nichts geladen und vom Server nichts gesendet. Abgeleiteter Consent wird nie exportiert.",
        necessary: "Läuft unter dem Zweck Notwendig, weil das Ziel deine eigenen Systeme sind (Verarbeitung auf Verantwortlichenseite). Kennungen werden trotzdem ohne Analytics-Consent entfernt, Click-IDs ohne Marketing-Consent.",
      },
      source: "Shop-Webhooks tragen keinen eigenen Consent. Eine verifizierte Bestellung erbt den Consent-Datensatz des gepaarten Browser-Kaufs; ohne ihn wird sie als operativer Datensatz gespeichert und erreicht nie eine Werbeplattform.",
    },
    setup: {
      title: "Einrichtung in wenigen Schritten",
      intro: "Die detaillierten Prüfungen übernimmt der Assistent. Du siehst die Meilensteine, die eine Entscheidung von dir brauchen.",
      destination: [
        { title: "Kennungen eingeben", text: "Die öffentlichen IDs der Plattform hinzufügen. Formate werden gegen die Anbieter-Dokumentation validiert, bevor etwas gespeichert wird." },
        { title: "Zugangsdaten verbinden", text: "Token in die sichere Karte einfügen oder das Konto per OAuth verbinden. Geheimnisse wandern direkt in den verschlüsselten Tresor." },
        { title: "Mappen und testen", text: "Standard-Events sind auf die Eventnamen der Plattform vorgemappt. Ein markierter Testevent läuft durch die echte Pipeline und zeigt die Antwort des Anbieters." },
        { title: "Veröffentlichen", text: "Diff prüfen, freigeben, signierte Konfigurationsversion veröffentlichen. Bei Bedarf Rollback per Klick." },
      ],
      source: [
        { title: "Shop verbinden", text: "Shop-Domain und Fallback-Währung eingeben. Track erzeugt Webhook-URL und Secret — einmalig sichtbar." },
        { title: "Shop-Seite installieren", text: "Pixel-Extension, Plugin oder App installieren und die Webhooks mit dem erzeugten Secret registrieren." },
        { title: "Mit Testbestellung prüfen", text: "Der erste signierte Webhook schaltet die Verbindung auf verbunden; beobachtete Topics und letzter Webhook werden live angezeigt." },
      ],
    },
    knowledge: {
      title: "Aus Tracking Knowledge",
      text: "Leitfäden vom Team, das diesen Connector baut.",
      all: "Alle Tracking-Knowledge-Artikel",
      none: "Noch kein eigener Artikel — der Tracking-Knowledge-Hub behandelt Server-Side Tracking, Deduplizierung und Consent allgemein.",
      minutes: (n) => `${n} Min. Lesezeit`,
    },
    faq: {
      title: "Fragen",
      destination: [
        { q: "Kann ich nur serverseitig senden?", a: "Ja. Wähle im Assistenten den Servermodus; das Anbieter-Skript wird nie geladen und das Matching stützt sich auf gehashte Kennungen und vom Tracker erfasste Click-IDs." },
        { q: "Wie werden Duplikate vermieden?", a: "Browser-Tag und Server-Request tragen dieselbe Event-ID, Käufe zusätzlich die Bestellnummer. Der Worker dedupliziert wiederholte Quell-Events zudem vor der Zustellung." },
        { q: "Was, wenn sich die Anbieter-API ändert?", a: "API-Versionen sind zentral mit Prüfdatum gepinnt; Sunset-Warnungen erscheinen im Destination-Zustand lange bevor ein Endpunkt abgeschaltet wird." },
      ],
      source: [
        { q: "Brauche ich den Browser-Kauf trotzdem?", a: "Er ist optional, aber wertvoll: Er trägt Consent-Datensatz und Click-IDs des Besuchers, die der Server nicht kennen kann. Der verifizierte Shop-Datensatz ersetzt ihn bei Wert und Positionen." },
        { q: "Wird dieselbe Bestellung doppelt gezählt?", a: "Nein. Browser-Kauf, Server-API und Shop-Webhook teilen die aus der Bestellnummer abgeleitete Event-ID, und der Conversion-Datensatz hält eine Zeile pro Bestellung." },
        { q: "Was passiert, wenn die Plattform einen Webhook erneut sendet?", a: "Wiederholte Zustellungen erzeugen deterministische Event-IDs und laufen in den Dedup-Schutz auf Eventebene; nichts wird erneut gezählt." },
      ],
    },
    cta: {
      title: (name) => `${name} verbinden`,
      text: "Mit dem geführten Assistenten einrichten oder den Chat-Assistenten machen lassen.",
      start: "Kostenlos starten",
      all: "Alle Integrationen",
    },
  },
};
