import type { IntegrationsCopy } from "../types";

/**
 * English (source language) copy of the integrations area. Same shape as every other locale file; see docs/14-localization.md.
 */

export const INTEGRATIONS_COPY_EN: IntegrationsCopy = {
  eyebrow: "Integrations",
  title: "Every platform with browser tag, server API and shared deduplication",
  text: "Advertising platforms, analytics, affiliate networks, your own systems and three shop platforms — each implemented, documented and tested against the vendor contract. No “coming soon”.",
  cta: "Connect your first platform",
  ctaText: "The assistant walks through identifiers, credentials, mapping and a verified test event.",
  start: "Start free",
  how: "How it works",
  breadcrumbs: { home: "Track", label: "Integrations", nav: "Breadcrumb" },
  stats: {
    destinations: (n) => `${n} destination types`,
    presets: (n) => `${n} affiliate postback presets`,
    shops: (n) => `${n} shop platforms`,
  },
  diagram: {
    title: "How events reach a destination",
    description: "Browser events from the website and server or offline events from your systems arrive at Track, pass the consent and policy gate and are delivered to advertising platforms, analytics and your own systems.",
    caption: "One event, one consent decision, one delivery per destination. Browser and server paths share the same event id, so platforms count each conversion once.",
    nodes: { website: "Website", websiteSub: "browser tag", server: "Server · CRM", serverSub: "server · offline", track: "Track", trackSub: "policy · dedup", consent: "Consent", ads: "Ad platforms", analytics: "Analytics", own: "Own systems" },
  },
  explorer: {
    heading: "Find your platform",
    searchLabel: "Search integrations",
    searchPlaceholder: "Search by platform, product or click id (e.g. Meta, GA4, gclid)",
    clear: "Clear search",
    resultsAll: "{total} integrations",
    resultsSome: "{shown} of {total} integrations",
    categoryFilter: "Filter by category",
    modeFilter: "Filter by delivery mode",
    allCategories: "All categories",
    allModes: "All modes",
    reset: "Reset filters",
    emptyTitle: "No integration matches",
    emptyText: "Try a shorter search term or remove a filter. Every platform listed here is implemented today — there is no waiting list to search for.",
    resultsHeading: "Results",
    details: "Details",
    presets: "{n} network presets",
  },
  categories: { ads: "Ads", analytics: "Analytics", commerce: "Commerce", affiliate: "Affiliate", custom: "Own systems" },
  categoryText: {
    ads: "Pixel or tag in the browser plus the vendor's conversions API on the server, deduplicated on a shared event id.",
    analytics: "Browser measurement plus server-side collection with validation before anything is sent.",
    commerce: "Shop platforms deliver verified orders and refunds to Track; the browser adds consent and click ids.",
    affiliate: "Server-to-server postbacks to affiliate and performance networks, attributed by the captured click id.",
    custom: "Signed JSON events to your own endpoints — CRM, data warehouse, internal tools.",
  },
  kinds: { destination: "Destination", source: "Shop integration" },
  modes: { browser: "Browser", server: "Server", offline: "Offline" },
  modeText: {
    browser: "The Track snippet loads the vendor tag only after consent for its purpose. No vendor code lives in your template.",
    server: "The worker delivers the same event through the vendor's API — with retries, health checks and a redacted payload preview per attempt.",
    offline: "Server events flagged as offline (CRM deals, store purchases) reach platforms whose API accepts non-web action sources.",
  },
  modesSection: {
    title: "Three delivery modes, one event",
    text: "Which modes a platform supports is decided by its API, not by a plan. The catalogue below shows exactly what each connector implements.",
    hybridTitle: "Hybrid by default",
    hybridText: "When a platform supports both paths, browser tag and server request carry the same event id and purchases add the order id. The vendor deduplicates, and Track's own guard drops repeated source events before delivery.",
  },
  verification: {
    vendor_docs: "Implemented · verified against the vendor documentation",
    secondary_sources: "Implemented · verified against secondary references (vendor docs behind a login)",
    recorded_payloads: "Implemented · tested with signed, recorded webhook payloads",
  },
  verificationShort: { vendor_docs: "Implemented", secondary_sources: "Implemented (secondary sources)", recorded_payloads: "Implemented (recorded payloads)" },
  verifiedOn: (date) => `verified ${date}`,
  access: {
    open: "No vendor approval needed",
    vendor_setup: "Requires setup in the vendor account",
    vendor_approval: "Requires vendor approval",
    vendor_beta: "Vendor API in beta",
  },
  purposes: { necessary: "Necessary", analytics: "Analytics", marketing: "Marketing" },
  credentialKinds: {
    access_token: "API access token",
    api_secret: "API secret",
    oauth_refresh_token: "OAuth connection",
    oauth_access_token: "OAuth connection",
    oauth_token_secret: "OAuth token secret",
    client_id: "API client ID",
    client_secret: "API client secret",
    webhook_secret: "Webhook secret",
    signing_secret: "Signing secret (generated by Track)",
  },
  oauthProviders: { google: "Google", linkedin: "LinkedIn", amazon: "Amazon", x: "X" },
  optional: "optional",
  detail: {
    eyebrow: { destination: "Integration · destination", source: "Integration · shop platform" },
    flow: {
      title: (name) => `How events reach ${name}`,
      text: {
        destination: "Every path ends in the same place: the policy engine checks the consent purpose this destination requires, strips what may not leave, and the worker delivers with the shared event id.",
        source: "The shop's own webhooks are the authoritative source for purchases and refunds. Track verifies the signature, pairs the order with the browser purchase by order id and only then routes it on — consent is inherited, never assumed.",
      },
      diagramTitle: (name) => `Data flow from your website and systems through Track to ${name}`,
      caption: {
        destination: "Supported paths only. Unsupported modes are not drawn — and not claimed.",
        source: "Browser purchase and verified shop webhook are paired by order id; the shop record inherits the visitor's consent and click ids.",
      },
      nodes: {
        website: "Website",
        websiteSub: "browser tag",
        server: "Your server",
        serverSub: "server API",
        offline: "CRM · offline",
        offlineSub: "offline conversions",
        shop: "Shop webhooks",
        shopSub: "orders · refunds",
        track: "Track",
        trackSub: "policy · dedup",
        trackPairing: "pairing by order id",
        consent: "Consent",
        destinations: "Destinations",
      },
      edges: { browser: "browser", server: "server", offline: "offline", shop: "signed webhook" },
    },
    modeDetail: {
      browser: "Browser tag — loaded by the Track snippet after consent; the vendor script never sits in your template and is never loaded without the required purpose.",
      server: "Server API — delivered by the worker with retries, health checks, error classification and a redacted payload preview for every attempt.",
      offline: "Offline conversions — server events flagged as offline (CRM deals, phone orders, store purchases) reach this platform with the vendor's offline action source.",
    },
    sourceModes: {
      browser: "Browser — the storefront script sends standard events with the visitor's consent state and click ids; the purchase carries the order id for pairing.",
      server: "Server — the shop's signed webhooks deliver paid orders and refunds with totals and line items; Track verifies every signature before accepting a record.",
    },
    hybrid: (field) => `Hybrid — browser tag and server request share one event id; the platform deduplicates on ${field}.`,
    hybridNoField: "Hybrid — browser tag and server request share one event id; conversions are matched on the order id.",
    sends: {
      title: "What is sent",
      intro: "Only what you configure in the event mapping, and only after the policy engine has allowed the event for this destination.",
      event: "Event name and timestamp, mapped from Track's standard events to the platform's event names.",
      eventId: (field) => `The shared event id in the platform's ${field} field, so browser and server deliveries count once.`,
      eventIdNoField: "The shared event id, so browser and server deliveries can be matched.",
      clickIds: (ids) => `Click ids this platform may receive: ${ids}. Other vendors' click ids are never forwarded.`,
      noClickIds: "No vendor click ids — this destination is your own system, so attribution stays with you.",
      order: "Order id, value, currency and items for purchase-type events.",
      hashed: "SHA-256-hashed identifiers (e-mail, phone, external id) for matching — only with the required consent and only if captured.",
      noHashed: "No hashed identifiers — this platform attributes on its click id alone.",
      consent: "The consent state the event was collected under, where the platform accepts consent signals.",
      neverTitle: "Never sent",
      never: ["Raw e-mail addresses, phone numbers or names — identifiers are hashed on ingest.", "Inferred values: unknown stays unknown, nothing is guessed.", "Events collected without the purpose this destination requires.", "Secrets: tokens live in the encrypted vault and never reach the browser, the assistant or a log."],
    },
    receives: {
      title: "What Track receives",
      intro: "Two complementary paths, paired by order id in the ingest stage.",
      items: ["Paid orders and refunds from the shop's signed webhooks: order id, totals, currency, line items and the customer's matching data — hashed on ingest.", "Standard browser events from the storefront (view, add to cart, checkout, purchase) with the visitor's consent record and captured click ids.", "The order id on both paths, so the verified shop record supersedes the browser purchase without double counting."],
      neverTitle: "Never assumed",
      never: ["Marketing consent: a shop webhook carries no consent of its own. Without a paired browser purchase the record stays an operational record and reaches only destinations that need no consent.", "Raw customer data in ad platforms — matching data is hashed before it is stored.", "Unsigned or unverifiable webhooks — a failed signature check is recorded and dropped."],
    },
    facts: {
      title: "Technical facts",
      dedup: "Deduplication field",
      pairing: "Pairing key",
      clickIds: "Click ids",
      purpose: "Consent purpose",
      apiVersion: "Pinned API version",
      verified: "Verification",
      status: "Implementation status",
      docs: "Vendor documentation",
      docsLink: (name) => `${name} API documentation`,
      ownDocs: "Track documentation",
      none: "none",
      presets: "Network presets",
    },
    ids: {
      title: "What you need",
      intro: "Public identifiers can be typed in chat or the wizard; secrets go through the secure credential card or OAuth and are stored encrypted.",
      publicIds: "Public identifiers",
      credentials: "Credentials",
      vault: "stored in the encrypted vault",
      noCredentials: "No credentials — this platform accepts server events with the public identifiers alone.",
      key: "Key",
      label: "Description",
    },
    prerequisites: "Vendor prerequisite",
    consent: {
      title: "Consent",
      text: {
        marketing: "Requires the marketing purpose. Without it nothing is loaded in the browser and nothing is sent from the server. Inferred consent is never exported, and Global Privacy Control opt-outs block delivery.",
        analytics: "Requires the analytics purpose. Without it nothing is loaded in the browser and nothing is sent from the server. Inferred consent is never exported.",
        necessary: "Runs under the necessary purpose because it targets your own systems (controller-side processing). Identifiers are still stripped without analytics consent and click ids without marketing consent.",
      },
      source: "Shop webhooks carry no consent of their own. A verified order inherits the consent record of the paired browser purchase; without one it is stored as an operational record and never reaches an advertising platform.",
    },
    setup: {
      title: "Setup in a few steps",
      intro: "The assistant runs the detailed checks. You see the milestones that need a decision from you.",
      destination: [
        { title: "Enter identifiers", text: "Add the public IDs from the platform. Formats are validated against the vendor's documentation before anything is saved." },
        { title: "Connect credentials", text: "Paste the token into the secure card or connect the account via OAuth. Secrets go straight into the encrypted vault." },
        { title: "Map and test", text: "Standard events are pre-mapped to the platform's event names. A flagged test event runs through the real pipeline and shows the vendor's answer." },
        { title: "Publish", text: "Review the diff, approve, publish a signed configuration version. Roll back with one click if needed." },
      ],
      source: [
        { title: "Connect the shop", text: "Enter the shop domain and fallback currency. Track generates the webhook URL and the secret once." },
        { title: "Install the shop side", text: "Install the pixel extension, plugin or app and register the webhooks with the generated secret." },
        { title: "Verify with a test order", text: "The first signed webhook flips the connection to connected; the observed topics and the last webhook are shown live." },
      ],
    },
    knowledge: {
      title: "From Tracking Knowledge",
      text: "Guides written by the team that builds this connector.",
      all: "All Tracking Knowledge articles",
      none: "No dedicated article yet — the Tracking Knowledge hub covers server-side tracking, deduplication and consent in general.",
      minutes: (n) => `${n} min read`,
    },
    faq: {
      title: "Questions",
      destination: [
        { q: "Can I run server-only?", a: "Yes. Choose server mode in the wizard; the vendor script is never loaded and matching relies on hashed identifiers and click ids captured by the tracker." },
        { q: "How are duplicates avoided?", a: "The browser tag and the server request carry the same event id, and purchases add the order id. The worker also deduplicates repeated source events before delivery." },
        { q: "What if the vendor API changes?", a: "API versions are pinned centrally with the verification date; sunset warnings appear in the destination health long before an endpoint is retired." },
      ],
      source: [
        { q: "Do I still need the browser purchase?", a: "It is optional but valuable: it carries the visitor's consent record and click ids, which the server cannot know. The verified shop record supersedes it for value and items." },
        { q: "Is the same order counted twice?", a: "No. Browser purchase, server API and shop webhook share the order-derived event id, and the conversion record keeps one row per order." },
        { q: "What happens if a webhook is retried by the platform?", a: "Redeliveries produce deterministic event ids and hit the event-level dedup guard; nothing is counted again." },
      ],
    },
    cta: {
      title: (name) => `Connect ${name}`,
      text: "Set it up with the guided wizard or let the assistant do it in chat.",
      start: "Start free",
      all: "All integrations",
    },
  },
};
