import type { IntegrationsCopy } from "../types";

/**
 * Spanish (es, Spain) copy of the integrations area. Same shape as en.ts; see docs/14-localization.md.
 * Register: tú (tuteo). Product, platform and API names stay in English; "destination" is "destino".
 */

export const INTEGRATIONS_COPY_ES: IntegrationsCopy = {
  eyebrow: "Integraciones",
  title: "Todas las plataformas con etiqueta de navegador, API de servidor y deduplicación compartida",
  text: "Plataformas publicitarias, analítica, redes de afiliación, tus propios sistemas y tres plataformas de e-commerce: cada una implementada, documentada y probada contra el contrato de API del proveedor. Nada de «próximamente».",
  cta: "Conecta tu primera plataforma",
  ctaText: "El asistente te guía por los identificadores, las credenciales, el mapeo y un evento de prueba verificado.",
  start: "Empieza gratis",
  how: "Cómo funciona",
  breadcrumbs: { home: "Track", label: "Integraciones", nav: "Ruta de navegación" },
  stats: {
    destinations: (n) => `${n} tipos de destino`,
    presets: (n) => `${n} presets de postback de afiliación`,
    shops: (n) => `${n} plataformas de e-commerce`,
  },
  diagram: {
    title: "Cómo llegan los eventos a un destino",
    description: "Los eventos de navegador del sitio web y los eventos de servidor u offline de tus sistemas llegan a Track, pasan el control de consentimiento y de políticas y se entregan a las plataformas publicitarias, a la analítica y a tus propios sistemas.",
    caption: "Un evento, una decisión de consentimiento, una entrega por destino. Las rutas de navegador y de servidor comparten el mismo ID de evento, de modo que las plataformas cuentan cada conversión una sola vez.",
    nodes: { website: "Sitio web", websiteSub: "etiqueta de navegador", server: "Servidor · CRM", serverSub: "servidor · offline", track: "Track", trackSub: "políticas · dedup", consent: "Consentimiento", ads: "Plataformas publicitarias", analytics: "Analítica", own: "Sistemas propios" },
  },
  explorer: {
    heading: "Encuentra tu plataforma",
    searchLabel: "Buscar integraciones",
    searchPlaceholder: "Busca por plataforma, producto o ID de clic (p. ej. Meta, GA4, gclid)",
    clear: "Borrar búsqueda",
    resultsAll: "{total} integraciones",
    resultsSome: "{shown} de {total} integraciones",
    categoryFilter: "Filtrar por categoría",
    modeFilter: "Filtrar por modo de entrega",
    allCategories: "Todas las categorías",
    allModes: "Todos los modos",
    reset: "Restablecer filtros",
    emptyTitle: "Ninguna integración coincide",
    emptyText: "Prueba con un término más corto o quita un filtro. Todas las plataformas de esta lista están implementadas hoy: no hay ninguna lista de espera en la que buscar.",
    resultsHeading: "Resultados",
    details: "Detalles",
    presets: "{n} presets de red",
  },
  categories: { ads: "Publicidad", analytics: "Analítica", commerce: "E-commerce", affiliate: "Afiliación", custom: "Sistemas propios" },
  categoryText: {
    ads: "Píxel o etiqueta en el navegador más la API de conversiones del proveedor en el servidor, deduplicados con un ID de evento compartido.",
    analytics: "Medición en el navegador más recogida server-side, con validación antes de enviar nada.",
    commerce: "Las plataformas de e-commerce entregan a Track pedidos y reembolsos verificados; el navegador añade el consentimiento y los IDs de clic.",
    affiliate: "Postbacks de servidor a servidor hacia redes de afiliación y de performance, atribuidos por el ID de clic capturado.",
    custom: "Eventos JSON firmados hacia tus propios endpoints: CRM, data warehouse, herramientas internas.",
  },
  kinds: { destination: "Destino", source: "Integración de tienda" },
  modes: { browser: "Navegador", server: "Servidor", offline: "Offline" },
  modeText: {
    browser: "El snippet de Track carga la etiqueta del proveedor solo tras el consentimiento para su finalidad. Ningún código del proveedor vive en tu plantilla.",
    server: "El worker entrega el mismo evento a través de la API del proveedor, con reintentos, comprobaciones de salud y una vista previa del payload con los secretos ocultos por cada intento.",
    offline: "Los eventos de servidor marcados como offline (oportunidades de CRM, compras en tienda física) llegan a las plataformas cuya API acepta fuentes de acción no web.",
  },
  modesSection: {
    title: "Tres modos de entrega, un solo evento",
    text: "Qué modos admite una plataforma lo decide su API, no un plan. El catálogo de abajo muestra exactamente lo que implementa cada conector.",
    hybridTitle: "Híbrido por defecto",
    hybridText: "Cuando una plataforma admite ambas rutas, la etiqueta de navegador y la petición de servidor llevan el mismo ID de evento y las compras añaden el ID de pedido. El proveedor deduplica, y la propia protección de Track descarta los eventos de origen repetidos antes de la entrega.",
  },
  verification: {
    vendor_docs: "Implementada · verificada contra la documentación del proveedor",
    secondary_sources: "Implementada · verificada contra referencias secundarias (documentación del proveedor accesible solo con inicio de sesión)",
    recorded_payloads: "Implementada · probada con payloads de webhook firmados y grabados",
  },
  verificationShort: { vendor_docs: "Implementada", secondary_sources: "Implementada (fuentes secundarias)", recorded_payloads: "Implementada (payloads grabados)" },
  verifiedOn: (date) => `verificada el ${date}`,
  access: {
    open: "No requiere aprobación del proveedor",
    vendor_setup: "Requiere configuración en la cuenta del proveedor",
    vendor_approval: "Requiere aprobación del proveedor",
    vendor_beta: "API del proveedor en beta",
  },
  purposes: { necessary: "Necesaria", analytics: "Analítica", marketing: "Marketing" },
  credentialKinds: {
    access_token: "Token de acceso a la API",
    api_secret: "Secreto de la API",
    oauth_refresh_token: "Conexión OAuth",
    oauth_access_token: "Conexión OAuth",
    oauth_token_secret: "Secreto del token OAuth",
    client_id: "ID de cliente de la API",
    client_secret: "Secreto de cliente de la API",
    webhook_secret: "Secreto del webhook",
    signing_secret: "Secreto de firma (generado por Track)",
  },
  oauthProviders: { google: "Google", linkedin: "LinkedIn", amazon: "Amazon", x: "X" },
  optional: "opcional",
  detail: {
    eyebrow: { destination: "Integración · destino", source: "Integración · plataforma de e-commerce" },
    flow: {
      title: (name) => `Cómo llegan los eventos a ${name}`,
      text: {
        destination: "Todas las rutas terminan en el mismo sitio: el motor de políticas comprueba la finalidad de consentimiento que exige este destino, elimina lo que no puede salir y el worker entrega con el ID de evento compartido.",
        source: "Los webhooks de la propia tienda son la fuente autorizada para compras y reembolsos. Track verifica la firma, empareja el pedido con la compra del navegador por ID de pedido y solo entonces lo enruta; el consentimiento se hereda, nunca se presupone.",
      },
      diagramTitle: (name) => `Flujo de datos desde tu sitio web y tus sistemas, a través de Track, hasta ${name}`,
      caption: {
        destination: "Solo rutas admitidas. Los modos no admitidos no se dibujan, ni se prometen.",
        source: "La compra del navegador y el webhook verificado de la tienda se emparejan por ID de pedido; el registro de la tienda hereda el consentimiento y los IDs de clic del visitante.",
      },
      nodes: {
        website: "Sitio web",
        websiteSub: "etiqueta de navegador",
        server: "Tu servidor",
        serverSub: "API de servidor",
        offline: "CRM · offline",
        offlineSub: "conversiones offline",
        shop: "Webhooks de la tienda",
        shopSub: "pedidos · reembolsos",
        track: "Track",
        trackSub: "políticas · dedup",
        trackPairing: "emparejamiento por ID de pedido",
        consent: "Consentimiento",
        destinations: "Destinos",
      },
      edges: { browser: "navegador", server: "servidor", offline: "offline", shop: "webhook firmado" },
    },
    modeDetail: {
      browser: "Etiqueta de navegador: la carga el snippet de Track tras el consentimiento; el script del proveedor nunca está en tu plantilla y nunca se carga sin la finalidad requerida.",
      server: "API de servidor: el worker entrega con reintentos, comprobaciones de salud, clasificación de errores y una vista previa del payload con los secretos ocultos en cada intento.",
      offline: "Conversiones offline: los eventos de servidor marcados como offline (oportunidades de CRM, pedidos telefónicos, compras en tienda física) llegan a esta plataforma con la fuente de acción offline del proveedor.",
    },
    sourceModes: {
      browser: "Navegador: el script de la tienda envía los eventos estándar con el estado del consentimiento y los IDs de clic del visitante; la compra lleva el ID de pedido para el emparejamiento.",
      server: "Servidor: los webhooks firmados de la tienda entregan los pedidos pagados y los reembolsos con importes y líneas de pedido; Track verifica cada firma antes de aceptar un registro.",
    },
    hybrid: (field) => `Híbrido: la etiqueta de navegador y la petición de servidor comparten un ID de evento; la plataforma deduplica por ${field}.`,
    hybridNoField: "Híbrido: la etiqueta de navegador y la petición de servidor comparten un ID de evento; las conversiones se emparejan por ID de pedido.",
    sends: {
      title: "Qué se envía",
      intro: "Solo lo que configures en el mapeo de eventos, y solo después de que el motor de políticas haya autorizado el evento para este destino.",
      event: "Nombre del evento y marca de tiempo, mapeados desde los eventos estándar de Track a los nombres de evento de la plataforma.",
      eventId: (field) => `El ID de evento compartido en el campo ${field} de la plataforma, para que las entregas de navegador y de servidor cuenten una sola vez.`,
      eventIdNoField: "El ID de evento compartido, para que las entregas de navegador y de servidor puedan emparejarse.",
      clickIds: (ids) => `IDs de clic que puede recibir esta plataforma: ${ids}. Los IDs de clic de otros proveedores nunca se reenvían.`,
      noClickIds: "Sin IDs de clic de proveedores: este destino es tu propio sistema, así que la atribución se queda contigo.",
      order: "ID de pedido, valor, moneda y artículos en los eventos de tipo compra.",
      hashed: "Identificadores con hash SHA-256 (correo electrónico, teléfono, ID externo) para el matching, solo con el consentimiento requerido y solo si se han capturado.",
      noHashed: "Sin identificadores con hash: esta plataforma atribuye únicamente por su ID de clic.",
      consent: "El estado del consentimiento con el que se recogió el evento, cuando la plataforma acepta señales de consentimiento.",
      neverTitle: "Nunca se envía",
      never: ["Correos electrónicos, teléfonos o nombres en claro: los identificadores se convierten en hash en la ingesta.", "Valores inferidos: lo desconocido sigue siendo desconocido, no se adivina nada.", "Eventos recogidos sin la finalidad que exige este destino.", "Secretos: los tokens viven en el almacén cifrado y nunca llegan al navegador, al asistente ni a un log."],
    },
    receives: {
      title: "Qué recibe Track",
      intro: "Dos rutas complementarias, emparejadas por ID de pedido en la fase de ingesta.",
      items: ["Pedidos pagados y reembolsos desde los webhooks firmados de la tienda: ID de pedido, importes, moneda, líneas de pedido y los datos de matching del cliente, convertidos en hash en la ingesta.", "Eventos estándar de navegador desde la tienda (vista, añadir al carrito, checkout, compra) con el registro de consentimiento del visitante y los IDs de clic capturados.", "El ID de pedido en ambas rutas, de modo que el registro verificado de la tienda sustituye a la compra del navegador sin contar dos veces."],
      neverTitle: "Nunca se presupone",
      never: ["El consentimiento de marketing: un webhook de tienda no lleva consentimiento propio. Sin una compra de navegador emparejada, el registro se queda como registro operativo y solo llega a destinos que no necesitan consentimiento.", "Datos de clientes en claro en plataformas publicitarias: los datos de matching se convierten en hash antes de almacenarse.", "Webhooks sin firma o no verificables: una comprobación de firma fallida se registra y se descarta."],
    },
    facts: {
      title: "Datos técnicos",
      dedup: "Campo de deduplicación",
      pairing: "Clave de emparejamiento",
      clickIds: "IDs de clic",
      purpose: "Finalidad del consentimiento",
      apiVersion: "Versión de API fijada",
      verified: "Verificación",
      status: "Estado de implementación",
      docs: "Documentación del proveedor",
      docsLink: (name) => `Documentación de la API de ${name}`,
      ownDocs: "Documentación de Track",
      none: "ninguno",
      presets: "Presets de red",
    },
    ids: {
      title: "Qué necesitas",
      intro: "Los identificadores públicos se pueden escribir en el chat o en el asistente paso a paso; los secretos pasan por la tarjeta segura de credenciales o por OAuth y se guardan cifrados.",
      publicIds: "Identificadores públicos",
      credentials: "Credenciales",
      vault: "guardado en el almacén cifrado",
      noCredentials: "Sin credenciales: esta plataforma acepta eventos de servidor solo con los identificadores públicos.",
      key: "Clave",
      label: "Descripción",
    },
    prerequisites: "Requisito previo del proveedor",
    consent: {
      title: "Consentimiento",
      text: {
        marketing: "Requiere la finalidad de marketing. Sin ella no se carga nada en el navegador ni se envía nada desde el servidor. El consentimiento inferido nunca se exporta, y las señales de exclusión de Global Privacy Control bloquean la entrega.",
        analytics: "Requiere la finalidad de analítica. Sin ella no se carga nada en el navegador ni se envía nada desde el servidor. El consentimiento inferido nunca se exporta.",
        necessary: "Funciona bajo la finalidad necesaria porque apunta a tus propios sistemas (tratamiento del lado del responsable). Aun así, sin consentimiento de analítica se eliminan los identificadores y, sin consentimiento de marketing, los IDs de clic.",
      },
      source: "Los webhooks de tienda no llevan consentimiento propio. Un pedido verificado hereda el registro de consentimiento de la compra de navegador emparejada; sin ella se guarda como registro operativo y nunca llega a una plataforma publicitaria.",
    },
    setup: {
      title: "Configuración en pocos pasos",
      intro: "El asistente ejecuta las comprobaciones detalladas. Tú ves los hitos que necesitan una decisión tuya.",
      destination: [
        { title: "Introduce los identificadores", text: "Añade los IDs públicos de la plataforma. Los formatos se validan contra la documentación del proveedor antes de guardar nada." },
        { title: "Conecta las credenciales", text: "Pega el token en la tarjeta segura o conecta la cuenta mediante OAuth. Los secretos van directamente al almacén cifrado." },
        { title: "Mapea y prueba", text: "Los eventos estándar vienen premapeados a los nombres de evento de la plataforma. Un evento de prueba marcado recorre el pipeline real y muestra la respuesta del proveedor." },
        { title: "Publica", text: "Revisa el diff, aprueba y publica una versión de configuración firmada. Si hace falta, vuelve atrás con un clic." },
      ],
      source: [
        { title: "Conecta la tienda", text: "Introduce el dominio de la tienda y la moneda por defecto. Track genera la URL del webhook y el secreto una sola vez." },
        { title: "Instala la parte de la tienda", text: "Instala la extensión de píxel, el plugin o la app y registra los webhooks con el secreto generado." },
        { title: "Verifica con un pedido de prueba", text: "El primer webhook firmado pasa la conexión a conectada; los topics observados y el último webhook se muestran en directo." },
      ],
    },
    knowledge: {
      title: "De Tracking Knowledge",
      text: "Guías escritas por el equipo que construye este conector.",
      all: "Todos los artículos de Tracking Knowledge",
      none: "Todavía no hay un artículo específico; el hub de Tracking Knowledge cubre el tracking server-side, la deduplicación y el consentimiento en general.",
      minutes: (n) => `${n} min de lectura`,
    },
    faq: {
      title: "Preguntas",
      destination: [
        { q: "¿Puedo usar solo el modo servidor?", a: "Sí. Elige el modo servidor en el asistente paso a paso; el script del proveedor nunca se carga y el matching se basa en identificadores con hash e IDs de clic capturados por el tracker." },
        { q: "¿Cómo se evitan los duplicados?", a: "La etiqueta de navegador y la petición de servidor llevan el mismo ID de evento, y las compras añaden el ID de pedido. El worker también deduplica los eventos de origen repetidos antes de la entrega." },
        { q: "¿Qué pasa si cambia la API del proveedor?", a: "Las versiones de API se fijan de forma centralizada con la fecha de verificación; los avisos de retirada aparecen en la salud del destino mucho antes de que se retire un endpoint." },
      ],
      source: [
        { q: "¿Sigo necesitando la compra del navegador?", a: "Es opcional, pero valiosa: lleva el registro de consentimiento y los IDs de clic del visitante, que el servidor no puede conocer. El registro verificado de la tienda la sustituye en valor y artículos." },
        { q: "¿Se cuenta el mismo pedido dos veces?", a: "No. La compra del navegador, la API de servidor y el webhook de la tienda comparten el ID de evento derivado del pedido, y el registro de conversión mantiene una sola fila por pedido." },
        { q: "¿Qué ocurre si la plataforma reintenta un webhook?", a: "Las reentregas producen IDs de evento deterministas y chocan con la protección de deduplicación a nivel de evento; nada se cuenta de nuevo." },
      ],
    },
    cta: {
      title: (name) => `Conecta ${name}`,
      text: "Configúralo con el asistente paso a paso o deja que el asistente de IA lo haga en el chat.",
      start: "Empieza gratis",
      all: "Todas las integraciones",
    },
  },
};
