import type { IntegrationsCopy } from "../types";

/**
 * French (fr) copy of the integrations area. Same shape as en.ts; see docs/14-localization.md.
 * Register: vous. French typography (non-breaking space before : ; ? ! and inside « »).
 */

export const INTEGRATIONS_COPY_FR: IntegrationsCopy = {
  eyebrow: "Intégrations",
  title: "Chaque plateforme avec tag navigateur, API serveur et déduplication partagée",
  text: "Plateformes publicitaires, analytics, réseaux d’affiliation, vos propres systèmes et trois plateformes e-commerce — chacune implémentée, documentée et testée par rapport au contrat d’API du fournisseur. Pas de « bientôt disponible ».",
  cta: "Connectez votre première plateforme",
  ctaText: "L’assistant vous accompagne pour les identifiants, les identifiants d’accès, le mapping et un événement de test vérifié.",
  start: "Commencer gratuitement",
  how: "Comment ça fonctionne",
  breadcrumbs: { home: "Track", label: "Intégrations", nav: "Fil d’Ariane" },
  stats: {
    destinations: (n) => `${n} types de destinations`,
    presets: (n) => `${n} presets de postback d’affiliation`,
    shops: (n) => `${n} plateformes e-commerce`,
  },
  diagram: {
    title: "Comment les événements atteignent une destination",
    description: "Les événements navigateur du site web et les événements serveur ou hors ligne de vos systèmes arrivent chez Track, passent le contrôle du consentement et des règles, puis sont livrés aux plateformes publicitaires, aux outils d’analytics et à vos propres systèmes.",
    caption: "Un événement, une décision de consentement, une livraison par destination. Les chemins navigateur et serveur partagent le même identifiant d’événement, de sorte que les plateformes ne comptent chaque conversion qu’une seule fois.",
    nodes: { website: "Site web", websiteSub: "tag navigateur", server: "Serveur · CRM", serverSub: "serveur · hors ligne", track: "Track", trackSub: "règles · dédup", consent: "Consentement", ads: "Plateformes publicitaires", analytics: "Analytics", own: "Vos systèmes" },
  },
  explorer: {
    heading: "Trouvez votre plateforme",
    searchLabel: "Rechercher une intégration",
    searchPlaceholder: "Rechercher par plateforme, produit ou identifiant de clic (p. ex. Meta, GA4, gclid)",
    clear: "Effacer la recherche",
    resultsAll: "{total} intégrations",
    resultsSome: "{shown} intégrations sur {total}",
    categoryFilter: "Filtrer par catégorie",
    modeFilter: "Filtrer par mode de livraison",
    allCategories: "Toutes les catégories",
    allModes: "Tous les modes",
    reset: "Réinitialiser les filtres",
    emptyTitle: "Aucune intégration ne correspond",
    emptyText: "Essayez un terme plus court ou retirez un filtre. Chaque plateforme listée ici est implémentée aujourd’hui — il n’y a pas de liste d’attente à parcourir.",
    resultsHeading: "Résultats",
    details: "Détails",
    presets: "{n} presets réseau",
  },
  categories: { ads: "Publicité", analytics: "Analytics", commerce: "E-commerce", affiliate: "Affiliation", custom: "Vos systèmes" },
  categoryText: {
    ads: "Pixel ou tag dans le navigateur, plus l’API de conversions du fournisseur côté serveur, dédupliqués sur un identifiant d’événement partagé.",
    analytics: "Mesure navigateur plus collecte côté serveur, avec validation avant tout envoi.",
    commerce: "Les plateformes e-commerce livrent à Track des commandes et des remboursements vérifiés ; le navigateur ajoute le consentement et les identifiants de clic.",
    affiliate: "Postbacks serveur à serveur vers les réseaux d’affiliation et de performance, attribués grâce à l’identifiant de clic capturé.",
    custom: "Événements JSON signés vers vos propres endpoints — CRM, entrepôt de données, outils internes.",
  },
  kinds: { destination: "Destination", source: "Intégration e-commerce" },
  modes: { browser: "Navigateur", server: "Serveur", offline: "Hors ligne" },
  modeText: {
    browser: "Le snippet Track ne charge le tag du fournisseur qu’après consentement pour sa finalité. Aucun code du fournisseur ne réside dans votre template.",
    server: "Le worker livre le même événement via l’API du fournisseur — avec nouvelles tentatives, contrôles d’état et un aperçu masqué du payload pour chaque tentative.",
    offline: "Les événements serveur marqués hors ligne (affaires CRM, achats en magasin) atteignent les plateformes dont l’API accepte des sources d’action non web.",
  },
  modesSection: {
    title: "Trois modes de livraison, un seul événement",
    text: "Les modes pris en charge par une plateforme sont déterminés par son API, pas par une formule. Le catalogue ci-dessous montre exactement ce que chaque connecteur implémente.",
    hybridTitle: "Hybride par défaut",
    hybridText: "Lorsqu’une plateforme prend en charge les deux chemins, le tag navigateur et la requête serveur portent le même identifiant d’événement, et les achats ajoutent l’identifiant de commande. Le fournisseur déduplique, et la protection propre à Track écarte les événements source répétés avant la livraison.",
  },
  verification: {
    vendor_docs: "Implémentée · vérifiée par rapport à la documentation du fournisseur",
    secondary_sources: "Implémentée · vérifiée par rapport à des références secondaires (documentation du fournisseur accessible uniquement après connexion)",
    recorded_payloads: "Implémentée · testée avec des payloads de webhook signés et enregistrés",
  },
  verificationShort: { vendor_docs: "Implémentée", secondary_sources: "Implémentée (sources secondaires)", recorded_payloads: "Implémentée (payloads enregistrés)" },
  verifiedOn: (date) => `vérifiée le ${date}`,
  access: {
    open: "Aucune validation du fournisseur requise",
    vendor_setup: "Nécessite une configuration dans le compte du fournisseur",
    vendor_approval: "Nécessite une validation du fournisseur",
    vendor_beta: "API du fournisseur en bêta",
  },
  purposes: { necessary: "Nécessaire", analytics: "Analytics", marketing: "Marketing" },
  credentialKinds: {
    access_token: "Jeton d’accès API",
    api_secret: "Secret API",
    oauth_refresh_token: "Connexion OAuth",
    oauth_access_token: "Connexion OAuth",
    oauth_token_secret: "Secret de jeton OAuth",
    client_id: "Identifiant client API",
    client_secret: "Secret client API",
    webhook_secret: "Secret de webhook",
    signing_secret: "Secret de signature (généré par Track)",
  },
  oauthProviders: { google: "Google", linkedin: "LinkedIn", amazon: "Amazon", x: "X" },
  optional: "facultatif",
  detail: {
    eyebrow: { destination: "Intégration · destination", source: "Intégration · plateforme e-commerce" },
    flow: {
      title: (name) => `Comment les événements atteignent ${name}`,
      text: {
        destination: "Chaque chemin aboutit au même endroit : le moteur de règles vérifie la finalité de consentement requise par cette destination, retire ce qui ne doit pas sortir, et le worker livre avec l’identifiant d’événement partagé.",
        source: "Les webhooks de la boutique sont la source de référence pour les achats et les remboursements. Track vérifie la signature, apparie la commande avec l’achat navigateur par identifiant de commande, et ne la route qu’ensuite — le consentement est hérité, jamais présumé.",
      },
      diagramTitle: (name) => `Flux de données de votre site web et de vos systèmes vers ${name}, via Track`,
      caption: {
        destination: "Chemins pris en charge uniquement. Les modes non pris en charge ne sont pas dessinés — ni revendiqués.",
        source: "L’achat navigateur et le webhook vérifié de la boutique sont appariés par identifiant de commande ; l’enregistrement de la boutique hérite du consentement et des identifiants de clic du visiteur.",
      },
      nodes: {
        website: "Site web",
        websiteSub: "tag navigateur",
        server: "Votre serveur",
        serverSub: "API serveur",
        offline: "CRM · hors ligne",
        offlineSub: "conversions hors ligne",
        shop: "Webhooks boutique",
        shopSub: "commandes · remboursements",
        track: "Track",
        trackSub: "règles · dédup",
        trackPairing: "appariement par identifiant de commande",
        consent: "Consentement",
        destinations: "Destinations",
      },
      edges: { browser: "navigateur", server: "serveur", offline: "hors ligne", shop: "webhook signé" },
    },
    modeDetail: {
      browser: "Tag navigateur — chargé par le snippet Track après consentement ; le script du fournisseur ne réside jamais dans votre template et n’est jamais chargé sans la finalité requise.",
      server: "API serveur — livraison par le worker avec nouvelles tentatives, contrôles d’état, classification des erreurs et un aperçu masqué du payload pour chaque tentative.",
      offline: "Conversions hors ligne — les événements serveur marqués hors ligne (affaires CRM, commandes téléphoniques, achats en magasin) atteignent cette plateforme avec la source d’action hors ligne du fournisseur.",
    },
    sourceModes: {
      browser: "Navigateur — le script de la boutique envoie les événements standard avec l’état du consentement et les identifiants de clic du visiteur ; l’achat porte l’identifiant de commande pour l’appariement.",
      server: "Serveur — les webhooks signés de la boutique livrent les commandes payées et les remboursements avec totaux et lignes de commande ; Track vérifie chaque signature avant d’accepter un enregistrement.",
    },
    hybrid: (field) => `Hybride — le tag navigateur et la requête serveur partagent un même identifiant d’événement\u202f; la plateforme déduplique sur ${field}.`,
    hybridNoField: "Hybride — le tag navigateur et la requête serveur partagent un même identifiant d’événement ; les conversions sont rapprochées par identifiant de commande.",
    sends: {
      title: "Ce qui est envoyé",
      intro: "Uniquement ce que vous configurez dans le mapping des événements, et uniquement après que le moteur de règles a autorisé l’événement pour cette destination.",
      event: "Nom et horodatage de l’événement, mappés des événements standard de Track vers les noms d’événements de la plateforme.",
      eventId: (field) => `L’identifiant d’événement partagé dans le champ ${field} de la plateforme, afin que les livraisons navigateur et serveur ne soient comptées qu’une fois.`,
      eventIdNoField: "L’identifiant d’événement partagé, afin que les livraisons navigateur et serveur puissent être rapprochées.",
      clickIds: (ids) => `Identifiants de clic que cette plateforme peut recevoir\u00a0: ${ids}. Les identifiants de clic d’autres fournisseurs ne sont jamais transmis.`,
      noClickIds: "Aucun identifiant de clic de fournisseur — cette destination est votre propre système, l’attribution reste donc chez vous.",
      order: "Identifiant de commande, valeur, devise et articles pour les événements de type achat.",
      hashed: "Identifiants hachés en SHA-256 (e-mail, téléphone, identifiant externe) pour la correspondance — uniquement avec le consentement requis et uniquement s’ils ont été capturés.",
      noHashed: "Aucun identifiant haché — cette plateforme attribue uniquement sur son identifiant de clic.",
      consent: "L’état du consentement sous lequel l’événement a été collecté, lorsque la plateforme accepte des signaux de consentement.",
      neverTitle: "Jamais envoyé",
      never: ["Adresses e-mail, numéros de téléphone ou noms en clair — les identifiants sont hachés à l’ingestion.", "Valeurs déduites : l’inconnu reste inconnu, rien n’est deviné.", "Événements collectés sans la finalité requise par cette destination.", "Secrets : les jetons résident dans le coffre-fort chiffré et n’atteignent jamais le navigateur, l’assistant ni un journal."],
    },
    receives: {
      title: "Ce que Track reçoit",
      intro: "Deux chemins complémentaires, appariés par identifiant de commande à l’étape d’ingestion.",
      items: ["Commandes payées et remboursements issus des webhooks signés de la boutique : identifiant de commande, totaux, devise, lignes de commande et données de correspondance du client — hachées à l’ingestion.", "Événements navigateur standard de la boutique (consultation, ajout au panier, paiement, achat) avec l’enregistrement de consentement du visiteur et les identifiants de clic capturés.", "L’identifiant de commande sur les deux chemins, de sorte que l’enregistrement vérifié de la boutique remplace l’achat navigateur sans double comptage."],
      neverTitle: "Jamais présumé",
      never: ["Le consentement marketing : un webhook de boutique ne porte aucun consentement propre. Sans achat navigateur apparié, l’enregistrement reste un enregistrement opérationnel et n’atteint que les destinations qui ne nécessitent aucun consentement.", "Des données client en clair dans les plateformes publicitaires — les données de correspondance sont hachées avant d’être stockées.", "Des webhooks non signés ou invérifiables — un échec de vérification de signature est consigné, et le webhook écarté."],
    },
    facts: {
      title: "Données techniques",
      dedup: "Champ de déduplication",
      pairing: "Clé d’appariement",
      clickIds: "Identifiants de clic",
      purpose: "Finalité du consentement",
      apiVersion: "Version d’API figée",
      verified: "Vérification",
      status: "État de l’implémentation",
      docs: "Documentation du fournisseur",
      docsLink: (name) => `Documentation de l’API ${name}`,
      ownDocs: "Documentation Track",
      none: "aucun",
      presets: "Presets réseau",
    },
    ids: {
      title: "Ce dont vous avez besoin",
      intro: "Les identifiants publics peuvent être saisis dans le chat ou dans l’assistant guidé ; les secrets passent par la carte d’identifiants d’accès sécurisée ou par OAuth, et sont stockés chiffrés.",
      publicIds: "Identifiants publics",
      credentials: "Identifiants d’accès",
      vault: "stockées dans le coffre-fort chiffré",
      noCredentials: "Aucun identifiant d’accès — cette plateforme accepte les événements serveur avec les seuls identifiants publics.",
      key: "Clé",
      label: "Description",
    },
    prerequisites: "Prérequis côté fournisseur",
    consent: {
      title: "Consentement",
      text: {
        marketing: "Nécessite la finalité marketing. Sans elle, rien n’est chargé dans le navigateur et rien n’est envoyé depuis le serveur. Un consentement déduit n’est jamais exporté, et les refus exprimés via Global Privacy Control bloquent la livraison.",
        analytics: "Nécessite la finalité analytics. Sans elle, rien n’est chargé dans le navigateur et rien n’est envoyé depuis le serveur. Un consentement déduit n’est jamais exporté.",
        necessary: "Fonctionne sous la finalité nécessaire, car elle cible vos propres systèmes (traitement côté responsable du traitement). Les identifiants sont tout de même retirés sans consentement analytics, et les identifiants de clic sans consentement marketing.",
      },
      source: "Les webhooks de boutique ne portent aucun consentement propre. Une commande vérifiée hérite de l’enregistrement de consentement de l’achat navigateur apparié ; sans lui, elle est stockée comme enregistrement opérationnel et n’atteint jamais une plateforme publicitaire.",
    },
    setup: {
      title: "Configuration en quelques étapes",
      intro: "L’assistant exécute les vérifications détaillées. Vous voyez les étapes clés qui nécessitent une décision de votre part.",
      destination: [
        { title: "Saisir les identifiants", text: "Ajoutez les identifiants publics de la plateforme. Les formats sont validés par rapport à la documentation du fournisseur avant tout enregistrement." },
        { title: "Connecter les identifiants d’accès", text: "Collez le jeton dans la carte sécurisée ou connectez le compte via OAuth. Les secrets vont directement dans le coffre-fort chiffré." },
        { title: "Mapper et tester", text: "Les événements standard sont pré-mappés vers les noms d’événements de la plateforme. Un événement de test marqué traverse le pipeline réel et affiche la réponse du fournisseur." },
        { title: "Publier", text: "Vérifiez le diff, approuvez, publiez une version de configuration signée. Revenez en arrière en un clic si nécessaire." },
      ],
      source: [
        { title: "Connecter la boutique", text: "Saisissez le domaine de la boutique et la devise de repli. Track génère l’URL du webhook et le secret, une seule fois." },
        { title: "Installer côté boutique", text: "Installez l’extension pixel, le plugin ou l’application, puis enregistrez les webhooks avec le secret généré." },
        { title: "Vérifier avec une commande de test", text: "Le premier webhook signé fait passer la connexion à l’état connecté ; les topics observés et le dernier webhook sont affichés en direct." },
      ],
    },
    knowledge: {
      title: "Extrait de Tracking Knowledge",
      text: "Des guides rédigés par l’équipe qui construit ce connecteur.",
      all: "Tous les articles Tracking Knowledge",
      none: "Pas encore d’article dédié — le hub Tracking Knowledge couvre le tracking côté serveur, la déduplication et le consentement en général.",
      minutes: (n) => `${n} min de lecture`,
    },
    faq: {
      title: "Questions",
      destination: [
        { q: "Puis-je fonctionner uniquement côté serveur ?", a: "Oui. Choisissez le mode serveur dans l’assistant guidé ; le script du fournisseur n’est jamais chargé, et la correspondance repose sur les identifiants hachés et les identifiants de clic capturés par le tracker." },
        { q: "Comment les doublons sont-ils évités ?", a: "Le tag navigateur et la requête serveur portent le même identifiant d’événement, et les achats ajoutent l’identifiant de commande. Le worker déduplique également les événements source répétés avant la livraison." },
        { q: "Que se passe-t-il si l’API du fournisseur change ?", a: "Les versions d’API sont figées de manière centralisée avec leur date de vérification ; des avertissements de fin de vie apparaissent dans l’état de santé de la destination bien avant le retrait d’un endpoint." },
      ],
      source: [
        { q: "Ai-je encore besoin de l’achat navigateur ?", a: "Il est facultatif mais précieux : il porte l’enregistrement de consentement et les identifiants de clic du visiteur, que le serveur ne peut pas connaître. L’enregistrement vérifié de la boutique le remplace pour la valeur et les articles." },
        { q: "La même commande est-elle comptée deux fois ?", a: "Non. L’achat navigateur, l’API serveur et le webhook de la boutique partagent l’identifiant d’événement dérivé de la commande, et l’enregistrement de conversion conserve une seule ligne par commande." },
        { q: "Que se passe-t-il si la plateforme renvoie un webhook ?", a: "Les renvois produisent des identifiants d’événement déterministes et sont interceptés par la protection de déduplication au niveau de l’événement ; rien n’est compté à nouveau." },
      ],
    },
    cta: {
      title: (name) => `Connecter ${name}`,
      text: "Configurez-la avec l’assistant guidé ou laissez l’assistant IA s’en charger dans le chat.",
      start: "Commencer gratuitement",
      all: "Toutes les intégrations",
    },
  },
};
