import type { IntegrationsCopy } from "../types";

/**
 * Italian (it) copy of the integrations area. Same shape as en.ts; see docs/14-localization.md.
 * Register: tu. Product, platform and API names stay in English; "destination" is "destinazione",
 * "event id" / "order id" are "ID evento" / "ID ordine", "click id" is "click ID".
 */

export const INTEGRATIONS_COPY_IT: IntegrationsCopy = {
  eyebrow: "Integrazioni",
  title: "Ogni piattaforma con tag browser, API server e deduplicazione condivisa",
  text: "Piattaforme pubblicitarie, analytics, network di affiliazione, i tuoi sistemi e tre piattaforme e-commerce: ognuna implementata, documentata e testata rispetto al contratto API del vendor. Nessun «prossimamente».",
  cta: "Collega la tua prima piattaforma",
  ctaText: "L’assistente ti guida tra identificatori, credenziali, mappatura e un evento di test verificato.",
  start: "Inizia gratis",
  how: "Come funziona",
  breadcrumbs: { home: "Track", label: "Integrazioni", nav: "Percorso di navigazione" },
  stats: {
    destinations: (n) => `${n} tipi di destinazione`,
    presets: (n) => `${n} preset di postback per affiliazioni`,
    shops: (n) => `${n} piattaforme e-commerce`,
  },
  diagram: {
    title: "Come gli eventi raggiungono una destinazione",
    description: "Gli eventi browser del sito web e gli eventi server o offline dei tuoi sistemi arrivano a Track, passano il gate di consenso e policy e vengono consegnati a piattaforme pubblicitarie, analytics e sistemi propri.",
    caption: "Un evento, una decisione sul consenso, una consegna per destinazione. Il percorso browser e quello server condividono lo stesso ID evento, così le piattaforme contano ogni conversione una sola volta.",
    nodes: { website: "Sito web", websiteSub: "tag browser", server: "Server · CRM", serverSub: "server · offline", track: "Track", trackSub: "policy · dedup", consent: "Consenso", ads: "Piattaforme ads", analytics: "Analytics", own: "Sistemi propri" },
  },
  explorer: {
    heading: "Trova la tua piattaforma",
    searchLabel: "Cerca tra le integrazioni",
    searchPlaceholder: "Cerca per piattaforma, prodotto o click ID (es. Meta, GA4, gclid)",
    clear: "Cancella la ricerca",
    resultsAll: "{total} integrazioni",
    resultsSome: "{shown} di {total} integrazioni",
    categoryFilter: "Filtra per categoria",
    modeFilter: "Filtra per modalità di consegna",
    allCategories: "Tutte le categorie",
    allModes: "Tutte le modalità",
    reset: "Reimposta i filtri",
    emptyTitle: "Nessuna integrazione corrisponde",
    emptyText: "Prova con un termine più breve o rimuovi un filtro. Ogni piattaforma elencata qui è già implementata: non esiste una lista d’attesa in cui cercare.",
    resultsHeading: "Risultati",
    details: "Dettagli",
    presets: "{n} preset di network",
  },
  categories: { ads: "Ads", analytics: "Analytics", commerce: "E-commerce", affiliate: "Affiliazione", custom: "Sistemi propri" },
  categoryText: {
    ads: "Pixel o tag nel browser più la Conversions API del vendor sul server, deduplicati su un ID evento condiviso.",
    analytics: "Misurazione nel browser più raccolta server-side, con validazione prima di qualsiasi invio.",
    commerce: "Le piattaforme e-commerce consegnano a Track ordini e rimborsi verificati; il browser aggiunge consenso e click ID.",
    affiliate: "Postback server-to-server verso network di affiliazione e performance, attribuiti tramite il click ID acquisito.",
    custom: "Eventi JSON firmati verso i tuoi endpoint: CRM, data warehouse, strumenti interni.",
  },
  kinds: { destination: "Destinazione", source: "Integrazione e-commerce" },
  modes: { browser: "Browser", server: "Server", offline: "Offline" },
  modeText: {
    browser: "Lo snippet di Track carica il tag del vendor solo dopo il consenso per la sua finalità. Nessun codice del vendor risiede nel tuo template.",
    server: "Il worker consegna lo stesso evento tramite l’API del vendor, con retry, health check e un’anteprima del payload con dati oscurati per ogni tentativo.",
    offline: "Gli eventi server contrassegnati come offline (opportunità CRM, acquisti in negozio) raggiungono le piattaforme la cui API accetta origini di azione non web.",
  },
  modesSection: {
    title: "Tre modalità di consegna, un solo evento",
    text: "Quali modalità supporta una piattaforma lo decide la sua API, non un piano. Il catalogo qui sotto mostra esattamente cosa implementa ogni connettore.",
    hybridTitle: "Ibrido per impostazione predefinita",
    hybridText: "Quando una piattaforma supporta entrambi i percorsi, tag browser e richiesta server trasportano lo stesso ID evento e gli acquisti aggiungono l’ID ordine. Il vendor deduplica e la protezione interna di Track scarta gli eventi sorgente ripetuti prima della consegna.",
  },
  verification: {
    vendor_docs: "Implementata · verificata sulla documentazione del vendor",
    secondary_sources: "Implementata · verificata su fonti secondarie (documentazione del vendor dietro login)",
    recorded_payloads: "Implementata · testata con payload di webhook firmati e registrati",
  },
  verificationShort: { vendor_docs: "Implementata", secondary_sources: "Implementata (fonti secondarie)", recorded_payloads: "Implementata (payload registrati)" },
  verifiedOn: (date) => `verificata il ${date}`,
  access: {
    open: "Nessuna approvazione del vendor necessaria",
    vendor_setup: "Richiede la configurazione nell’account del vendor",
    vendor_approval: "Richiede l’approvazione del vendor",
    vendor_beta: "API del vendor in beta",
  },
  purposes: { necessary: "Necessario", analytics: "Analytics", marketing: "Marketing" },
  credentialKinds: {
    access_token: "Token di accesso API",
    api_secret: "Secret API",
    oauth_refresh_token: "Connessione OAuth",
    oauth_access_token: "Connessione OAuth",
    oauth_token_secret: "Token secret OAuth",
    client_id: "ID client API",
    client_secret: "Client secret API",
    webhook_secret: "Secret del webhook",
    signing_secret: "Secret di firma (generato da Track)",
  },
  oauthProviders: { google: "Google", linkedin: "LinkedIn", amazon: "Amazon", x: "X" },
  optional: "facoltativo",
  detail: {
    eyebrow: { destination: "Integrazione · destinazione", source: "Integrazione · piattaforma e-commerce" },
    flow: {
      title: (name) => `Come gli eventi raggiungono ${name}`,
      text: {
        destination: "Ogni percorso finisce nello stesso punto: il motore delle policy verifica la finalità di consenso richiesta da questa destinazione, rimuove ciò che non può uscire e il worker consegna con l’ID evento condiviso.",
        source: "I webhook dello shop sono la fonte autorevole per acquisti e rimborsi. Track verifica la firma, abbina l’ordine all’acquisto browser tramite l’ID ordine e solo allora lo inoltra: il consenso viene ereditato, mai presunto.",
      },
      diagramTitle: (name) => `Flusso dei dati dal tuo sito web e dai tuoi sistemi attraverso Track fino a ${name}`,
      caption: {
        destination: "Solo i percorsi supportati. Le modalità non supportate non vengono disegnate, né dichiarate.",
        source: "Acquisto browser e webhook verificato dello shop vengono abbinati tramite l’ID ordine; il record dello shop eredita consenso e click ID del visitatore.",
      },
      nodes: {
        website: "Sito web",
        websiteSub: "tag browser",
        server: "Il tuo server",
        serverSub: "API server",
        offline: "CRM · offline",
        offlineSub: "conversioni offline",
        shop: "Webhook dello shop",
        shopSub: "ordini · rimborsi",
        track: "Track",
        trackSub: "policy · dedup",
        trackPairing: "abbinamento per ID ordine",
        consent: "Consenso",
        destinations: "Destinazioni",
      },
      edges: { browser: "browser", server: "server", offline: "offline", shop: "webhook firmato" },
    },
    modeDetail: {
      browser: "Tag browser: caricato dallo snippet di Track dopo il consenso; lo script del vendor non risiede mai nel tuo template e non viene mai caricato senza la finalità richiesta.",
      server: "API server: consegna tramite il worker con retry, health check, classificazione degli errori e un’anteprima del payload con dati oscurati per ogni tentativo.",
      offline: "Conversioni offline: gli eventi server contrassegnati come offline (opportunità CRM, ordini telefonici, acquisti in negozio) raggiungono questa piattaforma con l’origine di azione offline del vendor.",
    },
    sourceModes: {
      browser: "Browser: lo script dello storefront invia gli eventi standard con lo stato del consenso e i click ID del visitatore; l’acquisto trasporta l’ID ordine per l’abbinamento.",
      server: "Server: i webhook firmati dello shop consegnano ordini pagati e rimborsi con totali e righe d’ordine; Track verifica ogni firma prima di accettare un record.",
    },
    hybrid: (field) => `Ibrido: tag browser e richiesta server condividono un unico ID evento; la piattaforma deduplica su ${field}.`,
    hybridNoField: "Ibrido: tag browser e richiesta server condividono un unico ID evento; le conversioni vengono abbinate tramite l’ID ordine.",
    sends: {
      title: "Cosa viene inviato",
      intro: "Solo ciò che configuri nella mappatura degli eventi, e solo dopo che il motore delle policy ha autorizzato l’evento per questa destinazione.",
      event: "Nome dell’evento e timestamp, mappati dagli eventi standard di Track ai nomi evento della piattaforma.",
      eventId: (field) => `L’ID evento condiviso nel campo ${field} della piattaforma, così le consegne browser e server contano una sola volta.`,
      eventIdNoField: "L’ID evento condiviso, così le consegne browser e server possono essere abbinate.",
      clickIds: (ids) => `Click ID che questa piattaforma può ricevere: ${ids}. I click ID di altri fornitori non vengono mai inoltrati.`,
      noClickIds: "Nessun click ID di vendor: questa destinazione è un tuo sistema, quindi l’attribuzione resta a te.",
      order: "ID ordine, valore, valuta e articoli per gli eventi di tipo acquisto.",
      hashed: "Identificatori con hash SHA-256 (e-mail, telefono, ID esterno) per il matching, solo con il consenso richiesto e solo se acquisiti.",
      noHashed: "Nessun identificatore con hash: questa piattaforma attribuisce solo tramite il suo click ID.",
      consent: "Lo stato del consenso con cui l’evento è stato raccolto, dove la piattaforma accetta segnali di consenso.",
      neverTitle: "Mai inviato",
      never: ["Indirizzi e-mail, numeri di telefono o nomi in chiaro: gli identificatori vengono sottoposti a hash all’ingresso.", "Valori dedotti: ciò che è sconosciuto resta sconosciuto, niente viene indovinato.", "Eventi raccolti senza la finalità richiesta da questa destinazione.", "Secret: i token vivono nel vault cifrato e non raggiungono mai il browser, l’assistente o un log."],
    },
    receives: {
      title: "Cosa riceve Track",
      intro: "Due percorsi complementari, abbinati tramite l’ID ordine nella fase di ingest.",
      items: ["Ordini pagati e rimborsi dai webhook firmati dello shop: ID ordine, totali, valuta, righe d’ordine e i dati di matching del cliente, sottoposti a hash all’ingresso.", "Eventi browser standard dallo storefront (visualizzazione, aggiunta al carrello, checkout, acquisto) con il record di consenso e i click ID acquisiti del visitatore.", "L’ID ordine su entrambi i percorsi, così il record verificato dello shop sostituisce l’acquisto browser senza doppio conteggio."],
      neverTitle: "Mai presunto",
      never: ["Consenso marketing: un webhook dello shop non trasporta un consenso proprio. Senza un acquisto browser abbinato, il record resta un record operativo e raggiunge solo destinazioni che non richiedono consenso.", "Dati cliente in chiaro nelle piattaforme pubblicitarie: i dati di matching vengono sottoposti a hash prima di essere salvati.", "Webhook non firmati o non verificabili: un controllo di firma fallito viene registrato e scartato."],
    },
    facts: {
      title: "Fatti tecnici",
      dedup: "Campo di deduplicazione",
      pairing: "Chiave di abbinamento",
      clickIds: "Click ID",
      purpose: "Finalità di consenso",
      apiVersion: "Versione API bloccata",
      verified: "Verifica",
      status: "Stato dell’implementazione",
      docs: "Documentazione del vendor",
      docsLink: (name) => `Documentazione API di ${name}`,
      ownDocs: "Documentazione Track",
      none: "nessuno",
      presets: "Preset di network",
    },
    ids: {
      title: "Cosa ti serve",
      intro: "Gli identificatori pubblici possono essere inseriti in chat o nella procedura guidata; i secret passano dalla scheda credenziali sicura o da OAuth e vengono salvati cifrati.",
      publicIds: "Identificatori pubblici",
      credentials: "Credenziali",
      vault: "salvato nel vault cifrato",
      noCredentials: "Nessuna credenziale: questa piattaforma accetta eventi server con i soli identificatori pubblici.",
      key: "Chiave",
      label: "Descrizione",
    },
    prerequisites: "Prerequisito del vendor",
    consent: {
      title: "Consenso",
      text: {
        marketing: "Richiede la finalità marketing. Senza di essa niente viene caricato nel browser e niente viene inviato dal server. Il consenso dedotto non viene mai esportato e gli opt-out tramite Global Privacy Control bloccano la consegna.",
        analytics: "Richiede la finalità analytics. Senza di essa niente viene caricato nel browser e niente viene inviato dal server. Il consenso dedotto non viene mai esportato.",
        necessary: "Opera con la finalità necessaria perché si rivolge ai tuoi sistemi (trattamento lato titolare). Gli identificatori vengono comunque rimossi senza consenso analytics e i click ID senza consenso marketing.",
      },
      source: "I webhook dello shop non trasportano un consenso proprio. Un ordine verificato eredita il record di consenso dell’acquisto browser abbinato; senza di esso viene salvato come record operativo e non raggiunge mai una piattaforma pubblicitaria.",
    },
    setup: {
      title: "Configurazione in pochi passaggi",
      intro: "L’assistente esegue i controlli di dettaglio. Tu vedi le tappe che richiedono una tua decisione.",
      destination: [
        { title: "Inserisci gli identificatori", text: "Aggiungi gli ID pubblici della piattaforma. I formati vengono validati sulla documentazione del vendor prima di salvare qualsiasi cosa." },
        { title: "Collega le credenziali", text: "Incolla il token nella scheda sicura o collega l’account via OAuth. I secret finiscono direttamente nel vault cifrato." },
        { title: "Mappa e testa", text: "Gli eventi standard sono già mappati ai nomi evento della piattaforma. Un evento di test contrassegnato percorre la pipeline reale e mostra la risposta del vendor." },
        { title: "Pubblica", text: "Controlla il diff, approva, pubblica una versione di configurazione firmata. Se serve, torna indietro con un clic." },
      ],
      source: [
        { title: "Collega lo shop", text: "Inserisci il dominio dello shop e la valuta di fallback. Track genera l’URL del webhook e il secret una sola volta." },
        { title: "Installa il lato shop", text: "Installa l’estensione pixel, il plugin o l’app e registra i webhook con il secret generato." },
        { title: "Verifica con un ordine di test", text: "Il primo webhook firmato porta la connessione allo stato connesso; i topic osservati e l’ultimo webhook vengono mostrati in tempo reale." },
      ],
    },
    knowledge: {
      title: "Da Tracking Knowledge",
      text: "Guide scritte dal team che sviluppa questo connettore.",
      all: "Tutti gli articoli di Tracking Knowledge",
      none: "Nessun articolo dedicato per ora: l’hub Tracking Knowledge tratta tracking server-side, deduplicazione e consenso in generale.",
      minutes: (n) => `${n} min di lettura`,
    },
    faq: {
      title: "Domande",
      destination: [
        { q: "Posso usare solo la modalità server?", a: "Sì. Scegli la modalità server nella procedura guidata; lo script del vendor non viene mai caricato e il matching si basa su identificatori con hash e click ID acquisiti dal tracker." },
        { q: "Come vengono evitati i duplicati?", a: "Il tag browser e la richiesta server trasportano lo stesso ID evento e gli acquisti aggiungono l’ID ordine. Il worker deduplica inoltre gli eventi sorgente ripetuti prima della consegna." },
        { q: "E se l’API del vendor cambia?", a: "Le versioni API sono bloccate centralmente con la data di verifica; gli avvisi di dismissione compaiono nello stato di salute della destinazione molto prima che un endpoint venga ritirato." },
      ],
      source: [
        { q: "Mi serve ancora l’acquisto browser?", a: "È facoltativo ma prezioso: trasporta il record di consenso e i click ID del visitatore, che il server non può conoscere. Il record verificato dello shop lo sostituisce per valore e articoli." },
        { q: "Lo stesso ordine viene contato due volte?", a: "No. Acquisto browser, API server e webhook dello shop condividono l’ID evento derivato dall’ordine e il record di conversione mantiene una sola riga per ordine." },
        { q: "Cosa succede se la piattaforma ripete l’invio di un webhook?", a: "Le riconsegne producono ID evento deterministici e incontrano la protezione di deduplicazione a livello di evento; niente viene contato di nuovo." },
      ],
    },
    cta: {
      title: (name) => `Collega ${name}`,
      text: "Configura l’integrazione con la procedura guidata o lascia che l’assistente lo faccia in chat.",
      start: "Inizia gratis",
      all: "Tutte le integrazioni",
    },
  },
};
