import type { IntegrationsCopy } from "../types";

/**
 * Dutch (nl) copy of the integrations area, informal "je/jij" like the rest of the Dutch copy. Same shape as en.ts;
 * see docs/14-localization.md.
 */

export const INTEGRATIONS_COPY_NL: IntegrationsCopy = {
  eyebrow: "Integraties",
  title: "Elk platform met browsertag, server-API en gedeelde deduplicatie",
  text: "Advertentieplatformen, analytics, affiliatenetwerken, je eigen systemen en drie shopplatformen — elk geïmplementeerd, gedocumenteerd en getest tegen het contract van de leverancier. Geen “binnenkort beschikbaar”.",
  cta: "Koppel je eerste platform",
  ctaText: "De assistent loopt met je door identifiers, credentials, mapping en een geverifieerd testevent.",
  start: "Gratis starten",
  how: "Hoe het werkt",
  breadcrumbs: { home: "Track", label: "Integraties", nav: "Kruimelpad" },
  stats: {
    destinations: (n) => `${n} destinationtypes`,
    presets: (n) => `${n} affiliate-postbackpresets`,
    shops: (n) => `${n} shopplatformen`,
  },
  diagram: {
    title: "Hoe events een destination bereiken",
    description: "Browserevents van de website en server- of offline-events uit je systemen komen bij Track binnen, passeren de toestemmings- en policy-gate en worden afgeleverd bij advertentieplatformen, analytics en je eigen systemen.",
    caption: "Eén event, één toestemmingsbeslissing, één aflevering per destination. Browser- en serverpad delen dezelfde event-ID, zodat platformen elke conversie één keer tellen.",
    nodes: { website: "Website", websiteSub: "browsertag", server: "Server · CRM", serverSub: "server · offline", track: "Track", trackSub: "policy · dedup", consent: "Toestemming", ads: "Advertentieplatformen", analytics: "Analytics", own: "Eigen systemen" },
  },
  explorer: {
    heading: "Vind je platform",
    searchLabel: "Integraties doorzoeken",
    searchPlaceholder: "Zoek op platform, product of click-ID (bijv. Meta, GA4, gclid)",
    clear: "Zoekopdracht wissen",
    resultsAll: "{total} integraties",
    resultsSome: "{shown} van {total} integraties",
    categoryFilter: "Filteren op categorie",
    modeFilter: "Filteren op afleveringsmodus",
    allCategories: "Alle categorieën",
    allModes: "Alle modi",
    reset: "Filters resetten",
    emptyTitle: "Geen integratie gevonden",
    emptyText: "Probeer een kortere zoekterm of verwijder een filter. Elk platform in deze lijst is vandaag al geïmplementeerd — er is geen wachtlijst om te doorzoeken.",
    resultsHeading: "Resultaten",
    details: "Details",
    presets: "{n} netwerkpresets",
  },
  categories: { ads: "Ads", analytics: "Analytics", commerce: "Commerce", affiliate: "Affiliate", custom: "Eigen systemen" },
  categoryText: {
    ads: "Pixel of tag in de browser plus de conversions-API van de leverancier op de server, gededupliceerd op een gedeelde event-ID.",
    analytics: "Browsermeting plus server-side verzameling met validatie voordat er iets wordt verzonden.",
    commerce: "Shopplatformen leveren geverifieerde orders en terugbetalingen aan Track; de browser voegt toestemming en click-ID's toe.",
    affiliate: "Server-to-server-postbacks naar affiliate- en performancenetwerken, geattribueerd via de vastgelegde click-ID.",
    custom: "Ondertekende JSON-events naar je eigen endpoints — CRM, datawarehouse, interne tools.",
  },
  kinds: { destination: "Destination", source: "Shopintegratie" },
  modes: { browser: "Browser", server: "Server", offline: "Offline" },
  modeText: {
    browser: "De Track-snippet laadt de tag van de leverancier pas na toestemming voor het bijbehorende doel. Er staat geen leverancierscode in je template.",
    server: "De worker levert hetzelfde event af via de API van de leverancier — met retries, healthchecks en een gemaskeerde payload-preview per poging.",
    offline: "Serverevents die als offline zijn gemarkeerd (CRM-deals, winkelaankopen) bereiken platformen waarvan de API niet-webactiebronnen accepteert.",
  },
  modesSection: {
    title: "Drie afleveringsmodi, één event",
    text: "Welke modi een platform ondersteunt, bepaalt zijn API, niet een abonnement. De catalogus hieronder laat precies zien wat elke connector implementeert.",
    hybridTitle: "Standaard hybride",
    hybridText: "Als een platform beide paden ondersteunt, dragen browsertag en serverrequest dezelfde event-ID en voegen aankopen de order-ID toe. De leverancier dedupliceert, en de eigen guard van Track laat herhaalde bronevents vallen vóór de aflevering.",
  },
  verification: {
    vendor_docs: "Geïmplementeerd · geverifieerd tegen de documentatie van de leverancier",
    secondary_sources: "Geïmplementeerd · geverifieerd tegen secundaire bronnen (leveranciersdocumentatie achter een login)",
    recorded_payloads: "Geïmplementeerd · getest met ondertekende, opgenomen webhook-payloads",
  },
  verificationShort: { vendor_docs: "Geïmplementeerd", secondary_sources: "Geïmplementeerd (secundaire bronnen)", recorded_payloads: "Geïmplementeerd (opgenomen payloads)" },
  verifiedOn: (date) => `geverifieerd op ${date}`,
  access: {
    open: "Geen goedkeuring van de leverancier nodig",
    vendor_setup: "Vereist configuratie in het account bij de leverancier",
    vendor_approval: "Vereist goedkeuring van de leverancier",
    vendor_beta: "API van de leverancier in bèta",
  },
  purposes: { necessary: "Noodzakelijk", analytics: "Analytics", marketing: "Marketing" },
  credentialKinds: {
    access_token: "API-toegangstoken",
    api_secret: "API-secret",
    oauth_refresh_token: "OAuth-koppeling",
    oauth_access_token: "OAuth-koppeling",
    oauth_token_secret: "OAuth-tokensecret",
    client_id: "API-client-ID",
    client_secret: "API-clientsecret",
    webhook_secret: "Webhook-secret",
    signing_secret: "Signing secret (gegenereerd door Track)",
  },
  oauthProviders: { google: "Google", linkedin: "LinkedIn", amazon: "Amazon", x: "X" },
  optional: "optioneel",
  detail: {
    eyebrow: { destination: "Integratie · destination", source: "Integratie · shopplatform" },
    flow: {
      title: (name) => `Hoe events ${name} bereiken`,
      text: {
        destination: "Elk pad eindigt op dezelfde plek: de policy-engine controleert het toestemmingsdoel dat deze destination vereist, verwijdert wat niet naar buiten mag, en de worker levert af met de gedeelde event-ID.",
        source: "De eigen webhooks van de shop zijn de gezaghebbende bron voor aankopen en terugbetalingen. Track verifieert de handtekening, koppelt de order via de order-ID aan de browseraankoop en routeert hem pas daarna door — toestemming wordt overgenomen, nooit aangenomen.",
      },
      diagramTitle: (name) => `Datastroom van je website en systemen via Track naar ${name}`,
      caption: {
        destination: "Alleen ondersteunde paden. Niet-ondersteunde modi worden niet getekend — en niet geclaimd.",
        source: "Browseraankoop en geverifieerde shopwebhook worden gekoppeld op order-ID; het shoprecord neemt de toestemming en click-ID's van de bezoeker over.",
      },
      nodes: {
        website: "Website",
        websiteSub: "browsertag",
        server: "Je server",
        serverSub: "server-API",
        offline: "CRM · offline",
        offlineSub: "offline conversies",
        shop: "Shopwebhooks",
        shopSub: "orders · terugbetalingen",
        track: "Track",
        trackSub: "policy · dedup",
        trackPairing: "koppeling op order-ID",
        consent: "Toestemming",
        destinations: "Destinations",
      },
      edges: { browser: "browser", server: "server", offline: "offline", shop: "ondertekende webhook" },
    },
    modeDetail: {
      browser: "Browsertag — geladen door de Track-snippet na toestemming; het script van de leverancier staat nooit in je template en wordt nooit geladen zonder het vereiste doel.",
      server: "Server-API — afgeleverd door de worker met retries, healthchecks, foutclassificatie en een gemaskeerde payload-preview voor elke poging.",
      offline: "Offline conversies — serverevents die als offline zijn gemarkeerd (CRM-deals, telefonische bestellingen, winkelaankopen) bereiken dit platform met de offline-actiebron van de leverancier.",
    },
    sourceModes: {
      browser: "Browser — het storefront-script verstuurt standaardevents met de toestemmingsstatus en click-ID's van de bezoeker; de aankoop draagt de order-ID voor de koppeling.",
      server: "Server — de ondertekende webhooks van de shop leveren betaalde orders en terugbetalingen met totalen en orderregels; Track verifieert elke handtekening voordat een record wordt geaccepteerd.",
    },
    hybrid: (field) => `Hybride — browsertag en serverrequest delen één event-ID; het platform dedupliceert op ${field}.`,
    hybridNoField: "Hybride — browsertag en serverrequest delen één event-ID; conversies worden gematcht op de order-ID.",
    sends: {
      title: "Wat wordt verzonden",
      intro: "Alleen wat je in de eventmapping configureert, en pas nadat de policy-engine het event voor deze destination heeft toegestaan.",
      event: "Eventnaam en tijdstempel, gemapt van de standaardevents van Track naar de eventnamen van het platform.",
      eventId: (field) => `De gedeelde event-ID in het veld ${field} van het platform, zodat browser- en serverafleveringen één keer tellen.`,
      eventIdNoField: "De gedeelde event-ID, zodat browser- en serverafleveringen aan elkaar gekoppeld kunnen worden.",
      clickIds: (ids) => `Click-ID's die dit platform mag ontvangen: ${ids}. Click-ID's van andere leveranciers worden nooit doorgestuurd.`,
      noClickIds: "Geen click-ID's van leveranciers — deze destination is je eigen systeem, dus de attributie blijft bij jou.",
      order: "Order-ID, waarde, valuta en items voor aankoopachtige events.",
      hashed: "SHA-256-gehashte identifiers (e-mail, telefoon, externe ID) voor matching — alleen met de vereiste toestemming en alleen als ze zijn vastgelegd.",
      noHashed: "Geen gehashte identifiers — dit platform attribueert uitsluitend op zijn click-ID.",
      consent: "De toestemmingsstatus waaronder het event is verzameld, als het platform toestemmingssignalen accepteert.",
      neverTitle: "Nooit verzonden",
      never: ["Onbewerkte e-mailadressen, telefoonnummers of namen — identifiers worden bij ontvangst gehasht.", "Afgeleide waarden: onbekend blijft onbekend, er wordt niets gegokt.", "Events die zijn verzameld zonder het doel dat deze destination vereist.", "Secrets: tokens staan in de versleutelde kluis en bereiken nooit de browser, de assistent of een log."],
    },
    receives: {
      title: "Wat Track ontvangt",
      intro: "Twee complementaire paden, in de ingest-fase gekoppeld op order-ID.",
      items: ["Betaalde orders en terugbetalingen uit de ondertekende webhooks van de shop: order-ID, totalen, valuta, orderregels en de matchinggegevens van de klant — bij ontvangst gehasht.", "Standaard browserevents uit de storefront (bekijken, in winkelwagen, checkout, aankoop) met het toestemmingsrecord en de vastgelegde click-ID's van de bezoeker.", "De order-ID op beide paden, zodat het geverifieerde shoprecord de browseraankoop vervangt zonder dubbeltelling."],
      neverTitle: "Nooit aangenomen",
      never: ["Marketingtoestemming: een shopwebhook draagt geen eigen toestemming. Zonder gekoppelde browseraankoop blijft het record een operationeel record en bereikt het alleen destinations die geen toestemming nodig hebben.", "Onbewerkte klantgegevens in advertentieplatformen — matchinggegevens worden gehasht voordat ze worden opgeslagen.", "Niet-ondertekende of niet-verifieerbare webhooks — een mislukte handtekeningcontrole wordt vastgelegd en het bericht wordt weggegooid."],
    },
    facts: {
      title: "Technische feiten",
      dedup: "Deduplicatieveld",
      pairing: "Koppelsleutel",
      clickIds: "Click-ID's",
      purpose: "Toestemmingsdoel",
      apiVersion: "Vastgezette API-versie",
      verified: "Verificatie",
      status: "Implementatiestatus",
      docs: "Documentatie van de leverancier",
      docsLink: (name) => `API-documentatie van ${name}`,
      ownDocs: "Track-documentatie",
      none: "geen",
      presets: "Netwerkpresets",
    },
    ids: {
      title: "Wat je nodig hebt",
      intro: "Publieke identifiers kun je in de chat of de wizard invoeren; secrets gaan via de beveiligde credentialkaart of OAuth en worden versleuteld opgeslagen.",
      publicIds: "Publieke identifiers",
      credentials: "Credentials",
      vault: "opgeslagen in de versleutelde kluis",
      noCredentials: "Geen credentials — dit platform accepteert serverevents met alleen de publieke identifiers.",
      key: "Sleutel",
      label: "Beschrijving",
    },
    prerequisites: "Vereiste bij de leverancier",
    consent: {
      title: "Toestemming",
      text: {
        marketing: "Vereist het marketingdoel. Zonder dat doel wordt er niets in de browser geladen en niets vanaf de server verzonden. Afgeleide toestemming wordt nooit geëxporteerd, en Global Privacy Control-opt-outs blokkeren de aflevering.",
        analytics: "Vereist het analyticsdoel. Zonder dat doel wordt er niets in de browser geladen en niets vanaf de server verzonden. Afgeleide toestemming wordt nooit geëxporteerd.",
        necessary: "Draait onder het doel ‘noodzakelijk’, omdat het je eigen systemen als doel heeft (verwerking aan de kant van de verwerkingsverantwoordelijke). Identifiers worden zonder analyticstoestemming nog steeds verwijderd, click-ID's zonder marketingtoestemming.",
      },
      source: "Shopwebhooks dragen geen eigen toestemming. Een geverifieerde order neemt het toestemmingsrecord van de gekoppelde browseraankoop over; zonder die koppeling wordt hij opgeslagen als operationeel record en bereikt hij nooit een advertentieplatform.",
    },
    setup: {
      title: "Instellen in een paar stappen",
      intro: "De assistent voert de gedetailleerde controles uit. Jij ziet de mijlpalen waarbij een beslissing van jou nodig is.",
      destination: [
        { title: "Identifiers invoeren", text: "Voeg de publieke ID's van het platform toe. De formaten worden gevalideerd tegen de documentatie van de leverancier voordat er iets wordt opgeslagen." },
        { title: "Credentials koppelen", text: "Plak het token in de beveiligde kaart of koppel het account via OAuth. Secrets gaan rechtstreeks de versleutelde kluis in." },
        { title: "Mappen en testen", text: "Standaardevents zijn vooraf gemapt op de eventnamen van het platform. Een gemarkeerd testevent doorloopt de echte pipeline en toont het antwoord van de leverancier." },
        { title: "Publiceren", text: "Bekijk de diff, keur goed en publiceer een ondertekende configuratieversie. Rol met één klik terug als dat nodig is." },
      ],
      source: [
        { title: "De shop koppelen", text: "Voer het shopdomein en de fallbackvaluta in. Track genereert de webhook-URL en het secret eenmalig." },
        { title: "De shopkant installeren", text: "Installeer de pixelextensie, plugin of app en registreer de webhooks met het gegenereerde secret." },
        { title: "Verifiëren met een testorder", text: "De eerste ondertekende webhook zet de koppeling op verbonden; de waargenomen topics en de laatste webhook worden live getoond." },
      ],
    },
    knowledge: {
      title: "Uit Tracking Knowledge",
      text: "Gidsen geschreven door het team dat deze connector bouwt.",
      all: "Alle Tracking Knowledge-artikelen",
      none: "Nog geen specifiek artikel — de Tracking Knowledge-hub behandelt server-side tracking, deduplicatie en toestemming in het algemeen.",
      minutes: (n) => `${n} min leestijd`,
    },
    faq: {
      title: "Vragen",
      destination: [
        { q: "Kan ik alleen server-side draaien?", a: "Ja. Kies de servermodus in de wizard; het script van de leverancier wordt nooit geladen en matching steunt op gehashte identifiers en click-ID's die de tracker vastlegt." },
        { q: "Hoe worden duplicaten voorkomen?", a: "De browsertag en het serverrequest dragen dezelfde event-ID, en aankopen voegen de order-ID toe. De worker dedupliceert bovendien herhaalde bronevents vóór de aflevering." },
        { q: "Wat als de API van de leverancier verandert?", a: "API-versies worden centraal vastgezet met de verificatiedatum; waarschuwingen over uitfasering verschijnen in de destination-health lang voordat een endpoint wordt uitgeschakeld." },
      ],
      source: [
        { q: "Heb ik de browseraankoop nog nodig?", a: "Die is optioneel maar waardevol: hij draagt het toestemmingsrecord en de click-ID's van de bezoeker, die de server niet kan kennen. Het geverifieerde shoprecord vervangt hem voor waarde en items." },
        { q: "Wordt dezelfde order dubbel geteld?", a: "Nee. Browseraankoop, server-API en shopwebhook delen de van de order afgeleide event-ID, en het conversierecord houdt één rij per order." },
        { q: "Wat gebeurt er als het platform een webhook opnieuw verstuurt?", a: "Herleveringen produceren deterministische event-ID's en komen terecht bij de dedup-guard op eventniveau; er wordt niets opnieuw geteld." },
      ],
    },
    cta: {
      title: (name) => `${name} koppelen`,
      text: "Stel het in met de begeleide wizard of laat de assistent het in de chat doen.",
      start: "Gratis starten",
      all: "Alle integraties",
    },
  },
};
