import { buildSignatureHeader, newUlid } from "@track-site/core";
import { DESTINATION_TRANSFER } from "@track-site/policy";
import { applyFieldMap } from "@track-site/config";
import type {
  Connector,
  ConnectorContext,
  ConnectorMeta,
  CredentialValidation,
  DispatchEvent,
  DispatchResult,
  EventMapping,
  ErrorClass,
  HealthResult,
  ValidationResult,
  VendorPayload,
} from "./connector.ts";
import { classifyHttpStatus, excerpt } from "./http.ts";
import { SsrfError, pinnedFetch, validateDestinationUrl } from "./ssrf.ts";
import { API_VERSIONS } from "./versions.ts";

/**
 * Generic signed webhook. Payloads carry only allow-listed fields, are signed with
 * `X-TrackSite-Signature: t=<ts>,n=<nonce>,v1=<hmac>` (timestamp + nonce, 5 min replay window)
 * and go through the SSRF guard with DNS pinning. Redirects are never followed.
 */
export const DEFAULT_ALLOWED_FIELDS = ["event_id", "name", "category", "client_ts", "server_ts", "url", "path", "host", "referrer", "utm", "props", "commerce", "consent", "source", "source_verified", "locale"];
const IDENTIFIER_FIELDS = ["anonymous_id", "session_id", "user_id", "user_data", "click_ids", "vendor_ids", "ip_truncated", "ua_family"];

export const webhookMeta: ConnectorMeta = {
  type: "webhook",
  displayName: "Generic webhook",
  apiVersion: API_VERSIONS.webhook.version,
  verifiedAt: API_VERSIONS.webhook.verifiedAt,
  sunsetWatch: null,
  docsUrl: API_VERSIONS.webhook.docsUrl,
  requiredPublicIds: [{ key: "url", label: "Endpoint URL", pattern: "^https://[^\\s]+$", example: "https://api.example.com/track-site", help: "Public https endpoint that receives signed JSON events." }],
  requiredCredentials: [{ kind: "signing_secret", label: "Signing secret", help: "Generated by track.site and shown once; verify every request with it.", secret: true, oauth: null }],
  supportsBrowser: false,
  supportsServer: true,
  dedupField: "id",
  transfer: DESTINATION_TRANSFER.webhook,
};

function pick(event: DispatchEvent["event"], fields: string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const f of fields) {
    const v = (event as unknown as Record<string, unknown>)[f];
    if (v !== undefined) out[f] = v;
  }
  return out;
}

export class WebhookConnector implements Connector {
  readonly meta = webhookMeta;

  async validateCredentials(ctx: ConnectorContext): Promise<CredentialValidation> {
    const secret = await ctx.getCredential("signing_secret");
    const url = String(ctx.publicConfig.url ?? "");
    const checkedAt = ctx.now().toISOString();
    if (!secret) return { ok: false, status: "not_connected", detail: "No signing secret generated yet", apiVersion: this.meta.apiVersion, checkedAt };
    try {
      await validateDestinationUrl(url, { allowPrivateNetwork: ctx.allowPrivateNetwork, allowHttp: ctx.allowPrivateNetwork });
    } catch (e) {
      return { ok: false, status: "invalid", detail: e instanceof Error ? e.message : "invalid url", apiVersion: this.meta.apiVersion, checkedAt };
    }
    return { ok: true, status: "valid", detail: "Endpoint resolves to a public address and a signing secret is configured", apiVersion: this.meta.apiVersion, checkedAt };
  }

  getBrowserConfig(): null {
    return null;
  }

  mapEvent(input: DispatchEvent, mapping: EventMapping, ctx: ConnectorContext): VendorPayload | null {
    if (!mapping.enabled) return null;
    const allowed = Array.isArray(ctx.settings.allowFields) ? (ctx.settings.allowFields as string[]) : DEFAULT_ALLOWED_FIELDS;
    const includeIdentifiers = ctx.settings.includeIdentifiers === true;
    const fields = includeIdentifiers ? [...allowed, ...IDENTIFIER_FIELDS] : allowed.filter((f) => !IDENTIFIER_FIELDS.includes(f));
    const data = pick(input.event, fields);
    const mapped = mapping.fieldMap ? applyFieldMap(mapping.fieldMap, { event: input.event, click_ids: input.clickIds }) : {};
    const body = {
      id: input.dedupId,
      type: mapping.vendorEvent || input.event.name,
      version: this.meta.apiVersion,
      site: input.event.site_tracking_id,
      environment: input.event.environment_id,
      sent_at: ctx.now().toISOString(),
      test: ctx.testMode,
      data: { ...data, ...mapped },
    };
    return {
      vendorEventName: body.type,
      dedupKey: input.dedupId,
      endpoint: String(ctx.publicConfig.url ?? ""),
      method: "POST",
      headers: { "content-type": "application/json", "user-agent": "track.site-webhook/1", "x-tracksite-event": body.type },
      body,
      preview: { ...body, data: { ...body.data, user_data: body.data.user_data ? "[hashed]" : undefined } },
      eventId: input.event.event_id,
    };
  }

  validatePayload(payload: VendorPayload): ValidationResult {
    const errors: string[] = [];
    if (!/^https?:\/\//.test(payload.endpoint)) errors.push("endpoint must be an http(s) url");
    const size = JSON.stringify(payload.body).length;
    if (size > 256_000) errors.push("payload exceeds 256 KB");
    return { ok: errors.length === 0, errors };
  }

  async sendTest(ctx: ConnectorContext, payload: VendorPayload): Promise<DispatchResult> {
    const test: VendorPayload = { ...payload, body: { ...(payload.body as Record<string, unknown>), test: true } };
    const [r] = await this.dispatchBatch(ctx, [test]);
    return r!;
  }

  async dispatchBatch(ctx: ConnectorContext, payloads: VendorPayload[]): Promise<DispatchResult[]> {
    const secret = await ctx.getCredential("signing_secret");
    const results: DispatchResult[] = [];
    for (const p of payloads) {
      const started = Date.now();
      if (!secret) {
        results.push({ ok: false, httpStatus: null, errorClass: "credential_expired", errorCode: "missing_secret", message: "signing secret missing", retryAfterMs: null, vendorEventId: null, responseExcerpt: null, durationMs: 0, eventId: p.eventId });
        continue;
      }
      let target;
      try {
        target = await validateDestinationUrl(p.endpoint, { allowPrivateNetwork: ctx.allowPrivateNetwork, allowHttp: ctx.allowPrivateNetwork });
      } catch (e) {
        const msg = e instanceof SsrfError ? e.message : "invalid destination";
        results.push({ ok: false, httpStatus: null, errorClass: "permanent", errorCode: "ssrf_blocked", message: msg, retryAfterMs: null, vendorEventId: null, responseExcerpt: null, durationMs: Date.now() - started, eventId: p.eventId });
        continue;
      }
      const body = JSON.stringify(p.body);
      const ts = Math.floor(ctx.now().getTime() / 1000);
      const signature = await buildSignatureHeader(body, secret, ts, newUlid());
      try {
        const res = await pinnedFetch(target, { method: "POST", headers: { ...p.headers, "x-tracksite-signature": signature }, body, timeoutMs: Number(ctx.settings.timeoutMs ?? 10_000) });
        const text = await res.text();
        const cls = this.classifyError(res.status, text);
        results.push({
          ok: cls === "none",
          httpStatus: res.status,
          errorClass: cls,
          errorCode: cls === "none" ? null : `http_${res.status}`,
          message: cls === "none" ? null : excerpt(text, 200),
          retryAfterMs: res.headers.get("retry-after") ? Number(res.headers.get("retry-after")) * 1000 : null,
          vendorEventId: null,
          responseExcerpt: excerpt(text),
          durationMs: Date.now() - started,
          eventId: p.eventId,
        });
      } catch (e) {
        const timeout = e instanceof Error && e.name === "AbortError";
        results.push({ ok: false, httpStatus: null, errorClass: timeout ? "timeout" : "temporary", errorCode: timeout ? "timeout" : "network", message: e instanceof Error ? e.message.slice(0, 200) : "network error", retryAfterMs: null, vendorEventId: null, responseExcerpt: null, durationMs: Date.now() - started, eventId: p.eventId });
      }
    }
    return results;
  }

  classifyError(httpStatus: number | null, _body: unknown, error?: unknown): ErrorClass {
    if (error instanceof SsrfError) return "permanent";
    if (httpStatus !== null && httpStatus >= 300 && httpStatus < 400) return "permanent"; // redirects are not followed
    return classifyHttpStatus(httpStatus);
  }

  async getHealth(ctx: ConnectorContext): Promise<HealthResult> {
    const v = await this.validateCredentials(ctx);
    return {
      status: v.ok ? "healthy" : v.status === "not_connected" ? "not_connected" : "unhealthy",
      detail: v.detail,
      checkedAt: v.checkedAt,
      apiVersion: this.meta.apiVersion,
      sunsetWatch: null,
    };
  }

  async rotateOrRevokeSecret(): Promise<{ ok: boolean; detail: string }> {
    // rotation is performed by the credential service (new secret generated, old kept 24 h); nothing vendor-side
    return { ok: true, detail: "Signing secret rotated locally; update the receiving endpoint." };
  }
}
