import type { SecondaryCopy } from "../types";
import { CONSENT_CALL, SERVER_CALL, SNIPPET, browserEvents } from "./samples";

/**
 * German (de) copy of the secondary area. Same shape as en.ts; see docs/14-localization.md.
 */

export const SECONDARY_COPY_DE: SecondaryCopy = {
  common: { onThisPage: "Auf dieser Seite", breadcrumb: "Navigationspfad", home: "Startseite", updated: "Stand", copy: "Code kopieren", copied: "Kopiert", utc: "UTC", related: "Verwandte Seiten" },
  docs: {
    title: "Dokumentation",
    intro: "Alles, was du brauchst, um Track zu installieren, Server-Events zu senden, Consent zu integrieren und Destinationen zu konfigurieren. Der Dashboard-Assistent verlinkt bei jedem Schritt hierher.",
    toc: "Auf dieser Seite",
    eyebrow: "Dokumentation",
    links: { integrations: "Alle Integrationen", support: "Engineering-Support fragen", knowledge: "Tracking Knowledge" },
    quickstart: {
      title: "Drei Schritte bis zum funktionierenden Setup",
      text: "Einmal installieren, Events senden, die genutzten Plattformen verbinden. Jeder Schritt lässt sich im Dashboard prüfen, bevor du weitergehst.",
      outcomeLabel: "Das kannst du prüfen",
      steps: [
        { title: "Snippet installieren", text: "Füge ein asynchrones Script-Tag in deine Seiten ein. Es lädt die signierte Konfiguration für deine Tracking-ID und respektiert Consent ab dem ersten Seitenaufruf.", outcome: "Seitenaufrufe erscheinen im Event-Debugger." },
        { title: "Events senden", text: "Nutze die Standardevents aus dem Browser, einem Shop-Plugin oder deinem Server. Käufe tragen eine Bestellnummer, damit Browser- und Server-Kopie dedupliziert werden.", outcome: "Jedes Event zeigt seinen Consent-Status und den Grund, warum es zugestellt oder zurückgehalten wurde." },
        { title: "Destination verbinden", text: "Der geführte Assistent prüft Zugangsdaten, mappt Events, sendet einen echten Testevent und veröffentlicht erst nach deiner Freigabe.", outcome: "Zustellzustand und letzte erfolgreiche Zustellung sind pro Destination sichtbar." },
      ],
    },
    flow: {
      title: "So reist ein Event",
      text: "Jedes Event nimmt denselben Weg, egal ob es aus dem Browser, einem Shop-Plugin oder deinem Server kommt: Track validiert und dedupliziert es, prüft die Consent-Policy und routet es zu den konfigurierten Destinationen.",
      caption: "Website → Track → Consent/Policy → Destinationen. Ein Event ohne den erforderlichen Consent-Zweck stoppt am Gate; es wird weder gespeichert noch weitergeleitet.",
      nodes: { website: "Website", websiteSub: "Browser · Server", track: "Track", trackSub: "validieren · dedupe · routen", consent: "Consent", destinations: "Destinationen" },
      labels: { granted: "Zweck erteilt", held: "zurückgehalten: kein Zweck" },
    },
    guidesTitle: "Anleitungen",
    guides: [
      { id: "install", title: "Snippet installieren", text: "Füge das asynchrone Script auf jeder Seite ein, idealerweise im Head. Es lädt die signierte Konfiguration für deine Tracking-ID, respektiert Consent und blockiert nie das Rendering. Ersetze TRACKING_ID durch die sechsstellige ID aus deinem Dashboard.", code: SNIPPET, language: "html", codeTitle: "Snippet" },
      { id: "events", title: "Browser-Events senden", text: "Standardevents (page_view, view_item, add_to_cart, begin_checkout, purchase, generate_lead, sign_up, subscribe, start_trial, contact, book_appointment, download, search, login) tragen validierte Parameter; Custom-Events verwenden Namen in lowercase snake_case.", code: browserEvents("wird clientseitig vor dem Transport gehasht"), language: "js", codeTitle: "Browser" },
      { id: "server", title: "Server-API und Offline-Conversions", text: "Lege in Einstellungen → Server-Source-Keys einen Key an und sende Events aus Backend, CRM oder Kasse. Übergib dieselbe Bestellnummer wie das Browser-Event zur Deduplizierung; setze props.offline für Offline-Conversions.", code: SERVER_CALL, language: "bash", codeTitle: "POST /v1/s" },
      { id: "consent", title: "Consent-Integration", text: "Nutze ein unterstütztes CMP (TCF 2.2, GPP/GPC, Cookiebot, OneTrust, Usercentrics) — der Tracker liest es automatisch — oder rufe die Consent-API aus deinem eigenen Banner auf. Zwecke: necessary, analytics, marketing, personalization. Ein Widerruf stoppt alles sofort.", code: CONSENT_CALL, language: "js", codeTitle: "Consent-API" },
      { id: "destinations", title: "Destinationen", text: "Jede Destination hat einen geführten Assistenten: Kennungen, Tresor-Zugangsdaten oder OAuth, Anbieter-Validierung, Event-Mapping mit geprüften Standards, echter Testevent, Lint, Diff und freigabepflichtige Veröffentlichung. Browser und Server teilen eine Event-ID; Käufe ergänzen die Bestellnummer.", bullets: ["Meta, Google Ads/YouTube, GA4, TikTok, Microsoft, LinkedIn, Reddit, Pinterest, Snapchat", "X, Taboola, Outbrain, Amazon Ads, Spotify, Quora", "Yahoo DSP, The Trade Desk, Google Marketing Platform, AdRoll, Criteo, Affiliate-Postbacks (13 Presets), Webhooks"] },
      { id: "shops", title: "Shopsysteme", text: "Shopify (App mit Order-Webhooks und Web Pixel), WooCommerce (Plugin mit signierten Order-Webhooks) und Shopware 6 (App mit Storefront-Script und Order-Webhooks) senden verifizierte Kauf- und Erstattungsevents mit Bestellnummern. Plugin installieren, Tracking-ID und Source-Key einfügen, fertig.", bullets: ["Verifizierte Quelle: Events sind source_verified und gelten als maßgebliche Conversion", "Erstattungen erzeugen Events mit negativem Wert für Anbieter, die das unterstützen", "Browser-Käufe aus dem Theme werden über die Bestellnummer dedupliziert"] },
      { id: "privacy", title: "Datenschutz-Center und DSAR", text: "Aufbewahrungsfristen pro Datenart, Consent-Policy-Versionen pro Site und Betroffenenanfragen (Export, Löschen, Einschränken, Berichtigen, Widerspruch, Übertragbarkeit) werden unter Consent & Datenschutz bearbeitet. Anfragen nutzen nur gehashte Kennungen und erzeugen einen auditierten Bericht." },
    ],
    reference: {
      title: "Endpunkte im Überblick",
      text: "Alle Antworten sind JSON; 202 bedeutet, dass der Batch dauerhaft in der Queue liegt.",
      columns: { endpoint: "Endpunkt", purpose: "Zweck", notes: "Hinweise" },
      rows: [
        { endpoint: "POST /v1/e", purpose: "Browser-Batches", notes: "≤ 50 Events pro Batch" },
        { endpoint: "POST /v1/s", purpose: "Server-Batches", notes: "≤ 100 Events pro Batch, Bearer-Source-Key" },
        { endpoint: "POST /v1/affiliate/in/{trackingId}/{preset}", purpose: "Eingehende Affiliate-Netzwerk-Postbacks", notes: "13 Netzwerk-Presets" },
        { endpoint: "GET /c/{trackingId}/manifest.json", purpose: "Konfigurations-Manifest und signiertes Bundle", notes: "Ed25519-signiert, vom Browser-SDK geprüft" },
      ],
    },
  },
  support: {
    title: "Support",
    intro: "Kunden erreichen hier den Engineering-Support. Gib die Tracking-ID deiner Site an (sechs Zeichen, im Dashboard sichtbar), damit wir die richtigen Events prüfen — niemals Access-Tokens einfügen.",
    placeholder: "Tracking-ID, Destination, was du erwartet hast und was passiert ist.",
    eyebrow: "Support",
    formTitle: "An den Engineering-Support schreiben",
    before: {
      title: "Bevor du schreibst",
      items: [
        { title: "Dokumentation", text: "Installation, Events, Consent und Destinationen mit Codebeispielen.", href: "/docs" },
        { title: "Systemstatus", text: "Live-Zustand von Collector, Queue und Zustell-Worker.", href: "/status" },
        { title: "Tracking Knowledge", text: "Anleitungen zu Deduplizierung, Consent Mode und Click-IDs.", href: "/tracking-knowledge" },
      ],
    },
    include: {
      title: "Was uns schnell antworten lässt",
      items: ["Deine Tracking-ID (sechs Zeichen, im Dashboard sichtbar)", "Die betroffene Destination und der Eventname", "Was du erwartet hast und was passiert ist, mit Uhrzeit", "Screenshots aus Debugger oder Assistent — niemals Access-Tokens oder andere Geheimnisse"],
    },
    reply: "Wir antworten per E-Mail an die Adresse, die du angibst.",
  },
  contact: {
    title: "Kontakt",
    intro: "Fragen zu Tarifen, Enterprise-Volumen, Auftragsverarbeitung oder Partnerschaften. Wir antworten innerhalb eines Werktags.",
    enterprise: "Enterprise-Anfrage: individuelles Volumen, SSO, SLA, dedizierte Verarbeitung.",
    eyebrow: "Kontakt",
    formTitle: "Nachricht senden",
    topics: {
      title: "Wobei wir helfen",
      items: [
        { title: "Tarife und Abrechnung", text: "Welcher Tarif zu deinem Eventvolumen passt, wie die Jahresabrechnung funktioniert, Rechnungen." },
        { title: "Enterprise", text: "Individuelles Volumen, SSO, SLA und dedizierte Verarbeitung." },
        { title: "Auftragsverarbeitung", text: "Der Auftragsverarbeitungsvertrag, Unterauftragsverarbeiter und EU-Hosting." },
        { title: "Partnerschaften", text: "Agenturen, Shopsysteme und Consent-Management-Anbieter." },
      ],
    },
    other: {
      title: "Suchst du etwas anderes?",
      items: [
        { title: "Demo buchen", text: "Dreißig Minuten mit einem Engineer auf deiner echten Site.", href: "/demo" },
        { title: "Support", text: "Technische Fragen zu einem bestehenden Setup.", href: "/support" },
      ],
    },
  },
  demo: {
    title: "Demo buchen",
    intro: "Dreißig Minuten mit einem Engineer: Wir richten eine Destination auf deiner echten Site ein, senden einen Testevent und gehen Consent, Deduplizierung und den Debugger durch.",
    agenda: ["Dein Stack: Plattform, CMP, aktuelle Tags und Schmerzpunkte", "Live-Einrichtung einer Destination mit dem Assistenten", "Consent-Policy, Click-IDs und Offline-Conversions für deinen Fall", "Preise, Migrationsplan und Auftragsverarbeitungsvertrag"],
    placeholder: "Welche Plattformen und welches Shopsystem nutzt ihr, und was sollen wir zeigen?",
    eyebrow: "Live-Demo",
    formTitle: "Termin anfragen",
    agendaTitle: "Was die dreißig Minuten abdecken",
    duration: "30 Minuten, online, mit einem Engineer",
    prepare: { title: "Hilfreich, wenn du es bereithältst", items: ["Zugang zu deiner Website oder einer Staging-Kopie", "Die Plattformen, auf denen du wirbst", "Deine Consent-Management-Plattform, falls du eine nutzt"] },
    honest: "Kein Verkaufsskript: Du gehst mit einer konfigurierten Destination und einer ehrlichen Einschätzung, was Track für deinen Stack leisten kann und was nicht.",
  },
  status: {
    title: "Systemstatus",
    intro: "Live-Zustand der Track-Komponenten, bei jedem Seitenaufruf geprüft. Vorfälle werden hier veröffentlicht, wenn sie auftreten.",
    component: "Komponente",
    state: "Zustand",
    checked: "Geprüft",
    ok: "betriebsbereit",
    degraded: "eingeschränkt",
    down: "nicht verfügbar",
    db: "Control-Plane-Datenbank",
    queue: "Event-Queue-Rückstand",
    worker: "Zustell-Worker (letzter Zustellversuch)",
    collector: "Collector (Ingest)",
    none: "noch keine Daten",
    incidents: "Vorfälle",
    noIncidents: "Keine Vorfälle verzeichnet.",
    note: "Der Status wird aus derselben Datenbank und Queue abgeleitet, die das Produkt nutzt; es gibt keinen separaten Statusdienst, der abweichen könnte.",
    eyebrow: "Status",
    componentsTitle: "Komponenten",
    detail: "Detail",
    pending: "{n} ausstehend",
    checkedAt: "Geprüft um",
    flow: { title: "Eventpfad und aktueller Zustand", caption: "Collector → Queue → Zustell-Worker → Destinationen; die Control-Plane-Datenbank hält Konfiguration und Zustellprotokolle. Farbe und Beschriftung jedes Knotens entsprechen der Tabelle oben.", collector: "Collector", queue: "Queue", worker: "Zustell-Worker", database: "Datenbank", destinations: "Destinationen" },
    incidentsText: "Ist eine Komponente eingeschränkt oder nicht verfügbar, werden Vorfall, Auswirkung und Behebung hier festgehalten.",
  },
  security: {
    title: "Sicherheit",
    intro: "Wie Track Kundendaten schützt: Architektur, Kontrollen und die Garantien, die du im Produkt nachprüfen kannst.",
    eyebrow: "Sicherheit",
    flow: {
      title: "Wo Daten auf ihrem Weg geschützt sind",
      text: "Vom ersten Request bis zur Zustellung hat jeder Schritt eine Kontrolle: Origin-Prüfung, Rate-Limits und HMAC-Signaturen am Collector, eine dauerhafte Queue, die Consent-Policy vor jedem Routing und Worker mit Retries, Circuit Breakern und Dead-Letter-Queue. Kill-Switches stoppen eine Site oder Organisation in Sekunden.",
      caption: "Signierte Konfiguration erreicht den Browser, Events erreichen den Collector, und nur Events, die die Policy passieren, erreichen eine Destination. Anbieter-Zugangsdaten verlassen den Tresor nur innerhalb des Workers.",
      nodes: { website: "Website", config: "Signierte Config", configSub: "Ed25519 · fail closed", collector: "Collector", collectorSub: "Origin · Rate-Limit · HMAC", queue: "Queue", queueSub: "dauerhaft", policy: "Policy", worker: "Worker", workerSub: "Retries · Breaker · DLQ", destination: "Destination", vault: "Tresor", vaultSub: "KMS-Envelope", kill: "Kill-Switch" },
    },
    controls: {
      title: "Kontrollen im Überblick",
      text: "Jede Kontrolle ist in den Abschnitten oben beschrieben; diese Tabelle ist die Kurzfassung.",
      columns: { control: "Kontrolle", scope: "Geltungsbereich", mechanism: "Mechanismus" },
      rows: [
        { control: "Mandantentrennung", scope: "Jede Mandantentabelle, Anwendungsrolle", mechanism: "Organisations-ID auf jeder Zeile, PostgreSQL Row-Level Security erzwungen" },
        { control: "Geheimnisspeicher", scope: "Anbieter-Zugangsdaten", mechanism: "Envelope Encryption (AES-256-GCM-Datenschlüssel, umhüllt von AWS KMS oder einem lokalen Master-Key); sichtbar sind nur Referenz und die letzten vier Zeichen" },
        { control: "Signierte Konfiguration", scope: "Browser-SDK", mechanism: "Unveränderliche, versionierte, Ed25519-signierte Bundles, per WebCrypto geprüft; Fail-closed" },
        { control: "Ingest-Schutz", scope: "Collector", mechanism: "Origin-Prüfung, Rate-Limits, HMAC-signierte Server-Requests, dauerhafte Queue vor der Antwort" },
        { control: "Zustellung", scope: "Worker", mechanism: "Retries, Circuit Breaker und Dead-Letter-Queue" },
        { control: "Kill-Switches", scope: "Pro Site oder Organisation", mechanism: "Stoppen Erfassung und Zustellung in Sekunden" },
        { control: "Datensparsamkeit", scope: "Event-Properties, IP-Adressen", mechanism: "PII-Scanner blockiert personenbezogene Daten vor dem Speichern; IPs beim Empfang gekürzt; kein Fingerprinting" },
        { control: "Audit", scope: "Audit-Log, Usage-Ledger", mechanism: "Append-only über Datenbank-Trigger" },
        { control: "Zugriff", scope: "Organisationsmitglieder", mechanism: "Sechs Rollen, MFA und Passkeys, Break-Glass-Zugriff mit Pflichtbegründung und Audit-Eintrag" },
      ],
    },
    report: { title: "Sicherheitslücken melden", text: "Bitte melde Schwachstellen verantwortungsvoll an", missing: "die im Impressum veröffentlichte Adresse", ack: "Wir bestätigen innerhalb von zwei Werktagen und nennen Meldende nie ohne Zustimmung." },
  },
  legal: {
    eyebrow: "Rechtliches",
    operator: { title: "Betreiber", company: "Unternehmen", address: "Anschrift", representatives: "Vertretungsberechtigte", email: "E-Mail", phone: "Telefon", register: "Registereintrag", vatId: "USt-IdNr.", dpo: "Datenschutzbeauftragte:r", missing: "Diese Angaben werden vom Betreiber vor dem Start veröffentlicht (Umgebungsvariablen LEGAL_*)." },
    related: { privacy: "Datenschutzerklärung", terms: "Nutzungsbedingungen", dpa: "Auftragsverarbeitung", subprocessors: "Unterauftragsverarbeiter", imprint: "Impressum", security: "Sicherheit" },
  },
  subprocessors: {
    title: "Unterauftragsverarbeiter",
    intro: "Dritte, die Kundendaten im Auftrag des Betreibers verarbeiten, sowie die Werbeanbieter, die Events nur erhalten, wenn ein Kunde sie als Destination konfiguriert.",
    processorsTitle: "Vom Betreiber eingesetzte Auftragsverarbeiter",
    columns: { name: "Anbieter", purpose: "Zweck", region: "Region", basis: "Übermittlungsgrundlage" },
    vendors: "Destinationsanbieter (vom Kunden gewählt)",
    vendorsText: "Jede Destination zeigt im Einrichtungsassistenten Datenempfänger, Region und Übermittlungsgrundlage. Daten erreichen einen Anbieter nur für aktivierte Destinationen und nur mit dem erforderlichen Consent-Zweck.",
    updated: "Kunden werden 30 Tage vor Änderungen informiert.",
  },
  imprint: {
    title: "Impressum",
    intro: "Angaben gemäß § 5 DDG und § 18 MStV zum Betreiber von track.site.",
    dispute: "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung bereit (https://ec.europa.eu/consumers/odr). Der Betreiber ist nicht verpflichtet und nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.",
    liability: "Trotz sorgfältiger Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links; für deren Inhalt sind ausschließlich die Betreiber der verlinkten Seiten verantwortlich.",
  },
};
