import type { SecondaryCopy } from "../types";
import { CONSENT_CALL, SERVER_CALL, SNIPPET, browserEvents } from "./samples";

/**
 * English (source language) copy of the secondary area. Same shape as every other locale file; see docs/14-localization.md.
 */

export const SECONDARY_COPY_EN: SecondaryCopy = {
  common: { onThisPage: "On this page", breadcrumb: "Breadcrumb", home: "Home", updated: "Last updated", copy: "Copy code", copied: "Copied", utc: "UTC", related: "Related pages" },
  docs: {
    title: "Documentation",
    intro: "Everything needed to install Track, send server events, integrate consent and configure destinations. The dashboard assistant links here for each step.",
    toc: "On this page",
    eyebrow: "Documentation",
    links: { integrations: "All integrations", support: "Ask engineering support", knowledge: "Tracking Knowledge" },
    quickstart: {
      title: "Three steps to a working setup",
      text: "Install once, send your events, connect the platforms you use. Each step can be verified in the dashboard before you move on.",
      outcomeLabel: "You can verify",
      steps: [
        { title: "Install the snippet", text: "Add one asynchronous script tag to your pages. It loads the signed configuration for your tracking ID and respects consent from the first page view.", outcome: "Page views appear in the event debugger." },
        { title: "Send your events", text: "Use the standard events from the browser, a shop plugin or your server. Purchases carry an order id so the browser and server copies are deduplicated.", outcome: "Every event shows its consent state and the reason it was delivered or held." },
        { title: "Connect a destination", text: "The guided wizard validates credentials, maps events, sends a real test event and publishes only after your approval.", outcome: "Delivery health and the last successful delivery are shown per destination." },
      ],
    },
    flow: {
      title: "How an event travels",
      text: "Every event takes the same route, whether it comes from the browser, a shop plugin or your server: Track validates and deduplicates it, evaluates the consent policy and routes it to the destinations you configured.",
      caption: "Website → Track → Consent/Policy → Destinations. An event without the required consent purpose stops at the gate; it is neither stored nor forwarded.",
      nodes: { website: "Website", websiteSub: "browser · server", track: "Track", trackSub: "validate · dedupe · route", consent: "Consent", destinations: "Destinations" },
      labels: { granted: "purpose granted", held: "held: no purpose" },
    },
    guidesTitle: "Guides",
    guides: [
      { id: "install", title: "Install the snippet", text: "Add the asynchronous script to every page, ideally in the head. It loads the signed configuration for your tracking ID, respects consent and never blocks rendering. Replace TRACKING_ID with the six-character ID from your dashboard.", code: SNIPPET, language: "html", codeTitle: "Snippet" },
      { id: "events", title: "Send browser events", text: "Standard events (page_view, view_item, add_to_cart, begin_checkout, purchase, generate_lead, sign_up, subscribe, start_trial, contact, book_appointment, download, search, login) carry validated parameters; custom events use lowercase snake_case names.", code: browserEvents("hashed client-side before transport"), language: "js", codeTitle: "Browser" },
      { id: "server", title: "Server API and offline conversions", text: "Create a source key in Settings → Server source keys and send events from your backend, CRM or POS. Provide the same order id as the browser event for deduplication; add props.offline for offline conversions.", code: SERVER_CALL, language: "bash", codeTitle: "POST /v1/s" },
      { id: "consent", title: "Consent integration", text: "Use a supported CMP (TCF 2.2, GPP/GPC, Cookiebot, OneTrust, Usercentrics) — the tracker reads it automatically — or call the consent API from your own banner. Purposes: necessary, analytics, marketing, personalization. Withdrawal stops everything immediately.", code: CONSENT_CALL, language: "js", codeTitle: "Consent API" },
      { id: "destinations", title: "Destinations", text: "Every destination has a guided wizard: identifiers, vault credentials or OAuth, vendor validation, event mapping with verified defaults, a real test event, lint, diff and approval-gated publish. Browser and server share one event id; purchases add the order id.", bullets: ["Meta, Google Ads/YouTube, GA4, TikTok, Microsoft, LinkedIn, Reddit, Pinterest, Snapchat", "X, Taboola, Outbrain, Amazon Ads, Spotify, Quora", "Yahoo DSP, The Trade Desk, Google Marketing Platform, AdRoll, Criteo, affiliate postbacks (13 presets), webhooks"] },
      { id: "shops", title: "Shop platforms", text: "Shopify (app with order webhooks and web pixel), WooCommerce (plugin with signed order webhooks) and Shopware 6 (app with storefront script and order webhooks) send verified purchase and refund events with order ids. Install the plugin, paste the tracking ID and source key, done.", bullets: ["Verified source: events are marked source_verified and used as the authoritative conversion", "Refunds create negative-value events for vendors that support them", "Browser purchases from the theme are deduplicated by order id"] },
      { id: "privacy", title: "Privacy center and DSAR", text: "Retention windows per data kind, consent policy versions per site and data subject requests (export, delete, restrict, rectify, object, portability) are handled in Consent & Privacy. Requests use hashed identifiers only and produce an audited report." },
    ],
    reference: {
      title: "Endpoints at a glance",
      text: "All responses are JSON; 202 means the batch is durably queued.",
      columns: { endpoint: "Endpoint", purpose: "Purpose", notes: "Notes" },
      rows: [
        { endpoint: "POST /v1/e", purpose: "Browser batches", notes: "≤ 50 events per batch" },
        { endpoint: "POST /v1/s", purpose: "Server batches", notes: "≤ 100 events per batch, Bearer source key" },
        { endpoint: "POST /v1/affiliate/in/{trackingId}/{preset}", purpose: "Inbound affiliate network postbacks", notes: "13 network presets" },
        { endpoint: "GET /c/{trackingId}/manifest.json", purpose: "Configuration manifest and signed bundle", notes: "Ed25519-signed, verified by the browser SDK" },
      ],
    },
  },
  support: {
    title: "Support",
    intro: "Customers reach engineering support here. Include your site's tracking ID (six characters, shown in the dashboard) so we can look at the right events — never paste access tokens.",
    placeholder: "Tracking ID, destination, what you expected and what happened.",
    eyebrow: "Support",
    formTitle: "Write to engineering support",
    before: {
      title: "Before you write",
      items: [
        { title: "Documentation", text: "Installation, events, consent and destinations with code samples.", href: "/docs" },
        { title: "System status", text: "Live health of collector, queue and delivery worker.", href: "/status" },
        { title: "Tracking Knowledge", text: "Guides on deduplication, consent mode and click ids.", href: "/tracking-knowledge" },
      ],
    },
    include: {
      title: "What helps us answer quickly",
      items: ["Your tracking ID (six characters, shown in the dashboard)", "The destination and the event name concerned", "What you expected and what happened, with a time", "Screenshots of the debugger or the wizard step — never access tokens or other secrets"],
    },
    reply: "We reply by e-mail to the address you enter.",
  },
  contact: {
    title: "Contact",
    intro: "Questions about plans, enterprise volume, data processing agreements or partnerships. We answer within one business day.",
    enterprise: "Enterprise request: individual volume, SSO, SLA, dedicated processing.",
    eyebrow: "Contact",
    formTitle: "Send a message",
    topics: {
      title: "What we can help with",
      items: [
        { title: "Plans and billing", text: "Which plan fits your event volume, how yearly billing works, invoices." },
        { title: "Enterprise", text: "Individual volume, SSO, SLA and dedicated processing." },
        { title: "Data processing", text: "The data processing agreement, subprocessors and EU hosting." },
        { title: "Partnerships", text: "Agencies, shop platforms and consent management providers." },
      ],
    },
    other: {
      title: "Looking for something else?",
      items: [
        { title: "Book a demo", text: "Thirty minutes with an engineer on your real site.", href: "/demo" },
        { title: "Support", text: "Technical questions about an existing setup.", href: "/support" },
      ],
    },
  },
  demo: {
    title: "Book a demo",
    intro: "Thirty minutes with an engineer: we set up a destination on your real site, send a test event and walk through consent, deduplication and the debugger.",
    agenda: ["Your stack: platform, CMP, current tags and pain points", "Live setup of one destination with the assistant", "Consent policy, click ids and offline conversions for your case", "Pricing, migration plan and data processing agreement"],
    placeholder: "Which platforms and shop system do you use, and what should we show?",
    eyebrow: "Live demo",
    formTitle: "Request a slot",
    agendaTitle: "What the thirty minutes cover",
    duration: "30 minutes, online, with an engineer",
    prepare: { title: "Useful to have ready", items: ["Access to your website or a staging copy", "The platforms you advertise on", "Your consent management platform, if you use one"] },
    honest: "No sales script: you leave with one configured destination and an honest assessment of what Track can and cannot do for your stack.",
  },
  status: {
    title: "System status",
    intro: "Live health of the Track components, checked on every page load. Incident history is published here when one occurs.",
    component: "Component",
    state: "State",
    checked: "Checked",
    ok: "operational",
    degraded: "degraded",
    down: "unavailable",
    db: "Control plane database",
    queue: "Event queue backlog",
    worker: "Delivery worker (last delivery attempt)",
    collector: "Collector (ingest)",
    none: "no data yet",
    incidents: "Incidents",
    noIncidents: "No incidents recorded.",
    note: "Status is derived from the same database and queue the product uses; there is no separate status service to disagree with.",
    eyebrow: "Status",
    componentsTitle: "Components",
    detail: "Detail",
    pending: "{n} pending",
    checkedAt: "Checked at",
    flow: { title: "Event path and current health", caption: "Collector → queue → delivery worker → destinations; the control plane database holds configuration and delivery records. Colour and label of every node match the table above.", collector: "Collector", queue: "Queue", worker: "Delivery worker", database: "Database", destinations: "Destinations" },
    incidentsText: "When a component is degraded or unavailable, the incident, its impact and the resolution are recorded here.",
  },
  security: {
    title: "Security",
    intro: "How Track protects customer data: architecture, controls and the guarantees you can verify in the product.",
    eyebrow: "Security",
    flow: {
      title: "Where data is protected on its way",
      text: "From the first request to the delivery, every hop has a control: origin checks, rate limits and HMAC signatures at the collector, a durable queue, the consent policy before any routing, and workers with retries, circuit breakers and a dead-letter queue. Kill switches stop a site or an organization within seconds.",
      caption: "Signed configuration reaches the browser, events reach the collector, and only events that pass the policy reach a destination. Vendor credentials leave the vault only inside the worker.",
      nodes: { website: "Website", config: "Signed config", configSub: "Ed25519 · fail closed", collector: "Collector", collectorSub: "origin · rate limit · HMAC", queue: "Queue", queueSub: "durable", policy: "Policy", worker: "Worker", workerSub: "retries · breaker · DLQ", destination: "Destination", vault: "Vault", vaultSub: "KMS envelope", kill: "Kill switch" },
    },
    controls: {
      title: "Controls at a glance",
      text: "Each control is described in the sections above; this table is the short version.",
      columns: { control: "Control", scope: "Scope", mechanism: "Mechanism" },
      rows: [
        { control: "Tenant isolation", scope: "Every tenant table, application role", mechanism: "Organization id on every row, PostgreSQL row-level security enforced" },
        { control: "Secret storage", scope: "Vendor credentials", mechanism: "Envelope encryption (AES-256-GCM data keys wrapped by AWS KMS or a local master key); only a reference and the last four characters are visible" },
        { control: "Signed configuration", scope: "Browser SDK", mechanism: "Immutable, versioned, Ed25519-signed bundles verified with WebCrypto; fail closed" },
        { control: "Ingest protection", scope: "Collector", mechanism: "Origin validation, rate limits, HMAC-signed server requests, durable queue before the response" },
        { control: "Delivery", scope: "Workers", mechanism: "Retries, circuit breakers and a dead-letter queue" },
        { control: "Kill switches", scope: "Per site or organization", mechanism: "Stop collection and delivery within seconds" },
        { control: "Data minimisation", scope: "Event properties, IP addresses", mechanism: "PII scanner blocks personal data before storage; IPs truncated on ingest; no fingerprinting" },
        { control: "Audit", scope: "Audit log, usage ledger", mechanism: "Append-only through database triggers" },
        { control: "Access", scope: "Organization members", mechanism: "Six roles, MFA and passkeys, break-glass access with mandatory reason and audit entry" },
      ],
    },
    report: { title: "Report a vulnerability", text: "Please report vulnerabilities responsibly to", missing: "the address published in the imprint", ack: "We acknowledge within two business days and never name reporters without consent." },
  },
  legal: {
    eyebrow: "Legal",
    operator: { title: "Operator", company: "Company", address: "Address", representatives: "Represented by", email: "E-mail", phone: "Phone", register: "Register", vatId: "VAT ID", dpo: "Data protection officer", missing: "These details are published by the operator before launch (LEGAL_* environment variables)." },
    related: { privacy: "Privacy policy", terms: "Terms of service", dpa: "Data processing agreement", subprocessors: "Subprocessors", imprint: "Imprint", security: "Security" },
  },
  subprocessors: {
    title: "Subprocessors",
    intro: "Third parties that process customer data on behalf of the operator, and the advertising vendors that receive events only when a customer configures them as a destination.",
    processorsTitle: "Processors engaged by the operator",
    columns: { name: "Provider", purpose: "Purpose", region: "Region", basis: "Transfer basis" },
    vendors: "Destination vendors (customer-selected)",
    vendorsText: "Each destination shows its data recipient, region and transfer basis in the setup wizard. Data reaches a vendor only for destinations you enable, only with the consent purpose the destination requires.",
    updated: "Customers are notified 30 days before changes.",
  },
  imprint: {
    title: "Imprint",
    intro: "Legal information about the operator of track.site pursuant to § 5 DDG and § 18 MStV.",
    dispute: "The European Commission provides a platform for online dispute resolution (https://ec.europa.eu/consumers/odr). The operator is neither obliged nor willing to participate in dispute resolution proceedings before a consumer arbitration board.",
    liability: "Despite careful control we assume no liability for the content of external links; the operators of the linked pages are solely responsible for their content.",
  },
};
