import type { SecondaryCopy } from "../types";
import { CONSENT_CALL, SERVER_CALL, SNIPPET, browserEvents } from "./samples";

/**
 * French (fr) copy of the secondary area. Same shape as en.ts; see docs/14-localization.md.
 * Register: vous. French typography (non-breaking space before : ; ? ! and inside « »).
 */

export const SECONDARY_COPY_FR: SecondaryCopy = {
  common: { onThisPage: "Sur cette page", breadcrumb: "Fil d’Ariane", home: "Accueil", updated: "Dernière mise à jour", copy: "Copier le code", copied: "Copié", utc: "UTC", related: "Pages associées" },
  docs: {
    title: "Documentation",
    intro: "Tout ce qu’il faut pour installer Track, envoyer des événements serveur, intégrer le consentement et configurer des destinations. L’assistant du tableau de bord renvoie ici à chaque étape.",
    toc: "Sur cette page",
    eyebrow: "Documentation",
    links: { integrations: "Toutes les intégrations", support: "Contacter le support technique", knowledge: "Tracking Knowledge" },
    quickstart: {
      title: "Trois étapes pour une configuration opérationnelle",
      text: "Installez une fois, envoyez vos événements, connectez les plateformes que vous utilisez. Chaque étape peut être vérifiée dans le tableau de bord avant de passer à la suivante.",
      outcomeLabel: "Vous pouvez vérifier",
      steps: [
        { title: "Installer le snippet", text: "Ajoutez une balise script asynchrone à vos pages. Elle charge la configuration signée de votre identifiant de tracking et respecte le consentement dès la première page vue.", outcome: "Les pages vues apparaissent dans le Live Event Debugger." },
        { title: "Envoyer vos événements", text: "Utilisez les événements standard depuis le navigateur, un plugin e-commerce ou votre serveur. Les achats portent un identifiant de commande, de sorte que les copies navigateur et serveur sont dédupliquées.", outcome: "Chaque événement affiche son état de consentement et la raison pour laquelle il a été livré ou retenu." },
        { title: "Connecter une destination", text: "L’assistant guidé valide les identifiants d’accès, mappe les événements, envoie un véritable événement de test et ne publie qu’après votre approbation.", outcome: "L’état de santé de la livraison et la dernière livraison réussie sont affichés par destination." },
      ],
    },
    flow: {
      title: "Le parcours d’un événement",
      text: "Chaque événement suit le même chemin, qu’il vienne du navigateur, d’un plugin e-commerce ou de votre serveur : Track le valide et le déduplique, évalue la politique de consentement et le route vers les destinations que vous avez configurées.",
      caption: "Site web → Track → Consentement/Règles → Destinations. Un événement sans la finalité de consentement requise s’arrête au contrôle ; il n’est ni stocké ni transmis.",
      nodes: { website: "Site web", websiteSub: "navigateur · serveur", track: "Track", trackSub: "valider · dédupliquer · router", consent: "Consentement", destinations: "Destinations" },
      labels: { granted: "finalité accordée", held: "retenu : pas de finalité" },
    },
    guidesTitle: "Guides",
    guides: [
      { id: "install", title: "Installer le snippet", text: "Ajoutez le script asynchrone sur chaque page, idéalement dans le head. Il charge la configuration signée de votre identifiant de tracking, respecte le consentement et ne bloque jamais le rendu. Remplacez TRACKING_ID par l’identifiant à six caractères de votre tableau de bord.", code: SNIPPET, language: "html", codeTitle: "Snippet" },
      { id: "events", title: "Envoyer des événements navigateur", text: "Les événements standard (page_view, view_item, add_to_cart, begin_checkout, purchase, generate_lead, sign_up, subscribe, start_trial, contact, book_appointment, download, search, login) portent des paramètres validés ; les événements personnalisés utilisent des noms en snake_case minuscule.", code: browserEvents("haché côté client avant le transport"), language: "js", codeTitle: "Navigateur" },
      { id: "server", title: "API serveur et conversions hors ligne", text: "Créez une clé de source dans Paramètres → Clés de source serveur et envoyez des événements depuis votre backend, votre CRM ou votre caisse. Fournissez le même identifiant de commande que l’événement navigateur pour la déduplication ; ajoutez props.offline pour les conversions hors ligne.", code: SERVER_CALL, language: "bash", codeTitle: "POST /v1/s" },
      { id: "consent", title: "Intégration du consentement", text: "Utilisez une CMP prise en charge (TCF 2.2, GPP/GPC, Cookiebot, OneTrust, Usercentrics) — le tracker la lit automatiquement — ou appelez l’API de consentement depuis votre propre bandeau. Finalités : necessary, analytics, marketing, personalization. Un retrait arrête tout immédiatement.", code: CONSENT_CALL, language: "js", codeTitle: "API de consentement" },
      { id: "destinations", title: "Destinations", text: "Chaque destination dispose d’un assistant guidé : identifiants, identifiants d’accès dans le coffre-fort ou OAuth, validation par le fournisseur, mapping des événements avec des valeurs par défaut vérifiées, un véritable événement de test, lint, diff et publication soumise à approbation. Navigateur et serveur partagent un même identifiant d’événement ; les achats ajoutent l’identifiant de commande.", bullets: ["Meta, Google Ads/YouTube, GA4, TikTok, Microsoft, LinkedIn, Reddit, Pinterest, Snapchat", "X, Taboola, Outbrain, Amazon Ads, Spotify, Quora", "Yahoo DSP, The Trade Desk, Google Marketing Platform, AdRoll, Criteo, postbacks d’affiliation (13 presets), webhooks"] },
      { id: "shops", title: "Plateformes e-commerce", text: "Shopify (application avec webhooks de commande et web pixel), WooCommerce (plugin avec webhooks de commande signés) et Shopware 6 (application avec script de boutique et webhooks de commande) envoient des événements d’achat et de remboursement vérifiés, avec identifiants de commande. Installez le plugin, collez l’identifiant de tracking et la clé de source, c’est terminé.", bullets: ["Source vérifiée : les événements sont marqués source_verified et utilisés comme conversion de référence", "Les remboursements créent des événements à valeur négative pour les fournisseurs qui les prennent en charge", "Les achats navigateur issus du thème sont dédupliqués par identifiant de commande"] },
      { id: "privacy", title: "Centre de confidentialité et demandes d’exercice des droits", text: "Les durées de conservation par type de données, les versions de politique de consentement par site et les demandes des personnes concernées (export, suppression, limitation, rectification, opposition, portabilité) sont gérées dans Consentement et confidentialité. Les demandes utilisent uniquement des identifiants hachés et produisent un rapport audité." },
    ],
    reference: {
      title: "Les endpoints en un coup d’œil",
      text: "Toutes les réponses sont en JSON ; 202 signifie que le lot est durablement mis en file d’attente.",
      columns: { endpoint: "Endpoint", purpose: "Rôle", notes: "Remarques" },
      rows: [
        { endpoint: "POST /v1/e", purpose: "Lots navigateur", notes: "≤ 50 événements par lot" },
        { endpoint: "POST /v1/s", purpose: "Lots serveur", notes: "≤ 100 événements par lot, clé de source en Bearer" },
        { endpoint: "POST /v1/affiliate/in/{trackingId}/{preset}", purpose: "Postbacks entrants des réseaux d’affiliation", notes: "13 presets réseau" },
        { endpoint: "GET /c/{trackingId}/manifest.json", purpose: "Manifeste de configuration et bundle signé", notes: "Signé Ed25519, vérifié par le SDK navigateur" },
      ],
    },
  },
  support: {
    title: "Support",
    intro: "Les clients contactent ici le support technique. Indiquez l’identifiant de tracking de votre site (six caractères, affiché dans le tableau de bord) pour que nous examinions les bons événements — ne collez jamais de jetons d’accès.",
    placeholder: "Identifiant de tracking, destination, ce que vous attendiez et ce qui s’est passé.",
    eyebrow: "Support",
    formTitle: "Écrire au support technique",
    before: {
      title: "Avant d’écrire",
      items: [
        { title: "Documentation", text: "Installation, événements, consentement et destinations, avec exemples de code.", href: "/docs" },
        { title: "État du système", text: "État de santé en direct du collecteur, de la file d’attente et du worker de livraison.", href: "/status" },
        { title: "Tracking Knowledge", text: "Guides sur la déduplication, le Consent Mode et les identifiants de clic.", href: "/tracking-knowledge" },
      ],
    },
    include: {
      title: "Ce qui nous aide à répondre rapidement",
      items: ["Votre identifiant de tracking (six caractères, affiché dans le tableau de bord)", "La destination et le nom de l’événement concernés", "Ce que vous attendiez et ce qui s’est passé, avec l’heure", "Des captures d’écran du débogueur ou de l’étape de l’assistant guidé — jamais de jetons d’accès ni d’autres secrets"],
    },
    reply: "Nous répondons par e-mail à l’adresse que vous indiquez.",
  },
  contact: {
    title: "Contact",
    intro: "Questions sur les formules, les volumes Enterprise, les accords de traitement des données ou les partenariats. Nous répondons sous un jour ouvré.",
    enterprise: "Demande Enterprise : volume individuel, SSO, SLA, traitement dédié.",
    eyebrow: "Contact",
    formTitle: "Envoyer un message",
    topics: {
      title: "Ce sur quoi nous pouvons vous aider",
      items: [
        { title: "Formules et facturation", text: "Quelle formule correspond à votre volume d’événements, comment fonctionne la facturation annuelle, les factures." },
        { title: "Enterprise", text: "Volume individuel, SSO, SLA et traitement dédié." },
        { title: "Traitement des données", text: "L’accord de traitement des données, les sous-traitants ultérieurs et l’hébergement dans l’UE." },
        { title: "Partenariats", text: "Agences, plateformes e-commerce et fournisseurs de gestion du consentement." },
      ],
    },
    other: {
      title: "Vous cherchez autre chose ?",
      items: [
        { title: "Réserver une démo", text: "Trente minutes avec un ingénieur sur votre site réel.", href: "/demo" },
        { title: "Support", text: "Questions techniques sur une configuration existante.", href: "/support" },
      ],
    },
  },
  demo: {
    title: "Réserver une démo",
    intro: "Trente minutes avec un ingénieur : nous configurons une destination sur votre site réel, envoyons un événement de test et passons en revue le consentement, la déduplication et le débogueur.",
    agenda: ["Votre stack : plateforme, CMP, tags actuels et points de friction", "Configuration en direct d’une destination avec l’assistant", "Politique de consentement, identifiants de clic et conversions hors ligne pour votre cas", "Tarifs, plan de migration et accord de traitement des données"],
    placeholder: "Quelles plateformes et quel plateforme e-commerce utilisez-vous, et que souhaitez-vous voir ?",
    eyebrow: "Démo en direct",
    formTitle: "Demander un créneau",
    agendaTitle: "Le programme des trente minutes",
    duration: "30 minutes, en ligne, avec un ingénieur",
    prepare: { title: "Utile à avoir sous la main", items: ["Un accès à votre site web ou à une copie de staging", "Les plateformes sur lesquelles vous faites de la publicité", "Votre plateforme de gestion du consentement, si vous en utilisez une"] },
    honest: "Pas de discours commercial : vous repartez avec une destination configurée et une évaluation honnête de ce que Track peut et ne peut pas faire pour votre stack.",
  },
  status: {
    title: "État du système",
    intro: "État de santé en direct des composants de Track, vérifié à chaque chargement de page. L’historique des incidents est publié ici lorsqu’il y en a.",
    component: "Composant",
    state: "État",
    checked: "Vérifié",
    ok: "opérationnel",
    degraded: "dégradé",
    down: "indisponible",
    db: "Base de données du control plane",
    queue: "Retard de la file d’attente d’événements",
    worker: "Worker de livraison (dernière tentative de livraison)",
    collector: "Collecteur (ingestion)",
    none: "pas encore de données",
    incidents: "Incidents",
    noIncidents: "Aucun incident enregistré.",
    note: "L’état est dérivé de la même base de données et de la même file d’attente que celles utilisées par le produit ; il n’existe pas de service de statut séparé qui pourrait les contredire.",
    eyebrow: "Statut",
    componentsTitle: "Composants",
    detail: "Détail",
    pending: "{n} en attente",
    checkedAt: "Vérifié à",
    flow: { title: "Chemin des événements et état actuel", caption: "Collecteur → file d’attente → worker de livraison → destinations ; la base de données du control plane contient la configuration et les enregistrements de livraison. La couleur et le libellé de chaque nœud correspondent au tableau ci-dessus.", collector: "Collecteur", queue: "File d’attente", worker: "Worker de livraison", database: "Base de données", destinations: "Destinations" },
    incidentsText: "Lorsqu’un composant est dégradé ou indisponible, l’incident, son impact et sa résolution sont consignés ici.",
  },
  security: {
    title: "Sécurité",
    intro: "Comment Track protège les données de ses clients : architecture, contrôles et garanties que vous pouvez vérifier dans le produit.",
    eyebrow: "Sécurité",
    flow: {
      title: "Où les données sont protégées sur leur trajet",
      text: "De la première requête à la livraison, chaque étape a son contrôle : vérification des origines, limitation de débit et signatures HMAC au collecteur, une file d’attente durable, la politique de consentement avant tout routage, et des workers avec nouvelles tentatives, circuit breakers et dead-letter queue. Les kill switches arrêtent un site ou une organisation en quelques secondes.",
      caption: "La configuration signée atteint le navigateur, les événements atteignent le collecteur, et seuls les événements qui passent la politique atteignent une destination. Les identifiants d’accès des fournisseurs ne quittent le coffre-fort qu’à l’intérieur du worker.",
      nodes: { website: "Site web", config: "Config signée", configSub: "Ed25519 · fail closed", collector: "Collecteur", collectorSub: "origine · limitation de débit · HMAC", queue: "File d’attente", queueSub: "durable", policy: "Politique", worker: "Worker", workerSub: "tentatives · circuit breaker · DLQ", destination: "Destination", vault: "Coffre-fort", vaultSub: "enveloppe KMS", kill: "Kill switch" },
    },
    controls: {
      title: "Les contrôles en un coup d’œil",
      text: "Chaque contrôle est décrit dans les sections ci-dessus ; ce tableau en est la version courte.",
      columns: { control: "Contrôle", scope: "Périmètre", mechanism: "Mécanisme" },
      rows: [
        { control: "Isolation des tenants", scope: "Chaque table tenant, rôle applicatif", mechanism: "Identifiant d’organisation sur chaque ligne, sécurité au niveau des lignes PostgreSQL appliquée" },
        { control: "Stockage des secrets", scope: "Identifiants d’accès des fournisseurs", mechanism: "Chiffrement par enveloppe (clés de données AES-256-GCM enveloppées par AWS KMS ou une clé maître locale) ; seuls une référence et les quatre derniers caractères sont visibles" },
        { control: "Configuration signée", scope: "SDK navigateur", mechanism: "Bundles immuables, versionnés et signés Ed25519, vérifiés avec WebCrypto ; fail closed" },
        { control: "Protection de l’ingestion", scope: "Collecteur", mechanism: "Validation des origines, limitation de débit, requêtes serveur signées HMAC, file d’attente durable avant la réponse" },
        { control: "Livraison", scope: "Workers", mechanism: "Nouvelles tentatives, circuit breakers et dead-letter queue" },
        { control: "Kill switches", scope: "Par site ou organisation", mechanism: "Arrêt de la collecte et de la livraison en quelques secondes" },
        { control: "Minimisation des données", scope: "Propriétés d’événement, adresses IP", mechanism: "Le scanner PII bloque les données personnelles avant stockage ; les IP sont tronquées à l’ingestion ; pas de fingerprinting" },
        { control: "Audit", scope: "Journal d’audit, registre d’utilisation", mechanism: "Ajout seul (append-only) via des triggers de base de données" },
        { control: "Accès", scope: "Membres de l’organisation", mechanism: "Six rôles, MFA et passkeys, accès d’urgence (break-glass) avec motif obligatoire et entrée d’audit" },
      ],
    },
    report: { title: "Signaler une vulnérabilité", text: "Merci de signaler les vulnérabilités de manière responsable à", missing: "l’adresse publiée dans les mentions légales", ack: "Nous accusons réception sous deux jours ouvrés et ne nommons jamais les personnes à l’origine d’un signalement sans leur consentement." },
  },
  legal: {
    eyebrow: "Juridique",
    operator: { title: "Exploitant", company: "Société", address: "Adresse", representatives: "Représentée par", email: "E-mail", phone: "Téléphone", register: "Registre", vatId: "Numéro de TVA", dpo: "Délégué à la protection des données", missing: "Ces informations sont publiées par l’exploitant avant le lancement (variables d’environnement LEGAL_*)." },
    related: { privacy: "Politique de confidentialité", terms: "Conditions générales d’utilisation", dpa: "Accord de traitement des données", subprocessors: "Sous-traitants ultérieurs", imprint: "Mentions légales", security: "Sécurité" },
  },
  subprocessors: {
    title: "Sous-traitants ultérieurs",
    intro: "Les tiers qui traitent des données clients pour le compte de l’exploitant, et les plateformes publicitaires qui ne reçoivent des événements que lorsqu’un client les configure comme destination.",
    processorsTitle: "Sous-traitants engagés par l’exploitant",
    columns: { name: "Prestataire", purpose: "Finalité", region: "Région", basis: "Base du transfert" },
    vendors: "Fournisseurs de destination (choisis par le client)",
    vendorsText: "Chaque destination affiche son destinataire des données, sa région et sa base de transfert dans l’assistant guidé. Les données n’atteignent un fournisseur que pour les destinations que vous activez, et uniquement avec la finalité de consentement que la destination requiert.",
    updated: "Les clients sont informés 30 jours avant toute modification.",
  },
  imprint: {
    title: "Mentions légales",
    intro: "Informations légales sur l’exploitant de www.track.site conformément aux § 5 DDG et § 18 MStV.",
    dispute: "La Commission européenne met à disposition une plateforme de règlement en ligne des litiges (https://ec.europa.eu/consumers/odr). L’exploitant n’est ni tenu ni disposé à participer à une procédure de règlement des litiges devant un organisme de conciliation des consommateurs.",
    liability: "Malgré un contrôle attentif, nous n’assumons aucune responsabilité quant au contenu des liens externes ; les exploitants des pages liées sont seuls responsables de leur contenu.",
  },
};
