import type { SecondaryCopy } from "../types";
import { CONSENT_CALL, SERVER_CALL, SNIPPET, browserEvents } from "./samples";

/**
 * Dutch (nl) copy of the secondary area, informal "je/jij" like the rest of the Dutch copy. Same shape as en.ts;
 * see docs/14-localization.md.
 */

export const SECONDARY_COPY_NL: SecondaryCopy = {
  common: { onThisPage: "Op deze pagina", breadcrumb: "Kruimelpad", home: "Home", updated: "Laatst bijgewerkt", copy: "Code kopiëren", copied: "Gekopieerd", utc: "UTC", related: "Gerelateerde pagina's" },
  docs: {
    title: "Documentatie",
    intro: "Alles wat je nodig hebt om Track te installeren, serverevents te versturen, toestemming te integreren en destinations te configureren. De dashboardassistent linkt bij elke stap hiernaartoe.",
    toc: "Op deze pagina",
    eyebrow: "Documentatie",
    links: { integrations: "Alle integraties", support: "Vraag het engineering-support", knowledge: "Tracking Knowledge" },
    quickstart: {
      title: "Drie stappen naar een werkende setup",
      text: "Eén keer installeren, je events versturen, de platformen koppelen die je gebruikt. Elke stap kun je in het dashboard controleren voordat je verdergaat.",
      outcomeLabel: "Dit kun je controleren",
      steps: [
        { title: "Installeer de snippet", text: "Voeg één asynchrone scripttag toe aan je pagina's. Die laadt de ondertekende configuratie voor je tracking-ID en respecteert toestemming vanaf de eerste paginaweergave.", outcome: "Paginaweergaven verschijnen in de event-debugger." },
        { title: "Verstuur je events", text: "Gebruik de standaardevents vanuit de browser, een shopplugin of je server. Aankopen dragen een order-ID, zodat de browser- en serverkopie worden gededupliceerd.", outcome: "Elk event toont zijn toestemmingsstatus en de reden waarom het is afgeleverd of vastgehouden." },
        { title: "Koppel een destination", text: "De begeleide wizard valideert credentials, mapt events, verstuurt een echt testevent en publiceert pas na jouw goedkeuring.", outcome: "Afleverstatus en de laatste geslaagde aflevering worden per destination getoond." },
      ],
    },
    flow: {
      title: "Hoe een event reist",
      text: "Elk event volgt dezelfde route, of het nu uit de browser, een shopplugin of je server komt: Track valideert en dedupliceert het, evalueert het toestemmingsbeleid en routeert het naar de destinations die je hebt geconfigureerd.",
      caption: "Website → Track → Toestemming/Policy → Destinations. Een event zonder het vereiste toestemmingsdoel stopt bij de gate; het wordt niet opgeslagen en niet doorgestuurd.",
      nodes: { website: "Website", websiteSub: "browser · server", track: "Track", trackSub: "valideren · dedupliceren · routeren", consent: "Toestemming", destinations: "Destinations" },
      labels: { granted: "doel toegestaan", held: "vastgehouden: geen doel" },
    },
    guidesTitle: "Handleidingen",
    guides: [
      { id: "install", title: "Installeer de snippet", text: "Voeg het asynchrone script toe aan elke pagina, bij voorkeur in de head. Het laadt de ondertekende configuratie voor je tracking-ID, respecteert toestemming en blokkeert nooit het renderen. Vervang TRACKING_ID door de ID van zes tekens uit je dashboard.", code: SNIPPET, language: "html", codeTitle: "Snippet" },
      { id: "events", title: "Browserevents versturen", text: "Standaardevents (page_view, view_item, add_to_cart, begin_checkout, purchase, generate_lead, sign_up, subscribe, start_trial, contact, book_appointment, download, search, login) dragen gevalideerde parameters; custom events gebruiken namen in lowercase snake_case.", code: browserEvents("wordt client-side gehasht vóór verzending"), language: "js", codeTitle: "Browser" },
      { id: "server", title: "Server-API en offline conversies", text: "Maak een source key aan onder Instellingen → Server source keys en verstuur events vanuit je backend, CRM of kassasysteem. Geef dezelfde order-ID mee als het browserevent voor deduplicatie; voeg props.offline toe voor offline conversies.", code: SERVER_CALL, language: "bash", codeTitle: "POST /v1/s" },
      { id: "consent", title: "Toestemming integreren", text: "Gebruik een ondersteund CMP (TCF 2.2, GPP/GPC, Cookiebot, OneTrust, Usercentrics) — de tracker leest het automatisch uit — of roep de consent-API aan vanuit je eigen banner. Doelen: necessary, analytics, marketing, personalization. Intrekken stopt alles onmiddellijk.", code: CONSENT_CALL, language: "js", codeTitle: "Consent-API" },
      { id: "destinations", title: "Destinations", text: "Elke destination heeft een begeleide wizard: identifiers, credentials uit de kluis of OAuth, validatie bij de leverancier, eventmapping met geverifieerde standaardwaarden, een echt testevent, lint, diff en publiceren na goedkeuring. Browser en server delen één event-ID; aankopen voegen de order-ID toe.", bullets: ["Meta, Google Ads/YouTube, GA4, TikTok, Microsoft, LinkedIn, Reddit, Pinterest, Snapchat", "X, Taboola, Outbrain, Amazon Ads, Spotify, Quora", "Yahoo DSP, The Trade Desk, Google Marketing Platform, AdRoll, Criteo, affiliate-postbacks (13 presets), webhooks"] },
      { id: "shops", title: "Shopplatformen", text: "Shopify (app met orderwebhooks en web pixel), WooCommerce (plugin met ondertekende orderwebhooks) en Shopware 6 (app met storefront-script en orderwebhooks) versturen geverifieerde aankoop- en terugbetalingsevents met order-ID's. Plugin installeren, tracking-ID en source key plakken, klaar.", bullets: ["Geverifieerde bron: events worden gemarkeerd als source_verified en gelden als de gezaghebbende conversie", "Terugbetalingen maken events met negatieve waarde aan voor leveranciers die dat ondersteunen", "Browseraankopen uit het thema worden gededupliceerd op order-ID"] },
      { id: "privacy", title: "Privacycenter en DSAR", text: "Bewaartermijnen per gegevenssoort, versies van het toestemmingsbeleid per site en verzoeken van betrokkenen (export, verwijderen, beperken, rectificeren, bezwaar maken, overdraagbaarheid) worden afgehandeld onder Toestemming & privacy. Verzoeken gebruiken alleen gehashte identifiers en leveren een geauditeerd rapport op." },
    ],
    reference: {
      title: "Endpoints in één oogopslag",
      text: "Alle antwoorden zijn JSON; 202 betekent dat de batch duurzaam in de queue staat.",
      columns: { endpoint: "Endpoint", purpose: "Doel", notes: "Opmerkingen" },
      rows: [
        { endpoint: "POST /v1/e", purpose: "Browserbatches", notes: "≤ 50 events per batch" },
        { endpoint: "POST /v1/s", purpose: "Serverbatches", notes: "≤ 100 events per batch, Bearer source key" },
        { endpoint: "POST /v1/affiliate/in/{trackingId}/{preset}", purpose: "Inkomende postbacks van affiliatenetwerken", notes: "13 netwerkpresets" },
        { endpoint: "GET /c/{trackingId}/manifest.json", purpose: "Configuratiemanifest en ondertekende bundle", notes: "Ed25519-ondertekend, geverifieerd door de browser-SDK" },
      ],
    },
  },
  support: {
    title: "Support",
    intro: "Klanten bereiken hier engineering-support. Vermeld de tracking-ID van je site (zes tekens, zichtbaar in het dashboard), zodat we naar de juiste events kunnen kijken — plak nooit toegangstokens.",
    placeholder: "Tracking-ID, destination, wat je verwachtte en wat er gebeurde.",
    eyebrow: "Support",
    formTitle: "Schrijf naar engineering-support",
    before: {
      title: "Voordat je schrijft",
      items: [
        { title: "Documentatie", text: "Installatie, events, toestemming en destinations met codevoorbeelden.", href: "/docs" },
        { title: "Systeemstatus", text: "Live status van collector, queue en delivery-worker.", href: "/status" },
        { title: "Tracking Knowledge", text: "Gidsen over deduplicatie, Consent Mode en click-ID's.", href: "/tracking-knowledge" },
      ],
    },
    include: {
      title: "Waarmee we snel kunnen antwoorden",
      items: ["Je tracking-ID (zes tekens, zichtbaar in het dashboard)", "De betreffende destination en de eventnaam", "Wat je verwachtte en wat er gebeurde, met tijdstip", "Screenshots van de debugger of de wizardstap — nooit toegangstokens of andere secrets"],
    },
    reply: "We antwoorden per e-mail op het adres dat je invult.",
  },
  contact: {
    title: "Contact",
    intro: "Vragen over abonnementen, Enterprise-volumes, verwerkersovereenkomsten of partnerschappen. We antwoorden binnen één werkdag.",
    enterprise: "Enterprise-aanvraag: volume op maat, SSO, SLA, dedicated verwerking.",
    eyebrow: "Contact",
    formTitle: "Stuur een bericht",
    topics: {
      title: "Waarmee we kunnen helpen",
      items: [
        { title: "Abonnementen en facturatie", text: "Welk abonnement past bij je eventvolume, hoe jaarlijkse facturatie werkt, facturen." },
        { title: "Enterprise", text: "Volume op maat, SSO, SLA en dedicated verwerking." },
        { title: "Gegevensverwerking", text: "De verwerkersovereenkomst, subverwerkers en EU-hosting." },
        { title: "Partnerschappen", text: "Bureaus, shopplatformen en aanbieders van consentmanagement." },
      ],
    },
    other: {
      title: "Zoek je iets anders?",
      items: [
        { title: "Demo boeken", text: "Dertig minuten met een engineer op je echte site.", href: "/demo" },
        { title: "Support", text: "Technische vragen over een bestaande setup.", href: "/support" },
      ],
    },
  },
  demo: {
    title: "Demo boeken",
    intro: "Dertig minuten met een engineer: we zetten een destination op je echte site op, versturen een testevent en lopen door toestemming, deduplicatie en de debugger.",
    agenda: ["Je stack: platform, CMP, huidige tags en pijnpunten", "Live inrichten van één destination met de assistent", "Toestemmingsbeleid, click-ID's en offline conversies voor jouw situatie", "Prijzen, migratieplan en verwerkersovereenkomst"],
    placeholder: "Welke platformen en welk shopsysteem gebruik je, en wat moeten we laten zien?",
    eyebrow: "Live demo",
    formTitle: "Vraag een tijdslot aan",
    agendaTitle: "Wat de dertig minuten omvatten",
    duration: "30 minuten, online, met een engineer",
    prepare: { title: "Handig om bij de hand te hebben", items: ["Toegang tot je website of een stagingkopie", "De platformen waarop je adverteert", "Je consentmanagementplatform, als je er een gebruikt"] },
    honest: "Geen verkoopscript: je vertrekt met één geconfigureerde destination en een eerlijke inschatting van wat Track wel en niet voor je stack kan doen.",
  },
  status: {
    title: "Systeemstatus",
    intro: "Live status van de Track-componenten, gecontroleerd bij elke paginaweergave. De incidentgeschiedenis wordt hier gepubliceerd zodra er een incident is.",
    component: "Component",
    state: "Status",
    checked: "Gecontroleerd",
    ok: "operationeel",
    degraded: "verminderd",
    down: "niet beschikbaar",
    db: "Control-plane-database",
    queue: "Achterstand in de eventqueue",
    worker: "Delivery-worker (laatste afleverpoging)",
    collector: "Collector (ingest)",
    none: "nog geen data",
    incidents: "Incidenten",
    noIncidents: "Geen incidenten geregistreerd.",
    note: "De status wordt afgeleid uit dezelfde database en queue die het product gebruikt; er is geen aparte statusdienst die kan afwijken.",
    eyebrow: "Status",
    componentsTitle: "Componenten",
    detail: "Detail",
    pending: "{n} openstaand",
    checkedAt: "Gecontroleerd om",
    flow: { title: "Eventpad en huidige status", caption: "Collector → queue → delivery-worker → destinations; de control-plane-database bevat de configuratie en de afleverrecords. Kleur en label van elke node komen overeen met de tabel hierboven.", collector: "Collector", queue: "Queue", worker: "Delivery-worker", database: "Database", destinations: "Destinations" },
    incidentsText: "Als een component verminderd of niet beschikbaar is, worden het incident, de impact en de oplossing hier vastgelegd.",
  },
  security: {
    title: "Beveiliging",
    intro: "Hoe Track klantgegevens beschermt: architectuur, controles en de garanties die je in het product kunt verifiëren.",
    eyebrow: "Beveiliging",
    flow: {
      title: "Waar data onderweg wordt beschermd",
      text: "Van het eerste request tot de aflevering heeft elke stap een controle: origin-checks, rate limits en HMAC-handtekeningen bij de collector, een duurzame queue, het toestemmingsbeleid vóór elke routering, en workers met retries, circuit breakers en een dead-letter queue. Kill switches stoppen een site of organisatie binnen seconden.",
      caption: "Ondertekende configuratie bereikt de browser, events bereiken de collector, en alleen events die de policy passeren bereiken een destination. Credentials van leveranciers verlaten de kluis alleen binnen de worker.",
      nodes: { website: "Website", config: "Ondertekende config", configSub: "Ed25519 · fail closed", collector: "Collector", collectorSub: "origin · rate limit · HMAC", queue: "Queue", queueSub: "duurzaam", policy: "Policy", worker: "Worker", workerSub: "retries · breaker · DLQ", destination: "Destination", vault: "Kluis", vaultSub: "KMS-envelope", kill: "Kill switch" },
    },
    controls: {
      title: "Controles in één oogopslag",
      text: "Elke controle wordt in de secties hierboven beschreven; deze tabel is de korte versie.",
      columns: { control: "Controle", scope: "Bereik", mechanism: "Mechanisme" },
      rows: [
        { control: "Tenant-isolatie", scope: "Elke tenanttabel, applicatierol", mechanism: "Organisatie-ID op elke rij, PostgreSQL row-level security afgedwongen" },
        { control: "Opslag van secrets", scope: "Credentials van leveranciers", mechanism: "Envelope-encryptie (AES-256-GCM-datasleutels, gewrapt door AWS KMS of een lokale mastersleutel); alleen een referentie en de laatste vier tekens zijn zichtbaar" },
        { control: "Ondertekende configuratie", scope: "Browser-SDK", mechanism: "Onveranderlijke, geversioneerde, Ed25519-ondertekende bundles, geverifieerd met WebCrypto; fail closed" },
        { control: "Ingest-bescherming", scope: "Collector", mechanism: "Origin-validatie, rate limits, HMAC-ondertekende serverrequests, duurzame queue vóór het antwoord" },
        { control: "Aflevering", scope: "Workers", mechanism: "Retries, circuit breakers en een dead-letter queue" },
        { control: "Kill switches", scope: "Per site of organisatie", mechanism: "Stoppen verzameling en aflevering binnen seconden" },
        { control: "Dataminimalisatie", scope: "Eventproperties, IP-adressen", mechanism: "PII-scanner blokkeert persoonsgegevens vóór opslag; IP-adressen worden bij ontvangst ingekort; geen fingerprinting" },
        { control: "Audit", scope: "Auditlog, usage ledger", mechanism: "Append-only via databasetriggers" },
        { control: "Toegang", scope: "Organisatieleden", mechanism: "Zes rollen, MFA en passkeys, break-glass-toegang met verplichte reden en auditvermelding" },
      ],
    },
    report: { title: "Een kwetsbaarheid melden", text: "Meld kwetsbaarheden verantwoord aan", missing: "het adres dat in het colofon is gepubliceerd", ack: "We bevestigen de ontvangst binnen twee werkdagen en noemen melders nooit zonder toestemming." },
  },
  legal: {
    eyebrow: "Juridisch",
    operator: { title: "Exploitant", company: "Bedrijf", address: "Adres", representatives: "Vertegenwoordigd door", email: "E-mail", phone: "Telefoon", register: "Registerinschrijving", vatId: "Btw-nummer", dpo: "Functionaris voor gegevensbescherming", missing: "Deze gegevens worden vóór de lancering door de exploitant gepubliceerd (omgevingsvariabelen LEGAL_*)." },
    related: { privacy: "Privacyverklaring", terms: "Gebruiksvoorwaarden", dpa: "Verwerkersovereenkomst", subprocessors: "Subverwerkers", imprint: "Colofon", security: "Beveiliging" },
  },
  subprocessors: {
    title: "Subverwerkers",
    intro: "Derden die klantgegevens namens de exploitant verwerken, en de advertentieleveranciers die alleen events ontvangen als een klant ze als destination configureert.",
    processorsTitle: "Door de exploitant ingeschakelde verwerkers",
    columns: { name: "Aanbieder", purpose: "Doel", region: "Regio", basis: "Doorgiftegrondslag" },
    vendors: "Destination-leveranciers (door de klant gekozen)",
    vendorsText: "Elke destination toont in de setupwizard de ontvanger van de data, de regio en de doorgiftegrondslag. Data bereikt een leverancier alleen voor destinations die je inschakelt, en alleen met het toestemmingsdoel dat de destination vereist.",
    updated: "Klanten worden 30 dagen vóór wijzigingen geïnformeerd.",
  },
  imprint: {
    title: "Colofon",
    intro: "Wettelijke informatie over de exploitant van deze website conform § 5 DDG en § 18 MStV.",
    dispute: "De Europese Commissie biedt een platform voor onlinegeschillenbeslechting (https://ec.europa.eu/consumers/odr). De exploitant is niet verplicht en niet bereid om deel te nemen aan een geschillenprocedure voor een geschillencommissie voor consumenten.",
    liability: "Ondanks zorgvuldige controle aanvaarden we geen aansprakelijkheid voor de inhoud van externe links; voor de inhoud daarvan zijn uitsluitend de beheerders van de gelinkte pagina's verantwoordelijk.",
  },
};
