import type { KnowledgeCopy, KnowledgeHubCopy } from "../types";

/**
 * German (de) copy of the knowledge area. Same shape as en.ts; see docs/14-localization.md.
 */

export const KNOWLEDGE_HUB_COPY_DE: KnowledgeHubCopy = {
  meta: {
    description: "Leitfäden, Tutorials und Referenzen zu Server-Side Tracking, Consent, Deduplizierung und Attribution für alle Werbeplattformen und Shopsysteme.",
    searchTitle: "Suche „{q}“",
  },
  breadcrumbs: { label: "Navigationspfad", home: "Track" },
  hero: {
    eyebrow: "Track",
    lead: "Server-Side Tracking, Consent, Deduplizierung und Attribution, erklärt vom Team, das die Connectoren baut. Suchen, nach Thema stöbern oder einem Lernpfad folgen.",
    articles: { one: "{n} Artikel", other: "{n} Artikel" },
    topics: { one: "{n} Thema", other: "{n} Themen" },
    browse: "Zum Verzeichnis",
    rss: "RSS-Feed",
  },
  search: {
    label: "Tracking Knowledge durchsuchen",
    placeholder: "Suchen, z. B. event_id, Consent Mode, Shopify …",
    clear: "Suche leeren",
    submit: "Suchen",
    hint: "Tippfehler, Akzente und Umlaute werden toleriert. Die Ergebnisse aktualisieren sich beim Tippen.",
    resultsAll: "Alle {total} Artikel",
    resultsSome: "{n} von {total} Artikeln",
    resultsQuery: "{n} von {total} Artikeln für „{q}“",
  },
  featured: { eyebrow: "Leitartikel", read: "Artikel lesen" },
  topics: {
    eyebrow: "Themenwelten",
    title: "Neun Themen, eine Taxonomie",
    text: "Jeder Artikel gehört zu genau einem Thema. Öffne ein Thema, um seine Artikel im Verzeichnis zu sehen.",
    articles: { one: "{n} Artikel", other: "{n} Artikel" },
    descriptions: {
      "getting-started": "Event-Taxonomie, erste Einrichtung und Migrationspläne: hier beginnt das Tracking mit Track.",
      "pixel-platform-integrations": "Meta, Google, TikTok, LinkedIn, Microsoft und mehr: Pixel, Conversion-APIs und die Felder, die jede Plattform erwartet.",
      "server-side-tracking": "Was sich ändert, wenn Events den Browser verlassen: First-Party-Domains, Deduplizierung und Zustellung.",
      "ecommerce-tracking": "Shopify, WooCommerce und Shopware: verifizierte Bestellungen, Purchase-Events und Pairing per Bestellnummer.",
      "consent-privacy": "Consent Mode, TCF, Aufbewahrung und Betroffenenanfragen: Tracking, das die Entscheidung respektiert.",
      "attribution-analytics": "Click-IDs, Attributionsfenster, Offline-Conversions und Lead-Tracking ohne Doppelzählung.",
      "ai-data-quality": "Der Tracking Health Score, typisierte KI-Werkzeuge und die Prüfungen, die Daten ehrlich halten.",
      troubleshooting: "Ad-Blocker, ITP, Incident-Playbooks und der Kill Switch: wenn die Zahlen nicht aufgehen.",
      "product-updates": "Signierte Konfiguration, Releases und was sich in Track geändert hat.",
    },
  },
  paths: {
    eyebrow: "Lernpfade",
    title: "Kuratierte Lesereihenfolgen",
    text: "Mehrere Artikel in der Reihenfolge, die aufeinander aufbaut, mit der tatsächlichen Gesamtlesezeit.",
    steps: { one: "{n} Schritt", other: "{n} Schritte" },
    minutes: "{n} Min.",
    step: "Schritt {n}",
  },
  guides: {
    eyebrow: "Plattformen und Shopsysteme",
    title: "Guides je Plattform und Shopsystem",
    text: "Jede Plattform und jedes Shopsystem mit mindestens einem Artikel. Jeder Link öffnet das Verzeichnis gefiltert darauf.",
    platforms: "Plattformen",
    shopSystems: "Shopsysteme",
    articles: { one: "{n} Artikel", other: "{n} Artikel" },
  },
  fresh: {
    eyebrow: "Aktuell",
    newTitle: "Neu veröffentlicht",
    newText: "Die neuesten Artikel nach Veröffentlichungsdatum.",
    updatedTitle: "Kürzlich aktualisiert",
    updatedText: "Artikel, die nach ihrer Veröffentlichung überarbeitet wurden, neueste Überarbeitung zuerst.",
    updatedEmpty: "Noch kein Artikel wurde seit seiner Veröffentlichung überarbeitet. Überarbeitungen erscheinen hier mit Datum.",
  },
  directory: {
    eyebrow: "Verzeichnis",
    title: "Alle Artikel",
    text: "Filtere nach Thema, Plattform, Shopsystem, Inhaltstyp, Wissensstufe und Aktualität. Die Zahlen neben jedem Filter sind echte Trefferzahlen.",
    filtersTitle: "Filter",
    facets: { topic: "Thema", platform: "Plattform", shopSystem: "Shopsystem", contentType: "Inhaltstyp", level: "Wissensstufe", recency: "Aktualität" },
    all: "Alle",
    reset: "Filter zurücksetzen",
    listLabel: "Artikel",
    emptyTitle: "Zu dieser Suche passt noch kein Artikel.",
    emptyText: "Probiere ein kürzeres Wort, prüfe die Schreibweise oder entferne einen Filter. Jeder veröffentlichte Artikel steht im Verzeichnis.",
    emptyAction: "Alle Artikel anzeigen",
    searching: "Suche läuft …",
  },
  card: { minutes: "{n} Min. Lesezeit", published: "Veröffentlicht", updated: "Aktualisiert" },
  cta: {
    eyebrow: "Track",
    title: "Sieh dir den Datenfluss auf deiner eigenen Website an",
    text: "Snippet einbinden, eine Destination verbinden und Events, Consent-Zustände und Zustellungen im Track-Dashboard verfolgen.",
    primary: "Mit deiner Domain starten",
    secondary: "So funktioniert Track",
  },
};

/** Index page metadata, feed and social-card copy; "Tracking Knowledge" is the fixed product name. */
export const KNOWLEDGE_COPY_DE: KnowledgeCopy = {
  name: "Tracking Knowledge",
  intro: "Praxisnahe Anleitungen zu serverseitigem Tracking, Consent, Deduplizierung, Attribution und den einzelnen Werbeplattformen — geschrieben vom Team, das die Connectoren baut.",
  cardAlt: "Track Tracking Knowledge: Anleitungen zu Server-Side Tracking, Consent, Deduplizierung und Attribution",
  feedDescription: "Anleitungen zu Server-Side Tracking, Consent und Attribution",
  all: "Alle Themen",
  minutes: "{n} Min. Lesezeit",
  rss: "RSS-Feed",
  empty: "Noch keine Artikel veröffentlicht.",
  emptyFiltered: "Für diese Auswahl gibt es noch keine Artikel.",
  filtered: "Gefilterte Ansicht",
  reset: "Alle Artikel anzeigen",
  updated: "Aktualisiert",
  published: "Veröffentlicht",
  reviewed: "Geprüft",
  sources: "Quellen",
  related: "Verwandte Artikel",
  by: "Von",
  topic: "Thema",
  level: "Wissensstufe",
  legal: "Dieser Artikel bietet allgemeine Informationen, keine Rechtsberatung. Wende dich für deinen konkreten Fall an deine Datenschutzberatung.",
  breadcrumbHome: "Track",
};
