import type { KnowledgeCopy, KnowledgeHubCopy } from "../types";

/**
 * English (source language) copy of the knowledge area. Same shape as every other locale file; see docs/14-localization.md.
 */

export const KNOWLEDGE_HUB_COPY_EN: KnowledgeHubCopy = {
  meta: {
    description: "Guides, tutorials and references on server-side tracking, consent, deduplication and attribution for every advertising platform and shop system.",
    searchTitle: "Search “{q}”",
  },
  breadcrumbs: { label: "Breadcrumb", home: "Track" },
  hero: {
    eyebrow: "Track",
    lead: "Server-side tracking, consent, deduplication and attribution, explained by the team that builds the connectors. Search, browse by topic or follow a learning path.",
    articles: { one: "{n} article", other: "{n} articles" },
    topics: { one: "{n} topic", other: "{n} topics" },
    browse: "Browse the directory",
    rss: "RSS feed",
  },
  search: {
    label: "Search Tracking Knowledge",
    placeholder: "Search, e.g. event_id, Consent Mode, Shopify …",
    clear: "Clear search",
    submit: "Search",
    hint: "Typos, accents and umlauts are tolerated. Results update as you type.",
    resultsAll: "All {total} articles",
    resultsSome: "{n} of {total} articles",
    resultsQuery: "{n} of {total} articles for “{q}”",
  },
  featured: { eyebrow: "Featured story", read: "Read the article" },
  topics: {
    eyebrow: "Topic worlds",
    title: "Nine topics, one taxonomy",
    text: "Every article belongs to exactly one topic. Open a topic to see its articles in the directory.",
    articles: { one: "{n} article", other: "{n} articles" },
    descriptions: {
      "getting-started": "Event taxonomy, first setup and migration plans: where tracking with Track begins.",
      "pixel-platform-integrations": "Meta, Google, TikTok, LinkedIn, Microsoft and more: pixels, conversion APIs and the fields each platform expects.",
      "server-side-tracking": "What changes when events leave the browser: first-party domains, deduplication and delivery.",
      "ecommerce-tracking": "Shopify, WooCommerce and Shopware: verified orders, purchase events and pairing by order id.",
      "consent-privacy": "Consent Mode, TCF, retention and data subject requests: tracking that respects the choice.",
      "attribution-analytics": "Click ids, attribution windows, offline conversions and lead tracking without double counting.",
      "ai-data-quality": "The Tracking Health Score, typed AI tools and the checks that keep data honest.",
      troubleshooting: "Ad blockers, ITP, incident playbooks and the kill switch: when the numbers do not add up.",
      "product-updates": "Signed configuration, releases and what changed in Track.",
    },
  },
  paths: {
    eyebrow: "Learning paths",
    title: "Curated reading orders",
    text: "Several articles in the order that builds on each other, with the real total reading time.",
    steps: { one: "{n} step", other: "{n} steps" },
    minutes: "{n} min",
    step: "Step {n}",
  },
  guides: {
    eyebrow: "Platforms and shop systems",
    title: "Guides per platform and shop system",
    text: "Every platform and shop system with at least one article. Each link opens the directory filtered to it.",
    platforms: "Platforms",
    shopSystems: "Shop systems",
    articles: { one: "{n} article", other: "{n} articles" },
  },
  fresh: {
    eyebrow: "Fresh",
    newTitle: "Newly published",
    newText: "The latest articles by publication date.",
    updatedTitle: "Recently updated",
    updatedText: "Articles revised after their publication, most recent revision first.",
    updatedEmpty: "No article has been revised since its publication yet. Revisions appear here with their date.",
  },
  directory: {
    eyebrow: "Directory",
    title: "All articles",
    text: "Filter by topic, platform, shop system, content type, level and recency. The numbers next to each filter are real hit counts.",
    filtersTitle: "Filters",
    facets: { topic: "Topic", platform: "Platform", shopSystem: "Shop system", contentType: "Content type", level: "Level", recency: "Recency" },
    all: "All",
    reset: "Reset filters",
    listLabel: "Articles",
    emptyTitle: "No articles match this search yet.",
    emptyText: "Try a shorter word, check the spelling or remove a filter. Every published article is listed in the directory.",
    emptyAction: "Show all articles",
    searching: "Searching …",
  },
  card: { minutes: "{n} min read", published: "Published", updated: "Updated" },
  cta: {
    eyebrow: "Track",
    title: "See the flow on your own site",
    text: "Add the snippet, connect a destination and watch events, consent states and deliveries in the Track dashboard.",
    primary: "Start with your domain",
    secondary: "How Track works",
  },
};

/** Index page metadata, feed and social-card copy; "Tracking Knowledge" is the fixed product name. */
export const KNOWLEDGE_COPY_EN: KnowledgeCopy = {
  name: "Tracking Knowledge",
  intro: "Practical guides on server-side tracking, consent, deduplication, attribution and the individual advertising platforms — written by the team that builds the connectors.",
  cardAlt: "Track Tracking Knowledge: guides on server-side tracking, consent, deduplication and attribution",
  feedDescription: "Server-side tracking, consent and attribution guides",
  all: "All topics",
  minutes: "{n} min read",
  rss: "RSS feed",
  empty: "No articles published yet.",
  emptyFiltered: "No articles match this selection yet.",
  filtered: "Filtered view",
  reset: "Show all articles",
  updated: "Updated",
  published: "Published",
  reviewed: "Reviewed",
  sources: "Sources",
  related: "Related articles",
  by: "By",
  topic: "Topic",
  level: "Level",
  legal: "This article provides general information, not legal advice. Consult your data protection counsel for your specific situation.",
  breadcrumbHome: "Track",
};
