import type { DemoCopy, HomeCopy, LocalizedCopy } from "./types";

/**
 * Home page copy (supplement §4): benefit first, technical proof later; no invented customers,
 * numbers or results — every statement is a verifiable product fact or clearly labelled sample data.
 * The demo labels are function-free (placeholders in braces) because they are passed to a client
 * component; see `components/marketing/demo/text.ts`.
 */

const DEMO_EN: DemoCopy = {
  label: "Interactive demo",
  sample: "Sample data — nothing is sent to any platform",
  sampleShort: "Sample data",
  region: "Track product demo",
  configLive: "Config v{version} live",
  controls: {
    reset: "Reset demo",
    pause: "Pause stream",
    play: "Play stream",
    next: "Next event",
    paused: "Stream paused",
    reducedMotion: "Reduced motion is on: the stream only advances when you press “Next event”.",
    offscreen: "Stream paused while the demo is out of view",
    complete: "The stream loops through the same sample script.",
  },
  viewsLabel: "Demo views",
  views: { overview: "Overview", events: "Live Events", destinations: "Destinations", ai: "AI Setup", attribution: "Attribution" },
  metrics: { accepted: "Accepted", delivered: "Delivered", duplicates: "Duplicates removed", blocked: "Blocked by consent", held: "Held" },
  health: {
    title: "Tracking Health Score",
    outOf: "of 100",
    explain: "How the score is calculated",
    parts: {
      consent: { label: "Consent decisions", detail: "{decided} of {accepted} accepted events have a consent decision; {pending} pending" },
      dedup: { label: "Browser/server pairing", detail: "{paired} of {conversions} conversions arrived from both browser and server" },
      params: { label: "Purchase parameters", detail: "{complete} of {purchases} Purchase events carry value and currency" },
      delivery: { label: "Delivery", detail: "{delivered} of {routable} routable events delivered; {held} held" },
    },
  },
  events: {
    title: "Live event stream",
    latest: "Latest events",
    origin: { browser: "Browser", server: "Server" },
    dedup: { unique: "Single source", paired: "Paired with the other source", duplicate: "Duplicate dropped" },
    consent: { granted: "Consent granted", denied: "Consent denied", pending: "Consent pending" },
    outcome: { delivered: "Delivered", blocked: "Blocked", held: "Held", duplicate: "Duplicate" },
    reasons: {
      delivered: "Delivered to every routed destination.",
      consent_denied: "Marketing consent was denied — nothing is sent to ad platforms.",
      consent_pending: "No consent decision yet — the event waits and is not sent.",
      missing_currency: "The Purchase has a value but no currency — held until a currency is set.",
      duplicate: "The same event ID was already accepted from the other source — dropped and not counted.",
      released: "Released after the currency fix and delivered.",
    },
    routedTo: { one: "{n} destination", other: "{n} destinations" },
    none: "No destination",
    columns: { event: "Event", origin: "Origin", consent: "Consent", outcome: "Outcome", time: "Time" },
    detail: { eventId: "Event ID", value: "Value", currency: "Currency", missing: "missing", order: "Order", destinations: "Delivered to", route: "Route", expand: "Show details", collapse: "Hide details", consentLabel: "Consent", dedupLabel: "Deduplication" },
  },
  flow: { website: "Website", track: "Track", consent: "Consent / policy", destinations: "Destinations", caption: "Path of the latest event: website → Track → consent check → destinations." },
  destinations: {
    title: "Destination health",
    pick: "Choose a platform",
    health: { ok: "Healthy", warn: "Needs attention", bad: "Failing" },
    lastDelivery: "Last successful delivery",
    none: "No delivery yet in this run",
    modes: "Modes",
    browserServer: "Browser tag + server API",
    dedupKey: "Dedup key",
    clickParam: "Click ID",
    counts: { delivered: "Delivered", held: "Held", blocked: "Blocked by consent" },
    heldHint: { one: "{n} Purchase is held until a currency is set.", other: "{n} Purchases are held until a currency is set." },
    openAi: "Fix it in AI Setup",
  },
  ai: {
    title: "AI Setup",
    from: "Track AI",
    found: {
      one: "{n} Purchase event arrived with a value but without a currency. Destinations cannot report the revenue correctly without it.",
      other: "{n} Purchase events arrived with a value but without a currency. Destinations cannot report the revenue correctly without it.",
    },
    foundNone: "No open recommendation. Purchase events now carry value and currency.",
    evidence: "Evidence in the sample stream",
    evidenceRow: "{name} · {origin} · value {value}, currency missing · {time}",
    question: "Which currency should Track apply when the shop sends none?",
    options: { EUR: "Euro (EUR)", USD: "US dollar (USD)", GBP: "Pound sterling (GBP)" },
    confirm: "Confirm and publish draft",
    result: {
      one: "Config v{version} published for the demo. {n} held Purchase was delivered.",
      other: "Config v{version} published for the demo. {n} held Purchases were delivered.",
      zero: "Config v{version} published for the demo.",
    },
    note: "This changes only the sample data. In your workspace Track AI prepares the same change as a draft and waits for your approval.",
    overviewHint: { one: "Recommendation: {n} Purchase is held without a currency", other: "Recommendation: {n} Purchases are held without a currency" },
    overviewDone: "Recommendation resolved: currency set, held Purchases delivered",
    open: "Open AI Setup",
    stepLabel: "Default currency",
  },
  attribution: {
    title: "Attribution & click IDs",
    intro: "Which click IDs the sample sessions carried, whether consent allowed forwarding them, and what stays unknown.",
    columns: { platform: "Platform", clickId: "Click ID", captured: "Observed", consent: "Consent", forwarded: "Forwarded server-side" },
    captured: { yes: "Yes", no: "Not in this run" },
    forwarded: { yes: "Yes", no: "Withheld", na: "—" },
    consentNa: "—",
    note: "Observed facts only: click IDs seen on landing URLs of the sample sessions. Cross-device journeys are unknown and stay unknown — nothing is modelled.",
  },
  announce: { event: "New event: {name} from {origin}, {outcome}.", setupDone: "Setup step confirmed. Held Purchases delivered.", reset: "Demo reset to its starting state." },
  mobileHint: "Compact demo: the same sample data with fewer rows.",
};

const DEMO_DE: DemoCopy = {
  label: "Interaktive Demo",
  sample: "Beispieldaten – es wird nichts an eine Plattform gesendet",
  sampleShort: "Beispieldaten",
  region: "Track-Produktdemo",
  configLive: "Config v{version} live",
  controls: {
    reset: "Demo zurücksetzen",
    pause: "Stream pausieren",
    play: "Stream abspielen",
    next: "Nächstes Event",
    paused: "Stream pausiert",
    reducedMotion: "Reduzierte Bewegung ist aktiv: Der Stream läuft nur weiter, wenn du „Nächstes Event“ drückst.",
    offscreen: "Stream pausiert, solange die Demo nicht sichtbar ist",
    complete: "Der Stream wiederholt dasselbe Beispielskript.",
  },
  viewsLabel: "Demo-Ansichten",
  views: { overview: "Overview", events: "Live Events", destinations: "Destinations", ai: "AI Setup", attribution: "Attribution" },
  metrics: { accepted: "Angenommen", delivered: "Zugestellt", duplicates: "Duplikate entfernt", blocked: "Durch Consent blockiert", held: "Zurückgehalten" },
  health: {
    title: "Tracking Health Score",
    outOf: "von 100",
    explain: "So entsteht der Score",
    parts: {
      consent: { label: "Consent-Entscheidungen", detail: "{decided} von {accepted} angenommenen Events haben eine Consent-Entscheidung; {pending} offen" },
      dedup: { label: "Browser/Server-Paarung", detail: "{paired} von {conversions} Conversions kamen aus Browser und Server" },
      params: { label: "Purchase-Parameter", detail: "{complete} von {purchases} Purchase-Events enthalten Wert und Währung" },
      delivery: { label: "Zustellung", detail: "{delivered} von {routable} zustellbaren Events zugestellt; {held} zurückgehalten" },
    },
  },
  events: {
    title: "Live-Eventstream",
    latest: "Letzte Events",
    origin: { browser: "Browser", server: "Server" },
    dedup: { unique: "Eine Quelle", paired: "Mit der anderen Quelle gepaart", duplicate: "Duplikat verworfen" },
    consent: { granted: "Consent erteilt", denied: "Consent abgelehnt", pending: "Consent offen" },
    outcome: { delivered: "Zugestellt", blocked: "Blockiert", held: "Zurückgehalten", duplicate: "Duplikat" },
    reasons: {
      delivered: "An alle gerouteten Ziele zugestellt.",
      consent_denied: "Marketing-Consent wurde abgelehnt – nichts geht an Werbeplattformen.",
      consent_pending: "Noch keine Consent-Entscheidung – das Event wartet und wird nicht gesendet.",
      missing_currency: "Der Purchase hat einen Wert, aber keine Währung – zurückgehalten, bis eine Währung gesetzt ist.",
      duplicate: "Dieselbe Event-ID wurde bereits aus der anderen Quelle angenommen – verworfen und nicht gezählt.",
      released: "Nach der Währungskorrektur freigegeben und zugestellt.",
    },
    routedTo: { one: "{n} Ziel", other: "{n} Ziele" },
    none: "Kein Ziel",
    columns: { event: "Event", origin: "Herkunft", consent: "Consent", outcome: "Ergebnis", time: "Zeit" },
    detail: { eventId: "Event-ID", value: "Wert", currency: "Währung", missing: "fehlt", order: "Bestellung", destinations: "Zugestellt an", route: "Route", expand: "Details anzeigen", collapse: "Details ausblenden", consentLabel: "Consent", dedupLabel: "Deduplizierung" },
  },
  flow: { website: "Website", track: "Track", consent: "Consent / Policy", destinations: "Ziele", caption: "Weg des letzten Events: Website → Track → Consent-Prüfung → Ziele." },
  destinations: {
    title: "Destination Health",
    pick: "Plattform wählen",
    health: { ok: "Gesund", warn: "Braucht Aufmerksamkeit", bad: "Fehlerhaft" },
    lastDelivery: "Letzte erfolgreiche Zustellung",
    none: "In diesem Durchlauf noch keine Zustellung",
    modes: "Modi",
    browserServer: "Browser-Tag + Server-API",
    dedupKey: "Dedup-Schlüssel",
    clickParam: "Click-ID",
    counts: { delivered: "Zugestellt", held: "Zurückgehalten", blocked: "Durch Consent blockiert" },
    heldHint: { one: "{n} Purchase wird zurückgehalten, bis eine Währung gesetzt ist.", other: "{n} Purchases werden zurückgehalten, bis eine Währung gesetzt ist." },
    openAi: "Im AI Setup beheben",
  },
  ai: {
    title: "AI Setup",
    from: "Track AI",
    found: {
      one: "{n} Purchase-Event kam mit Wert, aber ohne Währung an. Die Ziele können den Umsatz so nicht korrekt ausweisen.",
      other: "{n} Purchase-Events kamen mit Wert, aber ohne Währung an. Die Ziele können den Umsatz so nicht korrekt ausweisen.",
    },
    foundNone: "Keine offene Empfehlung. Purchase-Events enthalten jetzt Wert und Währung.",
    evidence: "Beleg im Beispielstream",
    evidenceRow: "{name} · {origin} · Wert {value}, Währung fehlt · {time}",
    question: "Welche Währung soll Track verwenden, wenn der Shop keine sendet?",
    options: { EUR: "Euro (EUR)", USD: "US-Dollar (USD)", GBP: "Pfund Sterling (GBP)" },
    confirm: "Bestätigen und Entwurf veröffentlichen",
    result: {
      one: "Config v{version} für die Demo veröffentlicht. {n} zurückgehaltener Purchase wurde zugestellt.",
      other: "Config v{version} für die Demo veröffentlicht. {n} zurückgehaltene Purchases wurden zugestellt.",
      zero: "Config v{version} für die Demo veröffentlicht.",
    },
    note: "Das ändert nur die Beispieldaten. In deinem Workspace bereitet Track AI dieselbe Änderung als Entwurf vor und wartet auf deine Freigabe.",
    overviewHint: { one: "Empfehlung: {n} Purchase wird ohne Währung zurückgehalten", other: "Empfehlung: {n} Purchases werden ohne Währung zurückgehalten" },
    overviewDone: "Empfehlung erledigt: Währung gesetzt, zurückgehaltene Purchases zugestellt",
    open: "AI Setup öffnen",
    stepLabel: "Standardwährung",
  },
  attribution: {
    title: "Attribution & Click-IDs",
    intro: "Welche Click-IDs die Beispielsitzungen trugen, ob Consent die Weitergabe erlaubte und was unbekannt bleibt.",
    columns: { platform: "Plattform", clickId: "Click-ID", captured: "Beobachtet", consent: "Consent", forwarded: "Serverseitig weitergegeben" },
    captured: { yes: "Ja", no: "Nicht in diesem Durchlauf" },
    forwarded: { yes: "Ja", no: "Zurückgehalten", na: "—" },
    consentNa: "—",
    note: "Nur beobachtete Fakten: Click-IDs auf Landing-URLs der Beispielsitzungen. Geräteübergreifende Journeys sind unbekannt und bleiben es – nichts wird modelliert.",
  },
  announce: { event: "Neues Event: {name} aus {origin}, {outcome}.", setupDone: "Setup-Schritt bestätigt. Zurückgehaltene Purchases zugestellt.", reset: "Demo auf den Ausgangszustand zurückgesetzt." },
  mobileHint: "Kompakte Demo: dieselben Beispieldaten mit weniger Zeilen.",
};

export const HOME_COPY: LocalizedCopy<HomeCopy> = {
  en: {
    eyebrow: "AI-first tag manager",
    title: "One snippet. Every platform. Every conversion counted once.",
    subtitle: "Track collects your website events first-party, checks consent before anything leaves your site and delivers them server-side to Meta, Google, TikTok, LinkedIn and more — deduplicated, explained, and set up together with Track AI.",
    cta: "Start with your domain",
    ctaSecondary: "See how it works",
    domainPlaceholder: "yourshop.com",
    domainLabel: "Your website",
    domainHelp: "We only check the format here. Next, we create your site with a six-character tracking ID and guide you through the setup in chat.",
    domainInvalid: "Enter a domain such as yourshop.com — without https:// or a path.",
    trust: {
      eu: "EU data region",
      consent: "Consent checked before delivery",
      signed: "Signed, versioned configs",
      noCode: "No custom HTML or JavaScript",
    },
    demoHeading: "Interactive product demo",
    platforms: {
      title: "Works with the platforms and shop systems you already use",
      text: "Browser tag plus server-side API for every destination that offers one, sharing one event ID so nothing is counted twice. Shopify, WooCommerce and Shopware send verified orders directly.",
      all: "All integrations",
      groups: { ads: "Ad platforms", analytics: "Analytics", commerce: "Shop systems" },
      modes: { browser: "Browser", server: "Server", offline: "Offline" },
    },
    outcomes: {
      eyebrow: "What you get",
      title: "Three things your tracking should do — and usually doesn't",
      text: "Pixels alone lose events, server-side setups need engineers, and consent is often a banner instead of a rule. Track turns all three into one guided setup.",
      items: [
        { title: "Every conversion counted once", text: "Browser and server send the same event ID; Track merges the pair and forwards one conversion per order. Replays never create a second one.", proof: "In the demo: the dedup marker in the live event stream" },
        { title: "Only what consent allows leaves your site", text: "Each event passes a policy check before delivery. A denied consent blocks the destination, a missing decision never becomes a yes, and every decision is recorded with its reason.", proof: "In the demo: the block reason on every held event" },
        { title: "You always know what to fix next", text: "A tracking health score with explainable parts and Track AI recommendations that point to the exact event and parameter — with a draft you approve.", proof: "In the demo: the Purchase that arrives without a currency" },
      ],
    },
    flow: {
      eyebrow: "How it works",
      title: "Snippet → Track → Platforms",
      text: "One asynchronous script on your pages, one router in the EU that checks consent and merges duplicates, and every destination fed server-side from the same verified event.",
      steps: [
        { title: "Install one snippet", text: "Add the asynchronous tracker with your six-character site ID. It loads a signed configuration, never blocks rendering and fails safe if anything is wrong." },
        { title: "Track checks and routes", text: "Events are validated, matched to their consent decision, deduplicated by event ID and order ID, then queued for each destination separately." },
        { title: "Platforms receive verified events", text: "Meta, Google, TikTok, LinkedIn, Reddit and more get browser and server events with shared IDs; you see the delivery status and the last response per destination." },
      ],
      snippetTitle: "The snippet",
      copy: "Copy snippet",
      copied: "Copied",
      caption: "Website → Track → Consent / policy → Destinations: the path every event takes.",
      nodes: { website: "Your website", track: "Track", consent: "Consent / policy", destination: "Destinations" },
      more: "Read the full walkthrough",
    },
    aiSetup: {
      eyebrow: "Guided setup",
      title: "Set up with Track AI. Publish only what you approve.",
      text: "Track AI detects your platform, proposes a measurement plan and connects destinations with validated inputs. Every change becomes a draft with a readable diff — nothing goes live until you confirm.",
      bullets: ["Detects your CMS or shop system and the events that matter for it", "Asks one question at a time; credentials go into secure cards, never into the chat", "Every change is a draft with a diff, an approval button and one-click rollback"],
      transcriptLabel: "Example conversation (static)",
      transcript: [
        { role: "assistant", text: "I checked demo-shop.example and detected Shopware 6. Purchase events arrive with a value but without a currency, so Meta and TikTok cannot count revenue." },
        { role: "you", text: "Use EUR as the default." },
        { role: "assistant", text: "The change is ready for your review. Nothing changes until you confirm." },
      ],
      approval: { title: "Draft v15 — review before publishing", diff: ["+ purchase.currency: default EUR when the shop sends none", "+ destinations.meta.value_currency: EUR", "= 1 held Purchase event would be delivered"], confirm: "Publish v15", cancel: "Discard" },
      note: "Static example with sample data. In your workspace the same flow runs against your real configuration and asks for your confirmation before publishing.",
      more: "How Track AI works",
    },
    useCases: {
      eyebrow: "Use cases",
      title: "Built for shops, lead generation and agencies",
      text: "The same router with a measurement plan that fits your business.",
      items: [
        { title: "E-commerce", text: "Verified orders instead of browser guesses.", points: ["Purchase, refund and subscription events from Shopify, WooCommerce or Shopware webhooks", "Order ID as the source of truth for deduplication", "Value and currency validated before delivery"] },
        { title: "Lead generation", text: "Every qualified lead attributed, none counted twice.", points: ["Lead events from forms and server with a shared event ID", "Click IDs such as gclid and li_fat_id forwarded only with consent", "Offline conversions uploaded when the deal is won"] },
        { title: "Agencies", text: "Many sites, one workflow.", points: ["Several sites and brands per workspace", "Drafts, approvals and an audit log for every change", "Tracking health per client without opening five dashboards"] },
      ],
    },
    trustSection: {
      eyebrow: "Consent, security, EU data",
      title: "Privacy is enforced in code, not promised in a banner",
      text: "Track is built as a data, consent and routing layer. These are product facts you can verify in the documentation and the data processing agreement.",
      groups: [
        { title: "Consent", items: ["Strict opt-in defaults; a missing decision never becomes a yes", "Consent Mode v2, TCF 2.2, GPP and GPC signals plus the common CMPs", "Server-side delivery never bypasses a denied consent"] },
        { title: "Security", items: ["Signed, versioned configurations verified in the browser", "Credentials envelope-encrypted; secrets never reach chat, logs or the model", "Row-level security isolates every workspace in the database"] },
        { title: "EU data", items: ["Processing in the EU data region by default", "Processor under Art. 28 GDPR with a data processing agreement", "No fingerprinting, no consent bypass, no synthetic conversions"] },
      ],
      links: { security: "Security", privacy: "Privacy", dpa: "Data processing (DPA)", subprocessors: "Subprocessors" },
    },
    knowledge: {
      eyebrow: "Tracking Knowledge",
      title: "Learn how tracking really works",
      text: "Guides on server-side tracking, deduplication and consent — written by the team building Track.",
      all: "All articles",
      minutes: "{n} min read",
    },
    pricing: {
      eyebrow: "Pricing",
      title: "Plans that grow with your event volume",
      text: "Every plan includes browser and server-side tracking, all standard destinations, Track AI and the consent engine. Monthly billing is the default; a year costs ten monthly instalments.",
      perMonth: "per month",
      events: "{n} accepted events per month",
      sites: { one: "{n} production website", other: "{n} production websites" },
      custom: "Custom",
      customText: "Custom volume, contract and SLA.",
      trial: "{days}-day {plan} trial, no credit card, no automatic conversion into a paid plan.",
      all: "Compare all plans",
      taxNote: "Net list prices in EUR; VAT is added where applicable.",
      recommended: "Recommended",
      enterprise: "Enterprise",
      enterpriseText: "Custom volumes, infrastructure, governance and SLA.",
      contact: "Talk to sales",
    },
    finalCta: {
      title: "Ready for verified events?",
      text: "Create your site, paste the snippet and let Track AI guide the rest. No credit card needed to start.",
      cta: "Create your site",
      secondary: "Book a demo",
    },
    demo: DEMO_EN,
  },
  de: {
    eyebrow: "AI-first Tag Manager",
    title: "Ein Snippet. Jede Plattform. Jede Conversion genau einmal gezählt.",
    subtitle: "Track erfasst deine Website-Events first-party, prüft Consent, bevor etwas deine Seite verlässt, und liefert sie serverseitig an Meta, Google, TikTok, LinkedIn und mehr – dedupliziert, erklärt und gemeinsam mit Track AI eingerichtet.",
    cta: "Mit deiner Domain starten",
    ctaSecondary: "So funktioniert es",
    domainPlaceholder: "deinshop.de",
    domainLabel: "Deine Website",
    domainHelp: "Hier prüfen wir nur das Format. Danach legen wir deine Site mit einer sechsstelligen Tracking-ID an und führen dich im Chat durch die Einrichtung.",
    domainInvalid: "Gib eine Domain wie deinshop.de ein – ohne https:// und ohne Pfad.",
    trust: {
      eu: "EU-Datenregion",
      consent: "Consent wird vor der Zustellung geprüft",
      signed: "Signierte, versionierte Konfigurationen",
      noCode: "Kein Custom HTML oder JavaScript",
    },
    demoHeading: "Interaktive Produktdemo",
    platforms: {
      title: "Funktioniert mit den Plattformen und Shopsystemen, die du schon nutzt",
      text: "Browser-Tag plus serverseitige API für jedes Ziel, das eine anbietet – mit einer gemeinsamen Event-ID, damit nichts doppelt zählt. Shopify, WooCommerce und Shopware senden verifizierte Bestellungen direkt.",
      all: "Alle Integrationen",
      groups: { ads: "Werbeplattformen", analytics: "Analytics", commerce: "Shopsysteme" },
      modes: { browser: "Browser", server: "Server", offline: "Offline" },
    },
    outcomes: {
      eyebrow: "Was du bekommst",
      title: "Drei Dinge, die dein Tracking können sollte – und meist nicht kann",
      text: "Pixel allein verlieren Events, serverseitige Setups brauchen Entwickler, und Consent ist oft ein Banner statt einer Regel. Track macht aus allen dreien eine geführte Einrichtung.",
      items: [
        { title: "Jede Conversion genau einmal gezählt", text: "Browser und Server senden dieselbe Event-ID; Track führt das Paar zusammen und leitet eine Conversion pro Bestellung weiter. Wiederholungen erzeugen nie eine zweite.", proof: "In der Demo: die Dedup-Markierung im Live-Eventstream" },
        { title: "Nur, was Consent erlaubt, verlässt deine Seite", text: "Jedes Event durchläuft vor der Zustellung eine Policy-Prüfung. Ein abgelehnter Consent blockiert das Ziel, eine fehlende Entscheidung wird nie zum Ja, und jede Entscheidung wird mit Grund festgehalten.", proof: "In der Demo: der Blockgrund an jedem zurückgehaltenen Event" },
        { title: "Du weißt immer, was als Nächstes zu tun ist", text: "Ein Tracking Health Score mit erklärbaren Teilwerten und Track-AI-Empfehlungen, die auf das genaue Event und den Parameter zeigen – mit einem Entwurf, den du freigibst.", proof: "In der Demo: der Purchase, der ohne Währung ankommt" },
      ],
    },
    flow: {
      eyebrow: "So funktioniert es",
      title: "Snippet → Track → Plattformen",
      text: "Ein asynchrones Script auf deinen Seiten, ein Router in der EU, der Consent prüft und Duplikate zusammenführt, und jedes Ziel serverseitig aus demselben verifizierten Event versorgt.",
      steps: [
        { title: "Ein Snippet einbauen", text: "Den asynchronen Tracker mit deiner sechsstelligen Site-ID einfügen. Er lädt eine signierte Konfiguration, blockiert nie das Rendering und ist fail-safe, falls etwas nicht stimmt." },
        { title: "Track prüft und routet", text: "Events werden validiert, ihrer Consent-Entscheidung zugeordnet, über Event-ID und Bestellnummer dedupliziert und dann je Ziel getrennt in die Warteschlange gestellt." },
        { title: "Plattformen erhalten verifizierte Events", text: "Meta, Google, TikTok, LinkedIn, Reddit und mehr bekommen Browser- und Server-Events mit gemeinsamen IDs; du siehst Zustellstatus und letzte Antwort je Ziel." },
      ],
      snippetTitle: "Das Snippet",
      copy: "Snippet kopieren",
      copied: "Kopiert",
      caption: "Website → Track → Consent / Policy → Ziele: der Weg, den jedes Event nimmt.",
      nodes: { website: "Deine Website", track: "Track", consent: "Consent / Policy", destination: "Ziele" },
      more: "Den ganzen Ablauf lesen",
    },
    aiSetup: {
      eyebrow: "Geführte Einrichtung",
      title: "Mit Track AI einrichten. Veröffentlicht wird nur, was du freigibst.",
      text: "Track AI erkennt deine Plattform, schlägt einen Messplan vor und verbindet Ziele mit validierten Eingaben. Jede Änderung wird zum Entwurf mit lesbarem Diff – nichts geht live, bevor du bestätigst.",
      bullets: ["Erkennt dein CMS oder Shopsystem und die Events, die dafür zählen", "Stellt eine Frage nach der anderen; Zugangsdaten landen in sicheren Karten, nie im Chat", "Jede Änderung ist ein Entwurf mit Diff, Freigabe-Button und Rollback per Klick"],
      transcriptLabel: "Beispielunterhaltung (statisch)",
      transcript: [
        { role: "assistant", text: "Ich habe demo-shop.example geprüft und Shopware 6 erkannt. Purchase-Events kommen mit Wert, aber ohne Währung an, deshalb können Meta und TikTok keinen Umsatz zählen." },
        { role: "you", text: "Nimm EUR als Standard." },
        { role: "assistant", text: "Die Änderung ist bereit für deine Prüfung. Nichts ändert sich, bevor du bestätigst." },
      ],
      approval: { title: "Entwurf v15 – vor der Veröffentlichung prüfen", diff: ["+ purchase.currency: Standard EUR, wenn der Shop keine sendet", "+ destinations.meta.value_currency: EUR", "= 1 zurückgehaltenes Purchase-Event würde zugestellt"], confirm: "v15 veröffentlichen", cancel: "Verwerfen" },
      note: "Statisches Beispiel mit Beispieldaten. In deinem Workspace läuft derselbe Ablauf gegen deine echte Konfiguration und fragt vor der Veröffentlichung nach deiner Bestätigung.",
      more: "So arbeitet Track AI",
    },
    useCases: {
      eyebrow: "Anwendungsfälle",
      title: "Gebaut für Shops, Lead-Generierung und Agenturen",
      text: "Derselbe Router mit einem Messplan, der zu deinem Geschäft passt.",
      items: [
        { title: "E-Commerce", text: "Verifizierte Bestellungen statt Browser-Schätzungen.", points: ["Purchase-, Refund- und Subscription-Events aus Shopify-, WooCommerce- oder Shopware-Webhooks", "Bestellnummer als Source of Truth für die Deduplizierung", "Wert und Währung vor der Zustellung validiert"] },
        { title: "Lead-Generierung", text: "Jeder qualifizierte Lead zugeordnet, keiner doppelt gezählt.", points: ["Lead-Events aus Formular und Server mit gemeinsamer Event-ID", "Click-IDs wie gclid und li_fat_id nur mit Consent weitergegeben", "Offline-Conversions hochgeladen, wenn der Abschluss steht"] },
        { title: "Agenturen", text: "Viele Sites, ein Arbeitsablauf.", points: ["Mehrere Sites und Marken pro Workspace", "Entwürfe, Freigaben und ein Audit-Log für jede Änderung", "Tracking Health je Kunde, ohne fünf Dashboards zu öffnen"] },
      ],
    },
    trustSection: {
      eyebrow: "Consent, Sicherheit, EU-Daten",
      title: "Datenschutz wird im Code erzwungen, nicht im Banner versprochen",
      text: "Track ist als Daten-, Consent- und Routing-Layer gebaut. Das sind Produktfakten, die du in der Dokumentation und im Auftragsverarbeitungsvertrag nachprüfen kannst.",
      groups: [
        { title: "Consent", items: ["Strikte Opt-in-Defaults; eine fehlende Entscheidung wird nie zum Ja", "Consent Mode v2, TCF 2.2, GPP- und GPC-Signale sowie die gängigen CMPs", "Serverseitige Zustellung umgeht nie einen abgelehnten Consent"] },
        { title: "Sicherheit", items: ["Signierte, versionierte Konfigurationen, im Browser verifiziert", "Zugangsdaten envelope-verschlüsselt; Secrets gelangen nie in Chat, Logs oder das Modell", "Row-Level Security isoliert jeden Workspace in der Datenbank"] },
        { title: "EU-Daten", items: ["Verarbeitung standardmäßig in der EU-Datenregion", "Auftragsverarbeiter nach Art. 28 DSGVO mit Auftragsverarbeitungsvertrag", "Kein Fingerprinting, keine Consent-Umgehung, keine synthetischen Conversions"] },
      ],
      links: { security: "Sicherheit", privacy: "Datenschutz", dpa: "Auftragsverarbeitung (AVV)", subprocessors: "Subunternehmer" },
    },
    knowledge: {
      eyebrow: "Tracking Knowledge",
      title: "Verstehen, wie Tracking wirklich funktioniert",
      text: "Leitfäden zu Server-Side Tracking, Deduplizierung und Consent – geschrieben vom Team, das Track baut.",
      all: "Alle Artikel",
      minutes: "{n} Min. Lesezeit",
    },
    pricing: {
      eyebrow: "Preise",
      title: "Tarife, die mit deinem Eventvolumen wachsen",
      text: "Jeder Tarif enthält Browser- und Server-Side-Tracking, alle Standard-Destinations, Track AI und die Consent Engine. Monatliche Abrechnung ist voreingestellt; ein Jahr kostet zehn Monatsraten.",
      perMonth: "pro Monat",
      events: "{n} akzeptierte Events pro Monat",
      sites: { one: "{n} produktive Website", other: "{n} produktive Websites" },
      custom: "Custom",
      customText: "Individuelles Volumen, Vertrag und SLA.",
      trial: "{days} Tage {plan} testen, keine Kreditkarte, keine automatische Umwandlung in einen bezahlten Tarif.",
      all: "Alle Tarife vergleichen",
      taxNote: "Listenpreise netto in EUR; zzgl. USt., sofern anwendbar.",
      recommended: "Empfohlen",
      enterprise: "Enterprise",
      enterpriseText: "Individuelle Volumina, Infrastruktur, Governance und SLA.",
      contact: "Mit dem Vertrieb sprechen",
    },
    finalCta: {
      title: "Bereit für verifizierte Events?",
      text: "Site anlegen, Snippet einfügen und Track AI durch den Rest führen lassen. Zum Start ist keine Kreditkarte nötig.",
      cta: "Site anlegen",
      secondary: "Demo buchen",
    },
    demo: DEMO_DE,
  },
};
