import type { KnowledgeHubCopy, LocalizedCopy } from "./types";

export type { KnowledgeHubCopy, PluralText } from "./types";

/**
 * Copy of the Tracking Knowledge hub (supplement §6: hero + search, featured story, topic worlds,
 * learning paths, platform/shop guides, fresh lists, directory with filters, restrained product CTA).
 * The product name stays "Tracking Knowledge" in every language; everything around it is localized.
 * Placeholders (`{n}`, `{total}`, `{q}`) are filled by `components/marketing/knowledge/hub/text.ts`
 * because the object crosses the server → client boundary as a prop. No popularity numbers, badges
 * or success rates: every count shown on the page is a real count from the loader.
 */
export const KNOWLEDGE_HUB_COPY: LocalizedCopy<KnowledgeHubCopy> = {
  en: {
    meta: {
      description: "Guides, tutorials and references on server-side tracking, consent, deduplication and attribution for every advertising platform and shop system.",
      searchTitle: "Search “{q}”",
    },
    breadcrumbs: { label: "Breadcrumb", home: "Track" },
    hero: {
      eyebrow: "Track",
      lead: "Server-side tracking, consent, deduplication and attribution, explained by the team that builds the connectors. Search, browse by topic or follow a learning path.",
      articles: { one: "{n} article", other: "{n} articles" },
      topics: { one: "{n} topic", other: "{n} topics" },
      browse: "Browse the directory",
      rss: "RSS feed",
    },
    search: {
      label: "Search Tracking Knowledge",
      placeholder: "Search, e.g. event_id, Consent Mode, Shopify …",
      clear: "Clear search",
      submit: "Search",
      hint: "Typos, accents and umlauts are tolerated. Results update as you type.",
      resultsAll: "All {total} articles",
      resultsSome: "{n} of {total} articles",
      resultsQuery: "{n} of {total} articles for “{q}”",
    },
    featured: { eyebrow: "Featured story", read: "Read the article" },
    topics: {
      eyebrow: "Topic worlds",
      title: "Nine topics, one taxonomy",
      text: "Every article belongs to exactly one topic. Open a topic to see its articles in the directory.",
      articles: { one: "{n} article", other: "{n} articles" },
      descriptions: {
        "getting-started": "Event taxonomy, first setup and migration plans: where tracking with Track begins.",
        "pixel-platform-integrations": "Meta, Google, TikTok, LinkedIn, Microsoft and more: pixels, conversion APIs and the fields each platform expects.",
        "server-side-tracking": "What changes when events leave the browser: first-party domains, deduplication and delivery.",
        "ecommerce-tracking": "Shopify, WooCommerce and Shopware: verified orders, purchase events and pairing by order id.",
        "consent-privacy": "Consent Mode, TCF, retention and data subject requests: tracking that respects the choice.",
        "attribution-analytics": "Click ids, attribution windows, offline conversions and lead tracking without double counting.",
        "ai-data-quality": "The Tracking Health Score, typed AI tools and the checks that keep data honest.",
        troubleshooting: "Ad blockers, ITP, incident playbooks and the kill switch: when the numbers do not add up.",
        "product-updates": "Signed configuration, releases and what changed in Track.",
      },
    },
    paths: {
      eyebrow: "Learning paths",
      title: "Curated reading orders",
      text: "Several articles in the order that builds on each other, with the real total reading time.",
      steps: { one: "{n} step", other: "{n} steps" },
      minutes: "{n} min",
      step: "Step {n}",
    },
    guides: {
      eyebrow: "Platforms and shop systems",
      title: "Guides per platform and shop system",
      text: "Every platform and shop system with at least one article. Each link opens the directory filtered to it.",
      platforms: "Platforms",
      shopSystems: "Shop systems",
      articles: { one: "{n} article", other: "{n} articles" },
    },
    fresh: {
      eyebrow: "Fresh",
      newTitle: "Newly published",
      newText: "The latest articles by publication date.",
      updatedTitle: "Recently updated",
      updatedText: "Articles revised after their publication, most recent revision first.",
      updatedEmpty: "No article has been revised since its publication yet. Revisions appear here with their date.",
    },
    directory: {
      eyebrow: "Directory",
      title: "All articles",
      text: "Filter by topic, platform, shop system, content type, level and recency. The numbers next to each filter are real hit counts.",
      filtersTitle: "Filters",
      facets: { topic: "Topic", platform: "Platform", shopSystem: "Shop system", contentType: "Content type", level: "Level", recency: "Recency" },
      all: "All",
      reset: "Reset filters",
      listLabel: "Articles",
      emptyTitle: "No articles match this search yet.",
      emptyText: "Try a shorter word, check the spelling or remove a filter. Every published article is listed in the directory.",
      emptyAction: "Show all articles",
      searching: "Searching …",
    },
    card: { minutes: "{n} min read", published: "Published", updated: "Updated" },
    cta: {
      eyebrow: "Track",
      title: "See the flow on your own site",
      text: "Add the snippet, connect a destination and watch events, consent states and deliveries in the Track dashboard.",
      primary: "Start with your domain",
      secondary: "How Track works",
    },
  },
  de: {
    meta: {
      description: "Leitfäden, Tutorials und Referenzen zu Server-Side Tracking, Consent, Deduplizierung und Attribution für alle Werbeplattformen und Shopsysteme.",
      searchTitle: "Suche „{q}“",
    },
    breadcrumbs: { label: "Navigationspfad", home: "Track" },
    hero: {
      eyebrow: "Track",
      lead: "Server-Side Tracking, Consent, Deduplizierung und Attribution, erklärt vom Team, das die Connectoren baut. Suchen, nach Thema stöbern oder einem Lernpfad folgen.",
      articles: { one: "{n} Artikel", other: "{n} Artikel" },
      topics: { one: "{n} Thema", other: "{n} Themen" },
      browse: "Zum Verzeichnis",
      rss: "RSS-Feed",
    },
    search: {
      label: "Tracking Knowledge durchsuchen",
      placeholder: "Suchen, z. B. event_id, Consent Mode, Shopify …",
      clear: "Suche leeren",
      submit: "Suchen",
      hint: "Tippfehler, Akzente und Umlaute werden toleriert. Die Ergebnisse aktualisieren sich beim Tippen.",
      resultsAll: "Alle {total} Artikel",
      resultsSome: "{n} von {total} Artikeln",
      resultsQuery: "{n} von {total} Artikeln für „{q}“",
    },
    featured: { eyebrow: "Leitartikel", read: "Artikel lesen" },
    topics: {
      eyebrow: "Themenwelten",
      title: "Neun Themen, eine Taxonomie",
      text: "Jeder Artikel gehört zu genau einem Thema. Öffne ein Thema, um seine Artikel im Verzeichnis zu sehen.",
      articles: { one: "{n} Artikel", other: "{n} Artikel" },
      descriptions: {
        "getting-started": "Event-Taxonomie, erste Einrichtung und Migrationspläne: hier beginnt das Tracking mit Track.",
        "pixel-platform-integrations": "Meta, Google, TikTok, LinkedIn, Microsoft und mehr: Pixel, Conversion-APIs und die Felder, die jede Plattform erwartet.",
        "server-side-tracking": "Was sich ändert, wenn Events den Browser verlassen: First-Party-Domains, Deduplizierung und Zustellung.",
        "ecommerce-tracking": "Shopify, WooCommerce und Shopware: verifizierte Bestellungen, Purchase-Events und Pairing per Bestellnummer.",
        "consent-privacy": "Consent Mode, TCF, Aufbewahrung und Betroffenenanfragen: Tracking, das die Entscheidung respektiert.",
        "attribution-analytics": "Click-IDs, Attributionsfenster, Offline-Conversions und Lead-Tracking ohne Doppelzählung.",
        "ai-data-quality": "Der Tracking Health Score, typisierte KI-Werkzeuge und die Prüfungen, die Daten ehrlich halten.",
        troubleshooting: "Ad-Blocker, ITP, Incident-Playbooks und der Kill Switch: wenn die Zahlen nicht aufgehen.",
        "product-updates": "Signierte Konfiguration, Releases und was sich in Track geändert hat.",
      },
    },
    paths: {
      eyebrow: "Lernpfade",
      title: "Kuratierte Lesereihenfolgen",
      text: "Mehrere Artikel in der Reihenfolge, die aufeinander aufbaut, mit der tatsächlichen Gesamtlesezeit.",
      steps: { one: "{n} Schritt", other: "{n} Schritte" },
      minutes: "{n} Min.",
      step: "Schritt {n}",
    },
    guides: {
      eyebrow: "Plattformen und Shopsysteme",
      title: "Guides je Plattform und Shopsystem",
      text: "Jede Plattform und jedes Shopsystem mit mindestens einem Artikel. Jeder Link öffnet das Verzeichnis gefiltert darauf.",
      platforms: "Plattformen",
      shopSystems: "Shopsysteme",
      articles: { one: "{n} Artikel", other: "{n} Artikel" },
    },
    fresh: {
      eyebrow: "Aktuell",
      newTitle: "Neu veröffentlicht",
      newText: "Die neuesten Artikel nach Veröffentlichungsdatum.",
      updatedTitle: "Kürzlich aktualisiert",
      updatedText: "Artikel, die nach ihrer Veröffentlichung überarbeitet wurden, neueste Überarbeitung zuerst.",
      updatedEmpty: "Noch kein Artikel wurde seit seiner Veröffentlichung überarbeitet. Überarbeitungen erscheinen hier mit Datum.",
    },
    directory: {
      eyebrow: "Verzeichnis",
      title: "Alle Artikel",
      text: "Filtere nach Thema, Plattform, Shopsystem, Inhaltstyp, Wissensstufe und Aktualität. Die Zahlen neben jedem Filter sind echte Trefferzahlen.",
      filtersTitle: "Filter",
      facets: { topic: "Thema", platform: "Plattform", shopSystem: "Shopsystem", contentType: "Inhaltstyp", level: "Wissensstufe", recency: "Aktualität" },
      all: "Alle",
      reset: "Filter zurücksetzen",
      listLabel: "Artikel",
      emptyTitle: "Zu dieser Suche passt noch kein Artikel.",
      emptyText: "Probiere ein kürzeres Wort, prüfe die Schreibweise oder entferne einen Filter. Jeder veröffentlichte Artikel steht im Verzeichnis.",
      emptyAction: "Alle Artikel anzeigen",
      searching: "Suche läuft …",
    },
    card: { minutes: "{n} Min. Lesezeit", published: "Veröffentlicht", updated: "Aktualisiert" },
    cta: {
      eyebrow: "Track",
      title: "Sieh dir den Datenfluss auf deiner eigenen Website an",
      text: "Snippet einbinden, eine Destination verbinden und Events, Consent-Zustände und Zustellungen im Track-Dashboard verfolgen.",
      primary: "Mit deiner Domain starten",
      secondary: "So funktioniert Track",
    },
  },
};
