/**
 * Marketing + dashboard catalog of destinations. Every entry is a real connector in
 * packages/connectors (no "coming soon"). Access notes describe vendor-side prerequisites.
 */
export interface IntegrationCatalogEntry {
  slug: string;
  type: string;
  name: string;
  group: 1 | 2 | 3 | "commerce";
  browser: boolean;
  server: boolean;
  offline: boolean;
  auth: "token" | "oauth" | "api_secret" | "signing_secret" | "postback";
  dedup: string;
  accessNote: { en: string; de: string } | null;
  summary: { en: string; de: string };
}

export const INTEGRATIONS: IntegrationCatalogEntry[] = [
  { slug: "meta", type: "meta", name: "Meta Ads (Facebook & Instagram)", group: 1, browser: true, server: true, offline: true, auth: "token", dedup: "event_id = browser eventID", accessNote: null, summary: { en: "Meta Pixel plus Conversions API with shared event IDs, hashed matching data and test event codes.", de: "Meta Pixel plus Conversions API mit gemeinsamen Event-IDs, gehashten Matching-Daten und Test-Event-Codes." } },
  { slug: "google-ads", type: "google_ads", name: "Google Ads & YouTube Ads", group: 1, browser: true, server: true, offline: true, auth: "oauth", dedup: "order_id / gclid", accessNote: { en: "Requires a Google Ads developer token approved for your OAuth app.", de: "Benötigt einen für die OAuth-App freigegebenen Google-Ads-Developer-Token." }, summary: { en: "Google tag conversions, Enhanced Conversions and online/offline click-conversion uploads via the Google Ads API.", de: "Google-Tag-Conversions, Enhanced Conversions sowie Online-/Offline-Click-Conversion-Uploads über die Google Ads API." } },
  { slug: "google-analytics", type: "ga4", name: "Google Analytics 4", group: 1, browser: true, server: true, offline: false, auth: "api_secret", dedup: "transaction_id", accessNote: null, summary: { en: "gtag.js plus Measurement Protocol (EU endpoint) with debug validation before sending.", de: "gtag.js plus Measurement Protocol (EU-Endpunkt) mit Debug-Validierung vor dem Versand." } },
  { slug: "tiktok", type: "tiktok", name: "TikTok Ads", group: 1, browser: true, server: true, offline: true, auth: "token", dedup: "event_id", accessNote: null, summary: { en: "TikTok Pixel and Events API with ttclid matching and deduplication.", de: "TikTok Pixel und Events API mit ttclid-Matching und Deduplizierung." } },
  { slug: "microsoft", type: "microsoft", name: "Microsoft Advertising", group: 1, browser: true, server: true, offline: true, auth: "token", dedup: "eventId (UET + CAPI)", accessNote: null, summary: { en: "UET tag plus the Microsoft Conversions API (capi.uet.microsoft.com) with shared event ids, hashed identifiers and consent signals.", de: "UET-Tag plus Microsoft Conversions API (capi.uet.microsoft.com) mit gemeinsamen Event-IDs, gehashten Kennungen und Consent-Signalen." } },
  { slug: "linkedin", type: "linkedin", name: "LinkedIn Ads", group: 1, browser: true, server: true, offline: true, auth: "oauth", dedup: "eventId", accessNote: { en: "Conversions API requires the Advertising API product on your LinkedIn app.", de: "Die Conversions API benötigt das Advertising-API-Produkt in deiner LinkedIn-App." }, summary: { en: "Insight Tag and Conversions API with li_fat_id matching and versioned REST endpoints.", de: "Insight Tag und Conversions API mit li_fat_id-Matching und versionierten REST-Endpunkten." } },
  { slug: "reddit", type: "reddit", name: "Reddit Ads", group: 1, browser: true, server: true, offline: false, auth: "token", dedup: "conversion_id", accessNote: null, summary: { en: "Reddit Pixel and Conversions API with rdt_cid and test mode.", de: "Reddit Pixel und Conversions API mit rdt_cid und Testmodus." } },
  { slug: "pinterest", type: "pinterest", name: "Pinterest Ads", group: 1, browser: true, server: true, offline: true, auth: "token", dedup: "event_id", accessNote: null, summary: { en: "Pinterest Tag and Conversions API with epik click ids.", de: "Pinterest Tag und Conversions API mit epik-Click-IDs." } },
  { slug: "snapchat", type: "snapchat", name: "Snapchat Ads", group: 1, browser: true, server: true, offline: true, auth: "token", dedup: "event_id = client_dedup_id", accessNote: null, summary: { en: "Snap Pixel and Conversions API v3 with ScCid matching.", de: "Snap Pixel und Conversions API v3 mit ScCid-Matching." } },
  { slug: "x", type: "x", name: "X Ads (Twitter)", group: 2, browser: true, server: true, offline: false, auth: "oauth", dedup: "conversion_id", accessNote: null, summary: { en: "X Pixel and Conversion API with twclid.", de: "X Pixel und Conversion API mit twclid." } },
  { slug: "taboola", type: "taboola", name: "Taboola", group: 2, browser: true, server: true, offline: false, auth: "postback", dedup: "click id + event name", accessNote: null, summary: { en: "Taboola Pixel and server-to-server conversion tracking with tblci.", de: "Taboola Pixel und Server-to-Server-Conversion-Tracking mit tblci." } },
  { slug: "outbrain", type: "outbrain", name: "Outbrain", group: 2, browser: true, server: true, offline: false, auth: "postback", dedup: "click id + event name", accessNote: null, summary: { en: "Outbrain Pixel and server-to-server conversions with ob_click_id / dicbo.", de: "Outbrain Pixel und Server-to-Server-Conversions mit ob_click_id / dicbo." } },
  { slug: "amazon", type: "amazon", name: "Amazon Ads & DSP", group: 2, browser: true, server: true, offline: false, auth: "oauth", dedup: "event id", accessNote: { en: "Conversions API access depends on your Amazon Ads account and region.", de: "Der Zugang zur Conversions API hängt von Amazon-Ads-Konto und Region ab." }, summary: { en: "Amazon Ad Tag plus Conversions API via Amazon Ads API.", de: "Amazon Ad Tag plus Conversions API über die Amazon Ads API." } },
  { slug: "spotify", type: "spotify", name: "Spotify Ads", group: 2, browser: true, server: true, offline: false, auth: "postback", dedup: "order id", accessNote: null, summary: { en: "Spotify Pixel and Conversions API.", de: "Spotify Pixel und Conversions API." } },
  { slug: "quora", type: "quora", name: "Quora Ads", group: 2, browser: true, server: true, offline: false, auth: "token", dedup: "event id", accessNote: null, summary: { en: "Quora Pixel and Conversion API with qclid.", de: "Quora Pixel und Conversion API mit qclid." } },
  { slug: "yahoo", type: "yahoo", name: "Yahoo DSP", group: 3, browser: true, server: true, offline: true, auth: "api_secret", dedup: "eventId", accessNote: null, summary: { en: "Yahoo Dot pixel and Conversion API.", de: "Yahoo Dot Pixel und Conversion API." } },
  { slug: "tradedesk", type: "tradedesk", name: "The Trade Desk", group: 3, browser: true, server: true, offline: true, auth: "token", dedup: "event id", accessNote: null, summary: { en: "Universal Pixel and Real-Time Conversion Events API.", de: "Universal Pixel und Real-Time Conversion Events API." } },
  { slug: "google-marketing-platform", type: "gmp", name: "Google Marketing Platform", group: 3, browser: true, server: true, offline: true, auth: "oauth", dedup: "ordinal + order id", accessNote: null, summary: { en: "Floodlight tags plus server-side Floodlight conversions for CM360, DV360 and SA360.", de: "Floodlight-Tags plus serverseitige Floodlight-Conversions für CM360, DV360 und SA360." } },
  { slug: "adroll", type: "adroll", name: "AdRoll", group: 3, browser: true, server: true, offline: false, auth: "token", dedup: "event id", accessNote: { en: "The Conversions and Events API is a gated beta; AdRoll must enable it for your account.", de: "Die Conversions and Events API ist eine freigeschaltete Beta; AdRoll muss sie für dein Konto aktivieren." }, summary: { en: "AdRoll Pixel plus Conversions and Events API.", de: "AdRoll Pixel plus Conversions and Events API." } },
  { slug: "criteo", type: "criteo", name: "Criteo", group: 3, browser: true, server: true, offline: false, auth: "postback", dedup: "transaction id", accessNote: { en: "Server-side events depend on the Criteo product enabled for your account.", de: "Serverseitige Events hängen vom für dein Konto aktivierten Criteo-Produkt ab." }, summary: { en: "Criteo OneTag plus the officially available server-side event endpoints.", de: "Criteo OneTag plus die offiziell verfügbaren serverseitigen Event-Endpunkte." } },
  { slug: "affiliate-postbacks", type: "affiliate", name: "Affiliate & performance networks", group: 3, browser: false, server: true, offline: true, auth: "postback", dedup: "transaction id", accessNote: null, summary: { en: "Universal server-to-server postbacks with presets for Awin, CJ, Impact, TradeTracker, Tradedoubler, Partnerize, Rakuten, Webgains, Digistore24, Adcell, Belboon, TUNE and Everflow.", de: "Universelle Server-to-Server-Postbacks mit Presets für Awin, CJ, Impact, TradeTracker, Tradedoubler, Partnerize, Rakuten, Webgains, Digistore24, Adcell, Belboon, TUNE und Everflow." } },
  { slug: "webhook", type: "webhook", name: "Generic webhook", group: 3, browser: false, server: true, offline: true, auth: "signing_secret", dedup: "event id", accessNote: null, summary: { en: "Signed JSON webhooks to your own systems with allow-listed fields.", de: "Signierte JSON-Webhooks an deine eigenen Systeme mit Allowlist-Feldern." } },
  { slug: "shopify", type: "shopify", name: "Shopify", group: "commerce", browser: true, server: true, offline: false, auth: "oauth", dedup: "order id", accessNote: null, summary: { en: "Web pixel extension plus verified order and refund webhooks.", de: "Web-Pixel-Extension plus verifizierte Order- und Refund-Webhooks." } },
  { slug: "woocommerce", type: "woocommerce", name: "WooCommerce", group: "commerce", browser: true, server: true, offline: false, auth: "signing_secret", dedup: "order id", accessNote: null, summary: { en: "Small plugin with signed order webhooks and a browser adapter.", de: "Kleines Plugin mit signierten Order-Webhooks und Browser-Adapter." } },
  { slug: "shopware", type: "shopware", name: "Shopware 6", group: "commerce", browser: true, server: true, offline: false, auth: "signing_secret", dedup: "order id", accessNote: null, summary: { en: "Shopware app with storefront script and signed order webhooks.", de: "Shopware-App mit Storefront-Script und signierten Order-Webhooks." } },
];

export function integrationBySlug(slug: string): IntegrationCatalogEntry | undefined {
  return INTEGRATIONS.find((i) => i.slug === slug);
}
