/**
 * Marketing + dashboard catalogue of integrations. Every entry is either a real connector in
 * packages/connectors (kind `destination`) or a verified shop integration from docs/10 (kind
 * `source`) — no "coming soon".
 *
 * The technical facts (delivery modes, dedup field, click ids, public ids, credential kinds, consent
 * purpose, API version, verification) mirror the connector metadata, `@track-site/policy` and
 * `packages/connectors/src/versions.ts`. `components/marketing/integrations/catalog.test.ts`
 * cross-checks every destination against the connector registry so the marketing pages can never
 * claim support the code does not have. Access notes describe vendor-side prerequisites.
 */
export type IntegrationCategory = "ads" | "analytics" | "commerce" | "affiliate" | "custom";
export type IntegrationMode = "browser" | "server" | "offline";
/** `destination` = Track delivers events to it; `source` = it delivers verified orders to Track. */
export type IntegrationKind = "destination" | "source";
/** How the implementation was checked: primary vendor documentation, secondary references (vendor docs behind a login), or recorded webhook payloads (shop platforms). */
export type IntegrationVerification = "vendor_docs" | "secondary_sources" | "recorded_payloads";
/** Vendor-side prerequisite before the server path delivers. */
export type IntegrationAccess = "open" | "vendor_setup" | "vendor_approval" | "vendor_beta";
export type ConsentPurposeId = "necessary" | "analytics" | "marketing";
export type CredentialKindId = "access_token" | "api_secret" | "oauth_refresh_token" | "oauth_access_token" | "oauth_token_secret" | "client_id" | "client_secret" | "webhook_secret" | "signing_secret";

export const INTEGRATION_CATEGORIES: readonly IntegrationCategory[] = ["ads", "analytics", "commerce", "affiliate", "custom"];
export const INTEGRATION_MODES: readonly IntegrationMode[] = ["browser", "server", "offline"];

export interface LocalizedText {
  en: string;
  de: string;
}

export interface IntegrationPublicId {
  /** Config key as the connector expects it (shown in monospace). */
  key: string;
  label: LocalizedText;
  optional?: boolean;
}

export interface IntegrationCredential {
  kind: CredentialKindId;
  /** OAuth provider id when the credential is obtained by connecting an account. */
  oauth: string | null;
  /** The destination delivers without it (network feature that is off by default). */
  optional?: boolean;
}

export interface IntegrationCatalogEntry {
  slug: string;
  /** Connector type in packages/connectors (destinations) or the shop platform id (sources). */
  type: string;
  name: string;
  /** Short label for chips, tiles and diagrams. */
  shortName: string;
  /** 1–2 characters for the original monogram glyph (no third-party logos in the repo). */
  monogram: string;
  kind: IntegrationKind;
  category: IntegrationCategory;
  /** Editorial tier used for the default ordering inside a category (1 = core platforms). */
  group: 1 | 2 | 3 | "commerce";
  browser: boolean;
  server: boolean;
  offline: boolean;
  auth: "token" | "oauth" | "api_secret" | "signing_secret" | "postback";
  /** Human-readable deduplication rule. */
  dedup: string;
  /** Vendor field that carries the shared event id (connector `dedupField`); `order_id` pairing key for sources. */
  dedupField: string | null;
  /** Click ids the policy engine allows for this destination (`DESTINATION_CLICK_IDS`). */
  clickIds: string[];
  publicIds: IntegrationPublicId[];
  credentials: IntegrationCredential[];
  /** Consent purpose the policy engine requires by default (`DESTINATION_PURPOSE`). */
  consentPurpose: ConsentPurposeId;
  /** The connector forwards hashed identifiers (SHA-256 e-mail/phone/external id) for matching. */
  hashedMatching: boolean;
  /** Pinned API version (`versions.ts`); null for sources. */
  apiVersion: string | null;
  /** Public vendor documentation the implementation was verified against; null when the docs are Track's own. */
  docsUrl: string | null;
  verification: IntegrationVerification;
  /** ISO date of the verification; null when only recorded payloads exist. */
  verifiedAt: string | null;
  access: IntegrationAccess;
  /** Network presets of a multi-network connector (affiliate). */
  presets?: string[];
  /** Search aliases (product names, click id names, common abbreviations). */
  keywords: string[];
  /** Knowledge article tags that mark an article as related (in addition to `platforms`/`shopSystems` = slug). */
  knowledgeTags: string[];
  accessNote: LocalizedText | null;
  summary: LocalizedText;
}

const META_DOCS = "https://developers.facebook.com/docs/marketing-api/conversions-api/using-the-api";

export const INTEGRATIONS: IntegrationCatalogEntry[] = [
  {
    slug: "meta",
    type: "meta",
    name: "Meta Ads (Facebook & Instagram)",
    shortName: "Meta",
    monogram: "Me",
    kind: "destination",
    category: "ads",
    group: 1,
    browser: true,
    server: true,
    offline: true,
    auth: "token",
    dedup: "event_id = browser eventID",
    dedupField: "event_id",
    clickIds: ["fbclid"],
    publicIds: [{ key: "pixel_id", label: { en: "Pixel / dataset ID", de: "Pixel-/Dataset-ID" } }],
    credentials: [{ kind: "access_token", oauth: null }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v25.0",
    docsUrl: META_DOCS,
    verification: "vendor_docs",
    verifiedAt: "2026-09-02",
    access: "open",
    keywords: ["facebook", "instagram", "capi", "conversions api", "pixel", "fbclid"],
    knowledgeTags: ["meta"],
    accessNote: null,
    summary: { en: "Meta Pixel plus Conversions API with shared event IDs, hashed matching data and test event codes.", de: "Meta Pixel plus Conversions API mit gemeinsamen Event-IDs, gehashten Matching-Daten und Test-Event-Codes." },
  },
  {
    slug: "google-ads",
    type: "google_ads",
    name: "Google Ads & YouTube Ads",
    shortName: "Google Ads",
    monogram: "GA",
    kind: "destination",
    category: "ads",
    group: 1,
    browser: true,
    server: true,
    offline: true,
    auth: "oauth",
    dedup: "order_id / gclid",
    dedupField: "orderId",
    clickIds: ["gclid", "gbraid", "wbraid"],
    publicIds: [
      { key: "conversion_id", label: { en: "Google tag conversion ID", de: "Google-Tag-Conversion-ID" } },
      { key: "customer_id", label: { en: "Google Ads customer ID", de: "Google-Ads-Kundennummer" } },
      { key: "login_customer_id", label: { en: "Manager (MCC) customer ID", de: "Manager-Kundennummer (MCC)" }, optional: true },
    ],
    credentials: [{ kind: "oauth_refresh_token", oauth: "google" }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v25",
    docsUrl: "https://developers.google.com/google-ads/api/docs/conversions/upload-clicks",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "vendor_approval",
    keywords: ["youtube", "gclid", "enhanced conversions", "adwords", "google tag", "click conversions"],
    knowledgeTags: ["google-ads", "enhanced-conversions"],
    accessNote: { en: "Requires a Google Ads developer token approved for your OAuth app.", de: "Benötigt einen für die OAuth-App freigegebenen Google-Ads-Developer-Token." },
    summary: { en: "Google tag conversions, Enhanced Conversions and online/offline click-conversion uploads via the Google Ads API.", de: "Google-Tag-Conversions, Enhanced Conversions sowie Online-/Offline-Click-Conversion-Uploads über die Google Ads API." },
  },
  {
    slug: "google-analytics",
    type: "ga4",
    name: "Google Analytics 4",
    shortName: "GA4",
    monogram: "G4",
    kind: "destination",
    category: "analytics",
    group: 1,
    browser: true,
    server: true,
    offline: false,
    auth: "api_secret",
    dedup: "transaction_id",
    dedupField: "transaction_id",
    clickIds: ["gclid", "gbraid", "wbraid"],
    publicIds: [{ key: "measurement_id", label: { en: "Measurement ID", de: "Measurement-ID" } }],
    credentials: [{ kind: "api_secret", oauth: null }],
    consentPurpose: "analytics",
    hashedMatching: true,
    apiVersion: "mp-v2",
    docsUrl: "https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference",
    verification: "vendor_docs",
    verifiedAt: "2026-09-02",
    access: "open",
    keywords: ["ga4", "google analytics", "measurement protocol", "gtag", "analytics"],
    knowledgeTags: ["ga4", "measurement-protocol"],
    accessNote: null,
    summary: { en: "gtag.js plus Measurement Protocol (EU endpoint) with debug validation before sending.", de: "gtag.js plus Measurement Protocol (EU-Endpunkt) mit Debug-Validierung vor dem Versand." },
  },
  {
    slug: "tiktok",
    type: "tiktok",
    name: "TikTok Ads",
    shortName: "TikTok",
    monogram: "TT",
    kind: "destination",
    category: "ads",
    group: 1,
    browser: true,
    server: true,
    offline: true,
    auth: "token",
    dedup: "event_id",
    dedupField: "event_id",
    clickIds: ["ttclid"],
    publicIds: [{ key: "pixel_id", label: { en: "Pixel code", de: "Pixel-Code" } }],
    credentials: [{ kind: "access_token", oauth: null }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v1.3",
    docsUrl: "https://business-api.tiktok.com/portal/docs?id=1771100865818625",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["events api", "ttclid", "pixel"],
    knowledgeTags: ["tiktok"],
    accessNote: null,
    summary: { en: "TikTok Pixel and Events API with ttclid matching and deduplication.", de: "TikTok Pixel und Events API mit ttclid-Matching und Deduplizierung." },
  },
  {
    slug: "microsoft",
    type: "microsoft",
    name: "Microsoft Advertising",
    shortName: "Microsoft Ads",
    monogram: "MS",
    kind: "destination",
    category: "ads",
    group: 1,
    browser: true,
    server: true,
    offline: true,
    auth: "token",
    dedup: "eventId (UET + CAPI)",
    dedupField: "eventId",
    clickIds: ["msclkid"],
    publicIds: [{ key: "uet_tag_id", label: { en: "UET tag ID", de: "UET-Tag-ID" } }],
    credentials: [{ kind: "access_token", oauth: null }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v1",
    docsUrl: "https://learn.microsoft.com/en-us/advertising/guides/uet-conversion-api-integration?view=bingads-13",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["bing", "uet", "msclkid", "conversions api"],
    knowledgeTags: ["microsoft-advertising", "uet"],
    accessNote: null,
    summary: { en: "UET tag plus the Microsoft Conversions API (capi.uet.microsoft.com) with shared event ids, hashed identifiers and consent signals.", de: "UET-Tag plus Microsoft Conversions API (capi.uet.microsoft.com) mit gemeinsamen Event-IDs, gehashten Kennungen und Consent-Signalen." },
  },
  {
    slug: "linkedin",
    type: "linkedin",
    name: "LinkedIn Ads",
    shortName: "LinkedIn",
    monogram: "Li",
    kind: "destination",
    category: "ads",
    group: 1,
    browser: true,
    server: true,
    offline: true,
    auth: "oauth",
    dedup: "eventId",
    dedupField: "eventId",
    clickIds: ["li_fat_id"],
    publicIds: [
      { key: "partner_id", label: { en: "Insight Tag partner ID", de: "Insight-Tag-Partner-ID" } },
      { key: "ad_account_id", label: { en: "Ad account ID", de: "Werbekonto-ID" } },
    ],
    credentials: [{ kind: "oauth_access_token", oauth: "linkedin" }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "202608",
    docsUrl: "https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads-reporting/conversions-api",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "vendor_approval",
    keywords: ["insight tag", "b2b", "li_fat_id", "conversions api"],
    knowledgeTags: ["linkedin"],
    accessNote: { en: "Conversions API requires the Advertising API product on your LinkedIn app.", de: "Die Conversions API benötigt das Advertising-API-Produkt in deiner LinkedIn-App." },
    summary: { en: "Insight Tag and Conversions API with li_fat_id matching and versioned REST endpoints.", de: "Insight Tag und Conversions API mit li_fat_id-Matching und versionierten REST-Endpunkten." },
  },
  {
    slug: "reddit",
    type: "reddit",
    name: "Reddit Ads",
    shortName: "Reddit",
    monogram: "Re",
    kind: "destination",
    category: "ads",
    group: 1,
    browser: true,
    server: true,
    offline: false,
    auth: "token",
    dedup: "conversion_id",
    dedupField: "conversion_id",
    clickIds: ["rdt_cid"],
    publicIds: [{ key: "pixel_id", label: { en: "Pixel / ad account ID", de: "Pixel-/Werbekonto-ID" } }],
    credentials: [{ kind: "access_token", oauth: null }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v3",
    docsUrl: "https://ads-api.reddit.com/docs/v3/guides/programs/capi/direct-integration",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["rdt_cid", "conversions api", "pixel"],
    knowledgeTags: ["reddit"],
    accessNote: null,
    summary: { en: "Reddit Pixel and Conversions API with rdt_cid and test mode.", de: "Reddit Pixel und Conversions API mit rdt_cid und Testmodus." },
  },
  {
    slug: "pinterest",
    type: "pinterest",
    name: "Pinterest Ads",
    shortName: "Pinterest",
    monogram: "Pi",
    kind: "destination",
    category: "ads",
    group: 1,
    browser: true,
    server: true,
    offline: true,
    auth: "token",
    dedup: "event_id",
    dedupField: "event_id",
    clickIds: ["epik"],
    publicIds: [
      { key: "tag_id", label: { en: "Pinterest tag ID", de: "Pinterest-Tag-ID" } },
      { key: "ad_account_id", label: { en: "Ad account ID", de: "Werbekonto-ID" } },
    ],
    credentials: [{ kind: "access_token", oauth: null }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v5",
    docsUrl: "https://developers.pinterest.com/docs/track-conversions/track-conversions-in-the-api/",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["epik", "conversions api", "tag"],
    knowledgeTags: ["pinterest"],
    accessNote: null,
    summary: { en: "Pinterest Tag and Conversions API with epik click ids.", de: "Pinterest Tag und Conversions API mit epik-Click-IDs." },
  },
  {
    slug: "snapchat",
    type: "snapchat",
    name: "Snapchat Ads",
    shortName: "Snapchat",
    monogram: "Sn",
    kind: "destination",
    category: "ads",
    group: 1,
    browser: true,
    server: true,
    offline: true,
    auth: "token",
    dedup: "event_id = client_dedup_id",
    dedupField: "event_id",
    clickIds: ["sccid"],
    publicIds: [{ key: "pixel_id", label: { en: "Snap Pixel ID", de: "Snap-Pixel-ID" } }],
    credentials: [{ kind: "access_token", oauth: null }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v3",
    docsUrl: "https://developers.snap.com/api/marketing-api/Conversions-API/Parameters",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["snap pixel", "sccid", "conversions api"],
    knowledgeTags: ["snapchat"],
    accessNote: null,
    summary: { en: "Snap Pixel and Conversions API v3 with ScCid matching.", de: "Snap Pixel und Conversions API v3 mit ScCid-Matching." },
  },
  {
    slug: "x",
    type: "x",
    name: "X Ads (Twitter)",
    shortName: "X Ads",
    monogram: "X",
    kind: "destination",
    category: "ads",
    group: 2,
    browser: true,
    server: true,
    offline: false,
    auth: "oauth",
    dedup: "conversion_id",
    dedupField: "conversion_id",
    clickIds: ["twclid"],
    publicIds: [{ key: "pixel_id", label: { en: "X Pixel ID", de: "X-Pixel-ID" } }],
    credentials: [
      { kind: "oauth_access_token", oauth: "x" },
      { kind: "oauth_token_secret", oauth: "x" },
    ],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "12",
    docsUrl: "https://docs.x.com/x-ads-api/measurement/web-conversions",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["twitter", "twclid", "conversion api"],
    knowledgeTags: [],
    accessNote: null,
    summary: { en: "X Pixel and Conversion API with twclid.", de: "X Pixel und Conversion API mit twclid." },
  },
  {
    slug: "taboola",
    type: "taboola",
    name: "Taboola",
    shortName: "Taboola",
    monogram: "Ta",
    kind: "destination",
    category: "ads",
    group: 2,
    browser: true,
    server: true,
    offline: false,
    auth: "postback",
    dedup: "click id + event name",
    dedupField: "orderid",
    clickIds: ["tblci"],
    publicIds: [{ key: "account_id", label: { en: "Taboola account ID (numeric)", de: "Taboola-Konto-ID (numerisch)" } }],
    credentials: [],
    consentPurpose: "marketing",
    hashedMatching: false,
    apiVersion: "log/3",
    docsUrl: "https://developers.taboola.com/pixel/docs/bulk-submit-s2s-conversions",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["native", "realize", "tblci", "s2s"],
    knowledgeTags: [],
    accessNote: null,
    summary: { en: "Taboola Pixel and server-to-server conversion tracking with tblci.", de: "Taboola Pixel und Server-to-Server-Conversion-Tracking mit tblci." },
  },
  {
    slug: "outbrain",
    type: "outbrain",
    name: "Outbrain",
    shortName: "Outbrain",
    monogram: "Ou",
    kind: "destination",
    category: "ads",
    group: 2,
    browser: true,
    server: true,
    offline: false,
    auth: "postback",
    dedup: "click id + event name",
    dedupField: "orderId",
    clickIds: ["ob_click_id", "dicbo"],
    publicIds: [{ key: "marketer_id", label: { en: "Outbrain marketer ID", de: "Outbrain-Marketer-ID" } }],
    credentials: [],
    consentPurpose: "marketing",
    hashedMatching: false,
    apiVersion: "unifiedPixel",
    docsUrl: "https://www.outbrain.com/help/advertisers/server2server-integrations/",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["native", "amplify", "ob_click_id", "dicbo", "s2s"],
    knowledgeTags: [],
    accessNote: null,
    summary: { en: "Outbrain Pixel and server-to-server conversions with ob_click_id / dicbo.", de: "Outbrain Pixel und Server-to-Server-Conversions mit ob_click_id / dicbo." },
  },
  {
    slug: "amazon",
    type: "amazon",
    name: "Amazon Ads & DSP",
    shortName: "Amazon Ads",
    monogram: "Am",
    kind: "destination",
    category: "ads",
    group: 2,
    browser: true,
    server: true,
    offline: true,
    auth: "oauth",
    dedup: "event id",
    dedupField: "eventId",
    clickIds: ["maas"],
    publicIds: [
      { key: "tag_id", label: { en: "Amazon Ad Tag ID", de: "Amazon-Ad-Tag-ID" } },
      { key: "account_id", label: { en: "Amazon Ads account ID", de: "Amazon-Ads-Konto-ID" } },
      { key: "region", label: { en: "API region (NA, EU, FE)", de: "API-Region (NA, EU, FE)" } },
      { key: "data_set_name", label: { en: "Events API data set name", de: "Data-Set-Name der Events API" } },
    ],
    credentials: [{ kind: "oauth_refresh_token", oauth: "amazon" }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "events-v1",
    docsUrl: "https://advertising.amazon.com/API/docs/en-us/guides/events/overview",
    verification: "secondary_sources",
    verifiedAt: "2026-09-03",
    access: "vendor_approval",
    keywords: ["dsp", "amazon ads", "ad tag", "events api"],
    knowledgeTags: [],
    accessNote: { en: "Conversions API access depends on your Amazon Ads account and region; conversion definitions must exist in the Ads account before events are accepted.", de: "Der Zugang zur Conversions API hängt von Amazon-Ads-Konto und Region ab; Conversion-Definitionen müssen im Ads-Konto existieren, bevor Events angenommen werden." },
    summary: { en: "Amazon Ad Tag plus Conversions API via Amazon Ads API.", de: "Amazon Ad Tag plus Conversions API über die Amazon Ads API." },
  },
  {
    slug: "spotify",
    type: "spotify",
    name: "Spotify Ads",
    shortName: "Spotify",
    monogram: "Sp",
    kind: "destination",
    category: "ads",
    group: 2,
    browser: true,
    server: true,
    offline: false,
    auth: "postback",
    dedup: "order id",
    dedupField: null,
    clickIds: ["spclid"],
    publicIds: [{ key: "pixel_id", label: { en: "Spotify pixel key", de: "Spotify-Pixel-Key" } }],
    credentials: [],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "pixel-v1",
    docsUrl: "https://help.adanalytics.spotify.com/server-side-gtm-ssgtm-integration-1",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["ad analytics", "audio", "podcast", "spclid"],
    knowledgeTags: [],
    accessNote: null,
    summary: { en: "Spotify Pixel and Conversions API.", de: "Spotify Pixel und Conversions API." },
  },
  {
    slug: "quora",
    type: "quora",
    name: "Quora Ads",
    shortName: "Quora",
    monogram: "Qu",
    kind: "destination",
    category: "ads",
    group: 2,
    browser: true,
    server: true,
    offline: false,
    auth: "token",
    dedup: "event id",
    dedupField: "event_id",
    clickIds: ["qclid"],
    publicIds: [
      { key: "pixel_id", label: { en: "Quora pixel ID", de: "Quora-Pixel-ID" } },
      { key: "account_id", label: { en: "Ad account ID", de: "Werbekonto-ID" } },
    ],
    credentials: [{ kind: "access_token", oauth: null }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v1",
    docsUrl: "https://www.quora.com/ads/conversion_api_doc",
    verification: "secondary_sources",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["qclid", "conversion api", "pixel"],
    knowledgeTags: [],
    accessNote: null,
    summary: { en: "Quora Pixel and Conversion API with qclid.", de: "Quora Pixel und Conversion API mit qclid." },
  },
  {
    slug: "yahoo",
    type: "yahoo",
    name: "Yahoo DSP",
    shortName: "Yahoo DSP",
    monogram: "Ya",
    kind: "destination",
    category: "ads",
    group: 3,
    browser: true,
    server: true,
    offline: true,
    auth: "api_secret",
    dedup: "eventId",
    dedupField: "eventId",
    clickIds: ["yclid", "vmcid"],
    publicIds: [
      { key: "pixel_id", label: { en: "Yahoo pixel ID", de: "Yahoo-Pixel-ID" } },
      { key: "project_id", label: { en: "Dot tag project ID", de: "Dot-Tag-Projekt-ID" } },
    ],
    credentials: [
      { kind: "client_id", oauth: null },
      { kind: "client_secret", oauth: null },
    ],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v1",
    docsUrl: "https://help.yahooinc.com/dsp-api/docs/standard-yahoo-conversion-api",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["dsp", "dot tag", "yclid", "conversion api"],
    knowledgeTags: [],
    accessNote: null,
    summary: { en: "Yahoo Dot pixel and Conversion API.", de: "Yahoo Dot Pixel und Conversion API." },
  },
  {
    slug: "tradedesk",
    type: "tradedesk",
    name: "The Trade Desk",
    shortName: "The Trade Desk",
    monogram: "TD",
    kind: "destination",
    category: "ads",
    group: 3,
    browser: true,
    server: true,
    offline: false,
    auth: "token",
    dedup: "event id",
    dedupField: "order_id",
    clickIds: ["ttd_uuid"],
    publicIds: [
      { key: "advertiser_id", label: { en: "Advertiser ID", de: "Advertiser-ID" } },
      { key: "pixel_id", label: { en: "Universal pixel ID", de: "Universal-Pixel-ID" } },
      { key: "tracker_id", label: { en: "Event tracker ID", de: "Event-Tracker-ID" }, optional: true },
    ],
    credentials: [],
    consentPurpose: "marketing",
    hashedMatching: false,
    apiVersion: "realtimeconversion",
    docsUrl: "https://partner.thetradedesk.com/v3/portal/data/doc/DataConversionEventsApi",
    verification: "secondary_sources",
    verifiedAt: "2026-09-03",
    access: "vendor_setup",
    keywords: ["ttd", "universal pixel", "dsp", "real-time conversions"],
    knowledgeTags: [],
    accessNote: { en: "Server events are accepted only for pixels or event trackers that already exist in The Trade Desk platform for your advertiser.", de: "Server-Events werden nur für Pixel oder Event-Tracker angenommen, die in der Trade-Desk-Plattform für deinen Advertiser bereits angelegt sind." },
    summary: { en: "Universal Pixel and Real-Time Conversion Events API.", de: "Universal Pixel und Real-Time Conversion Events API." },
  },
  {
    slug: "google-marketing-platform",
    type: "gmp",
    name: "Google Marketing Platform",
    shortName: "GMP Floodlight",
    monogram: "GM",
    kind: "destination",
    category: "ads",
    group: 3,
    browser: true,
    server: true,
    offline: true,
    auth: "oauth",
    dedup: "ordinal + order id",
    dedupField: "ordinal",
    clickIds: ["gclid", "dclid", "gbraid", "wbraid"],
    publicIds: [
      { key: "floodlight_configuration_id", label: { en: "Floodlight configuration ID (advertiser)", de: "Floodlight-Konfigurations-ID (Advertiser)" } },
      { key: "profile_id", label: { en: "CM360 user profile ID", de: "CM360-Nutzerprofil-ID" } },
    ],
    credentials: [{ kind: "oauth_refresh_token", oauth: "google" }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "v5",
    docsUrl: "https://developers.google.com/doubleclick-advertisers/rest/v5/conversions/batchinsert",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    keywords: ["floodlight", "cm360", "dv360", "sa360", "campaign manager", "display & video", "search ads 360", "dclid"],
    knowledgeTags: [],
    accessNote: null,
    summary: { en: "Floodlight tags plus server-side Floodlight conversions for CM360, DV360 and SA360.", de: "Floodlight-Tags plus serverseitige Floodlight-Conversions für CM360, DV360 und SA360." },
  },
  {
    slug: "adroll",
    type: "adroll",
    name: "AdRoll",
    shortName: "AdRoll",
    monogram: "AR",
    kind: "destination",
    category: "ads",
    group: 3,
    browser: true,
    server: true,
    offline: false,
    auth: "token",
    dedup: "event id",
    dedupField: "event_attributes.order_id",
    clickIds: ["adroll_clid"],
    publicIds: [
      { key: "advertiser_id", label: { en: "Advertisable EID", de: "Advertisable-EID" } },
      { key: "pixel_id", label: { en: "Pixel EID", de: "Pixel-EID" } },
    ],
    credentials: [{ kind: "access_token", oauth: null }],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "s2s-beta",
    docsUrl: "https://apidocs.nextroll.com/server-to-server-api/reference.html",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "vendor_beta",
    keywords: ["nextroll", "retargeting", "s2s"],
    knowledgeTags: [],
    accessNote: { en: "The Conversions and Events API is a gated beta; AdRoll must enable it for your account. The pixel works without it.", de: "Die Conversions and Events API ist eine freigeschaltete Beta; AdRoll muss sie für dein Konto aktivieren. Der Pixel funktioniert auch ohne." },
    summary: { en: "AdRoll Pixel plus Conversions and Events API.", de: "AdRoll Pixel plus Conversions and Events API." },
  },
  {
    slug: "criteo",
    type: "criteo",
    name: "Criteo",
    shortName: "Criteo",
    monogram: "Cr",
    kind: "destination",
    category: "ads",
    group: 3,
    browser: true,
    server: true,
    offline: false,
    auth: "postback",
    dedup: "transaction id",
    dedupField: "id",
    clickIds: ["crto_clid"],
    publicIds: [{ key: "account_id", label: { en: "Criteo account ID (partner ID)", de: "Criteo-Konto-ID (Partner-ID)" } }],
    credentials: [],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "s2s_v1.0.0",
    docsUrl: "https://guides.criteotilt.com/onetag/s2s/",
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "vendor_approval",
    keywords: ["onetag", "retargeting", "crto_clid", "s2s"],
    knowledgeTags: [],
    accessNote: { en: "Server-side events depend on the Criteo product enabled for your account.", de: "Serverseitige Events hängen vom für dein Konto aktivierten Criteo-Produkt ab." },
    summary: { en: "Criteo OneTag plus the officially available server-side event endpoints.", de: "Criteo OneTag plus die offiziell verfügbaren serverseitigen Event-Endpunkte." },
  },
  {
    slug: "affiliate-postbacks",
    type: "affiliate",
    name: "Affiliate & performance networks",
    shortName: "Affiliate networks",
    monogram: "Af",
    kind: "destination",
    category: "affiliate",
    group: 3,
    browser: false,
    server: true,
    offline: false,
    auth: "postback",
    dedup: "transaction id",
    dedupField: "order_id",
    clickIds: ["aff_click_id", "aff_sub_id", "awc", "cjevent", "irclickid", "tduid", "ttl", "utm_term"],
    publicIds: [{ key: "preset", label: { en: "Network preset", de: "Netzwerk-Preset" } }],
    credentials: [
      { kind: "access_token", oauth: null, optional: true },
      { kind: "api_secret", oauth: null, optional: true },
      { kind: "signing_secret", oauth: null, optional: true },
      { kind: "webhook_secret", oauth: null, optional: true },
    ],
    consentPurpose: "marketing",
    hashedMatching: true,
    apiVersion: "postback-v1",
    docsUrl: null,
    verification: "vendor_docs",
    verifiedAt: "2026-09-03",
    access: "open",
    presets: ["Awin", "CJ Affiliate", "impact.com", "TradeTracker", "Tradedoubler", "Partnerize", "Rakuten Advertising", "Webgains", "Digistore24", "ADCELL", "belboon", "TUNE (HasOffers)", "Everflow", "Custom postback"],
    keywords: ["postback", "s2s", "server-to-server", "partner", "performance", "affiliate"],
    knowledgeTags: ["affiliate", "postback"],
    accessNote: null,
    summary: { en: "Universal server-to-server postbacks with presets for Awin, CJ, Impact, TradeTracker, Tradedoubler, Partnerize, Rakuten, Webgains, Digistore24, Adcell, Belboon, TUNE and Everflow.", de: "Universelle Server-to-Server-Postbacks mit Presets für Awin, CJ, Impact, TradeTracker, Tradedoubler, Partnerize, Rakuten, Webgains, Digistore24, Adcell, Belboon, TUNE und Everflow." },
  },
  {
    slug: "webhook",
    type: "webhook",
    name: "Generic webhook",
    shortName: "Webhook",
    monogram: "WH",
    kind: "destination",
    category: "custom",
    group: 3,
    browser: false,
    server: true,
    offline: false,
    auth: "signing_secret",
    dedup: "event id",
    dedupField: "id",
    clickIds: [],
    publicIds: [{ key: "url", label: { en: "Endpoint URL (https)", de: "Endpunkt-URL (https)" } }],
    credentials: [{ kind: "signing_secret", oauth: null }],
    consentPurpose: "necessary",
    hashedMatching: true,
    apiVersion: "1",
    docsUrl: null,
    verification: "vendor_docs",
    verifiedAt: "2026-09-02",
    access: "open",
    keywords: ["custom", "crm", "data warehouse", "own systems", "hmac", "json", "signed"],
    knowledgeTags: [],
    accessNote: null,
    summary: { en: "Signed JSON webhooks to your own systems with allow-listed fields.", de: "Signierte JSON-Webhooks an deine eigenen Systeme mit Allowlist-Feldern." },
  },
  {
    slug: "shopify",
    type: "shopify",
    name: "Shopify",
    shortName: "Shopify",
    monogram: "Sh",
    kind: "source",
    category: "commerce",
    group: "commerce",
    browser: true,
    server: true,
    offline: false,
    auth: "signing_secret",
    dedup: "order id",
    dedupField: "order_id",
    clickIds: [],
    publicIds: [
      { key: "shop_domain", label: { en: "Shop domain", de: "Shop-Domain" } },
      { key: "default_currency", label: { en: "Fallback currency", de: "Fallback-Währung" } },
    ],
    credentials: [{ kind: "webhook_secret", oauth: null }],
    consentPurpose: "necessary",
    hashedMatching: true,
    apiVersion: null,
    docsUrl: null,
    verification: "recorded_payloads",
    verifiedAt: null,
    access: "open",
    keywords: ["shop", "web pixel", "orders", "refunds", "e-commerce", "ecommerce"],
    knowledgeTags: ["shopify"],
    accessNote: null,
    summary: { en: "Web pixel extension plus verified order and refund webhooks.", de: "Web-Pixel-Extension plus verifizierte Order- und Refund-Webhooks." },
  },
  {
    slug: "woocommerce",
    type: "woocommerce",
    name: "WooCommerce",
    shortName: "WooCommerce",
    monogram: "Wo",
    kind: "source",
    category: "commerce",
    group: "commerce",
    browser: true,
    server: true,
    offline: false,
    auth: "signing_secret",
    dedup: "order id",
    dedupField: "order_id",
    clickIds: [],
    publicIds: [
      { key: "shop_domain", label: { en: "Shop domain", de: "Shop-Domain" } },
      { key: "default_currency", label: { en: "Fallback currency", de: "Fallback-Währung" } },
    ],
    credentials: [{ kind: "webhook_secret", oauth: null }],
    consentPurpose: "necessary",
    hashedMatching: true,
    apiVersion: null,
    docsUrl: null,
    verification: "recorded_payloads",
    verifiedAt: null,
    access: "open",
    keywords: ["wordpress", "plugin", "shop", "orders", "e-commerce", "ecommerce"],
    knowledgeTags: ["woocommerce"],
    accessNote: null,
    summary: { en: "Small plugin with signed order webhooks and a browser adapter.", de: "Kleines Plugin mit signierten Order-Webhooks und Browser-Adapter." },
  },
  {
    slug: "shopware",
    type: "shopware",
    name: "Shopware 6",
    shortName: "Shopware",
    monogram: "SW",
    kind: "source",
    category: "commerce",
    group: "commerce",
    browser: true,
    server: true,
    offline: false,
    auth: "signing_secret",
    dedup: "order id",
    dedupField: "order_id",
    clickIds: [],
    publicIds: [
      { key: "shop_domain", label: { en: "Shop domain", de: "Shop-Domain" } },
      { key: "default_currency", label: { en: "Fallback currency", de: "Fallback-Währung" } },
      { key: "purchase_on", label: { en: "Purchase moment (paid or placed)", de: "Kaufzeitpunkt (bezahlt oder bestellt)" }, optional: true },
    ],
    credentials: [{ kind: "webhook_secret", oauth: null }],
    consentPurpose: "necessary",
    hashedMatching: true,
    apiVersion: null,
    docsUrl: null,
    verification: "recorded_payloads",
    verifiedAt: null,
    access: "open",
    keywords: ["shop", "app", "storefront", "orders", "e-commerce", "ecommerce"],
    knowledgeTags: ["shopware"],
    accessNote: null,
    summary: { en: "Shopware app with storefront script and signed order webhooks.", de: "Shopware-App mit Storefront-Script und signierten Order-Webhooks." },
  },
];

export function integrationBySlug(slug: string): IntegrationCatalogEntry | undefined {
  return INTEGRATIONS.find((i) => i.slug === slug);
}

/** Delivery modes of an entry in catalogue order. */
export function integrationModes(entry: Pick<IntegrationCatalogEntry, "browser" | "server" | "offline">): IntegrationMode[] {
  return INTEGRATION_MODES.filter((m) => entry[m]);
}

/** Catalogue text language for a locale (English for locales without catalogue copy). */
export function catalogLang(locale: string): keyof LocalizedText {
  return locale === "de" ? "de" : "en";
}
