import { ACTIVE_LOCALES, DEFAULT_LOCALE, type AppLocale } from "../i18n/routing";
import { INTEGRATIONS } from "./integrations-catalog";
import { KNOWLEDGE_PATH } from "./knowledge-routes";

/**
 * Indexable marketing routes as locale-neutral paths. Every public URL is served under a locale
 * prefix (`/en/...`, `/de/...`); `localizedPath()` in `@/lib/seo` adds it. Tracking Knowledge article
 * routes are added from content by the sitemap route handlers.
 */
export const FEATURE_PAGES = ["ai-setup", "server-side-tracking", "event-debugger", "data-quality", "consent", "attribution"] as const;

export { KNOWLEDGE_PATH } from "./knowledge-routes";

export const STATIC_MARKETING_ROUTES: Array<{ path: string; changeFrequency: "daily" | "weekly" | "monthly"; priority: number }> = [
  { path: "/", changeFrequency: "weekly", priority: 1 },
  { path: "/features", changeFrequency: "monthly", priority: 0.9 },
  ...FEATURE_PAGES.map((f) => ({ path: `/features/${f}`, changeFrequency: "monthly" as const, priority: 0.8 })),
  { path: "/how-it-works", changeFrequency: "monthly", priority: 0.8 },
  { path: "/integrations", changeFrequency: "weekly", priority: 0.9 },
  ...INTEGRATIONS.map((i) => ({ path: `/integrations/${i.slug}`, changeFrequency: "monthly" as const, priority: 0.7 })),
  { path: "/pricing", changeFrequency: "monthly", priority: 0.9 },
  { path: "/security", changeFrequency: "monthly", priority: 0.6 },
  { path: "/privacy", changeFrequency: "monthly", priority: 0.5 },
  { path: "/data-processing", changeFrequency: "monthly", priority: 0.5 },
  { path: "/subprocessors", changeFrequency: "monthly", priority: 0.4 },
  { path: "/docs", changeFrequency: "weekly", priority: 0.8 },
  { path: KNOWLEDGE_PATH, changeFrequency: "daily", priority: 0.8 },
  { path: "/contact", changeFrequency: "monthly", priority: 0.5 },
  { path: "/demo", changeFrequency: "monthly", priority: 0.6 },
  { path: "/support", changeFrequency: "monthly", priority: 0.5 },
  { path: "/terms", changeFrequency: "monthly", priority: 0.3 },
  { path: "/imprint", changeFrequency: "monthly", priority: 0.3 },
  { path: "/status", changeFrequency: "daily", priority: 0.3 },
];

/** Auth routes: served under every locale, never indexed (robots + `noindex`). */
export const AUTH_ROUTES = ["/login", "/signup", "/verify-email", "/forgot-password", "/reset-password", "/two-factor", "/accept-invitation"] as const;

/**
 * English URLs that existed without a prefix before the `/en` roll-out. `next.config.ts` redirects
 * them permanently to `/en/...` as a safety net; the proxy does the same for every other path.
 *
 * Redirect chains are forbidden (supplement §6): when a section moves (e.g. `/blog/...` →
 * `/[locale]/tracking-knowledge/...`), register its legacy redirects for BOTH the unprefixed and the
 * `/[locale]/blog/...` URLs (see `KNOWLEDGE_LEGACY_REDIRECTS`) and keep the old paths out of this
 * list, so `/blog/x` goes straight to the new URL instead of via `/en/blog/x`.
 */
export const LEGACY_UNPREFIXED_PATHS: readonly string[] = [...STATIC_MARKETING_ROUTES.map((r) => r.path), `${KNOWLEDGE_PATH}/feed.xml`];

export interface LegacyRedirect {
  /** Next.js redirect source pattern (path-to-regexp syntax). */
  source: string;
  destination: string;
  /** Unprefixed English URL: must not fire on the dedicated app/api/cdn hosts (see `next.config.ts`). */
  unprefixed: boolean;
}

/**
 * Articles whose localized slug no longer equals the old shared blog slug. Every entry produces an
 * explicit redirect that runs BEFORE the generic `/:locale/blog/:slug` rule, so the old URL lands
 * directly on the localized article. Empty while every slug is unchanged (the redirect matrix in
 * `docs/redirects-blog-to-tracking-knowledge.md`, generated by `scripts/redirect-matrix.mjs`, lists
 * the rows that need an entry here).
 */
export const KNOWLEDGE_SLUG_REDIRECTS: ReadonlyArray<{ locale: AppLocale; from: string; to: string }> = [];

/**
 * Blog → Tracking Knowledge (supplement §6): permanent redirects for every old URL — the unprefixed
 * English ones (`/blog`, `/blog/feed.xml`, `/blog/:slug`) straight to `/en/tracking-knowledge/...`
 * and the prefixed ones (`/:locale/blog/...`) to the same locale. Next.js keeps the query string, so
 * UTM parameters survive. Order matters: explicit slug rules first, `feed.xml` before `:slug`.
 */
export const KNOWLEDGE_LEGACY_REDIRECTS: readonly LegacyRedirect[] = (() => {
  const locale = `:locale(${ACTIVE_LOCALES.join("|")})`;
  const explicit = KNOWLEDGE_SLUG_REDIRECTS.flatMap<LegacyRedirect>((r) => [
    ...(r.locale === DEFAULT_LOCALE ? [{ source: `/blog/${r.from}`, destination: `/${DEFAULT_LOCALE}${KNOWLEDGE_PATH}/${r.to}`, unprefixed: true }] : []),
    { source: `/${r.locale}/blog/${r.from}`, destination: `/${r.locale}${KNOWLEDGE_PATH}/${r.to}`, unprefixed: false },
  ]);
  return [
    ...explicit,
    { source: "/blog", destination: `/${DEFAULT_LOCALE}${KNOWLEDGE_PATH}`, unprefixed: true },
    { source: "/blog/feed.xml", destination: `/${DEFAULT_LOCALE}${KNOWLEDGE_PATH}/feed.xml`, unprefixed: true },
    { source: "/blog/:slug", destination: `/${DEFAULT_LOCALE}${KNOWLEDGE_PATH}/:slug`, unprefixed: true },
    { source: `/${locale}/blog`, destination: `/:locale${KNOWLEDGE_PATH}`, unprefixed: false },
    { source: `/${locale}/blog/feed.xml`, destination: `/:locale${KNOWLEDGE_PATH}/feed.xml`, unprefixed: false },
    { source: `/${locale}/blog/:slug`, destination: `/:locale${KNOWLEDGE_PATH}/:slug`, unprefixed: false },
  ];
})();
