import type { PricingCopy } from "../types";

/**
 * German (de) copy of the pricing area. Same shape as en.ts; see docs/14-localization.md.
 */

export const PRICING_COPY_DE: PricingCopy = {
  eyebrow: "Preise",
  title: "Klare Tarife, die mit deinem Eventvolumen wachsen",
  text: "Jeder Tarif enthält Browser- und Server-Side-Tracking, alle Standard-Destinations, den AI-Assistenten, die Consent Engine und den Live Event Debugger. Wähle nach Websites, monatlichen Events, Teamgröße und Aufbewahrung. Preise netto in EUR; abgerechnet wird über Stripe.",
  hero: { facts: ["Monatliche Abrechnung als Standard, Kündigung zum Periodenende", "Nettopreise in EUR, zzgl. USt., sofern anwendbar", "{trialDays} Tage {trialPlan} testen, ohne Kreditkarte"] },
  interval: {
    legend: "Abrechnungszeitraum",
    monthly: "Monatlich",
    yearly: "Jährlich",
    monthlyHint: "Abrechnung jeden Monat. Kündigung zum Ende der laufenden Periode.",
    yearlyHint: "Einmal pro Jahr im Voraus. Der Jahrespreis entspricht zehn Monatsraten.",
    announceMonthly: "Monatspreise werden angezeigt.",
    announceYearly: "Jahrespreise werden angezeigt.",
  },
  recommended: "Empfohlen",
  contactSales: "Mit dem Vertrieb sprechen",
  start: "Jetzt starten",
  plansLabel: "Tarife",
  plan: {
    perMonth: "pro Monat",
    perYear: "pro Jahr",
    billedMonthly: "Monatliche Abrechnung. Kündigung zum Periodenende.",
    billedYearly: "{total} einmal pro Jahr belastet",
    equivalent: "≈ {monthly} pro Monat",
    instalments: "entspricht {n} Monatsraten",
    eventsLabel: "akzeptierte Events pro Monat",
    sites: "Websites",
    team: "Team",
    retention: "Aufbewahrung",
    unlimited: "Unbegrenzt (Fair Use)",
    days: "{n} Tage",
    months: "{n} Monate",
    choose: "{plan} wählen",
    trialHint: "Inklusive {days} Tage Testphase, keine Kreditkarte nötig",
    overageHint: "Optionaler Mehrverbrauch: {price} je {events} weitere Events, nur mit deiner ausdrücklichen Entscheidung.",
    recommended: "Empfohlen",
    listLabel: "Das bringt {plan} zusätzlich",
  },
  tax: {
    title: "Steuern und Rechnungen",
    text: "Alle Preise verstehen sich netto in EUR ohne Umsatzsteuer. Die Umsatzsteuer kommt hinzu, sofern sie nach deinem Rechnungsland anfällt. Unternehmen geben ihre USt-IdNr. im Checkout an; Rechnungen zu jeder Zahlung findest du im Billing-Portal.",
  },
  enterprise: {
    lead: "Individuelles Volumen, Governance und Infrastruktur",
    text: "Für Organisationen, die individuelle Event- und Site-Volumina, ein eigenes Rollenmodell, vertragliche Supportzeiten und einen Security Review brauchen. Wir planen das Setup gemeinsam mit dir; Preis, Mehrverbrauch und Aufbewahrung werden vertraglich vereinbart.",
    price: "Custom",
    benefitsTitle: "Das bringt Enterprise zusätzlich",
    trustTitle: "Dieselbe Grundlage wie jeder Tarif",
    trust: ["EU-Datenregion als Standard", "Auftragsverarbeiter nach Art. 28 DSGVO, AVV inklusive", "Row-Level-Mandantentrennung in der Datenbank", "Envelope-verschlüsselte Zugangsdaten; Secrets erreichen nie Chat, Logs oder das Modell", "Signierte, versionierte Konfigurationen mit Rollback"],
    cta: "Mit dem Vertrieb sprechen",
    secondary: "Demo buchen",
    overage: "Mehrverbrauch, Aufbewahrung und Volumen werden vertraglich vereinbart.",
  },
  includedSection: {
    title: "In jedem Tarif enthalten",
    text: "Die Grundfunktionen sind nie hinter einer Paywall: Datenschutz-, Consent-, Sicherheits-, Export- und Löschfunktionen funktionieren in jedem Tarif, und der AI-Assistent gehört zu jedem bezahlten Tarif. Upgrades bringen Volumen, Teamgröße, Aufbewahrung und erweiterte Module.",
    note: "Aus dem Tarifkatalog: jeder bezahlte Tarif enthält",
  },
  tools: {
    title: "Tarif finden und Kosten abschätzen",
    text: "Beide Werkzeuge nutzen denselben Tarifkatalog wie Checkout und Abrechnung: dieselben Limits, dieselben Preise, dieselben Eventpakete. Hier wird nichts gekauft.",
  },
  faqTitle: "Häufige Fragen",
  finder: {
    title: "Welcher Tarif passt?",
    text: "Beantworte vier Fragen. Die Empfehlung entsteht deterministisch aus dem Tarifkatalog: der kleinste Tarif, dessen Limits alle deine Antworten abdecken.",
    sites: "Produktive Websites",
    events: "Akzeptierte Events pro Monat",
    team: "Teammitglieder",
    retention: "Benötigte Eventaufbewahrung",
    retentionDays: "{n} Tage",
    retentionMonths: "{n} Monate",
    retentionLonger: "Länger als {n} Monate",
    eventsMore: "Mehr als {n}",
    resultLabel: "Empfehlung",
    result: "{plan} deckt dein Setup ab",
    resultEnterprise: "Dein Setup braucht eine Enterprise-Vereinbarung",
    resultEnterpriseText: "Mindestens eine Antwort liegt über den Pro-Limits. Individuelle Volumina, Aufbewahrung und Teamgröße werden vertraglich vereinbart.",
    checks: { sites: "Websites", events: "Events pro Monat", team: "Teammitglieder", retention: "Aufbewahrung" },
    limitOf: "{wanted} von {limit}",
    noCap: "{wanted}, kein festes Limit",
    cta: "Mit {plan} fortfahren",
    ctaEnterprise: "Mit dem Vertrieb sprechen",
    priceMonthly: "{price} pro Monat",
    priceYearly: "{price} pro Jahr, im Voraus",
  },
  calculator: {
    title: "Kosten abschätzen",
    text: "Bewege den Regler oder gib deine erwarteten akzeptierten Events pro Monat ein. Die Schätzung zeigt Tarifpreis, benötigte Eventpakete und ob ein höherer Tarif günstiger ist, bevor du etwas kaufst.",
    plan: "Tarif",
    events: "Erwartete akzeptierte Events pro Monat",
    slider: "Events pro Monat",
    eventsInput: "Genaue Anzahl Events",
    base: "Tarifpreis",
    included: "Enthaltene Events",
    above: "Events über dem Limit",
    packs: "Benötigte Eventpakete",
    packsValue: "{n} × {events} Events zu je {price}",
    packsNone: "Keine",
    overageCost: "Mehrverbrauch",
    total: "Geschätzte Gesamtkosten",
    perMonth: "pro Monat",
    perYear: "pro Jahr",
    cheaper: "{plan} würde für dieses Volumen {total} kosten, {savings} weniger als {current} mit Eventpaketen.",
    cheaperCta: "Mit {plan} rechnen",
    noCheaper: "Kein höherer Tarif ist für dieses Volumen günstiger.",
    beyondPro: "Volumen über dem Pro-Limit lassen sich auch individuell in einem Enterprise-Vertrag vereinbaren.",
    policyNote: "Eventpakete werden nur berechnet, wenn du Mehrverbrauch ausdrücklich erlaubst. Standardmäßig pausiert die Verarbeitung beim Limit nach der Grace Period, und du wirst bei {thresholds} deines Limits gewarnt.",
    cta: "Mit {plan} fortfahren",
  },
  matrix: {
    title: "Alle Tarife vergleichen",
    text: "Alles, was jeder Tarif enthält, nach Bereichen gruppiert: zuerst Limits und Preise, dann die Module.",
    feature: "Leistung",
    included: "Enthalten",
    notIncluded: "Nicht enthalten",
    custom: "Individuell",
    contractual: "Vertraglich",
    planLabel: "Tarif zum Anzeigen wählen",
    groups: {
      limits: "Limits und Preise",
      tracking: "Tracking und Destinations",
      commerce: "E-Commerce-Events",
      ai: "AI-Assistent",
      quality: "Datenqualität und Monitoring",
      governance: "Governance und Consent",
      data: "Daten, Attribution und Exporte",
      support: "Support und Onboarding",
      enterprise: "Enterprise",
    },
    rows: { sites: "Produktive Websites", events: "Akzeptierte Events pro Monat", team: "Teammitglieder", retention: "Eventaufbewahrung", monthly: "Monatspreis", yearly: "Jahrespreis, im Voraus", overage: "Optionales Eventpaket" },
    unlimited: "Unbegrenzt innerhalb der Fair-Use-Grenzen",
    days: "{n} Tage",
    months: "{n} Monate",
    pack: "{price} je {events} Events",
    perMonth: "pro Monat",
    perYear: "pro Jahr",
    summaryCount: "{included} von {total} enthalten",
  },
  whatCounts: "Was zählt als Event?",
  whatCountsText: "Ein Event wird genau einmal gezählt, wenn es von der Track-Ingestion erfolgreich angenommen wurde. Die Weiterleitung desselben Events an mehrere Destinations erhöht den Verbrauch nicht.",
  events: {
    notCountedTitle: "Nie berechnet",
    diagramTitle: "So wird ein Event gezählt",
    diagramDescription: "Eine Website sendet ein Event an Track. Track nimmt es einmal an und zählt es einmal. Anschließend leitet Track dasselbe Event an Meta, Google Ads und TikTok weiter; die Weiterleitung erhöht den Verbrauch nicht.",
    diagramCaption: "Ein akzeptiertes Event wird einmal berechnet, egal wie viele Destinations es erhalten.",
    nodes: { website: "Website", track: "Track", trackSub: "angenommen · einmal gezählt", destinations: ["Meta", "Google Ads", "TikTok"], fanOut: "Weiterleitung zählt nicht" },
  },
  overageTitle: "Mehrverbrauch und Kostenkontrolle",
  overageText: "Wenn du dich deinem monatlichen Eventlimit näherst, wirst du früh gewarnt, siehst eine Verbrauchsprognose und entscheidest selbst, wie zusätzliche Events behandelt werden. Nichts wird still gekauft oder umgestellt.",
  overageSection: {
    packsTitle: "Eventpakete je Tarif",
    packPlan: "Tarif",
    packSize: "Paketgröße",
    packPrice: "Preis je Paket",
    packEnterprise: "Vertraglich vereinbart",
    policyTitle: "Du entscheidest, wie Mehrverbrauch behandelt wird",
    policyText: "Mehrverbrauch wird niemals ohne deine Entscheidung aktiviert. In den Billing-Einstellungen wählst du eine von drei Regeln:",
    defaultTag: "Standard",
    thresholds: "Bei {thresholds} deines monatlichen Limits wirst du gewarnt und siehst eine Verbrauchsprognose.",
    grace: "Bei der Pausieren-Regel läuft die Verarbeitung bis zu {percent} % über dem Limit weiter, bevor sie pausiert; die Grace Period wird im Dashboard angezeigt.",
    honest: "Das Dashboard sagt dir ehrlich, ob ein Eventpaket oder der nächsthöhere Tarif günstiger ist. Es gibt keinen stillen Tarifwechsel, keinen ungefragten Kauf und kein Löschen von Konfigurationen bei einem Downgrade.",
  },
  trial: {
    title: "{plan} {days} Tage testen",
    text: "Die Testphase läuft im Tarif {plan} mit vollem Funktionsumfang und wird nie von selbst zu einem kostenpflichtigen Abonnement.",
    facts: ["Keine Kreditkarte erforderlich", "Bis zu {events} akzeptierte Testevents", "Keine automatische Umwandlung in einen bezahlten Tarif", "Nach der Testphase bleibt dein Workspace lesbar und exportierbar; nichts wird überraschend gelöscht"],
    cta: "{plan}-Testphase starten",
  },
  faq: [
    { q: "Was zählt als abrechenbares Event?", a: "Ein Event, das die Ingestion angenommen hat, genau einmal gezählt. Ungültige oder abgelehnte Events, erkannte Duplikate, technische Retries, Test- und Debug-Events, interne Systemereignisse und wegen fehlender Einwilligung verworfene Events werden nie berechnet. Die Weiterleitung eines Events an mehrere Destinations erhöht den Verbrauch nicht." },
    { q: "Was passiert beim Erreichen des Limits?", a: "Du wirst bei {thresholds} deines monatlichen Limits gewarnt. Nichts wird still gekauft oder umgestellt: Du entscheidest vorab, ob Eventpakete erlaubt sind, ein monatliches Kostenlimit gilt oder die Verarbeitung beim Limit nach der kommunizierten Grace Period pausiert. Ein Upgrade ist jederzeit möglich." },
    { q: "Wie funktioniert die {trialDays}-tägige Testphase?", a: "Die Testphase läuft {trialDays} Tage im Tarif {trialPlan} ohne Kreditkarte und umfasst bis zu {trialEvents} akzeptierte Events. Sie wird nie von selbst zu einem kostenpflichtigen Abonnement. Danach bleibt dein Workspace lesbar und exportierbar, bis du einen Tarif wählst." },
    { q: "Zahle ich pro Destination?", a: "Nein. Alle Standard-Destinations sind in jedem Tarif enthalten, und ein akzeptiertes Event zählt einmal, unabhängig davon, wie viele Destinations es erhalten." },
    { q: "Zählen Staging- und Preview-Subdomains als Websites?", a: "Nein. Staging- und Preview-Subdomains einer produktiven Website zählen nicht zum Website-Limit." },
    { q: "Welche Steuern fallen an?", a: "Die Preise sind netto in EUR. Die Umsatzsteuer kommt hinzu, sofern sie nach deinem Rechnungsland anfällt. Unternehmen geben ihre USt-IdNr. im Checkout an." },
    { q: "Kann ich den Tarif wechseln oder kündigen?", a: "Upgrades gelten sofort. Monatstarife enden zum Ende der laufenden Periode, Jahrestarife laufen bis zum Ende des vorausbezahlten Jahres. Kündigung und Tarifwechsel erledigst du im Stripe-Billing-Portal. Ein Downgrade löscht nie still Konfigurationen, und deine Daten bleiben für die konfigurierte Aufbewahrungsfrist erhalten und können exportiert werden." },
    { q: "Ist der AI-Assistent begrenzt?", a: "Der AI-Assistent ist in jedem bezahlten Tarif enthalten. Normale Antworten, Rückfragen und Validierungen werden nicht gezählt, und du siehst nie Modell-Tokens." },
    { q: "Wie funktioniert die Enterprise-Abrechnung?", a: "Enterprise-Tarife werden individuell bepreist und per Rechnung oder Bestellung (PO) abgerechnet, mit vertraglichen Volumina, Aufbewahrung, SLA und Supportzeiten. Sprich mit dem Vertrieb, um das Setup zu planen." },
  ],
  cta: "Mit Track starten",
  ctaText: "Lege deine Site ohne Kreditkarte an, konfiguriere die erste Destination und wähle einen Tarif, wenn du bereit bist.",
};
