import type { PricingCopy } from "../types";

/**
 * English (source language) copy of the pricing area. Same shape as every other locale file; see docs/14-localization.md.
 */

export const PRICING_COPY_EN: PricingCopy = {
  eyebrow: "Pricing",
  title: "Clear plans that grow with your event volume",
  text: "Every plan includes browser and server-side tracking, all standard destinations, the AI assistant, the consent engine and the live event debugger. Pick a plan by websites, monthly events, team size and retention. Prices are net in EUR; billing runs through Stripe.",
  hero: { facts: ["Monthly billing by default, cancel at the end of the period", "Net prices in EUR, VAT added where applicable", "{trialDays}-day {trialPlan} trial without a credit card"] },
  interval: {
    legend: "Billing interval",
    monthly: "Monthly",
    yearly: "Yearly",
    monthlyHint: "Billed every month. Cancel at the end of the current period.",
    yearlyHint: "Paid once per year in advance. The yearly price equals ten monthly instalments.",
    announceMonthly: "Showing monthly prices.",
    announceYearly: "Showing yearly prices.",
  },
  recommended: "Recommended",
  contactSales: "Talk to sales",
  start: "Get started",
  plansLabel: "Plans",
  plan: {
    perMonth: "per month",
    perYear: "per year",
    billedMonthly: "Billed monthly. Cancel at the end of the period.",
    billedYearly: "{total} charged once per year",
    equivalent: "≈ {monthly} per month",
    instalments: "equals {n} monthly instalments",
    eventsLabel: "accepted events per month",
    sites: "Websites",
    team: "Team",
    retention: "Retention",
    unlimited: "Unlimited (fair use)",
    days: "{n} days",
    months: "{n} months",
    choose: "Choose {plan}",
    trialHint: "Includes a {days}-day trial, no credit card required",
    overageHint: "Optional overage: {price} per {events} additional events, only with your explicit choice.",
    recommended: "Recommended",
    listLabel: "What {plan} adds",
  },
  tax: {
    title: "Taxes and invoices",
    text: "All prices are net in EUR and exclude VAT. VAT is added where applicable based on your billing country. Businesses can enter their VAT ID during checkout; invoices for every payment are available in the billing portal.",
  },
  enterprise: {
    lead: "Custom volume, governance and infrastructure",
    text: "For organisations that need individual event and site volumes, their own role model, contractual support hours and a security review. We scope the setup together with you; pricing, overage and retention are agreed in the contract.",
    price: "Custom",
    benefitsTitle: "What Enterprise adds",
    trustTitle: "The same foundation as every plan",
    trust: ["EU data region by default", "Processor under Art. 28 GDPR, DPA included", "Row-level tenant isolation in the database", "Envelope-encrypted credentials; secrets never reach chat, logs or the model", "Signed, versioned configurations with rollback"],
    cta: "Talk to sales",
    secondary: "Book a demo",
    overage: "Overage, retention and volumes are agreed in the contract.",
  },
  includedSection: {
    title: "Included in every plan",
    text: "The basics are never paywalled: privacy, consent, security, export and deletion functions work in every plan, and the AI assistant is part of every paid plan. Upgrades add volume, team size, retention and advanced modules.",
    note: "From the tariff catalogue: every paid plan includes",
  },
  tools: {
    title: "Find your plan and estimate your cost",
    text: "Both tools use the same tariff catalogue as checkout and billing: the same limits, the same prices, the same event packs. Nothing is bought here.",
  },
  faqTitle: "Frequently asked questions",
  finder: {
    title: "Which plan fits?",
    text: "Answer four questions. The recommendation is computed deterministically from the tariff catalogue: the smallest plan whose limits cover all your answers.",
    sites: "Production websites",
    events: "Accepted events per month",
    team: "Team members",
    retention: "Event retention you need",
    retentionDays: "{n} days",
    retentionMonths: "{n} months",
    retentionLonger: "Longer than {n} months",
    eventsMore: "More than {n}",
    resultLabel: "Recommendation",
    result: "{plan} covers your setup",
    resultEnterprise: "Your setup needs an Enterprise agreement",
    resultEnterpriseText: "At least one answer is above the Pro limits. Custom volumes, retention and team size are agreed in the contract.",
    checks: { sites: "Websites", events: "Events per month", team: "Team members", retention: "Retention" },
    limitOf: "{wanted} of {limit}",
    noCap: "{wanted}, no fixed cap",
    cta: "Continue with {plan}",
    ctaEnterprise: "Talk to sales",
    priceMonthly: "{price} per month",
    priceYearly: "{price} per year, paid in advance",
  },
  calculator: {
    title: "Estimate your cost",
    text: "Move the slider or type your expected accepted events per month. The estimate shows the plan price, the event packs you would need and whether a higher plan is cheaper, before you buy anything.",
    plan: "Plan",
    events: "Expected accepted events per month",
    slider: "Events per month",
    eventsInput: "Exact number of events",
    base: "Plan price",
    included: "Included events",
    above: "Events above the limit",
    packs: "Event packs needed",
    packsValue: "{n} × {events} events at {price} each",
    packsNone: "None",
    overageCost: "Overage",
    total: "Estimated total",
    perMonth: "per month",
    perYear: "per year",
    cheaper: "{plan} would cost {total} for this volume, {savings} less than {current} with event packs.",
    cheaperCta: "Estimate with {plan}",
    noCheaper: "No higher plan is cheaper for this volume.",
    beyondPro: "Volumes beyond the Pro limit can also be agreed individually in an Enterprise contract.",
    policyNote: "Event packs are only billed if you explicitly allow overage. By default processing pauses at the limit after the grace window, and you are warned at {thresholds} of your limit.",
    cta: "Continue with {plan}",
  },
  matrix: {
    title: "Compare all plans",
    text: "Everything each plan includes, grouped by area: limits and prices first, then the modules.",
    feature: "Feature",
    included: "Included",
    notIncluded: "Not included",
    custom: "Custom",
    contractual: "Contractual",
    planLabel: "Choose a plan to view",
    groups: {
      limits: "Limits and prices",
      tracking: "Tracking and destinations",
      commerce: "E-commerce events",
      ai: "AI assistant",
      quality: "Data quality and monitoring",
      governance: "Governance and consent",
      data: "Data, attribution and exports",
      support: "Support and onboarding",
      enterprise: "Enterprise",
    },
    rows: { sites: "Production websites", events: "Accepted events per month", team: "Team members", retention: "Event retention", monthly: "Monthly price", yearly: "Yearly price, paid in advance", overage: "Optional event pack" },
    unlimited: "Unlimited within fair use",
    days: "{n} days",
    months: "{n} months",
    pack: "{price} per {events} events",
    perMonth: "per month",
    perYear: "per year",
    summaryCount: "{included} of {total} included",
  },
  whatCounts: "What counts as an event?",
  whatCountsText: "An event is counted exactly once when the Track ingestion accepts it. Forwarding the same event to several destinations does not increase usage.",
  events: {
    notCountedTitle: "Never billed",
    diagramTitle: "How an event is counted",
    diagramDescription: "A website sends an event to Track. Track accepts it once and counts it once. Track then forwards the same event to Meta, Google Ads and TikTok; the forwarding does not increase usage.",
    diagramCaption: "One accepted event is billed once, no matter how many destinations receive it.",
    nodes: { website: "Website", track: "Track", trackSub: "accepted · counted once", destinations: ["Meta", "Google Ads", "TikTok"], fanOut: "forwarding does not count" },
  },
  overageTitle: "Overage and cost control",
  overageText: "When you approach your monthly event limit you are warned early, see a usage forecast and decide yourself how additional events are handled. Nothing is bought or switched silently.",
  overageSection: {
    packsTitle: "Event packs per plan",
    packPlan: "Plan",
    packSize: "Pack size",
    packPrice: "Price per pack",
    packEnterprise: "Agreed in the contract",
    policyTitle: "You choose how overage is handled",
    policyText: "Overage is never activated without your decision. In the billing settings you pick one of three policies:",
    defaultTag: "Default",
    thresholds: "You are warned at {thresholds} of your monthly limit and see a usage forecast.",
    grace: "With the pause policy, processing continues up to {percent} % above the limit before it pauses; the grace window is shown in the dashboard.",
    honest: "The dashboard tells you honestly whether an event pack or the next plan is cheaper. There is no silent plan change, no unrequested purchase and no deletion of configurations on a downgrade.",
  },
  trial: {
    title: "Try {plan} for {days} days",
    text: "The trial runs on the {plan} plan with its full feature set and never turns into a paid subscription on its own.",
    facts: ["No credit card required", "Up to {events} accepted trial events", "No automatic conversion into a paid plan", "After the trial your workspace stays readable and exportable; nothing is deleted by surprise"],
    cta: "Start the {plan} trial",
  },
  faq: [
    { q: "What counts as a billable event?", a: "An event that the ingestion accepted, counted once. Invalid or rejected events, detected duplicates, technical retries, test and debug events, internal system events and events dropped for missing consent are never billed. Forwarding one event to several destinations does not increase usage." },
    { q: "What happens when I reach the limit?", a: "You are warned at {thresholds} of your monthly limit. Nothing is bought or switched silently: you choose in advance whether to allow event packs, set a monthly cost limit, or pause processing at the limit after the communicated grace window. Upgrades are possible at any time." },
    { q: "How does the {trialDays}-day trial work?", a: "The trial runs on {trialPlan} for {trialDays} days without a credit card and covers up to {trialEvents} accepted events. It never converts into a paid subscription on its own. Afterwards your workspace stays readable and exportable until you pick a plan." },
    { q: "Do I pay per destination?", a: "No. All standard destinations are included in every plan, and one accepted event counts once regardless of how many destinations receive it." },
    { q: "Do staging and preview subdomains count as websites?", a: "No. Staging and preview subdomains of a production website do not count towards the website limit." },
    { q: "Which taxes apply?", a: "Prices are net in EUR. VAT is added where applicable based on your billing country. Businesses can enter their VAT ID during checkout." },
    { q: "Can I switch plans or cancel?", a: "Upgrades take effect immediately. Monthly plans end at the end of the current period; yearly plans run until the end of the prepaid year. You cancel and change plans in the Stripe billing portal. A downgrade never silently deletes configurations, and your data stays available for the configured retention window and can be exported." },
    { q: "Is the AI assistant limited?", a: "The AI assistant is included in every paid plan. Normal answers, follow-up questions and validations are not metered, and you never see model tokens." },
    { q: "How does Enterprise billing work?", a: "Enterprise plans are priced individually and billed by invoice or purchase order with contractual volumes, retention, SLA and support hours. Contact sales to scope the setup." },
  ],
  cta: "Start with Track",
  ctaText: "Create your site without a credit card, configure the first destination and pick a plan when you are ready.",
};
