import type { PricingCopy } from "../types";

/**
 * Spanish (es, Spain) copy of the pricing area. Same shape as en.ts; see docs/14-localization.md.
 * Register: tú. Prices, limits and packs never live here — they come from the tariff catalogue.
 * "Overage" is "consumo adicional", "retention" is "retención", "trial" is "prueba".
 */

export const PRICING_COPY_ES: PricingCopy = {
  eyebrow: "Precios",
  title: "Planes claros que crecen con tu volumen de eventos",
  text: "Todos los planes incluyen tracking en el navegador y server-side, todos los destinos estándar, el asistente de IA, el motor de consentimiento y el depurador de eventos en directo. Elige el plan según sitios web, eventos mensuales, tamaño del equipo y retención. Los precios son netos en EUR; la facturación se gestiona a través de Stripe.",
  hero: { facts: ["Facturación mensual por defecto, cancelación al final del periodo", "Precios netos en EUR; se añade el IVA cuando corresponde", "Prueba de {trialPlan} de {trialDays} días sin tarjeta de crédito"] },
  interval: {
    legend: "Intervalo de facturación",
    monthly: "Mensual",
    yearly: "Anual",
    monthlyHint: "Se factura cada mes. Cancela al final del periodo en curso.",
    yearlyHint: "Se paga una vez al año por adelantado. El precio anual equivale a diez cuotas mensuales.",
    announceMonthly: "Mostrando precios mensuales.",
    announceYearly: "Mostrando precios anuales.",
  },
  recommended: "Recomendado",
  contactSales: "Hablar con ventas",
  start: "Empezar",
  plansLabel: "Planes",
  plan: {
    perMonth: "al mes",
    perYear: "al año",
    billedMonthly: "Facturación mensual. Cancela al final del periodo.",
    billedYearly: "{total} cobrados una vez al año",
    equivalent: "≈ {monthly} al mes",
    instalments: "equivale a {n} cuotas mensuales",
    eventsLabel: "eventos aceptados al mes",
    sites: "Sitios web",
    team: "Equipo",
    retention: "Retención",
    unlimited: "Ilimitado (uso razonable)",
    days: "{n} días",
    months: "{n} meses",
    choose: "Elegir {plan}",
    trialHint: "Incluye una prueba de {days} días, sin tarjeta de crédito",
    overageHint: "Consumo adicional opcional: {price} por cada {events} eventos adicionales, solo si lo decides expresamente.",
    recommended: "Recomendado",
    listLabel: "Qué añade {plan}",
  },
  tax: {
    title: "Impuestos y facturas",
    text: "Todos los precios son netos en EUR y no incluyen IVA. El IVA se añade cuando corresponde según tu país de facturación. Las empresas pueden introducir su NIF-IVA durante el checkout; las facturas de cada pago están disponibles en el portal de facturación.",
  },
  enterprise: {
    lead: "Volumen, gobernanza e infraestructura a medida",
    text: "Para organizaciones que necesitan volúmenes propios de eventos y sitios, su propio modelo de roles, horas de soporte contractuales y una revisión de seguridad. Definimos la configuración contigo; el precio, el consumo adicional y la retención se acuerdan en el contrato.",
    price: "A medida",
    benefitsTitle: "Qué añade Enterprise",
    trustTitle: "La misma base que todos los planes",
    trust: ["Región de datos de la UE por defecto", "Encargado del tratamiento conforme al art. 28 del RGPD, DPA incluido", "Aislamiento por tenant a nivel de fila en la base de datos", "Credenciales con cifrado de sobre; los secretos nunca llegan al chat, a los logs ni al modelo", "Configuraciones firmadas y versionadas con reversión"],
    cta: "Hablar con ventas",
    secondary: "Reservar una demo",
    overage: "El consumo adicional, la retención y los volúmenes se acuerdan en el contrato.",
  },
  includedSection: {
    title: "Incluido en todos los planes",
    text: "Lo básico nunca está detrás de un muro de pago: las funciones de privacidad, consentimiento, seguridad, exportación y borrado funcionan en todos los planes, y el asistente de IA forma parte de todos los planes de pago. Subir de plan añade volumen, tamaño de equipo, retención y módulos avanzados.",
    note: "Del catálogo de tarifas: todos los planes de pago incluyen",
  },
  tools: {
    title: "Encuentra tu plan y estima tu coste",
    text: "Ambas herramientas usan el mismo catálogo de tarifas que el checkout y la facturación: los mismos límites, los mismos precios, los mismos paquetes de eventos. Aquí no se compra nada.",
  },
  faqTitle: "Preguntas frecuentes",
  finder: {
    title: "¿Qué plan encaja?",
    text: "Responde a cuatro preguntas. La recomendación se calcula de forma determinista a partir del catálogo de tarifas: el plan más pequeño cuyos límites cubren todas tus respuestas.",
    sites: "Sitios web en producción",
    events: "Eventos aceptados al mes",
    team: "Miembros del equipo",
    retention: "Retención de eventos que necesitas",
    retentionDays: "{n} días",
    retentionMonths: "{n} meses",
    retentionLonger: "Más de {n} meses",
    eventsMore: "Más de {n}",
    resultLabel: "Recomendación",
    result: "{plan} cubre tu configuración",
    resultEnterprise: "Tu configuración necesita un acuerdo Enterprise",
    resultEnterpriseText: "Al menos una respuesta supera los límites de Pro. Los volúmenes, la retención y el tamaño del equipo a medida se acuerdan en el contrato.",
    checks: { sites: "Sitios web", events: "Eventos al mes", team: "Miembros del equipo", retention: "Retención" },
    limitOf: "{wanted} de {limit}",
    noCap: "{wanted}, sin tope fijo",
    cta: "Continuar con {plan}",
    ctaEnterprise: "Hablar con ventas",
    priceMonthly: "{price} al mes",
    priceYearly: "{price} al año, pagados por adelantado",
  },
  calculator: {
    title: "Estima tu coste",
    text: "Mueve el control deslizante o escribe los eventos aceptados al mes que esperas. La estimación muestra el precio del plan, los paquetes de eventos que necesitarías y si un plan superior sale más barato, antes de comprar nada.",
    plan: "Plan",
    events: "Eventos aceptados al mes previstos",
    slider: "Eventos al mes",
    eventsInput: "Número exacto de eventos",
    base: "Precio del plan",
    included: "Eventos incluidos",
    above: "Eventos por encima del límite",
    packs: "Paquetes de eventos necesarios",
    packsValue: "{n} × {events} eventos a {price} cada uno",
    packsNone: "Ninguno",
    overageCost: "Consumo adicional",
    total: "Total estimado",
    perMonth: "al mes",
    perYear: "al año",
    cheaper: "{plan} costaría {total} para este volumen, {savings} menos que {current} con paquetes de eventos.",
    cheaperCta: "Estimar con {plan}",
    noCheaper: "Ningún plan superior sale más barato para este volumen.",
    beyondPro: "Los volúmenes por encima del límite de Pro también pueden acordarse individualmente en un contrato Enterprise.",
    policyNote: "Los paquetes de eventos solo se facturan si permites expresamente el consumo adicional. Por defecto, el procesamiento se pausa en el límite tras el periodo de gracia, y se te avisa cuando alcanzas el {thresholds} de tu límite.",
    cta: "Continuar con {plan}",
  },
  matrix: {
    title: "Compara todos los planes",
    text: "Todo lo que incluye cada plan, agrupado por área: primero límites y precios, después los módulos.",
    feature: "Función",
    included: "Incluido",
    notIncluded: "No incluido",
    custom: "A medida",
    contractual: "Contractual",
    planLabel: "Elige un plan para verlo",
    groups: {
      limits: "Límites y precios",
      tracking: "Tracking y destinos",
      commerce: "Eventos de e-commerce",
      ai: "Asistente de IA",
      quality: "Calidad de datos y monitorización",
      governance: "Gobernanza y consentimiento",
      data: "Datos, atribución y exportaciones",
      support: "Soporte y onboarding",
      enterprise: "Enterprise",
    },
    rows: { sites: "Sitios web en producción", events: "Eventos aceptados al mes", team: "Miembros del equipo", retention: "Retención de eventos", monthly: "Precio mensual", yearly: "Precio anual, pagado por adelantado", overage: "Paquete de eventos opcional" },
    unlimited: "Ilimitado dentro de un uso razonable",
    days: "{n} días",
    months: "{n} meses",
    pack: "{price} por {events} eventos",
    perMonth: "al mes",
    perYear: "al año",
    summaryCount: "{included} de {total} incluidos",
  },
  whatCounts: "¿Qué cuenta como evento?",
  whatCountsText: "Un evento se cuenta exactamente una vez cuando la ingesta de Track lo acepta. Reenviar el mismo evento a varios destinos no aumenta el consumo.",
  events: {
    notCountedTitle: "Nunca se factura",
    diagramTitle: "Cómo se cuenta un evento",
    diagramDescription: "Un sitio web envía un evento a Track. Track lo acepta una vez y lo cuenta una vez. Después, Track reenvía el mismo evento a Meta, Google Ads y TikTok; el reenvío no aumenta el consumo.",
    diagramCaption: "Un evento aceptado se factura una vez, sin importar cuántos destinos lo reciban.",
    nodes: { website: "Sitio web", track: "Track", trackSub: "aceptado · contado una vez", destinations: ["Meta", "Google Ads", "TikTok"], fanOut: "el reenvío no cuenta" },
  },
  overageTitle: "Consumo adicional y control de costes",
  overageText: "Cuando te acercas a tu límite mensual de eventos, se te avisa con antelación, ves una previsión de consumo y decides tú cómo se gestionan los eventos adicionales. Nada se compra ni se cambia en silencio.",
  overageSection: {
    packsTitle: "Paquetes de eventos por plan",
    packPlan: "Plan",
    packSize: "Tamaño del paquete",
    packPrice: "Precio por paquete",
    packEnterprise: "Se acuerda en el contrato",
    policyTitle: "Tú eliges cómo se gestiona el consumo adicional",
    policyText: "El consumo adicional nunca se activa sin tu decisión. En los ajustes de facturación eliges una de tres políticas:",
    defaultTag: "Por defecto",
    thresholds: "Se te avisa cuando alcanzas el {thresholds} de tu límite mensual y ves una previsión de consumo.",
    grace: "Con la política de pausa, el procesamiento continúa hasta un {percent} % por encima del límite antes de pausarse; el periodo de gracia se muestra en el panel.",
    honest: "El panel te dice con sinceridad si sale más barato un paquete de eventos o el siguiente plan. No hay cambios de plan silenciosos, ni compras no solicitadas, ni borrado de configuraciones al bajar de plan.",
  },
  trial: {
    title: "Prueba {plan} durante {days} días",
    text: "La prueba se ejecuta en el plan {plan} con todas sus funciones y nunca se convierte por sí sola en una suscripción de pago.",
    facts: ["Sin tarjeta de crédito", "Hasta {events} eventos de prueba aceptados", "Sin conversión automática a un plan de pago", "Al terminar la prueba, tu espacio de trabajo sigue siendo legible y exportable; nada se borra por sorpresa"],
    cta: "Empezar la prueba de {plan}",
  },
  faq: [
    { q: "¿Qué cuenta como evento facturable?", a: "Un evento que la ingesta ha aceptado, contado una sola vez. Los eventos inválidos o rechazados, los duplicados detectados, los reintentos técnicos, los eventos de prueba y depuración, los eventos internos del sistema y los eventos descartados por falta de consentimiento nunca se facturan. Reenviar un evento a varios destinos no aumenta el consumo." },
    { q: "¿Qué pasa cuando llego al límite?", a: "Se te avisa cuando alcanzas el {thresholds} de tu límite mensual. Nada se compra ni se cambia en silencio: decides de antemano si permites paquetes de eventos, fijas un límite de coste mensual o pausas el procesamiento en el límite tras el periodo de gracia comunicado. Puedes subir de plan en cualquier momento." },
    { q: "¿Cómo funciona la prueba de {trialDays} días?", a: "La prueba se ejecuta en {trialPlan} durante {trialDays} días sin tarjeta de crédito y cubre hasta {trialEvents} eventos aceptados. Nunca se convierte por sí sola en una suscripción de pago. Después, tu espacio de trabajo sigue siendo legible y exportable hasta que elijas un plan." },
    { q: "¿Pago por destino?", a: "No. Todos los destinos estándar están incluidos en todos los planes, y un evento aceptado cuenta una vez, independientemente de cuántos destinos lo reciban." },
    { q: "¿Los subdominios de staging y preview cuentan como sitios web?", a: "No. Los subdominios de staging y preview de un sitio web en producción no cuentan para el límite de sitios web." },
    { q: "¿Qué impuestos se aplican?", a: "Los precios son netos en EUR. El IVA se añade cuando corresponde según tu país de facturación. Las empresas pueden introducir su NIF-IVA durante el checkout." },
    { q: "¿Puedo cambiar de plan o cancelar?", a: "Las subidas de plan se aplican de inmediato. Los planes mensuales terminan al final del periodo en curso; los planes anuales continúan hasta el final del año prepagado. Cancelas y cambias de plan en el portal de facturación de Stripe. Bajar de plan nunca borra configuraciones en silencio, y tus datos siguen disponibles durante el periodo de retención configurado y se pueden exportar." },
    { q: "¿El asistente de IA tiene límites?", a: "El asistente de IA está incluido en todos los planes de pago. Las respuestas normales, las preguntas de seguimiento y las validaciones no se miden, y nunca ves tokens del modelo." },
    { q: "¿Cómo funciona la facturación de Enterprise?", a: "Los planes Enterprise tienen un precio individual y se facturan mediante factura u orden de compra, con volúmenes, retención, SLA y horas de soporte contractuales. Contacta con ventas para definir la configuración." },
  ],
  cta: "Empieza con Track",
  ctaText: "Crea tu sitio sin tarjeta de crédito, configura el primer destino y elige un plan cuando estés listo.",
};
