import type { PricingCopy } from "../types";

/**
 * French (fr) copy of the pricing area. Same shape as en.ts; see docs/14-localization.md.
 * Register: vous. Prices, limits, packs and the trial come from the tariff catalogue (placeholders).
 */

export const PRICING_COPY_FR: PricingCopy = {
  eyebrow: "Tarifs",
  title: "Des formules claires qui évoluent avec votre volume d’événements",
  text: "Chaque formule inclut le tracking navigateur et côté serveur, toutes les destinations standard, l’assistant IA, le Consent Engine et le Live Event Debugger. Choisissez votre formule selon le nombre de sites web, d’événements mensuels, la taille de l’équipe et la durée de conservation. Les prix s’entendent hors taxes, en EUR ; la facturation passe par Stripe.",
  hero: { facts: ["Facturation mensuelle par défaut, résiliation à la fin de la période", "Prix hors taxes en EUR, TVA en sus le cas échéant", "Essai {trialPlan} de {trialDays} jours, sans carte bancaire"] },
  interval: {
    legend: "Période de facturation",
    monthly: "Mensuel",
    yearly: "Annuel",
    monthlyHint: "Facturé chaque mois. Résiliation à la fin de la période en cours.",
    yearlyHint: "Payé une fois par an, d’avance. Le prix annuel équivaut à dix mensualités.",
    announceMonthly: "Affichage des prix mensuels.",
    announceYearly: "Affichage des prix annuels.",
  },
  recommended: "Recommandée",
  contactSales: "Contacter l’équipe commerciale",
  start: "Commencer",
  plansLabel: "Formules",
  plan: {
    perMonth: "par mois",
    perYear: "par an",
    billedMonthly: "Facturation mensuelle. Résiliation à la fin de la période.",
    billedYearly: "{total} prélevés une fois par an",
    equivalent: "≈ {monthly} par mois",
    instalments: "soit {n} mensualités",
    eventsLabel: "événements acceptés par mois",
    sites: "Sites web",
    team: "Équipe",
    retention: "Conservation",
    unlimited: "Illimité (usage raisonnable)",
    days: "{n} jours",
    months: "{n} mois",
    choose: "Choisir {plan}",
    trialHint: "Essai de {days} jours inclus, sans carte bancaire",
    overageHint: "Dépassement optionnel : {price} par {events} événements supplémentaires, uniquement sur votre décision explicite.",
    recommended: "Recommandée",
    listLabel: "Ce que {plan} ajoute",
  },
  tax: {
    title: "Taxes et factures",
    text: "Tous les prix s’entendent hors taxes, en EUR. La TVA est ajoutée le cas échéant selon votre pays de facturation. Les entreprises peuvent saisir leur numéro de TVA intracommunautaire lors du paiement ; les factures de chaque paiement sont disponibles dans le portail de facturation.",
  },
  enterprise: {
    lead: "Volumes, gouvernance et infrastructure sur mesure",
    text: "Pour les organisations qui ont besoin de volumes d’événements et de sites individuels, de leur propre modèle de rôles, d’heures de support contractuelles et d’une revue de sécurité. Nous cadrons la configuration avec vous ; le prix, le dépassement et la conservation sont fixés dans le contrat.",
    price: "Sur devis",
    benefitsTitle: "Ce qu’Enterprise ajoute",
    trustTitle: "Le même socle que chaque formule",
    trust: ["Région de données UE par défaut", "Sous-traitant au sens de l’art. 28 du RGPD, accord de traitement des données inclus", "Isolation des tenants au niveau des lignes dans la base de données", "Identifiants d’accès chiffrés par enveloppe ; les secrets n’atteignent jamais le chat, les journaux ni le modèle", "Configurations signées et versionnées, avec rollback"],
    cta: "Contacter l’équipe commerciale",
    secondary: "Réserver une démo",
    overage: "Le dépassement, la conservation et les volumes sont fixés dans le contrat.",
  },
  includedSection: {
    title: "Inclus dans chaque formule",
    text: "Les fondamentaux ne sont jamais réservés aux formules supérieures : les fonctions de confidentialité, de consentement, de sécurité, d’export et de suppression fonctionnent dans chaque formule, et l’assistant IA fait partie de chaque formule payante. Les formules supérieures ajoutent du volume, des membres d’équipe, de la conservation et des modules avancés.",
    note: "Selon le catalogue tarifaire : chaque formule payante inclut",
  },
  tools: {
    title: "Trouvez votre formule et estimez votre coût",
    text: "Les deux outils utilisent le même catalogue tarifaire que le paiement et la facturation : mêmes limites, mêmes prix, mêmes packs d’événements. Rien n’est acheté ici.",
  },
  faqTitle: "Questions fréquentes",
  finder: {
    title: "Quelle formule vous convient ?",
    text: "Répondez à quatre questions. La recommandation est calculée de manière déterministe à partir du catalogue tarifaire : la plus petite formule dont les limites couvrent toutes vos réponses.",
    sites: "Sites web de production",
    events: "Événements acceptés par mois",
    team: "Membres de l’équipe",
    retention: "Durée de conservation des événements dont vous avez besoin",
    retentionDays: "{n} jours",
    retentionMonths: "{n} mois",
    retentionLonger: "Plus de {n} mois",
    eventsMore: "Plus de {n}",
    resultLabel: "Recommandation",
    result: "{plan} couvre votre configuration",
    resultEnterprise: "Votre configuration nécessite un contrat Enterprise",
    resultEnterpriseText: "Au moins une réponse dépasse les limites de Pro. Les volumes, la conservation et la taille de l’équipe sur mesure sont fixés dans le contrat.",
    checks: { sites: "Sites web", events: "Événements par mois", team: "Membres de l’équipe", retention: "Conservation" },
    limitOf: "{wanted} sur {limit}",
    noCap: "{wanted}, sans plafond fixe",
    cta: "Continuer avec {plan}",
    ctaEnterprise: "Contacter l’équipe commerciale",
    priceMonthly: "{price} par mois",
    priceYearly: "{price} par an, payés d’avance",
  },
  calculator: {
    title: "Estimez votre coût",
    text: "Déplacez le curseur ou saisissez le nombre d’événements acceptés que vous attendez par mois. L’estimation indique le prix de la formule, les packs d’événements dont vous auriez besoin et si une formule supérieure revient moins cher, avant tout achat.",
    plan: "Formule",
    events: "Événements acceptés attendus par mois",
    slider: "Événements par mois",
    eventsInput: "Nombre exact d’événements",
    base: "Prix de la formule",
    included: "Événements inclus",
    above: "Événements au-delà de la limite",
    packs: "Packs d’événements nécessaires",
    packsValue: "{n} × {events} événements à {price} chacun",
    packsNone: "Aucun",
    overageCost: "Dépassement",
    total: "Total estimé",
    perMonth: "par mois",
    perYear: "par an",
    cheaper: "{plan} coûterait {total} pour ce volume, soit {savings} de moins que {current} avec des packs d’événements.",
    cheaperCta: "Estimer avec {plan}",
    noCheaper: "Aucune formule supérieure n’est moins chère pour ce volume.",
    beyondPro: "Les volumes au-delà de la limite de Pro peuvent aussi être négociés individuellement dans un contrat Enterprise.",
    policyNote: "Les packs d’événements ne sont facturés que si vous autorisez explicitement le dépassement. Par défaut, le traitement est suspendu à la limite après la période de grâce, et vous êtes averti à {thresholds} de votre limite.",
    cta: "Continuer avec {plan}",
  },
  matrix: {
    title: "Comparer toutes les formules",
    text: "Tout ce que chaque formule inclut, regroupé par domaine : limites et prix d’abord, puis les modules.",
    feature: "Fonctionnalité",
    included: "Inclus",
    notIncluded: "Non inclus",
    custom: "Sur mesure",
    contractual: "Contractuel",
    planLabel: "Choisissez une formule à afficher",
    groups: {
      limits: "Limites et prix",
      tracking: "Tracking et destinations",
      commerce: "Événements e-commerce",
      ai: "Assistant IA",
      quality: "Qualité des données et supervision",
      governance: "Gouvernance et consentement",
      data: "Données, attribution et exports",
      support: "Support et onboarding",
      enterprise: "Enterprise",
    },
    rows: { sites: "Sites web de production", events: "Événements acceptés par mois", team: "Membres de l’équipe", retention: "Conservation des événements", monthly: "Prix mensuel", yearly: "Prix annuel, payé d’avance", overage: "Pack d’événements optionnel" },
    unlimited: "Illimité dans le cadre d’un usage raisonnable",
    days: "{n} jours",
    months: "{n} mois",
    pack: "{price} par {events} événements",
    perMonth: "par mois",
    perYear: "par an",
    summaryCount: "{included} sur {total} inclus",
  },
  whatCounts: "Qu’est-ce qui compte comme un événement ?",
  whatCountsText: "Un événement est compté exactement une fois lorsque l’ingestion Track l’accepte. Transmettre le même événement à plusieurs destinations n’augmente pas la consommation.",
  events: {
    notCountedTitle: "Jamais facturé",
    diagramTitle: "Comment un événement est compté",
    diagramDescription: "Un site web envoie un événement à Track. Track l’accepte une fois et le compte une fois. Track transmet ensuite le même événement à Meta, Google Ads et TikTok ; la transmission n’augmente pas la consommation.",
    diagramCaption: "Un événement accepté est facturé une seule fois, quel que soit le nombre de destinations qui le reçoivent.",
    nodes: { website: "Site web", track: "Track", trackSub: "accepté · compté une fois", destinations: ["Meta", "Google Ads", "TikTok"], fanOut: "la transmission ne compte pas" },
  },
  overageTitle: "Dépassement et maîtrise des coûts",
  overageText: "Lorsque vous approchez de votre limite mensuelle d’événements, vous êtes averti tôt, vous voyez une prévision de consommation et vous décidez vous-même du traitement des événements supplémentaires. Rien n’est acheté ni modifié en silence.",
  overageSection: {
    packsTitle: "Packs d’événements par formule",
    packPlan: "Formule",
    packSize: "Taille du pack",
    packPrice: "Prix par pack",
    packEnterprise: "Fixé dans le contrat",
    policyTitle: "Vous choisissez comment gérer le dépassement",
    policyText: "Le dépassement n’est jamais activé sans votre décision. Dans les paramètres de facturation, vous choisissez l’une des trois règles :",
    defaultTag: "Par défaut",
    thresholds: "Vous êtes averti à {thresholds} de votre limite mensuelle et vous voyez une prévision de consommation.",
    grace: "Avec la règle de suspension, le traitement continue jusqu’à {percent} % au-delà de la limite avant d’être suspendu ; la période de grâce est affichée dans le tableau de bord.",
    honest: "Le tableau de bord vous indique honnêtement si un pack d’événements ou la formule supérieure revient moins cher. Pas de changement de formule silencieux, pas d’achat non demandé, et aucune suppression de configuration lors d’un passage à une formule inférieure.",
  },
  trial: {
    title: "Essayez {plan} pendant {days} jours",
    text: "L’essai s’exécute sur la formule {plan} avec l’ensemble de ses fonctionnalités et ne se transforme jamais de lui-même en abonnement payant.",
    facts: ["Sans carte bancaire", "Jusqu’à {events} événements d’essai acceptés", "Aucune conversion automatique en formule payante", "Après l’essai, votre espace de travail reste consultable et exportable ; rien n’est supprimé par surprise"],
    cta: "Démarrer l’essai {plan}",
  },
  faq: [
    { q: "Qu’est-ce qu’un événement facturable ?", a: "Un événement que l’ingestion a accepté, compté une seule fois. Les événements invalides ou rejetés, les doublons détectés, les nouvelles tentatives techniques, les événements de test et de débogage, les événements système internes et les événements écartés faute de consentement ne sont jamais facturés. Transmettre un événement à plusieurs destinations n’augmente pas la consommation." },
    { q: "Que se passe-t-il quand j’atteins la limite ?", a: "Vous êtes averti à {thresholds} de votre limite mensuelle. Rien n’est acheté ni modifié en silence : vous choisissez à l’avance d’autoriser les packs d’événements, de fixer un plafond de coût mensuel ou de suspendre le traitement à la limite après la période de grâce communiquée. Vous pouvez passer à une formule supérieure à tout moment." },
    { q: "Comment fonctionne l’essai de {trialDays} jours ?", a: "L’essai s’exécute sur {trialPlan} pendant {trialDays} jours, sans carte bancaire, et couvre jusqu’à {trialEvents} événements acceptés. Il ne se transforme jamais de lui-même en abonnement payant. Ensuite, votre espace de travail reste consultable et exportable jusqu’à ce que vous choisissiez une formule." },
    { q: "Dois-je payer par destination ?", a: "Non. Toutes les destinations standard sont incluses dans chaque formule, et un événement accepté compte une seule fois, quel que soit le nombre de destinations qui le reçoivent." },
    { q: "Les sous-domaines de staging et de preview comptent-ils comme des sites web ?", a: "Non. Les sous-domaines de staging et de preview d’un site web de production ne sont pas comptabilisés dans la limite de sites web." },
    { q: "Quelles taxes s’appliquent ?", a: "Les prix s’entendent hors taxes, en EUR. La TVA est ajoutée le cas échéant selon votre pays de facturation. Les entreprises peuvent saisir leur numéro de TVA intracommunautaire lors du paiement." },
    { q: "Puis-je changer de formule ou résilier ?", a: "Les passages à une formule supérieure prennent effet immédiatement. Les formules mensuelles se terminent à la fin de la période en cours ; les formules annuelles courent jusqu’à la fin de l’année prépayée. Vous résiliez et changez de formule dans le portail de facturation Stripe. Un passage à une formule inférieure ne supprime jamais de configuration en silence, et vos données restent disponibles pendant la durée de conservation configurée et peuvent être exportées." },
    { q: "L’assistant IA est-il limité ?", a: "L’assistant IA est inclus dans chaque formule payante. Les réponses habituelles, les questions de suivi et les validations ne sont pas décomptées, et vous ne voyez jamais de jetons de modèle." },
    { q: "Comment fonctionne la facturation Enterprise ?", a: "Les formules Enterprise sont tarifées individuellement et facturées sur facture ou bon de commande, avec des volumes, une conservation, un SLA et des heures de support contractuels. Contactez l’équipe commerciale pour cadrer la configuration." },
  ],
  cta: "Commencer avec Track",
  ctaText: "Créez votre site sans carte bancaire, configurez la première destination et choisissez une formule quand vous êtes prêt.",
};
