import type { PricingCopy } from "../types";

/**
 * Italian (it) copy of the pricing area. Same shape as en.ts; see docs/14-localization.md.
 * Register: tu. "Overage" is "consumo aggiuntivo", "retention" is "conservazione", "trial" is "prova";
 * plan names and product module names (Consent Engine, Live Event Debugger) stay English.
 */

export const PRICING_COPY_IT: PricingCopy = {
  eyebrow: "Prezzi",
  title: "Piani chiari che crescono con il tuo volume di eventi",
  text: "Ogni piano include tracking browser e server-side, tutte le destinazioni standard, l’assistente AI, il Consent Engine e il Live Event Debugger. Scegli il piano in base a siti web, eventi mensili, dimensione del team e conservazione. I prezzi sono netti in EUR; la fatturazione avviene tramite Stripe.",
  hero: { facts: ["Fatturazione mensile per impostazione predefinita, disdetta a fine periodo", "Prezzi netti in EUR, IVA aggiunta dove applicabile", "{trialDays} giorni di prova di {trialPlan} senza carta di credito"] },
  interval: {
    legend: "Intervallo di fatturazione",
    monthly: "Mensile",
    yearly: "Annuale",
    monthlyHint: "Fatturato ogni mese. Disdetta alla fine del periodo in corso.",
    yearlyHint: "Pagato una volta all’anno in anticipo. Il prezzo annuale equivale a dieci rate mensili.",
    announceMonthly: "Vengono mostrati i prezzi mensili.",
    announceYearly: "Vengono mostrati i prezzi annuali.",
  },
  recommended: "Consigliato",
  contactSales: "Parla con il team vendite",
  start: "Inizia ora",
  plansLabel: "Piani",
  plan: {
    perMonth: "al mese",
    perYear: "all’anno",
    billedMonthly: "Fatturazione mensile. Disdetta a fine periodo.",
    billedYearly: "{total} addebitati una volta all’anno",
    equivalent: "≈ {monthly} al mese",
    instalments: "equivale a {n} rate mensili",
    eventsLabel: "eventi accettati al mese",
    sites: "Siti web",
    team: "Team",
    retention: "Conservazione",
    unlimited: "Illimitato (fair use)",
    days: "{n} giorni",
    months: "{n} mesi",
    choose: "Scegli {plan}",
    trialHint: "Include {days} giorni di prova, senza carta di credito",
    overageHint: "Consumo aggiuntivo opzionale: {price} per {events} eventi in più, solo con la tua scelta esplicita.",
    recommended: "Consigliato",
    listLabel: "Cosa aggiunge {plan}",
  },
  tax: {
    title: "Imposte e fatture",
    text: "Tutti i prezzi sono netti in EUR, IVA esclusa. L’IVA viene aggiunta dove applicabile in base al tuo paese di fatturazione. Le aziende possono inserire la partita IVA durante il checkout; le fatture di ogni pagamento sono disponibili nel portale di fatturazione.",
  },
  enterprise: {
    lead: "Volumi, governance e infrastruttura su misura",
    text: "Per le organizzazioni che hanno bisogno di volumi di eventi e siti personalizzati, un proprio modello di ruoli, ore di supporto contrattuali e una security review. Definiamo la configurazione insieme a te; prezzo, consumo aggiuntivo e conservazione vengono concordati nel contratto.",
    price: "Su misura",
    benefitsTitle: "Cosa aggiunge Enterprise",
    trustTitle: "La stessa base di ogni piano",
    trust: ["Regione dati UE per impostazione predefinita", "Responsabile del trattamento ai sensi dell’art. 28 GDPR, accordo sul trattamento dei dati incluso", "Isolamento dei tenant a livello di riga nel database", "Credenziali cifrate con envelope encryption; i secret non raggiungono mai chat, log o il modello", "Configurazioni firmate e versionate con rollback"],
    cta: "Parla con il team vendite",
    secondary: "Prenota una demo",
    overage: "Consumo aggiuntivo, conservazione e volumi vengono concordati nel contratto.",
  },
  includedSection: {
    title: "Incluso in ogni piano",
    text: "Le basi non sono mai a pagamento: le funzioni di privacy, consenso, sicurezza, esportazione e cancellazione funzionano in ogni piano e l’assistente AI fa parte di ogni piano a pagamento. Gli upgrade aggiungono volume, dimensione del team, conservazione e moduli avanzati.",
    note: "Dal catalogo tariffario: ogni piano a pagamento include",
  },
  tools: {
    title: "Trova il tuo piano e stima il costo",
    text: "Entrambi gli strumenti usano lo stesso catalogo tariffario di checkout e fatturazione: gli stessi limiti, gli stessi prezzi, gli stessi pacchetti di eventi. Qui non si acquista nulla.",
  },
  faqTitle: "Domande frequenti",
  finder: {
    title: "Quale piano fa per te?",
    text: "Rispondi a quattro domande. La raccomandazione viene calcolata in modo deterministico dal catalogo tariffario: il piano più piccolo i cui limiti coprono tutte le tue risposte.",
    sites: "Siti web in produzione",
    events: "Eventi accettati al mese",
    team: "Membri del team",
    retention: "Conservazione degli eventi di cui hai bisogno",
    retentionDays: "{n} giorni",
    retentionMonths: "{n} mesi",
    retentionLonger: "Più di {n} mesi",
    eventsMore: "Più di {n}",
    resultLabel: "Raccomandazione",
    result: "{plan} copre la tua configurazione",
    resultEnterprise: "La tua configurazione richiede un accordo Enterprise",
    resultEnterpriseText: "Almeno una risposta supera i limiti di Pro. Volumi, conservazione e dimensione del team personalizzati vengono concordati nel contratto.",
    checks: { sites: "Siti web", events: "Eventi al mese", team: "Membri del team", retention: "Conservazione" },
    limitOf: "{wanted} di {limit}",
    noCap: "{wanted}, nessun limite fisso",
    cta: "Continua con {plan}",
    ctaEnterprise: "Parla con il team vendite",
    priceMonthly: "{price} al mese",
    priceYearly: "{price} all’anno, pagati in anticipo",
  },
  calculator: {
    title: "Stima il tuo costo",
    text: "Sposta il cursore o inserisci gli eventi accettati al mese che prevedi. La stima mostra il prezzo del piano, i pacchetti di eventi di cui avresti bisogno e se un piano superiore è più conveniente, prima di acquistare qualsiasi cosa.",
    plan: "Piano",
    events: "Eventi accettati al mese previsti",
    slider: "Eventi al mese",
    eventsInput: "Numero esatto di eventi",
    base: "Prezzo del piano",
    included: "Eventi inclusi",
    above: "Eventi oltre il limite",
    packs: "Pacchetti di eventi necessari",
    packsValue: "{n} × {events} eventi a {price} ciascuno",
    packsNone: "Nessuno",
    overageCost: "Consumo aggiuntivo",
    total: "Totale stimato",
    perMonth: "al mese",
    perYear: "all’anno",
    cheaper: "{plan} costerebbe {total} per questo volume, {savings} in meno rispetto a {current} con i pacchetti di eventi.",
    cheaperCta: "Stima con {plan}",
    noCheaper: "Nessun piano superiore è più conveniente per questo volume.",
    beyondPro: "I volumi oltre il limite di Pro possono anche essere concordati individualmente in un contratto Enterprise.",
    policyNote: "I pacchetti di eventi vengono fatturati solo se autorizzi esplicitamente il consumo aggiuntivo. Per impostazione predefinita l’elaborazione si mette in pausa al limite dopo il periodo di tolleranza e ricevi un avviso al {thresholds} del tuo limite.",
    cta: "Continua con {plan}",
  },
  matrix: {
    title: "Confronta tutti i piani",
    text: "Tutto ciò che ogni piano include, raggruppato per area: prima limiti e prezzi, poi i moduli.",
    feature: "Funzionalità",
    included: "Incluso",
    notIncluded: "Non incluso",
    custom: "Su misura",
    contractual: "Contrattuale",
    planLabel: "Scegli un piano da visualizzare",
    groups: {
      limits: "Limiti e prezzi",
      tracking: "Tracking e destinazioni",
      commerce: "Eventi e-commerce",
      ai: "Assistente AI",
      quality: "Qualità dei dati e monitoraggio",
      governance: "Governance e consenso",
      data: "Dati, attribuzione ed esportazioni",
      support: "Supporto e onboarding",
      enterprise: "Enterprise",
    },
    rows: { sites: "Siti web in produzione", events: "Eventi accettati al mese", team: "Membri del team", retention: "Conservazione degli eventi", monthly: "Prezzo mensile", yearly: "Prezzo annuale, pagato in anticipo", overage: "Pacchetto di eventi opzionale" },
    unlimited: "Illimitato entro il fair use",
    days: "{n} giorni",
    months: "{n} mesi",
    pack: "{price} per {events} eventi",
    perMonth: "al mese",
    perYear: "all’anno",
    summaryCount: "{included} di {total} inclusi",
  },
  whatCounts: "Cosa conta come evento?",
  whatCountsText: "Un evento viene contato esattamente una volta quando l’ingest di Track lo accetta. Inoltrare lo stesso evento a più destinazioni non aumenta il consumo.",
  events: {
    notCountedTitle: "Mai fatturati",
    diagramTitle: "Come viene contato un evento",
    diagramDescription: "Un sito web invia un evento a Track. Track lo accetta una volta e lo conta una volta. Poi Track inoltra lo stesso evento a Meta, Google Ads e TikTok; l’inoltro non aumenta il consumo.",
    diagramCaption: "Un evento accettato viene fatturato una sola volta, indipendentemente da quante destinazioni lo ricevono.",
    nodes: { website: "Sito web", track: "Track", trackSub: "accettato · contato una volta", destinations: ["Meta", "Google Ads", "TikTok"], fanOut: "l’inoltro non conta" },
  },
  overageTitle: "Consumo aggiuntivo e controllo dei costi",
  overageText: "Quando ti avvicini al limite mensile di eventi ricevi un avviso per tempo, vedi una previsione di utilizzo e decidi tu come gestire gli eventi in più. Niente viene acquistato o cambiato in silenzio.",
  overageSection: {
    packsTitle: "Pacchetti di eventi per piano",
    packPlan: "Piano",
    packSize: "Dimensione del pacchetto",
    packPrice: "Prezzo per pacchetto",
    packEnterprise: "Concordato nel contratto",
    policyTitle: "Decidi tu come gestire il consumo aggiuntivo",
    policyText: "Il consumo aggiuntivo non viene mai attivato senza una tua decisione. Nelle impostazioni di fatturazione scegli una di tre policy:",
    defaultTag: "Predefinita",
    thresholds: "Ricevi un avviso al {thresholds} del tuo limite mensile e vedi una previsione di utilizzo.",
    grace: "Con la policy di pausa, l’elaborazione continua fino al {percent}% oltre il limite prima di fermarsi; il periodo di tolleranza è mostrato nella dashboard.",
    honest: "La dashboard ti dice onestamente se è più conveniente un pacchetto di eventi o il piano successivo. Nessun cambio di piano silenzioso, nessun acquisto non richiesto e nessuna cancellazione delle configurazioni in caso di downgrade.",
  },
  trial: {
    title: "Prova {plan} per {days} giorni",
    text: "La prova gira sul piano {plan} con tutte le sue funzionalità e non si trasforma mai da sola in un abbonamento a pagamento.",
    facts: ["Nessuna carta di credito richiesta", "Fino a {events} eventi di prova accettati", "Nessuna conversione automatica in un piano a pagamento", "Dopo la prova il tuo workspace resta leggibile ed esportabile; niente viene cancellato a sorpresa"],
    cta: "Inizia la prova di {plan}",
  },
  faq: [
    { q: "Cosa conta come evento fatturabile?", a: "Un evento accettato dall’ingest, contato una volta. Eventi non validi o rifiutati, duplicati rilevati, retry tecnici, eventi di test e debug, eventi interni di sistema ed eventi scartati per mancanza di consenso non vengono mai fatturati. Inoltrare un evento a più destinazioni non aumenta il consumo." },
    { q: "Cosa succede quando raggiungo il limite?", a: "Ricevi un avviso al {thresholds} del tuo limite mensile. Niente viene acquistato o cambiato in silenzio: decidi in anticipo se consentire i pacchetti di eventi, impostare un limite di costo mensile o mettere in pausa l’elaborazione al limite dopo il periodo di tolleranza comunicato. Gli upgrade sono possibili in qualsiasi momento." },
    { q: "Come funziona la prova di {trialDays} giorni?", a: "La prova gira su {trialPlan} per {trialDays} giorni senza carta di credito e copre fino a {trialEvents} eventi accettati. Non si trasforma mai da sola in un abbonamento a pagamento. In seguito il tuo workspace resta leggibile ed esportabile finché non scegli un piano." },
    { q: "Pago per destinazione?", a: "No. Tutte le destinazioni standard sono incluse in ogni piano e un evento accettato conta una volta, indipendentemente da quante destinazioni lo ricevono." },
    { q: "I sottodomini di staging e preview contano come siti web?", a: "No. I sottodomini di staging e preview di un sito web in produzione non contano ai fini del limite di siti web." },
    { q: "Quali imposte si applicano?", a: "I prezzi sono netti in EUR. L’IVA viene aggiunta dove applicabile in base al tuo paese di fatturazione. Le aziende possono inserire la partita IVA durante il checkout." },
    { q: "Posso cambiare piano o disdire?", a: "Gli upgrade hanno effetto immediato. I piani mensili terminano alla fine del periodo in corso; i piani annuali durano fino alla fine dell’anno prepagato. Disdici e cambi piano nel portale di fatturazione di Stripe. Un downgrade non cancella mai le configurazioni in silenzio e i tuoi dati restano disponibili per il periodo di conservazione configurato e possono essere esportati." },
    { q: "L’assistente AI è limitato?", a: "L’assistente AI è incluso in ogni piano a pagamento. Risposte normali, domande di approfondimento e validazioni non vengono conteggiate e non vedi mai i token del modello." },
    { q: "Come funziona la fatturazione Enterprise?", a: "I piani Enterprise hanno un prezzo individuale e vengono fatturati tramite fattura o ordine di acquisto con volumi, conservazione, SLA e ore di supporto contrattuali. Contatta il team vendite per definire la configurazione." },
  ],
  cta: "Inizia con Track",
  ctaText: "Crea il tuo sito senza carta di credito, configura la prima destinazione e scegli un piano quando sei pronto.",
};
