import type { PricingCopy } from "../types";

/**
 * Dutch (nl) copy of the pricing area, informal "je/jij" like the rest of the Dutch copy. Same shape as en.ts;
 * see docs/14-localization.md.
 */

export const PRICING_COPY_NL: PricingCopy = {
  eyebrow: "Prijzen",
  title: "Heldere abonnementen die meegroeien met je eventvolume",
  text: "Elk abonnement bevat browser- en server-side tracking, alle standaard-destinations, de AI-assistent, de Consent Engine en de Live Event Debugger. Kies een abonnement op basis van websites, maandelijkse events, teamgrootte en bewaartermijn. Prijzen zijn netto in EUR; de facturatie loopt via Stripe.",
  hero: { facts: ["Standaard maandelijkse facturatie, opzegbaar tegen het einde van de periode", "Nettoprijzen in EUR, exclusief btw waar van toepassing", "{trialDays} dagen {trialPlan} proberen zonder creditcard"] },
  interval: {
    legend: "Factureringsperiode",
    monthly: "Maandelijks",
    yearly: "Jaarlijks",
    monthlyHint: "Elke maand gefactureerd. Opzegbaar tegen het einde van de lopende periode.",
    yearlyHint: "Eén keer per jaar vooraf betaald. De jaarprijs is gelijk aan tien maandtermijnen.",
    announceMonthly: "Maandprijzen worden getoond.",
    announceYearly: "Jaarprijzen worden getoond.",
  },
  recommended: "Aanbevolen",
  contactSales: "Neem contact op met sales",
  start: "Aan de slag",
  plansLabel: "Abonnementen",
  plan: {
    perMonth: "per maand",
    perYear: "per jaar",
    billedMonthly: "Maandelijks gefactureerd. Opzegbaar tegen het einde van de periode.",
    billedYearly: "{total} eenmalig per jaar in rekening gebracht",
    equivalent: "≈ {monthly} per maand",
    instalments: "komt overeen met {n} maandtermijnen",
    eventsLabel: "geaccepteerde events per maand",
    sites: "Websites",
    team: "Team",
    retention: "Bewaartermijn",
    unlimited: "Onbeperkt (fair use)",
    days: "{n} dagen",
    months: "{n} maanden",
    choose: "Kies {plan}",
    trialHint: "Inclusief {days} dagen proefperiode, geen creditcard nodig",
    overageHint: "Optioneel meerverbruik: {price} per {events} extra events, alleen als jij daar uitdrukkelijk voor kiest.",
    recommended: "Aanbevolen",
    listLabel: "Wat {plan} toevoegt",
  },
  tax: {
    title: "Belastingen en facturen",
    text: "Alle prijzen zijn netto in EUR en exclusief btw. Btw wordt toegevoegd waar dat op basis van je factuurland van toepassing is. Bedrijven kunnen tijdens de checkout hun btw-nummer invoeren; facturen voor elke betaling vind je in het facturatieportaal.",
  },
  enterprise: {
    lead: "Volume, governance en infrastructuur op maat",
    text: "Voor organisaties die individuele event- en sitevolumes, een eigen rollenmodel, contractuele supporturen en een security review nodig hebben. We bepalen de scope van de setup samen met jou; prijs, meerverbruik en bewaartermijn worden contractueel vastgelegd.",
    price: "Op maat",
    benefitsTitle: "Wat Enterprise toevoegt",
    trustTitle: "Dezelfde basis als elk abonnement",
    trust: ["EU-dataregio als standaard", "Verwerker conform art. 28 AVG, verwerkersovereenkomst inbegrepen", "Tenant-isolatie op rijniveau in de database", "Envelope-versleutelde credentials; secrets bereiken nooit de chat, logs of het model", "Ondertekende, geversioneerde configuraties met rollback"],
    cta: "Neem contact op met sales",
    secondary: "Demo boeken",
    overage: "Meerverbruik, bewaartermijn en volumes worden contractueel vastgelegd.",
  },
  includedSection: {
    title: "Inbegrepen in elk abonnement",
    text: "De basis zit nooit achter een betaalmuur: privacy-, toestemmings-, beveiligings-, export- en verwijderfuncties werken in elk abonnement, en de AI-assistent maakt deel uit van elk betaald abonnement. Upgrades voegen volume, teamgrootte, bewaartermijn en geavanceerde modules toe.",
    note: "Uit de tariefcatalogus: elk betaald abonnement bevat",
  },
  tools: {
    title: "Vind je abonnement en schat je kosten in",
    text: "Beide tools gebruiken dezelfde tariefcatalogus als de checkout en de facturatie: dezelfde limieten, dezelfde prijzen, dezelfde eventpakketten. Hier wordt niets gekocht.",
  },
  faqTitle: "Veelgestelde vragen",
  finder: {
    title: "Welk abonnement past bij je?",
    text: "Beantwoord vier vragen. De aanbeveling wordt deterministisch berekend uit de tariefcatalogus: het kleinste abonnement waarvan de limieten al je antwoorden dekken.",
    sites: "Productiewebsites",
    events: "Geaccepteerde events per maand",
    team: "Teamleden",
    retention: "Benodigde bewaartermijn voor events",
    retentionDays: "{n} dagen",
    retentionMonths: "{n} maanden",
    retentionLonger: "Langer dan {n} maanden",
    eventsMore: "Meer dan {n}",
    resultLabel: "Aanbeveling",
    result: "{plan} dekt je setup",
    resultEnterprise: "Je setup vraagt om een Enterprise-overeenkomst",
    resultEnterpriseText: "Minstens één antwoord ligt boven de Pro-limieten. Volumes, bewaartermijn en teamgrootte op maat worden contractueel vastgelegd.",
    checks: { sites: "Websites", events: "Events per maand", team: "Teamleden", retention: "Bewaartermijn" },
    limitOf: "{wanted} van {limit}",
    noCap: "{wanted}, geen vaste limiet",
    cta: "Doorgaan met {plan}",
    ctaEnterprise: "Neem contact op met sales",
    priceMonthly: "{price} per maand",
    priceYearly: "{price} per jaar, vooraf betaald",
  },
  calculator: {
    title: "Schat je kosten in",
    text: "Verschuif de slider of typ het aantal geaccepteerde events dat je per maand verwacht. De schatting toont de abonnementsprijs, de eventpakketten die je nodig zou hebben en of een hoger abonnement goedkoper is — voordat je iets koopt.",
    plan: "Abonnement",
    events: "Verwachte geaccepteerde events per maand",
    slider: "Events per maand",
    eventsInput: "Exact aantal events",
    base: "Abonnementsprijs",
    included: "Inbegrepen events",
    above: "Events boven de limiet",
    packs: "Benodigde eventpakketten",
    packsValue: "{n} × {events} events à {price} per stuk",
    packsNone: "Geen",
    overageCost: "Meerverbruik",
    total: "Geschatte totaalkosten",
    perMonth: "per maand",
    perYear: "per jaar",
    cheaper: "{plan} zou voor dit volume {total} kosten, {savings} minder dan {current} met eventpakketten.",
    cheaperCta: "Rekenen met {plan}",
    noCheaper: "Geen hoger abonnement is goedkoper voor dit volume.",
    beyondPro: "Volumes boven de Pro-limiet kunnen ook individueel worden vastgelegd in een Enterprise-contract.",
    policyNote: "Eventpakketten worden alleen gefactureerd als je meerverbruik uitdrukkelijk toestaat. Standaard pauzeert de verwerking bij de limiet na de respijtperiode, en je wordt gewaarschuwd bij {thresholds} van je limiet.",
    cta: "Doorgaan met {plan}",
  },
  matrix: {
    title: "Alle abonnementen vergelijken",
    text: "Alles wat elk abonnement bevat, gegroepeerd per gebied: eerst limieten en prijzen, daarna de modules.",
    feature: "Functie",
    included: "Inbegrepen",
    notIncluded: "Niet inbegrepen",
    custom: "Op maat",
    contractual: "Contractueel",
    planLabel: "Kies een abonnement om te bekijken",
    groups: {
      limits: "Limieten en prijzen",
      tracking: "Tracking en destinations",
      commerce: "E-commerce-events",
      ai: "AI-assistent",
      quality: "Datakwaliteit en monitoring",
      governance: "Governance en toestemming",
      data: "Data, attributie en exports",
      support: "Support en onboarding",
      enterprise: "Enterprise",
    },
    rows: { sites: "Productiewebsites", events: "Geaccepteerde events per maand", team: "Teamleden", retention: "Bewaartermijn voor events", monthly: "Maandprijs", yearly: "Jaarprijs, vooraf betaald", overage: "Optioneel eventpakket" },
    unlimited: "Onbeperkt binnen fair use",
    days: "{n} dagen",
    months: "{n} maanden",
    pack: "{price} per {events} events",
    perMonth: "per maand",
    perYear: "per jaar",
    summaryCount: "{included} van {total} inbegrepen",
  },
  whatCounts: "Wat telt als een event?",
  whatCountsText: "Een event wordt precies één keer geteld zodra de ingestion van Track het accepteert. Hetzelfde event doorsturen naar meerdere destinations verhoogt het verbruik niet.",
  events: {
    notCountedTitle: "Nooit gefactureerd",
    diagramTitle: "Hoe een event wordt geteld",
    diagramDescription: "Een website stuurt een event naar Track. Track accepteert het één keer en telt het één keer. Daarna stuurt Track hetzelfde event door naar Meta, Google Ads en TikTok; het doorsturen verhoogt het verbruik niet.",
    diagramCaption: "Eén geaccepteerd event wordt één keer gefactureerd, ongeacht hoeveel destinations het ontvangen.",
    nodes: { website: "Website", track: "Track", trackSub: "geaccepteerd · één keer geteld", destinations: ["Meta", "Google Ads", "TikTok"], fanOut: "doorsturen telt niet" },
  },
  overageTitle: "Meerverbruik en kostenbeheersing",
  overageText: "Als je je maandelijkse eventlimiet nadert, word je vroeg gewaarschuwd, zie je een verbruiksprognose en bepaal je zelf hoe extra events worden afgehandeld. Er wordt niets stilzwijgend gekocht of omgezet.",
  overageSection: {
    packsTitle: "Eventpakketten per abonnement",
    packPlan: "Abonnement",
    packSize: "Pakketgrootte",
    packPrice: "Prijs per pakket",
    packEnterprise: "Contractueel vastgelegd",
    policyTitle: "Jij bepaalt hoe meerverbruik wordt afgehandeld",
    policyText: "Meerverbruik wordt nooit geactiveerd zonder jouw beslissing. In de facturatie-instellingen kies je een van drie regels:",
    defaultTag: "Standaard",
    thresholds: "Bij {thresholds} van je maandelijkse limiet word je gewaarschuwd en zie je een verbruiksprognose.",
    grace: "Met de pauzeerregel loopt de verwerking door tot {percent}% boven de limiet voordat die pauzeert; de respijtperiode wordt in het dashboard getoond.",
    honest: "Het dashboard vertelt je eerlijk of een eventpakket of het volgende abonnement goedkoper is. Er is geen stilzwijgende abonnementswijziging, geen ongevraagde aankoop en geen verwijdering van configuraties bij een downgrade.",
  },
  trial: {
    title: "Probeer {plan} {days} dagen",
    text: "De proefperiode draait op het {plan}-abonnement met alle functies en wordt nooit vanzelf een betaald abonnement.",
    facts: ["Geen creditcard nodig", "Tot {events} geaccepteerde testevents", "Geen automatische omzetting naar een betaald abonnement", "Na de proefperiode blijft je workspace leesbaar en exporteerbaar; er wordt niets onverwacht verwijderd"],
    cta: "Start de {plan}-proefperiode",
  },
  faq: [
    { q: "Wat telt als een factureerbaar event?", a: "Een event dat de ingestion heeft geaccepteerd, één keer geteld. Ongeldige of afgewezen events, gedetecteerde duplicaten, technische retries, test- en debugevents, interne systeemevents en events die zijn weggevallen door ontbrekende toestemming worden nooit gefactureerd. Eén event doorsturen naar meerdere destinations verhoogt het verbruik niet." },
    { q: "Wat gebeurt er als ik de limiet bereik?", a: "Je wordt gewaarschuwd bij {thresholds} van je maandelijkse limiet. Er wordt niets stilzwijgend gekocht of omgezet: je kiest vooraf of eventpakketten zijn toegestaan, stelt een maandelijkse kostenlimiet in, of laat de verwerking bij de limiet pauzeren na de gecommuniceerde respijtperiode. Upgraden kan op elk moment." },
    { q: "Hoe werkt de proefperiode van {trialDays} dagen?", a: "De proefperiode draait {trialDays} dagen op {trialPlan} zonder creditcard en omvat tot {trialEvents} geaccepteerde events. Die wordt nooit vanzelf een betaald abonnement. Daarna blijft je workspace leesbaar en exporteerbaar tot je een abonnement kiest." },
    { q: "Betaal ik per destination?", a: "Nee. Alle standaard-destinations zijn in elk abonnement inbegrepen, en een geaccepteerd event telt één keer, ongeacht hoeveel destinations het ontvangen." },
    { q: "Tellen staging- en preview-subdomeinen als websites?", a: "Nee. Staging- en preview-subdomeinen van een productiewebsite tellen niet mee voor de websitelimiet." },
    { q: "Welke belastingen zijn van toepassing?", a: "Prijzen zijn netto in EUR. Btw wordt toegevoegd waar dat op basis van je factuurland van toepassing is. Bedrijven kunnen tijdens de checkout hun btw-nummer invoeren." },
    { q: "Kan ik van abonnement wisselen of opzeggen?", a: "Upgrades gaan direct in. Maandabonnementen eindigen aan het einde van de lopende periode; jaarabonnementen lopen tot het einde van het vooruitbetaalde jaar. Opzeggen en wisselen doe je in het Stripe-facturatieportaal. Een downgrade verwijdert nooit stilzwijgend configuraties, en je data blijft beschikbaar gedurende de ingestelde bewaartermijn en kan worden geëxporteerd." },
    { q: "Is de AI-assistent beperkt?", a: "De AI-assistent is inbegrepen in elk betaald abonnement. Normale antwoorden, vervolgvragen en validaties worden niet gemeten, en je ziet nooit modeltokens." },
    { q: "Hoe werkt de facturatie voor Enterprise?", a: "Enterprise-abonnementen worden individueel geprijsd en gefactureerd per factuur of inkooporder, met contractuele volumes, bewaartermijn, SLA en supporturen. Neem contact op met sales om de setup te bepalen." },
  ],
  cta: "Start met Track",
  ctaText: "Maak je site aan zonder creditcard, configureer de eerste destination en kies een abonnement wanneer je er klaar voor bent.",
};
